### PR TITLE
Forbidden aggregated partition key column on mv

### LINKED ISSUE #4342: Be core when add partition on table which has mv
**Describe the bug**
The be core when add partition on table.
This table has materialized view.
The materialized view has a partition column which is not key in mv.

**To Reproduce**
1. create table 

```
test_sys_materialized_view_2_test_add_partiton_with_mv_db.test_sys_materialized_view_2_test_add_partiton_with_mv_tb ( k0 boolean NOT NULL, k1 tinyint NOT NULL, k2 smallint NOT NULL, k3 int NOT NULL, k4 bigint NOT NULL, k5 largeint NOT NULL, k6 decimal(9, 3) NOT NULL, k7 char(5) NOT NULL, k8 date NOT NULL, k9 datetime NOT NULL, k10 varchar(20) NOT NULL, k11 double NOT NULL, k12 float NOT NULL )  PARTITION BY RANGE(k1) ( PARTITION p1 VALUES LESS THAN ("-10"), PARTITION p2 VALUES LESS THAN ("0"), PARTITION p3 VALUES LESS THAN ("10") ) DISTRIBUTED BY HASH(k4, k5) BUCKETS 10
```

2. create materialized view

```
CREATE MATERIALIZED VIEW s8e55_ys_materialized_view_2_test_add_partiton_with_mv_index AS SELECT k0, max(k9), min(k11), sum(k12), hll_union(hll_hash(k7)), bitmap_union(to_bitmap(k1)) from test_sys_materialized_view_2_test_add_partiton_with_mv_db.test_sys_materialized_view_2_test_add_partiton_with_mv_tb group by k0
```

3. add partition

```
ALTER TABLE test_sys_materialized_view_2_test_add_partiton_with_mv_db.test_sys_materialized_view_2_test_add_partiton_with_mv_tb ADD PARTITION p4 VALUES LESS THAN ("20")
```

4. add partition failed
image
image

**Expected behavior**

The partition column also must be the key in materialized view.
So  the mv could not be created.

### PR DESCRIPTION
**Pull request by EmmyMiao87**
## Proposed changes

The partition column of table also must be the key in materialized view.
If not, when user wants to add partition of table, the be will core.
The materialized view could not create partition correctly when partition column has been aggregated.

Fixed #4342
Change-Id: Idee42a49c61034368c018d33c522dfced673f3bd

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java [hunk 1]
```diff
@@ -563,10 +563,36 @@ public PartitionInfo getPartitionInfo() {
         return partitionInfo;
     }
 
+    public List<String> getPartitionColumnNames() {
+        List<String> partitionColumnNames = Lists.newArrayList();
+        if (partitionInfo instanceof SinglePartitionInfo) {
+            return partitionColumnNames;
```
Comment (wutiangan) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java:569]: partitionColumnNames has upperCase？

File: fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java [hunk 2]
```diff
@@ -458,7 +458,14 @@ private RollupJobV2 createMaterializedViewJob(String mvName, String baseIndexNam
                 newMVColumns.add(mvColumnItem.toMVColumn(olapTable));
             }
         } else {
+            List<String> partitionOrDistributedColumnName = olapTable.getPartitionColumnNames();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java:461]: A `Set` may be better

File: fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java (hunk 1 above)
Comment (EmmyMiao87) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java:569]: It can but we need to check it ignore case

File: fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java (hunk 2 above)
Comment (EmmyMiao87) [reply fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java]: Fixed

**Review by morningman — APPROVED** [review]
LGTM
