### PR TITLE
[Bug] Fix mem limit -1 in partition aggregate node

### LINKED ISSUE #7169: [Bug] ERROR 1064 (HY000) Limit: -1
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache/incubator-doris:0.14

### What's Wrong?

ERROR 1064 (HY000): errCode = 2, detailMessage = Memory exceed limit. New partitioned Aggregation in spill Backend: 172.21.16.8, fragment: 67ef448d62ff4cac-999c74988410454a Used: 21566009856, Limit: -1. You can change the limit by session variable exec_mem_limit.
but already SET exec_mem_limit = 120G;
condition : 1. There are 800 million single tables,150GB
SQL :  select uuid,count(1) from table_a group by uuid limit 100;

### What You Expected?

sql get rigtht result

### How to Reproduce?

_No response_

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Fix mem limit -1 in partition aggregate node

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #7169) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/partitioned_aggregation_node.cc [hunk 1]
```diff
@@ -849,7 +849,7 @@ Status PartitionedAggregationNode::Partition::Spill(bool more_aggregate_rows) {
     // TODO(ml): enable spill
     std::stringstream msg;
     msg << "New partitioned Aggregation in spill";
-    LIMIT_EXCEEDED(parent->mem_tracker(), parent->state_, msg.str());
+    LIMIT_EXCEEDED(parent->state_->query_mem_tracker(), parent->state_, msg.str());
```
Comment (morningman) [inline be/src/exec/partitioned_aggregation_node.cc:852]: I think you can just use `instance_mem_tracker()`
cc @xinyiZzz

Comment (HappenLee) [reply be/src/exec/partitioned_aggregation_node.cc:852]: `instance_mem_tracker()` do not have mem limit so the limit of `instance_mem_tracker`  is -1. `instanc_mem_tracker` is child of `query_mem_tracker()` which have real limit number

**Review by morningman — APPROVED** [review]
LGTM
