### PR TITLE
Forbidden correlated having clause

### LINKED ISSUE #3377: The incorrect result of having clause with subquery
**Describe the bug**
1. SELECT k1 FROM test GROUP BY k1 HAVING EXISTS(SELECT k1 FROM baseall GROUP BY k1 HAVING SUM(test.k1) = k1);
Expect : empty when having predicate is not satisfied.
See error: return the result of select stmt without having predicate

2. select k1, count(*) cnt from test group by k1 having k1 in (select k1 from baseall order by k1 limit 2) order by k1 limit 5 offset 3;
Expect: empty
See error: return the result of select stmt without offset.

3. create view tt as select k1, count(*) cnt from test group by k1 having k1 in (select k1 from baseall order by k1 limit 2) order by k1;
Expect: success
ERROR 1064 (HY000): errCode = 2, detailMessage = failed to init view stmt

### PR DESCRIPTION
**Pull request by EmmyMiao87**
Fixed #3377

The correlated slot ref should be bound by the agg tuple of outer query.
However, the correlated having clause should not be analyzed correctly so the result is incorrect.
For example: 
```
SELECT k1 FROM test GROUP BY k1 HAVING EXISTS(SELECT k1 FROM baseall GROUP BY k1 HAVING SUM(test.k1) = k1);
```
The correlated predicate is not executed.

The limit offset should be rewritten also when there is subquery in having clause.
For example: 
```
select k1, count(*) cnt from test group by k1 having k1 in (select k1 from baseall order by k1 limit 2) order by k1 limit 5 offset 3;
```
The new stmt should has a limit element with offset.

The view which has subquery in having clause should not be created.
The reason is that the toSql function of query stmt is incorrect when there is subquery in having clause.
So the view def sql is incorrect and could not pass the sql parser.
Now, the view def sql use the original sql directly to fix this error.

Change-Id: If24206a8dee94013225fe7fdd30ab1fb034de34f

### CODE REVIEW

File: fe/src/main/java/org/apache/doris/analysis/BaseViewStmt.java [hunk 1]
```diff
@@ -109,33 +112,37 @@ protected void createColumnAndViewDefs(Analyzer analyzer) throws AnalysisExcepti
...
+        for (int i = 0; i < colNames.size(); ++i) {
+            if (i != 0) {
+                sb.append(", ");
+            }
+            String colRef = viewDefStmt.getColLabels().get(i);
+            if (!colRef.startsWith("`")) {
+                colRef = "`" + colRef + "`";
+            }
+            String colAlias = colNames.get(i);
+            sb.append(String.format("`%s`.%s AS `%s`", tableName.getTbl(), colRef, colAlias));
```
Comment (xy720) [inline fe/src/main/java/org/apache/doris/analysis/BaseViewStmt.java:141]: It is work for function call?
For example, if user input:
"create view test_view (h1, h2) as select function(a, b), col2 from testTbl"
will become
"select function(a, b) as h1, col2 as h2 from (select function(a, b), col2 from testTbl)"

File: fe/src/main/java/org/apache/doris/qe/ConnectProcessor.java [hunk 2]
```diff
@@ -225,7 +226,13 @@ private void handleQuery() {
         SqlScanner input = new SqlScanner(new StringReader(originStmt), ctx.getSessionVariable().getSqlMode());
         SqlParser parser = new SqlParser(input);
         try {
-            return SqlParserUtils.getMultiStmts(parser);
+            List<StatementBase> result = SqlParserUtils.getMultiStmts(parser);
+            String[] originStmtList = originStmt.split(";");
```
Comment (morningman) [inline fe/src/main/java/org/apache/doris/qe/ConnectProcessor.java:230]: There maybe `;` inside the query statement

**Review by morningman — CHANGES_REQUESTED** [review]

File: fe/src/main/java/org/apache/doris/analysis/LimitElement.java [hunk 3]
```diff
@@ -42,9 +42,9 @@ public LimitElement(long limit) {
         offset = 0;
     }
 
-    public LimitElement(long offset, long limit) {
-        this.offset = offset;
+    public LimitElement(long limit, long offset) {
```
Comment (kangkaisen) [inline fe/src/main/java/org/apache/doris/analysis/LimitElement.java:45]: Why do we change the order?

File: fe/src/main/java/org/apache/doris/analysis/SelectList.java [hunk 4]
```diff
@@ -98,6 +98,24 @@ public void rewriteExprs(ExprRewriter rewriter, Analyzer analyzer)
...
+
+    public String toOriginSql() {
+        // Select list
+        StringBuilder strBuilder = new StringBuilder();
+        strBuilder.append("SELECT ");
+        if (isDistinct) {
+            strBuilder.append("DISTINCT ");
+        }
+        for (int i = 0; i < items.size(); ++i) {
+            // strBuilder.append(selectList.getItems().get(i).toSql());
```
Comment (kangkaisen) [inline fe/src/main/java/org/apache/doris/analysis/SelectList.java:110]: Remove.

**Comment by kangkaisen** [comment]
`The reason is that the toSql function of query stmt is incorrect when there is subquery in having clause.`

@EmmyMiao87  Hi, why can't we make the toSql function correct ?

**Comment by kangkaisen** [comment]
> `The reason is that the toSql function of query stmt is incorrect when there is subquery in having clause.`
> 
> @EmmyMiao87 Hi, why can't we make the toSql function correct ?

OK, I see.

File: fe/src/main/java/org/apache/doris/analysis/BaseViewStmt.java (hunk 1 above)
Comment (EmmyMiao87) [reply fe/src/main/java/org/apache/doris/analysis/BaseViewStmt.java]: This change has been removed.

File: fe/src/main/java/org/apache/doris/analysis/LimitElement.java (hunk 3 above)
Comment (EmmyMiao87) [reply fe/src/main/java/org/apache/doris/analysis/LimitElement.java]: changed

**Review by morningman — APPROVED** [review]
LGTM
