### PR TITLE
[Bug] Fix bug that ConcurrentModificationException thrown 

### LINKED ISSUE #3588: [Bug] ConcurrentModificationException thrown when truncate table
**Describe the bug**
ConcurrentModificationException thrown when truncate table 

**To Reproduce**
1. create table with partition
2. add some temp partitiions
3. truncate table

### PR DESCRIPTION
**Pull request by morningman**
When truncate the table, a ConcurrentModificationException may thrown when there
are temp partitions in this table.

Fix: #3588

### CODE REVIEW

File: fe/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 1]
```diff
@@ -4514,7 +4514,7 @@ public long getNextId() {
                     for (Partition partition : olapTable.getAllPartitions()) {
                         long partitionId = partition.getId();
                         DataProperty dataProperty = partitionInfo.getDataProperty(partition.getId());
-                        Preconditions.checkNotNull(dataProperty);
+                        Preconditions.checkNotNull(dataProperty, partition.getName() + ", pId:" + partitionId + ", db: " + dbId + ", tbl: " + tableId);
```
Comment (wutiangan) [inline fe/src/main/java/org/apache/doris/catalog/Catalog.java:4517]: The second parameter is better to be a complete sentence.

Comment (morningman) [reply fe/src/main/java/org/apache/doris/catalog/Catalog.java:4517]: This is not a log, just for printing some debug info. So I think it is not necessary to be a sentence.

**Review by EmmyMiao87 — APPROVED** [review]
