### PR TITLE
[Bug] Fix hard cardinality check which makes queries fail

### LINKED ISSUE #4581: [Bug] SelectNode.cardinality < 0 cause query exception "Unexpected exception: null"
**Describe the bug**
When using select condition like `-1=-1` may cause `errCode = 2, detailMessage = Unexpected exception: null`.
This is due to`SelectNode.cardinality` computing error.

https://github.com/apache/incubator-doris/blob/81aa1c599def3c3f0d9cd80469fd06393ea764e7/fe/src/main/java/org/apache/doris/planner/SelectNode.java#L63-L73

This cardinality may be less than 0.

**To Reproduce**
1. Create a table
```sql
CREATE TABLE `table1` (
  `city_id` bigint(20) NULL,
  `tag_id` bigint(20) NULL,
  `dt` bigint(20) NULL,
  `num` bigint(20) NULL
) ENGINE=OLAP
DUPLICATE KEY(`city_id`, `tag_id`, `dt`)
COMMENT "OLAP"
PARTITION BY RANGE(`dt`)
(PARTITION p20200102 VALUES [("20200101"), ("20200102")),
PARTITION p20200103 VALUES [("20200102"), ("20200103")))
DISTRIBUTED BY HASH(`city_id`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```

2. Insert some data
```sql
INSERT INTO table1 VALUES (1, 2, 20200102, 3);
```

You may need to wait for the `cardinality` to be > 0 (I still dont know how the `cardinality` works). 

2. Launch a query
```sql
SELECT rank, tag_id
FROM (
    SELECT row_number() OVER (ORDER BY num DESC) AS rank, tag_id
    FROM table1
    ) t
WHERE -1=-1 or tag_id in (-1)
LIMIT 10
;
```
When the table is not empty (maybe `cardinality` means row number?), `cardinality` will be > 0, `computeSelectivity()` < 0, then the error occur.

I tried to remove some elements and this is the minimum sql to reproduce the bug.

Could someone explain what doe `cardinality` and `selectivity` means?
Is `Preconditions.checkState(cardinality >= 0);` necessary?

### PR DESCRIPTION
**Pull request by ccoffline**
## Proposed changes

#4581
fix hard `Preconditions.checkState()` by setting `cardinality` to `-1` when computation is invalid.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

- [x] I have create an issue on (Fix #4581), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/planner/SelectNode.java [hunk 1]
```diff
@@ -63,13 +62,14 @@ public void init(Analyzer analyzer) throws UserException {
...
+        double selectivity = computeSelectivity();
+        if (cardinality < 0 || selectivity < 0) {
+            this.cardinality = -1;
         } else {
-            cardinality = Math.round(((double) getChild(0).cardinality) * computeSelectivity());
-            Preconditions.checkState(cardinality >= 0);
+            this.cardinality = Math.round(cardinality * selectivity);
         }
-        LOG.info("stats Select: cardinality=" + Long.toString(cardinality));
+        LOG.info("stats Select: cardinality={}", this.cardinality);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SelectNode.java:72]:
```suggestion
        LOG.debug("stats Select: cardinality={}", this.cardinality);
```

**Review by morningman — APPROVED** [review]
LGTM
