### PR TITLE
[enhancement](Status) Optimize Status implementation

### LINKED ISSUE #11698: [Enhancement] Separate code and err msg in Status and save err msg in heap
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

The current `Status` implementation is to save all data to a fixed size (2KB) array on stack. This will lead to too large function stack space and may not be friendly to data locality (unnecessary page faults, TLB utilization, cacheline prefetching, etc.).
Another problem is when RVO(return value optimization) fails (there are many if-else branches in current codes, and the compiler may often be unable to do RVO), the move ctor cannot be used, causing the error message in `Status` to be copied layer by layer in the function call stack.
Doris moving the `Status`  data from heap to stack can be traced back to https://github.com/apache/doris/pull/8117. This PR is designed to avoid dynamic memory allocation. However, in practice, we often construct error messages through `fmt::format`(see `Status::ErrorFmt` https://github.com/apache/doris/blob/a6537a90cd4fda01de4a51b7abdc23a06cc8a901/be/src/common/status.h#L284-L289), so we cannot avoid dynamic memory allocation in fact.
If we separate the status code and err msg in `Status`:
1. The error msg constructed by `fmt::format` can be directly moved to `Status`.
2. When RVO fails, the compiler will use move ctor to pass `Status` to function caller to reduce the copy cost.

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by platoneko**
# Proposed changes

Issue Number: close #11698 

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/common/status.cpp [hunk 1]
```diff
@@ -58,18 +59,18 @@ Status::Status(const PStatus& s) {
...
+            _err_msg = s.error_msgs(0);
         }
     } else {
-        _length = 0;
+        _code = 0;
     }
 }
 
 // Implement it here to remove the boost header file from status.h to reduce precompile time
-Status Status::ConstructErrorStatus(int16_t precise_code, const Slice& msg) {
```
Comment (yiguolei) [inline be/src/common/status.cpp:72]: why remove msg here? I think the error should be  error message + error stack.

File: be/src/common/status.h [hunk 2]
```diff
@@ -241,47 +240,36 @@ enum ErrorCode {
...
-        return *this;
-    }
+    Status& operator=(Status&& rhs) noexcept = default;
 
     // "Copy" c'tor from TStatus.
     Status(const TStatus& status);
 
     Status(const PStatus& pstatus);
 
+    Status(TStatusCode::type code, std::string_view msg, int16_t precise_code = 1)
```
Comment (yiguolei) [inline be/src/common/status.h:263]: If these method is public, then user could call this method directly. Error stack is missing.

File: be/src/common/status.h [hunk 3]
```diff
@@ -291,125 +279,125 @@ class Status {
...
 
     template <typename... Args>
-    static Status Aborted(const std::string& fmt, Args&&... args) {
+    static Status Aborted(std::string_view fmt, Args&&... args) {
         return ErrorFmt(TStatusCode::ABORTED, fmt, std::forward<Args>(args)...);
     }
 
     template <typename... Args>
-    static Status DataQualityError(const std::string& fmt, Args&&... args) {
+    static Status DataQualityError(std::string_view fmt, Args&&... args) {
```
Comment (yiguolei) [inline be/src/common/status.h:383]: I find only OLAPInternalError has error stack, static Status DataQualityError(std::string_view fmt, Args&&... args) these method does not generate error stack.

**Review by yiguolei — APPROVED** [review]
LGTM
