### PR TITLE
[fix](be-ut) Fix unused-but-set-variable errors.

### LINKED ISSUE #8210: [Bug] run-be-ut.sh throws unused-but-set-variable errors.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Run `run-be-ut.sh` and it will throw `unused-but-set-variable` errors.

### What You Expected?

Run `run-be-ut.sh` without errors.

### How to Reproduce?

Run `run-be-ut.sh`.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #8210 .

## Problem Summary:

Please refer to #8210 .

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/test/exec/es_predicate_test.cpp [hunk 1]
```diff
@@ -142,6 +142,7 @@ Status EsPredicateTest::build_expr_context_list(std::vector<ExprContext*>& conju
 TEST_F(EsPredicateTest, normal) {
     std::vector<ExprContext*> conjunct_ctxs;
     Status status = build_expr_context_list(conjunct_ctxs);
+    ASSERT_TRUE(status.OK());
```
Comment (yangzhg) [inline be/test/exec/es_predicate_test.cpp:145]:
```suggestion
    ASSERT_TRUE(status.ok());
```

**Review by yangzhg — APPROVED** [review]
LGTM
