### PR TITLE
[fix](JSON) Fail to parse JSONPath (libc++)

### LINKED ISSUE #13939: [Bug](json) Fail to parse JSONPath
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris: master
STL: libc++

### What's Wrong?

```shell
******************************
   Running Backend Unit Test
******************************
Note: Google Test filter = JsonFunctionTest.*
[==========] Running 10 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 10 tests from JsonFunctionTest
[ RUN      ] JsonFunctionTest.string
Assertion failed: (IsString()), function GetString, file document.h, line 1852.
./run-be-ut.sh: line 271: 99599 Abort trap: 6           "${test}" --gtest_output="xml:${GTEST_OUTPUT_DIR}/${file_name}.xml" --gtest_print_time=true "${FILTER}"
```

### What You Expected?

Run BE UT successfully.

### How to Reproduce?

```shell
./run-be-ut.sh --run --filter="JsonFunctionTest.*"
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #13939

## Problem summary

```cpp
inline auto get_json_token(const std::string_view& path_string) {
#ifdef USE_LIBCPP
    return boost::tokenizer<boost::escaped_list_separator<char>>(
            std::string(path_string), boost::escaped_list_separator<char>("\\", ".", "\""));
#else
    return boost::tokenizer<boost::escaped_list_separator<char>>(
            path_string, boost::escaped_list_separator<char>("\\", ".", "\""));
#endif
}
```

**BE built with libc++**

In function `inline auto get_json_token(const std::string_view& path_string)`, we use a temporary `std::string` object to create `boost::tokenizer`. As a consequence, the result of `std::vector<std::string> paths(tok.begin(), tok.end())` ([be/src/exprs/json_functions.cpp#329](https://github.com/apache/doris/blob/master/be/src/exprs/json_functions.cpp#L329)) is wrong.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/util/string_util.h [hunk 1]
```diff
@@ -130,14 +130,16 @@ template <class T>
 using StringCaseUnorderedMap =
         std::unordered_map<std::string, T, StringCaseHasher, StringCaseEqual>;
 
-inline auto get_json_token(const std::string_view& path_string) {
 #ifdef USE_LIBCPP
+inline auto get_json_token(const std::string& path_string) {
```
Comment (BiteTheDDDDt) [inline be/src/util/string_util.h:134]: maybe we can use template to automatictly find path_string's type

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.29 seconds
 load time: 629 seconds
 storage size: 17180819256 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221103114412_clickbench_pr_39326.html

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]
