### PR TITLE
[fix](aggregate) agg table and unique table get different result when…

### LINKED ISSUE #14811: [Bug] agg table and unique table get different result when enable_vectorized_engine=false
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

相同的数据，使用agg table replace和unique table进行查询返回的结果不同

```
MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_agg where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_63    |
+------------+-----------+-----------+--------------+-----------+
1 row in set (0.02 sec)

MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_unique where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
1 row in set (0.02 sec)
```

### What You Expected?

返回相同值

### How to Reproduce?

创建两个表
```
CREATE TABLE `lineitem_agg` (
  `l_orderkey` bigint(20) NULL,
  `l_partkey` int(11) NULL,
  `l_suppkey` int(11) NULL,
  `l_linenumber` int(11) NULL,
  `l_quantity` decimal(15, 2) REPLACE NULL,
  `l_extendedprice` decimal(15, 2) REPLACE NULL,
  `l_discount` decimal(15, 2) REPLACE NULL,
  `l_tax` decimal(15, 2) REPLACE NULL,
  `l_returnflag` char(1) REPLACE NULL,
  `l_linestatus` char(1) REPLACE NULL,
  `l_shipdate` date REPLACE NULL,
  `l_commitdate` date REPLACE NULL,
  `l_receiptdate` date REPLACE NULL,
  `l_shipinstruct` char(25) REPLACE NULL,
  `l_shipmode` char(10) REPLACE NULL,
  `l_comment` varchar(44) REPLACE NULL
) ENGINE=OLAP
AGGREGATE KEY(`l_orderkey`, `l_partkey`, `l_suppkey`, `l_linenumber`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`l_orderkey`, `l_partkey`, `l_suppkey`, `l_linenumber`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);

CREATE TABLE `lineitem_unique` (
  `l_orderkey` bigint(20) NULL,
  `l_partkey` int(11) NULL,
  `l_suppkey` int(11) NULL,
  `l_linenumber` int(11) NULL,
  `l_quantity` decimal(15, 2) NULL,
  `l_extendedprice` decimal(15, 2) NULL,
  `l_discount` decimal(15, 2) NULL,
  `l_tax` decimal(15, 2) NULL,
  `l_returnflag` char(1) NULL,
  `l_linestatus` char(1) NULL,
  `l_shipdate` date NULL,
  `l_commitdate` date NULL,
  `l_receiptdate` date NULL,
  `l_shipinstruct` char(25) NULL,
  `l_shipmode` char(10) NULL,
  `l_comment` varchar(44) NULL
) ENGINE=OLAP
UNIQUE KEY(`l_orderkey`, `l_partkey`, `l_suppkey`, `l_linenumber`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`l_orderkey`, `l_partkey`, `l_suppkey`, `l_linenumber`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

导入数据1：
数据文件：
https://doris-agg-table-bug-1301087413.cos.ap-beijing.myqcloud.com/agg_table_bug/test_agg_table_data_1

这个数据中包含100w数据，其中每隔10000条表，有1条主键为 " 5970999942|130195832|5195859|1 " 的数据，并且l_comment值按序号递增的数据，一种有100条主键相同l_comment不同的行，以及另一组主键为" 5979996005|197922326|5422384|4 "的多行数据。

同一份数据文件导入两个表。

先关闭向量化：
```
set enable_vectorized_engine=false;
```
然后执行如下sql

```
MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_agg where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_63    |
+------------+-----------+-----------+--------------+-----------+
1 row in set (0.02 sec)

MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_unique where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
1 row in set (0.02 sec)
```

得到不一样的结果

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
… non-vectorized

when enable_vectorized_engine=false, agg table and unique table get different result, agg table will get replace column value with lower segment id from a rowset, but unique table get the one which has higher segment id.

Signed-off-by: nextdreamblue <zxw520blue1@163.com>

# Proposed changes

Issue Number: close #14811

## Problem summary

when enable_vectorized_engine=false, agg table and unique table get different result, agg table will get replace column value with lower segment id from a rowset, but unique table get the one which has higher segment id.

it is wrong, and this pr fix it.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.08 seconds
 load time: 437 seconds
 storage size: 17123356212 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221205095330_clickbench_pr_57874.html

File: be/src/olap/generic_iterators.cpp [hunk 1]
```diff
@@ -266,9 +266,17 @@ class MergeIterator : public RowwiseIterator {
             // here we sort segment id in reverse order, because of the row order in AGG_KEYS
             // dose no matter, but in UNIQUE_KEYS table we only read the latest is one, so we
             // return the row in reverse order of segment id
-            bool result = res == 0 ? lhs->data_id() < rhs->data_id() : res < 0;
-            if (_is_unique) {
-                result ? lhs->set_skip(true) : rhs->set_skip(true);
+            bool result = false;
```
Comment (liaoxin01) [inline be/src/olap/generic_iterators.cpp:269]: Please add some comments.
The following method may be clearer.
```
 if (_is_unique) {
     bool result = res == 0 ? lhs->data_id() < rhs->data_id() : res < 0;
     result ? lhs->set_skip(true) : rhs->set_skip(true);
     return result;
 }     
 return lhs->data_id() > rhs->data_id();
```

Comment (nextdreamblue) [reply be/src/olap/generic_iterators.cpp:269]: thanks, it is better

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM, thanks for the patch

**Review by dataroaring — APPROVED** [review]
LGTM
