### PR TITLE
[optimize] optimize default value for thriftserver's config key "thrift_client_timeout_ms"

### LINKED ISSUE #4824: [fe bug] query information_schema.tables cost 7s, even more
**Describe the bug**
exec the sql cost 7s , even more
```SQL
select * from information_schema.tables
```

**To Reproduce**
exec the sql
```SQL
select * from information_schema.tables
```

**Expected behavior**
cost less than 1s

### PR DESCRIPTION
**Pull request by francisoliverlee**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have create an issue on (Fix #4824), and have described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/common/Config.java [hunk 1]
```diff
@@ -318,8 +318,10 @@
      * The connection timeout and socket timeout config for thrift server
      * The value for thrift_client_timeout_ms is set to be larger than zero to prevent
      * some hang up problems in java.net.SocketInputStream.socketRead0
+     * 
+     * make it one hour to avoid fe close the socket so frequently, that be will retry to cost more time
      */
-    @ConfField public static int thrift_client_timeout_ms = 30000;
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/org/apache/doris/common/Config.java:322]: when will fe close the socket frequently?

Comment (francisoliverlee) [reply fe/fe-core/src/main/java/org/apache/doris/common/Config.java:322]: in our case, query information_schema.tables.  i find fe would send a TCP RST command(try tcpdump 9020 in fe) to be to close the socket becasuse of thrift_client_timeout_ms is meet, the be log comes "no more data to read", the be would retry in 1s(default).

**Review by imay — DISMISSED** [review]
LGTM

**Comment by caiconghui** [comment]
@francisoliverlee Please provide an issue related to this PR.

**Comment by francisoliverlee** [comment]
> @francisoliverlee Please provide an issue related to this PR.

https://github.com/apache/incubator-doris/issues/4824

**Review by caiconghui — DISMISSED** [review]
+1

File: fe/fe-core/src/main/java/org/apache/doris/common/Config.java [hunk 2]
```diff
@@ -318,8 +318,10 @@
      * The connection timeout and socket timeout config for thrift server
      * The value for thrift_client_timeout_ms is set to be larger than zero to prevent
      * some hang up problems in java.net.SocketInputStream.socketRead0
+     *
```
Comment (caiconghui) [inline fe/fe-core/src/main/java/org/apache/doris/common/Config.java:321]:
```
The connection timeout and socket timeout config for thrift server
The default value for thrift_client_timeout_ms is set to be zero to prevent readtimeout
```

 @ConfField public static int thrift_client_timeout_ms = 0;

**Review by caiconghui — APPROVED** [review]
+1
