### PR TITLE
[fix](scan) [fix](scan) _insert_data_normal should catch exception when BlockReader::_unique_key_next_block

### LINKED ISSUE #29387: [Bug] be crash in block scan
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.4-rc2

### What's Wrong?

image

### What You Expected?

not crash

### How to Reproduce?

I don't  known

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xingyingone**
[fix](scan) _insert_data_normal should catch exception when BlockReader::_unique_key_next_block

## Proposed changes

Issue Number: close #29387 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
run  buildall

File: be/src/vec/olap/block_reader.cpp [hunk 1]
```diff
@@ -429,12 +438,16 @@ Status BlockReader::_unique_key_next_block(Block* block, bool* eof) {
...
-                                                       _next_row.row_pos);
-    }
+
+    RETURN_IF_CATCH_EXCEPTION({
+        for (auto idx : _normal_columns_idx) {
+            columns[_return_columns_loc[idx]]->insert_from(*block->get_by_position(idx).column,
+                                                           _next_row.row_pos);
+        }
+    });
+    return Status::OK();
```
Comment (yiguolei) [inline be/src/vec/olap/block_reader.cpp:450]: line 450 is useless

File: be/src/vec/olap/block_reader.cpp [hunk 2]
```diff
@@ -325,7 +328,10 @@ Status BlockReader::_agg_key_next_block(Block* block, bool* eof) {
             _agg_data_counters.push_back(_last_agg_data_counter);
             _last_agg_data_counter = 0;
 
-            _insert_data_normal(target_columns);
+            auto status = _insert_data_normal(target_columns);
```
Comment (yiguolei) [inline be/src/vec/olap/block_reader.cpp:331]: RETURN_IF_ERROR(_insert_data_normal(target_columns));

**Comment by xingyingone** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM
