### PR TITLE
[Enhancement](Log) Reduce usage of log fatal(PART I)

### LINKED ISSUE #40835: [Enhancement](good first issue) Reduce usage of log fatal
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Except in storage layer exception, we should try best to avoid `LOG(FATAL)` which leads to BE crash.

### Solution

use `throw Exception` to replace them which not in `if constexpr`.
for those in `if constexpr else{...}`, use `static_assert` about template argument which used in that judgement to advance them to compile time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by linrrzqqq**
## Proposed changes

Issue Number: close #40835 

use `throw Exception` to replace them which not in `if constexpr`， and change part of `INTERNAL_ERROR` in this [pr](https://github.com/apache/doris/pull/38144/files)(file `aggregate_function_reader_first_last.h` and `aggregate_function_window.h`) to `FatalError`.
for those in `if constexpr else{...}`, use `static_assert` about template argument which used in that judgement to advance them to compile time

but there seems to be some bugs with the template parameter instantiation in the files `comparison_predicate.h`, `set_probe_sink_operator.cpp`, `set_sink_operator.cpp`,  `in_list_predicate.h` and `set_source_operator.cpp` that I haven't modified yet.

### CODE REVIEW

File: be/src/vec/functions/function_cast.h [hunk 1]
```diff
@@ -651,7 +651,7 @@ struct ConvertImplNumberToJsonb {
             } else if constexpr (std::is_same_v<ColumnFloat64, ColumnType>) {
                 writer.writeDouble(data[i]);
             } else {
-                LOG(FATAL) << "unsupported type ";
+                throw Exception(Status::NotSupported("unsupported type "));
```
Comment (zclllyybb) [inline be/src/vec/functions/function_cast.h:654]: for `if constexpr`, you can use `static_assert` rather than `throw`

File: be/src/common/elf.cpp [hunk 2]
```diff
@@ -40,21 +41,22 @@ Elf::Elf(const std::string& path) {
     std::error_code ec;
     elf_size = std::filesystem::file_size(_file, ec);
     if (ec) {
-        LOG(FATAL) << fmt::format("failed to get file size {}: ({}), {}", _file.native(),
-                                  ec.value(), ec.message());
+        throw Exception(Status::IOError("failed to get file size {}: ({}), {}", _file.native(),
```
Comment (zclllyybb) [inline be/src/common/elf.cpp:44]: please add a new error type. we can call it `FatalError`. and for all Exception changed from `LOG(FATAL)`, use it as the error code

File: build.sh [hunk 3]
```diff
@@ -551,8 +551,8 @@ FE_MODULES="$(
 
 # Clean and build Backend
 if [[ "${BUILD_BE}" -eq 1 ]]; then
-    update_submodule "be/src/apache-orc" "apache-orc" "https://github.com/apache/doris-thirdparty/archive/refs/heads/orc.tar.gz"
-    update_submodule "be/src/clucene" "clucene" "https://github.com/apache/doris-thirdparty/archive/refs/heads/clucene.tar.gz"
+    # update_submodule "be/src/apache-orc" "apache-orc" "https://github.com/apache/doris-thirdparty/archive/ads/clucene.tarefs/heads/orc.tar.gz"
```
Comment (zclllyybb) [inline build.sh:554]: don't commit this

File: be/src/olap/comparison_predicate.h [hunk 4]
```diff
@@ -524,7 +526,7 @@ class ComparisonPredicateBase : public ColumnPredicate {
                 _base_loop_bit<is_nullable, is_and>(sel, size, flags, null_map, data_array,
                                                     dict_code);
             } else {
-                LOG(FATAL) << "column_dictionary must use StringRef predicate.";
+                static_assert(!std::is_same_v<T, StringRef>, "column_dictionary must use StringRef predicate.");
```
Comment (zclllyybb) [inline be/src/olap/comparison_predicate.h:529]: we wrote `if constexpr (std::is_same_v<T, StringRef>)` upon
so here going into `else` means `T` is **not same** with `StringRef`. we want a failure here. so I think we should assert `std::is_same_v<T, StringRef>`, right?

Comment (Tobiichi-Origam1) [reply be/src/olap/comparison_predicate.h:529]: sorry I made a mistake here, and I have done fixing three similar errors in this file right away

File: be/src/gutil/port.h [hunk 5]
```diff
@@ -780,7 +780,7 @@ typedef int ssize_t;
 using std::ostream;
 inline ostream& operator<<(ostream& os, const unsigned __int64& num) {
     // Fake operator; doesn't actually do anything.
-    LOG(FATAL) << "64-bit ostream operator << not supported in VC++ 6";
+    throw Exception(Statsu::FatalError("64-bit ostream operator << not supported in VC++ 6"));
```
Comment (zclllyybb) [inline be/src/gutil/port.h:783]: here's a typo?

File: be/src/gutil/strings/escaping.cc [hunk 6]
```diff
@@ -899,8 +902,7 @@ int Base64UnescapeInternal(const char* src, int szsrc, char* dest, int szdest,
     // of data bytes that must remain in the input to avoid aborting the
     // loop.
 #define GET_INPUT(label, remain)                              \
-    label:                                                    \
-    --szsrc;                                                  \
+    label : --szsrc;                                          \
```
Comment (zclllyybb) [inline be/src/gutil/strings/escaping.cc:905]: dont re-format it if you didn't change

File: be/src/common/exception.cpp [hunk 7]
```diff
@@ -29,7 +29,8 @@ Exception::Exception(int code, const std::string_view& msg) {
         _err_msg->_stack = get_stack_trace();
     }
     if (config::exit_on_exception) {
-        LOG(FATAL) << "[ExitOnException] error code: " << code << ", message: " << msg;
+        throw Exception(
```
Comment (zclllyybb) [inline be/src/common/exception.cpp:32]: dont change this. we want always exit on exception here.

**Review by zclllyybb — CHANGES_REQUESTED** [review]
I think we should leave `dwarf.cpp`, `elf.cpp` and `gutil/port.h` as they are. dont patch this change on those filles.

File: be/src/gutil/strings/util.cc [hunk 8]
```diff
@@ -489,7 +491,7 @@ const char* strstr_delimited(const char* haystack, const char* needle, char deli
             ++haystack;
         }
     }
-    LOG(FATAL) << "Unreachable statement";
+    throw doris::Exception(doris::Status::FatalError("Unreachable statement"));
     return nullptr;
```
Comment (zclllyybb) [inline be/src/gutil/strings/util.cc:495]: remove this line

File: be/src/olap/in_list_predicate.h [hunk 9]
```diff
@@ -431,8 +431,8 @@ class InListPredicateBase : public ColumnPredicate {
                     }
                 }
             } else {
-                LOG(FATAL) << "column_dictionary must use StringRef predicate.";
-                __builtin_unreachable();
+                throw Exception(
```
Comment (zclllyybb) [inline be/src/olap/in_list_predicate.h:434]: use `static_assert`. or just not modify this in this PR

File: be/src/olap/key_coder.h [hunk 10]
```diff
@@ -300,7 +300,7 @@ class KeyCoderTraits<FieldType::OLAP_FIELD_TYPE_CHAR> {
     }
 
     static Status decode_ascending(Slice* encoded_key, size_t index_size, uint8_t* cell_ptr) {
-        LOG(FATAL) << "decode_ascending is not implemented";
+        throw Exception(Status::FatalError("decode_ascending is not implemented"));
         return Status::OK();
```
Comment (zclllyybb) [inline be/src/olap/key_coder.h:304]: remove the `return`s

File: be/src/olap/memtable.cpp [hunk 11]
```diff
@@ -28,6 +28,7 @@
 
 #include "bvar/bvar.h"
 #include "common/config.h"
+#include "common/exception.h"
```
Comment (zclllyybb) [inline be/src/olap/memtable.cpp:31]: remove this

File: be/src/vec/data_types/data_type_quantilestate.h [hunk 12]
```diff
@@ -94,9 +94,7 @@ class DataTypeQuantileState : public IDataType {
     Field get_default() const override { return QuantileState(); }
 
     [[noreturn]] Field get_field(const TExprNode& node) const override {
-        throw doris::Exception(ErrorCode::NOT_IMPLEMENTED_ERROR,
-                               "Unimplemented get_field for quantile state");
-        __builtin_unreachable();
+        throw Exception(Status::FatalError("Unimplemented get_field for quantile state"));
```
Comment (zclllyybb) [inline be/src/vec/data_types/data_type_quantilestate.h:97]: do not change this

File: be/src/vec/data_types/data_type_object.h [hunk 13]
```diff
@@ -87,7 +87,7 @@ class DataTypeObject : public IDataType {
         }
         std::stringstream error_string;
         node.printTo(error_string);
-        throw doris::Exception(ErrorCode::INTERNAL_ERROR, "Unkown literal {}", error_string.str());
+        throw Exception(Status::FatalError("Unkown literal {}", error_string.str()));
```
Comment (zclllyybb) [inline be/src/vec/data_types/data_type_object.h:90]: why change this

File: be/src/vec/functions/function_binary_arithmetic.h [hunk 14]
```diff
@@ -423,8 +423,8 @@ struct DecimalBinaryOperation {
 
         if constexpr (check_overflow && !is_to_null_type &&
                       ((!OpTraits::is_multiply && !OpTraits::is_plus_minus))) {
-            throw doris::Exception(ErrorCode::INTERNAL_ERROR,
-                                   "adapt_decimal_constant_constant Invalid function type!");
+            throw Exception(
```
Comment (zclllyybb) [inline be/src/vec/functions/function_binary_arithmetic.h:426]: do not change internal error to fatal error

File: be/src/pipeline/exec/operator.cpp [hunk 15]
```diff
@@ -398,8 +398,7 @@ std::shared_ptr<BasicSharedState> DataSinkOperatorX<LocalStateType>::create_shar
         return nullptr;
     } else if constexpr (std::is_same_v<typename LocalStateType::SharedStateType,
                                         MultiCastSharedState>) {
-        LOG(FATAL) << "should not reach here!";
-        return nullptr;
+        throw Exception(Status::FatalError("should not reach here!"));
```
Comment (zclllyybb) [inline be/src/pipeline/exec/operator.cpp:401]: try use `static_assert` for this

File: be/src/olap/tablet.cpp
Comment (zclllyybb) [inline be/src/olap/tablet.cpp:1]: dont change this file cuz it may lead to wrong data storage

File: be/src/olap/tablet_meta.cpp
Comment (zclllyybb) [inline be/src/olap/tablet_meta.cpp:1]: dont change this file cuz it may lead to wrong data storage

File: be/src/olap/storage_engine.cpp
Comment (zclllyybb) [inline be/src/olap/storage_engine.cpp:1]: dont change this file cuz it may lead to wrong data storage

File: be/test/testutil/test_util.cpp
Comment (zclllyybb) [inline be/test/testutil/test_util.cpp:1]: dont change this file

File: cloud/src/common/network_util.cpp
Comment (zclllyybb) [inline cloud/src/common/network_util.cpp:1]: dont change this file

**Review by zclllyybb — CHANGES_REQUESTED** [review]

File: be/src/util/expected.hpp
Comment (zclllyybb) [inline be/src/util/expected.hpp:1]: dont change this file

**Review by zclllyybb — CHANGES_REQUESTED** [review]

File: be/src/service/backend_options.cpp
Comment (zclllyybb) [inline be/src/service/backend_options.cpp:1]: dont change this file

File: be/src/vec/data_types/data_type_nothing.cpp
Comment (zclllyybb) [inline be/src/vec/data_types/data_type_nothing.cpp:1]: dont  change this

File: be/src/vec/olap/olap_data_convertor.h [hunk 16]
```diff
@@ -455,8 +455,8 @@ class OlapBlockDataConvertor {
 
         const void* get_data() const override { return _results.data(); };
         const void* get_data_at(size_t offset) const override {
-            LOG(FATAL) << "now not support get_data_at for OlapColumnDataConvertorArray";
-            __builtin_unreachable();
+            throw Exception(Status::FatalError(
```
Comment (zclllyybb) [inline be/src/vec/olap/olap_data_convertor.h:458]: use NOT_IMP for them

File: be/src/vec/exec/format/parquet/decoder.h [hunk 17]
```diff
@@ -79,8 +79,8 @@ class Decoder {
     }
 
     virtual MutableColumnPtr convert_dict_column_to_string_column(const ColumnInt32* dict_column) {
-        LOG(FATAL) << "Method convert_dict_column_to_string_column is not supported";
-        __builtin_unreachable();
+        throw Exception(
```
Comment (zclllyybb) [inline be/src/vec/exec/format/parquet/decoder.h:82]: use NOT_IMP for this

File: be/src/vec/exec/format/parquet/decoder.h [hunk 18]
```diff
@@ -79,7 +79,8 @@ class Decoder {
     }
 
     virtual MutableColumnPtr convert_dict_column_to_string_column(const ColumnInt32* dict_column) {
-        LOG(FATAL) << "Method convert_dict_column_to_string_column is not supported";
+        throw doris::Exception(ErrorCode::NOT_IMPLEMENTED_ERROR,
+                               "Method convert_dict_column_to_string_column is not supported");
         __builtin_unreachable();
```
Comment (zclllyybb) [inline be/src/vec/exec/format/parquet/decoder.h:84]: remove this line

File: be/src/vec/common/assert_cast.h [hunk 19]
```diff
@@ -45,33 +45,33 @@ PURE To assert_cast(From&& from) {
...
     };
 
 #ifndef NDEBUG
     try {
         return perform_cast(std::forward<From>(from));
     } catch (const std::exception& e) {
-        LOG(FATAL) << "assert cast err:" << e.what();
+        throw doris::Exception(doris::Status::FatalError("assert cast err:{}", e.what()));
     }
     __builtin_unreachable();
```
Comment (zclllyybb) [inline be/src/vec/common/assert_cast.h:68]: remove these two `__builtin_unreachable`, include L76

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run buildall

**Comment by linrrzqqq** [comment]
run p0

**Comment by linrrzqqq** [comment]
run p0

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]
