### PR TITLE
fix #9351 can't load parquet file with column name case sensitive with Doris column

### LINKED ISSUE #9351: [Bug] can't load parquet file with column name case sensitive with Doris column
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0-rc03

### What's Wrong?

doris table 
```
CREATE TABLE `record` (
 `id` varchar(50) NOT NULL ,
 `energySerial` varchar(3) NULL 
) ENGINE=OLAP
UNIQUE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 10;
```

```
LOAD LABEL test.record_20220502
( 
 DATA INFILE ("hdfs://172.0.0.9/tmp/part0.parq")
 INTO TABLE record format as parquet ( id,energyserial) 
 SET
 ( 
 id = id, 
energySerial = energyserial
 )
) WITH BROKER 'Broker_Doris' ( "username" = "hadoop" );
```

to show the key difference more clearly in sample above,
```
energySerial.toLowerCase() = energyserial
```

we get an load error msg like 
```
unknown reference column, column=energySerial, reference=energyserial 
```

we can't load that parquet column to doris

### What You Expected?

it could works

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by deardeng**
…h Doris column

# Proposed changes

Issue Number: close #9351 

## Problem Summary:

Describe the overview of changes.
1. change slotDescByName and exprMap to case insensitive map
2. change the realColName acquisition method

## Checklist(Required)

1. Does it affect the original behavior: No
3. Has unit tests been added: No Need
4. Has document been added or modified: No Need
5. Does it need to update dependencies: No
6. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java [hunk 1]
```diff
@@ -66,8 +66,8 @@ public class StreamLoadScanNode extends LoadScanNode {
     private TupleDescriptor srcTupleDesc;
     private TBrokerScanRange brokerScanRange;
 
-    private Map<String, SlotDescriptor> slotDescByName = Maps.newHashMap();
-    private Map<String, Expr> exprsByName = Maps.newHashMap();
+    private Map<String, SlotDescriptor> slotDescByName = Maps.newTreeMap(String.CASE_INSENSITIVE_ORDER);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java:69]: Better add comment to explain why we need CASE_INSENSITIVE_ORDER

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java [hunk 2]
```diff
@@ -1045,12 +1045,23 @@ private static void initColumns(Table tbl, List<ImportColumnDesc> columnExprs,
...
         for (ImportColumnDesc importColumnDesc : copiedColumnExprs) {
             // make column name case match with real column name
             String columnName = importColumnDesc.getColumnName();
-            String realColName = tbl.getColumn(columnName) == null ? columnName
-                    : tbl.getColumn(columnName).getName();
+            String realColName;
+            if (tbl.getColumn(columnName) == null || tmpSet.contains(columnName) ){
+                realColName = columnName;
+            } else {
+                    realColName = tbl.getColumn(columnName).getName();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1063]: `tbl.getColumn(columnName)` may be null here.

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java [hunk 3]
```diff
@@ -1045,12 +1045,23 @@ private static void initColumns(Table tbl, List<ImportColumnDesc> columnExprs,
             return;
         }
 
+        Set<String> tmpSet = Sets.newHashSet();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1048]: Better add comment to explain this logic.
Give an example is better.

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java [hunk 4]
```diff
@@ -1045,12 +1045,23 @@ private static void initColumns(Table tbl, List<ImportColumnDesc> columnExprs,
...
+        }
+
         // init slot desc add expr map, also transform hadoop functions
         for (ImportColumnDesc importColumnDesc : copiedColumnExprs) {
             // make column name case match with real column name
             String columnName = importColumnDesc.getColumnName();
-            String realColName = tbl.getColumn(columnName) == null ? columnName
-                    : tbl.getColumn(columnName).getName();
+            String realColName;
+            if (tbl.getColumn(columnName) == null || tmpSet.contains(columnName) ){
```
Comment (xy720) [inline fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1060]: It didn't make sense.
Only two case make tbl.getColumn(columnName) != null
1、The columnName match.
2、The columnName match with case insensitive.
And you already change exprMap to case insensitive map, so checking tmpSet.contains(columnName) seems no effect at all.

**Review by xy720 — COMMENTED** [review]
This bug actually has nothing to do with parquet format.
It is caused by the behavior that the user specifies a expr in the Set-Statement with the same name but different case as one of the column in table.

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java (hunk 4 above)
Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1060]: such case, 

CREATE TABLE `record` (
 `id` varchar(50) NOT NULL ,
 `SS` varchar(3) NULL 
) ENGINE=OLAP
UNIQUE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 10;

LOAD LABEL test.record
( 
 DATA INFILE ("hdfs://172.0.0.9/tmp/part0.parq")
 INTO TABLE record format as parquet
 (id, ss) 
 SET
 ( 
	id = id, 
	SS = ss
 )
) WITH BROKER 'Broker_Doris' ( "username" = "hadoop" );

copiedColumnExprs has entrys ("id", "ss", "id = id", "SS = ss"), 
exprMap has entrys ("id = id", "SS = ss"), 
tmpSet has keys ("id", "ss")

1. if don't check tmpSet.contains(columnName), realName will be SS. realName(SS) will be sent to BE. BE uses realName(SS) to match parquet file's SS column, and an error will be occur，parquet file's meta has only ss column
2. if use tmpSet.contains(columnName), realName will be ss

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java (hunk 2 above)
Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1063]: if tbl.getColumn(columnName) eq null, it will into line 1061, not here.

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java (hunk 3 above)
Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1048]: ok, I add some comments

File: fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java (hunk 1 above)
Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java:69]: For example, the column name 「A」 in the table and the mapping '(a) set (A = a)' in load sql， Slotdescbyname stores「a」, If Slotdescbyname case sensitive, later will use 「a」to get table's 「A」 column info, will throw exception.

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java (hunk 4 above)
Comment (xy720) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java:1060]: How about :
if (tbl.getColumn(columnName) == null || importColumnDesc.getExpr() == null){
    realColName = columnName;
} else {
    realColName = tbl.getColumn(columnName).getName();
}

File: fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java (hunk 1 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java:72]: What I mean is it would be better to add this comment in source file, so that other developer can understand it.

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java (hunk 2 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java]: My mistake, but please fix the code format(indent)

Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java]: done

File: fe/fe-core/src/main/java/org/apache/doris/load/Load.java (hunk 4 above)
Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/load/Load.java]: yes, it works and I change it.

File: fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java (hunk 1 above)
Comment (deardeng) [reply fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java]: done

**Review by xy720 — APPROVED** [review]
LGTM
