### PR TITLE
[fix](storage) Fix the bug of coredump when vec exec engine with delete condition

### LINKED ISSUE #8104: [Bug] [Vectorized] Core dump with query table have a `delete condition`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

vectorized

### What's Wrong?

vec block size is different with RowBlock v2 size， the mismatch cause the problem

### What You Expected?

query normal

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #8104 

## Problem Summary:

Fix coredump

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: （No)
5. Are there any changes that cannot be rolled back: (Yes)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/row_block2.cpp [hunk 1]
```diff
@@ -329,7 +329,8 @@ Status RowBlockV2::_copy_data_to_column(int cid, doris::vectorized::MutableColum
 }
 
 Status RowBlockV2::convert_to_vec_block(vectorized::Block* block) {
-    for (int i = 0; i < _schema.column_ids().size(); ++i) {
+    DCHECK_LE(block->columns(), _schema.column_ids().size());
+    for (int i = 0; i < block->columns(); ++i) {
```
Comment (wangbo) [inline be/src/olap/row_block2.cpp:333]: Maybe using ```schema.num_column_ids()```  instead of  ```block->columns()``` is better?

Comment (HappenLee) [reply be/src/olap/row_block2.cpp:333]: vec block column size is different with RowBlockV2 size, the mismatch cause the problem

**Review by wangbo — APPROVED** [review]
LGTM
