### PR TITLE
[opt](nereids) support prune partitions by specified tablet ids

### LINKED ISSUE #50255: [Bug] It does not prune partitions about querying one tablet of the table
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.7

### What's Wrong?

`explain select * from xx.table TABLET(12345) ;`

It does not do partition prunner and the partitions' number is not correct. The detail info is showing after the following screenshot.

Image

### What You Expected?

The partitions info can calculated by the specified tablet id.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhaorongsheng**
### What problem does this PR solve?

Issue Number: close #50255

support prune partitions by specified tablet ids

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanPartition.java [hunk 1]
```diff
@@ -49,65 +56,145 @@
...
+                            && scan.getTable().isPartitionedTable()
+                    )
+                    .thenApply(ctx -> {
+                        // Case1: sql without filter condition, e.g. SELECT * FROM tbl (${tabletID})
+                        LogicalOlapScan scan = ctx.root;
+                        OlapTable table = scan.getTable();
+                        return prunePartition(scan, table, null, ctx);
+                    }).toRule(RuleType.OLAP_SCAN_PARTITION_PRUNE),
+                logicalFilter(logicalOlapScan())
+                    .when(p -> !p.child().isPartitionPruned())
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanPartition.java:76]:
```suggestion
                logicalFilter(logicalOlapScan()
                    .whenNot(LogicalOlapScan::isPartitionPruned))
```

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanPartition.java [hunk 2]
```diff
@@ -49,65 +56,145 @@
...
+        if (prunedPartitionsByFilters != null) {
+            selectedPartitions.addAll(prunedPartitionsByFilters);
+        }
+
+        Set<Long> manuallySpecifiedTabletIds = ImmutableSet.copyOf(scan.getManuallySpecifiedTabletIds());
+        List<Long> selectPartitionIds = new ArrayList<>();
+        for (Partition partition : table.getPartitions()) {
+            if (!selectedPartitions.isEmpty() && !selectedPartitions.contains(partition.getId())) {
+                continue;
+            }
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanPartition.java:189]: remove local variable selectedPartitions and
```suggestion
            if (prunedPartitionsByFilters != null && !prunedPartitionsByFilters.contains(partition.getId()))) {
                continue;
            }
```

Comment (zhaorongsheng) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanPartition.java:189]: The type of `prunedPartitionsByFilters ` is `List`. The function `contains()` may cost too much if the list's length is high.

**Review by morrySnow — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Comment by 924060929** [comment]
run buildall
