### PR TITLE
[UT] Fix AlterTest UT failed

### LINKED ISSUE #3432: Dynamic partition UT bug
**Describe the bug**
UT org.apache.doris.alter.AlterTest#testConflictAlterOperations may failed in 
https://github.com/apache/incubator-doris/blob/09eb40e3560bd23ed2609f1878cb7fb33aa8b94e/fe/src/test/java/org/apache/doris/alter/AlterTest.java#L178
```
java.lang.NullPointerException
	at org.apache.doris.alter.AlterTest.testConflictAlterOperations(AlterTest.java:178)
```

Because p1 is null, show the tbl partitions
I get
```
partition_id: 10085; name: p20200429; partition_state.name: NORMAL; 
partition_id: 10150; name: p3; partition_state.name: NORMAL; 
partition_id: 10143; name: p20200430; partition_state.name: NORMAL; 
```
So dynamic partiton overwrited the origin partitions, p1 & p2 disappeared.

**To Reproduce**
Infrequently.

### PR DESCRIPTION
**Pull request by morningman**
Fix: #3432

### CODE REVIEW

File: fe/src/test/java/org/apache/doris/alter/AlterTest.java [hunk 1]
```diff
@@ -135,10 +135,10 @@ public void testConflictAlterOperations() throws Exception {
         waitSchemaChangeJobDone(true);
         
         // enable dynamic partition
+        // not adding the `start` property so that it won't drop the origin partition p1, p2 and p3
```
Comment (kangkaisen) [inline fe/src/test/java/org/apache/doris/alter/AlterTest.java:138]: Do we need a add another test case to cover the TTL(auto drop out of date partition) feature？

Comment (morningman) [reply fe/src/test/java/org/apache/doris/alter/AlterTest.java:138]: OK

**Review by kangkaisen — APPROVED** [review]
+1, LGTM
