### PR TITLE
[fix](planner)push constant expr in predicate to outer join's other conjuncts by mistake

### LINKED ISSUE #11526: [Bug] push constant expr in predicate to outer join's other conjuncts by mistake
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

- master
- 1.1.2
- 1.1.1
- 1.1.0

### What's Wrong?

push constant expr in predicate to outer join's other conjuncts by mistake

### What You Expected?

do not push constant expr in predicate to outer join's other conjuncts

### How to Reproduce?

```sql
CREATE TABLE if not EXISTS `wftest1` (
 `aa` varchar(200) NULL COMMENT "",
 `bb` int NULL COMMENT ""
) ENGINE = OLAP 
UNIQUE KEY (`aa`) COMMENT "aa" 
DISTRIBUTED BY HASH (`aa`) BUCKETS 3 PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);
 
CREATE TABLE if not EXISTS `wftest2` (
 `cc` varchar(200) NULL COMMENT "",
 `dd` int NULL COMMENT ""
) ENGINE = OLAP UNIQUE KEY (`cc`) COMMENT "cc" DISTRIBUTED BY HASH (`cc`) BUCKETS 3 PROPERTIES (
 "replication_allocation" = "tag.location.default: 1"
);

INSERT INTO  wftest1 VALUES ('a', 1), ('b', 1), ('c', 1);
INSERT INTO  wftest2 VALUES ('a', 1), ('b', 1), ('d', 1);

select t.* from (select  * from wftest1 t1 left join wftest2 t2 on t1.aa=t2.cc) t where dayofweek(current_date())=2; 
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #11526

## Problem summary

constant expr in predicate should not be pushed to outer join's other conjuncts

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: regression-test/suites/correctness/test_constant_push_down_through_outer_join.groovy [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+     sql """
+         INSERT INTO  wftest1 VALUES('a', 1), ('b', 1), ('c', 1);
+     """
+
+     sql """
+         INSERT INTO  wftest2 VALUES('a', 1), ('b', 1), ('d', 1);
+     """
+
+     order_qt_select """
+         select t.* from (select * from wftest1 t1 left join wftest2 t2 on t1.aa=t2.cc) t where dayofweek(current_date())=8;
```
Comment (Gabriel39) [inline regression-test/suites/correctness/test_constant_push_down_through_outer_join.groovy:58]: What should be returned for query `select * from wftest1 t1 left join wftest2 t2 on t1.aa=t2.cc and dayofweek(current_date())=8` ?

Comment (morrySnow) [reply regression-test/suites/correctness/test_constant_push_down_through_outer_join.groovy:58]: all rows of left table with all columns of right table filled by null.

**Review by morningman — APPROVED** [review]
LGTM
