### PR TITLE
[enhance]support alter table storage_medium

### LINKED ISSUE #49744: [Bug]  (good first issue) Support alter table storage_medium property
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris master

### What's Wrong?

Currently, modifying table storage_medium propertiy through SQL is not supported

please support it

```
CREATE TABLE `test` (
  `a` bigint NULL,
  `b` int NULL
) ENGINE=OLAP
UNIQUE KEY(`a`)
DISTRIBUTED BY HASH(`a`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

mysql> show create table test;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table

                                                                                                                                                                         |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test  | CREATE TABLE `test` (
  `a` bigint NULL,
  `b` int NULL
) ENGINE=OLAP
UNIQUE KEY(`a`)
DISTRIBUTED BY HASH(`a`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V2",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
); |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> ALTER TABLE test SET("storage_medium"="SSD");
ERROR 1105 (HY000): errCode = 2, detailMessage = Unknown table property: [storage_medium]

```

### What You Expected?

1. support ALTER TABLE test SET("storage_medium"="{storage_medium}");
2. add a regression test for it (or fe ut)

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cjj2010**
### What problem does this PR solve?

Issue Number: close #49744

Related PR: 

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. support alter table storage_medium 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [x] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by cjj2010** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ModifyTablePropertiesOp.java [hunk 1]
```diff
@@ -371,6 +371,9 @@ public void validate(ConnectContext ctx) throws UserException {
             throw new AnalysisException("You can not modify property 'enable_unique_key_skip_bitmap_column'.");
         } else if (properties.containsKey(PropertyAnalyzer.PROPERTIES_STORAGE_PAGE_SIZE)) {
             throw new AnalysisException("You can not modify storage_page_size");
+        } else if (properties.containsKey(PropertyAnalyzer.PROPERTIES_STORAGE_MEDIUM)) {
+            this.needTableStable = false;
+            this.opType = AlterOpType.MODIFY_TABLE_PROPERTY;
```
Comment (starocean999) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ModifyTablePropertiesOp.java:376]: other properties's opType is MODIFY_TABLE_PROPERTY_SYNC, please check if MODIFY_TABLE_PROPERTY is correct

**Comment by cjj2010** [comment]
run buildall

File: regression-test/suites/alter_p2/test_alter_table_property.groovy [hunk 2]
```diff
@@ -79,6 +79,13 @@ suite ("test_alter_table_property") {
     assertEquals(2, queryReplicaCount("p1"))
     assertEquals(replication_num, queryReplicaCount("p2"))
 
+    sql """ ALTER TABLE ${tableName} SET("storage_medium"="SSD") """
+
+    def result = sql "show create table ${tableName}"
```
Comment (deardeng) [inline regression-test/suites/alter_p2/test_alter_table_property.groovy:84]: please use `sql_return_maparray`

**Review by deardeng — CHANGES_REQUESTED** [review]

**Review by yujun777 — APPROVED** [review]
LGTM

File: regression-test/suites/alter_p2/test_alter_table_property.groovy (hunk 2 above)
Comment (cjj2010) [reply regression-test/suites/alter_p2/test_alter_table_property.groovy]: already fix ,thanks

**Comment by cjj2010** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM
