### PR TITLE
[fix](short circurt) fix return default value issue

### LINKED ISSUE #34056: [Bug] store row column, will get wrong result when query by SHORT-CIRCUIT
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

CREATE TABLE IF NOT EXISTS compaction_uniq_keys_row_store_regression_test1 (
                    `user_id` int NOT NULL COMMENT "用户id",
                    `date` DATE NOT NULL COMMENT "数据灌入日期时间",
                    `datev2` DATEV2 NOT NULL COMMENT "数据灌入日期时间",
                    `datetimev2_1` DATETIMEV2(3) NOT NULL COMMENT "数据灌入日期时间",
                    `datetimev2_2` DATETIMEV2(6) NOT NULL COMMENT "数据灌入日期时间",
                    `city` VARCHAR(20) COMMENT "用户所在城市",
                    `age` SMALLINT COMMENT "用户年龄",
                    `sex` TINYINT COMMENT "用户性别",
                    `last_visit_date` DATETIME DEFAULT "1970-01-01 00:00:00" COMMENT "用户最后一次访问时间",
                    `last_update_date` DATETIME DEFAULT "1970-01-01 00:00:00" COMMENT "用户最后一次更新时间",
                    `datetime_val1` DATETIMEV2(3) DEFAULT "1970-01-01 00:00:00.111" COMMENT "用户最后一次访问时间",
                    `datetime_val2` DATETIME(6) DEFAULT "1970-01-01 00:00:00" COMMENT "用户最后一次更新时间",
                    `last_visit_date_not_null` DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00" COMMENT "用户最后一次访问时间",
                    `cost` BIGINT DEFAULT "0" COMMENT "用户总消费",
                    `max_dwell_time` INT DEFAULT "0" COMMENT "用户最大停留时间",
                    `min_dwell_time` INT DEFAULT "99999" COMMENT "用户最小停留时间")
                UNIQUE KEY(`user_id`, `date`, `datev2`, `datetimev2_1`, `datetimev2_2`, `city`, `age`, `sex`) DISTRIBUTED BY HASH(`user_id`)
                PROPERTIES ( "replication_num" = "1", "enable_unique_key_merge_on_write" = "true", "light_schema_change" = "true",
                "store_row_column" = "true");

INSERT INTO compaction_uniq_keys_row_store_regression_test VALUES
                (3, '2017-10-01', '2017-10-01', '2017-10-01 11:11:11.027', '2017-10-01 11:11:11.017', 'Beijing', 10, 1, NULL, NULL, NULL, NULL, '2020-01-05', 1, 34, 20);

```
MySQL [test]> set experimental_enable_nereids_planner = true;Query OK, 0 rows affected (0.00 sec)

MySQL [test]> SELECT datetime_val1 FROM compaction_uniq_keys_row_store_regression_test t where user_id = 3 and date = '2017-10-01' and datev2 = '2017-10-01' and datetimev2_1 = '2017-10-01 11:11:11.027' and datetimev2_2 = '2017-10-01 11:11:11.017' and city = 'Beijing' and age = 10 and sex = 1;
+---------------+
| datetime_val1 |
+---------------+
| NULL          |
+---------------+
1 row in set (0.04 sec)

MySQL [test]>  SELECT datetime_val1 FROM compaction_uniq_keys_row_store_regression_test t where user_id = 3 and date = '2017-10-01' and datev2 = '2017-10-01' and datetimev2_1 = '2017-10-01 11:11:11.027' and datetimev2_2 = '2017-10-01 11:11:11.017' and city = 'Beijing' and age = 10;
+---------------+
| datetime_val1 |
+---------------+
| NULL          |
+---------------+
1 row in set (0.03 sec)

MySQL [test]> set experimental_enable_nereids_planner = false;
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> SELECT datetime_val1 FROM compaction_uniq_keys_row_store_regression_test t where user_id = 3 and date = '2017-10-01' and datev2 = '2017-10-01' and datetimev2_1 = '2017-10-01 11:11:11.027' and datetimev2_2 = '2017-10-01 11:11:11.017' and city = 'Beijing' and age = 10 and sex = 1;
+-------------------------+
| datetime_val1           |
+-------------------------+
| 1970-01-01 00:00:00.111 |
+-------------------------+
1 row in set (0.01 sec)

MySQL [test]>  SELECT datetime_val1 FROM compaction_uniq_keys_row_store_regression_test t where user_id = 3 and date = '2017-10-01' and datev2 = '2017-10-01' and datetimev2_1 = '2017-10-01 11:11:11.027' and datetimev2_2 = '2017-10-01 11:11:11.017' and city = 'Beijing' and age = 10;
+---------------+
| datetime_val1 |
+---------------+
| NULL          |
+---------------+
1 row in set (0.02 sec)

```

**when query by SHORT-CIRCUIT, will not get null but column default value**

### What You Expected?

return null

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by felixwluo**
## Proposed changes

Issue Number: close #34056

1. problem
`When using short circurt for point-checking, if a field in the table constructor clause has a default value and a NULL value is written later, the query returns the default value instead of the NULL value`

2. recurrence
```
CREATE TABLE IF NOT EXISTS test.test_001 (
    id int NOT NULL COMMENT "id",
    test_time DATETIMEV2(3) DEFAULT "1970-01-01 00:00:00.111" COMMENT "access time"
) UNIQUE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 1 PROPERTIES (
    "replication_num" = "1",
    "enable_unique_key_merge_on_write" = "true",
    "light_schema_change" = "true",
    "store_row_column" = "true"
);

insert into test.test_001 values (1, NULL);

set experimental_enable_nereids_planner = false;

select test_time from test.test_001 where id= 1;
```
The query result is 1970-01-01 00:00:00.111

3、after restoration
`Query returns NULL after repair`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by cjj2010 — COMMENTED** [review]
add a test column to verify this feature

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by cambyzju — DISMISSED** [review]
LGTM

**Review by eldenmoon — DISMISSED** [review]
LGTM

File: be/src/vec/jsonb/serialize.cpp [hunk 1]
```diff
@@ -107,7 +107,7 @@ void JsonbSerializeUtil::jsonb_to_block(const DataTypeSerDeSPtrs& serdes, const
             MutableColumnPtr col = column_type_name.column->assume_mutable();
             if (col->size() < num_rows + 1) {
                 DCHECK(col->size() == num_rows);
-                if (default_values[i].empty()) {
+                if (default_values[i].empty() || col->empty()) {
```
Comment (eldenmoon) [inline be/src/vec/jsonb/serialize.cpp:110]: maybe it's wrong, the col always empty for the start, so when `default_values[i]` is not emtpy, it may result incorrect value

**Comment by felixwluo** [comment]
run buildall

File: be/src/vec/data_types/serde/data_type_nullable_serde.cpp [hunk 2]
```diff
@@ -238,13 +238,14 @@ void DataTypeNullableSerDe::write_one_cell_to_jsonb(const IColumn& column, Jsonb
                                                     Arena* mem_pool, int32_t col_id,
                                                     int row_num) const {
     auto& nullable_col = assert_cast<const ColumnNullable&>(column);
+    result.writeKey(col_id);
     if (nullable_col.is_null_at(row_num)) {
         // do not insert to jsonb
```
Comment (eldenmoon) [inline be/src/vec/data_types/serde/data_type_nullable_serde.cpp:243]: remove this comment ，since null should be written

**Comment by eldenmoon** [comment]
run buildall

File: be/src/vec/data_types/serde/data_type_nullable_serde.cpp (hunk 2 above)
Comment (felixwluo) [reply be/src/vec/data_types/serde/data_type_nullable_serde.cpp]: done

**Comment by felixwluo** [comment]
run p0

**Comment by felixwluo** [comment]
run p0

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run p0

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by nextdreamblue — APPROVED** [review]
LGTM
