### PR TITLE
[fix] croaringbitmap compile support USE_AVX2=0

### LINKED ISSUE #10100: [Bug] When the 1.0.5-no-avx2 version queries data, the program crashes on the BE node
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

all version  of no-avx2 
Tested version:0.15.5-no-avx2
,1.0.0-preview2-no-avx2
,1.0.5-no-avx2

所有no-avx2发行的版本
已测试版本：0.15.5-no-avx2
,1.0.0-preview2-no-avx2
,1.0.5-no-avx2

### What's Wrong?

When we use the No-Avx2 version for data query, the BE node crashes directly
当我们使用No-Avx2版本进行数据查询时，BE节点直接崩溃

> Query example：

MYQL [fintell_poc]> select * from apply_info_v3;
ERROR 1064 (HY000): errCode = 2, detailMessage = there is no scanNode Backend. [10003: in black list(io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason)]`

> The log shows:

start time: Mon Jun 13 18:45:28 CST 2022
*** Aborted at 1655117413 (unix time) try "date -d @1655117413" if you are using GNU date ***
PC: @          0x352bf06 _avx2_run_container_cardinality.isra.0
*** SIGILL (@0x352bf06) received by PID 16929 (TID 0x7fae159fb700) from PID 55754502; stack trace: ***
    @          0x2f43f62 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fae19442630 (unknown)
    @          0x352bf06 _avx2_run_container_cardinality.isra.0
    @          0x3513a95 roaring_bitmap_get_cardinality
    @          0x1fe52d8 doris::segment_v2::SegmentIterator::_get_row_ranges_by_keys()
    @          0x1fe6cf1 doris::segment_v2::SegmentIterator::_init()
    @          0x1fe751e doris::segment_v2::SegmentIterator::next_batch()
    @          0x1805d34 doris::BetaRowsetReader::next_block()
    @          0x1764571 doris::CollectIterator::Level0Iterator::_refresh_current_row_v2()
    @          0x1765633 doris::CollectIterator::add_child()
    @          0x173a90f doris::Reader::_capture_rs_readers()
    @          0x1743d54 doris::Reader::init()
    @          0x1ea083e doris::OlapScanner::open()
    @          0x1e5ab9f doris::OlapScanNode::scanner_thread()
    @          0x18681af doris::PriorityThreadPool::work_thread()
    @          0x2f10737 thread_proxy
    @     0x7fae1943aea5 start_thread
    @     0x7fae18e61b0d __clone
    @                0x0 (unknown)
Connection closed`

### What You Expected?

A quick fix as we are planning to put it into production use.
快速的到解决，因为我们正在计划投入生产使用。

### How to Reproduce?

_No response_

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
Now third party package `CRoaring` will turn AVX2 dynamically.
We need to FORCE disable AVX2 while release `no-avx` Doris package.

# Proposed changes

Issue Number: close #10100 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
P0 regression failed

**Comment by cambyzju** [comment]
> P0 regression failed

Every body's P0 regression failed. It looks like the BE for regression is crashed.

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

File: thirdparty/build-thirdparty.sh [hunk 1]
```diff
@@ -787,7 +787,7 @@ build_bitshuffle() {
 build_croaringbitmap() {
     avx_flag=
     if [ ! -z "$USE_AVX2" -a "$USE_AVX2" -eq 0 ];then
-        echo "FORCE disable AVX for croaringbitmap"
+        echo "set USE_AVX2=$USE_AVX2 to FORCE disable AVX2 in croaringbitmap"
```
Comment (compiletheworld) [inline thirdparty/build-thirdparty.sh:790]: This prompt seems confusing, is it `disable` or `enable`?

Comment (cambyzju) [reply thirdparty/build-thirdparty.sh:790]: Only after set USE_AVX2=0, it will reach here.  It means disable AVX2.
Otherwise we will open AVX2 and there is no message printed.

**Review by yiguolei — APPROVED** [review]
LGTM
