### PR TITLE
[Bug] SimplifyInvalidDateBinaryPredicatesDateRule may cause invalid query plan

### LINKED ISSUE #5988: [Bug] query with date column predicate return empty set
**Describe the bug**
k1 is datetime type column.

SQL like: 
1. `select count(*) from tbl1 where k1 > '2021-6-1'`;
2. `select count(*) from tbl1 where k1 > to_date(now())`

will return empty set, which is not right.

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. "where 1k > to_date(now())" will return EMPTYSET in query plan.
2. DateLiteral should accept date string like "2021-6-1".

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #5988 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinghuayu007** [comment]
approved. I have  tested function `from_unixtime()`, but not function `to_date()`

File: fe/fe-core/src/main/java/org/apache/doris/rewrite/SimplifyInvalidDateBinaryPredicatesDateRule.java [hunk 1]
```diff
@@ -50,13 +52,29 @@ public Expr apply(Expr expr, Analyzer analyzer) throws AnalysisException {
         if (!valueExpr.isConstant()) {
             return expr;
         }
+
+        // This is not a very good implementation and tricky.
+        // We have to handle the following cases:
+        // A. k1 is datetime, sql with "k1 > to_date(now())" will be converted to k1 > cast(to_date("xxxx-xx-xx"))
+        // B. k1 is datetime, sql with "k1 > '2021-10-32 10:00:00.100010'" will be converted to k1 > cast('2021-10-32 10:00:00.100010' as datetime)
+        // C. k1 is datetime, sql with "k1 > '2021-10-32'" will be converted to k1 > cast('2021-10-32' as datetime)
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/rewrite/SimplifyInvalidDateBinaryPredicatesDateRule.java:60]: converted to null literal

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
