### PR TITLE
[Bug][Vectorized] Fix core bug of segment vectorized

### LINKED ISSUE #8799: [Bug] [vectorized-segment] Read bitmap/hll with default value error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Read bitmap/hll with default value error

### What You Expected?

normal

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
1. Read table with delete condition
2. Read table with default value HLL/Bitmap Column

# Proposed changes

Issue Number: close #8799 #8798 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/core/block.h [hunk 1]
```diff
@@ -104,6 +104,16 @@ class Block {
...
                                      uint16_t* sel_rowid_idx, uint16_t select_size, int block_cid,
                                      size_t batch_size) {
+        // Only the additional deleted filter condition need to materialize column be at the end of the block
+        // We should not to materialize the column of query engine do not need. So here just return OK.
+        // Eg:
+        //      `delete from table where a = 10;`
+        //      `select b from table;`
+        // a column only effective in segment iterator, the block from query engine only contain the b column.
+        // so the `block_cid >= data.size()` is true
+        if (block_cid >= data.size())
```
Comment (zenoyang) [inline be/src/vec/core/block.h:114]: After `_output_column_by_sel_idx` is executed, `Block::shrink_char_type_column_suffix_zero` may be executed, so it may be necessary to judge, for example

```cpp
void Block::shrink_char_type_column_suffix_zero(std::vector<size_t> char_type_idx) {
    for (auto idx : char_type_idx) {
        if (idx >= data.size()) {
            continue;
        }
        // ...
    }
}
```

Comment (HappenLee) [reply be/src/vec/core/block.h:114]: OK，I will fix it

**Review by zenoyang — COMMENTED** [review]
LGTM

**Review by wangbo — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM
