### PR TITLE
[enhancement] Optimize the fail logic of loading data when some backend failed

### LINKED ISSUE #7125: [enhancement] Optimize the fail logic of loading data when some backend failed
When loading data, when a tablet sink node writes data to other be, the logic for judging the write failure is that the total number of failed nodes exceeds half of the number of replicas, but a sink node may write multiple tablets, and the correct judgment is written The logic of entry failure is that the number of failed copies of each tablet exceeds half of the number of copies of this tablet

### PR DESCRIPTION
**Pull request by yangzhg**
mark the load job fail when more than a half of replica write failed of a tablet,
the code before is counting all replica has more than a half write failed.

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [x] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #7125) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/tablet_sink.h [hunk 1]
```diff
@@ -295,8 +305,10 @@ class IndexChannel {
     std::unordered_map<int64_t, NodeChannel*> _node_channels;
     // from tablet_id to backend channel
     std::unordered_map<int64_t, std::vector<NodeChannel*>> _channels_by_tablet;
+    // from backend channel to tablet_id
+    std::unordered_map<int64_t, std::set<int64_t>> _tablets_by_channel;
     // BeId
```
Comment (morningman) [inline be/src/exec/tablet_sink.h:310]: modify comment

File: be/src/exec/tablet_sink.h [hunk 2]
```diff
@@ -295,8 +305,10 @@ class IndexChannel {
     std::unordered_map<int64_t, NodeChannel*> _node_channels;
     // from tablet_id to backend channel
     std::unordered_map<int64_t, std::vector<NodeChannel*>> _channels_by_tablet;
+    // from backend channel to tablet_id
+    std::unordered_map<int64_t, std::set<int64_t>> _tablets_by_channel;
```
Comment (morningman) [inline be/src/exec/tablet_sink.h:309]:
```suggestion
    std::unordered_map<int64_t, std::unordered_set<int64_t>> _tablets_by_channel;
```

File: be/src/exec/tablet_sink.h [hunk 3]
```diff
@@ -295,8 +305,10 @@ class IndexChannel {
...
     // BeId
-    std::set<int64_t> _failed_channels;
+    std::unordered_map<int64_t, std::set<int64_t>> _failed_channels;
```
Comment (morningman) [inline be/src/exec/tablet_sink.h:311]:
```suggestion
    std::unordered_map<int64_t, std::unordered_set<int64_t>> _failed_channels;
```

**Review by morningman — APPROVED** [review]
LGTM
