### PR TITLE
[Fix](parquet-reader) Fix iceberg_schema_evolution regression test caused by slot col name different with parquet col name.

### LINKED ISSUE #17987: [Bug] Be crashed by iceberg_schema_evolution regression test.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### Description:
Be crashed by iceberg_schema_evolution regression test.
### FE log:
2023-03-21 02:04:35,024 [query] |Client=172.21.0.22:54966|User=root|Db=iceberg_schema_evolution|State=ERR|ErrorCode=1105|ErrorMessage=errCode = 2, detailMessage = query timeout|Time(ms)=300334|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=75243|QueryId=3bce0461a9c4c7f-ab523b1f728ed00b|IsQuery=true|feIp=172.21.0.31|Stmt=select * from rename_test where rename_1 in (3, 4) order by rename_1;|CpuTimeMS=0|SqlHash=51dd96367fb20f0fa73c6be8d3f16696|peakMemoryBytes=0|SqlDigest=|TraceId=|FuzzyVariables=batch_size=4064,disable_streaming_preaggregations=false,parallel_fragment_exec_instance_num=5,enable_pipeline_engine=false,enable_fold_constant_by_be=false,rewrite_or_to_in_predicate_threshold=2,enable_common_expr_pushdown=false,enable_local_exchange=true,partitioned_hash_join_rows_threshold=1048576,partitioned_hash_agg_rows_threshold=8,enable_share_hash_table_for_broadcast_join=true,external_sort_bytes_threshold=0,enable_two_phase_read_opt=true

### be.out
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

Query id: 3bce0461a9c4c7f-ab523b1f728ed00b ***
Aborted at 1679335175 (unix time) try "date -d @1679335175" if you are using GNU date ***
Current BE git commitID: 8ffc85b6ff ***
SIGABRT unknown detail explain (@0x2d4d7a) received by PID 2968954 (TID 2983127 OR 0x7fbab71e5700) from PID 2968954; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/doris_master/doris/be/src/common/signal_handler.h:413
 1# 0x00007FBF30B143C0 in /lib/x86_64-linux-gnu/libpthread.so.0
 2# raise in /lib/x86_64-linux-gnu/libc.so.6
 3# abort in /lib/x86_64-linux-gnu/libc.so.6
 4# _gnu_cxx::_verbose_terminate_handler() [clone .cold] in /mnt/ssd01/doris-master/VEC_UBSAN/be/lib/doris_be
 5# _cxxabiv1::_terminate(void ()) in /mnt/ssd01/doris-master/VEC_UBSAN/be/lib/doris_be
 6# 0x000055F5C6FEB581 in /mnt/ssd01/doris-master/VEC_UBSAN/be/lib/doris_be
 7# 0x000055F5C6FEB6D5 in /mnt/ssd01/doris-master/VEC_UBSAN/be/lib/doris_be
 8# std::__throw_out_of_range(char const*) in /mnt/ssd01/doris-master/VEC_UBSAN/be/lib/doris_be
 9# std::_detail::_Map_base<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>, std::allocator<std::pair<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >, std::detail::_Select1st, std::equal_to<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::detail::_Mod_range_hashing, std::detail::_Default_ranged_hash, std::detail::_Prime_rehash_policy, std::detail::_Hashtable_traits<true, false, true>, true>::at(std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const at /var/local/ldb_toolchain/include/c++/11/bits/hashtable_policy.h:776
10# std::unordered_map<std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::at(std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const at /var/local/ldb_toolchain/include/c++/11/bits/unordered_map.h:1001
11# doris::vectorized::RowGroupReader::can_filter_by_dict(std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tparquet::ColumnMetaData const&) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:127
12# doris::vectorized::RowGroupReader::init(doris::vectorized::FieldDescriptor const&, std::vector<doris::vectorized::RowRange, std::allocator<doris::vectorized::RowRange> >&, std::unordered_map<int, tparquet::OffsetIndex, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, tparquet::OffsetIndex> > >&, doris::TupleDescriptor const*, doris::RowDescriptor const*, std::unordered_map<std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const*, std::vector<doris::vectorized::VExprContext*, std::allocator<doris::vectorized::VExprContext*> > const*, std::unordered_map<int, std::vector<doris::vectorized::VExprContext*, std::allocator<doris::vectorized::VExprContext*> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, std::vector<doris::vectorized::VExprContext*, std::allocator<doris::vectorized::VExprContext*> > > > > const*) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:106
13# doris::vectorized::ParquetReader::_next_row_group_reader() at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_reader.cpp:490
14# doris::vectorized::ParquetReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_reader.cpp:418
15# doris::vectorized::IcebergTableReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/table/iceberg_reader.cpp:103
16# doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/scan/vfile_scanner.cpp:204
17# doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/scan/vscanner.cpp:69
18# doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, doris::vectorized::VScanner*) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/scan/scanner_scheduler.cpp:306
19# doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}::operator()() const at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/scan/scanner_scheduler.cpp:192
20# void std::_invoke_impl<void, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}&>(std::_invoke_other, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}&) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
21# std::enable_if<is_invocable_r_v<void, doris::vectorized::ScannerScheduler::schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}&>, void>::type std::_invoke_r<void, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}&>(doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}&) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:117
22# std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::{lambda()#1}::operator()() const::{lambda()#3}>::_M_invoke(std::_Any_data const&) at /var/local/ldb_toolchain/include/c++/11/bits/std_function.h:292
23# std::function<void ()>::operator()() const at /var/local/ldb_toolchain/include/c++/11/bits/std_function.h:560
24# doris::FunctionRunnable::run() at /home/zcp/repo_center/doris_master/doris/be/src/util/threadpool.cpp:46
25# doris::ThreadPool::dispatch_thread() at /home/zcp/repo_center/doris_master/doris/be/src/util/threadpool.cpp:537
26# void std::_invoke_impl<void, void (doris::ThreadPool::&)(), doris::ThreadPool&>(std::_invoke_memfun_deref, void (doris::ThreadPool::&)(), doris::ThreadPool&) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:74
27# std::_invoke_result<void (doris::ThreadPool::&)(), doris::ThreadPool&>::type std::_invoke<void (doris::ThreadPool::&)(), doris::ThreadPool&>(void (doris::ThreadPool::&)(), doris::ThreadPool&) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:97
28# void std::Bind<void (doris::ThreadPool::(doris::ThreadPool))()>::_call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) at /var/local/ldb_toolchain/include/c++/11/functional:422
29# void std::_Bind<void (doris::ThreadPool::(doris::ThreadPool))()>::operator()<, void>() at /var/local/ldb_toolchain/include/c++/11/functional:505
30# void std::_invoke_impl<void, std::_Bind<void (doris::ThreadPool::(doris::ThreadPool))()>&>(std::_invoke_other, std::_Bind<void (doris::ThreadPool::(doris::ThreadPool))()>&) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
31# std::enable_if<is_invocable_r_v<void, std::Bind<void (doris::ThreadPool::(doris::ThreadPool))()>&>, void>::type std::_invoke_r<void, std::_Bind<void (doris::ThreadPool::(doris::ThreadPool))()>&>(std::_Bind<void (doris::ThreadPool::(doris::ThreadPool))()>&) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:117
32# std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::(doris::ThreadPool))()> >::_M_invoke(std::_Any_data const&) at /var/local/ldb_toolchain/include/c++/11/bits/std_function.h:292
33# std::function<void ()>::operator()() const at /var/local/ldb_toolchain/include/c++/11/bits/std_function.h:560
34# doris::Thread::supervise_thread(void*) at /home/zcp/repo_center/doris_master/doris/be/src/util/thread.cpp:454
35# start_thread at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:478
36# __clone in /lib/x86_64-linux-gnu/libc.so.6

### What You Expected?

Iceberg_schema_evolution regression test run succeed.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kaka11chen**
# Proposed changes

Issue Number: close #17987 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.86 seconds
 stream load tsv:          477 seconds loaded 74807831229 Bytes, about 149 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230321195611_clickbench_pr_118136.html

File: be/src/vec/exec/format/parquet/vparquet_group_reader.cpp [hunk 1]
```diff
@@ -290,27 +292,28 @@ Status RowGroupReader::_read_column_data(Block* block, const std::vector<std::st
...
+                            std::make_shared<DataTypeNullable>(std::make_shared<DataTypeInt32>());
+                    block->replace_by_position(
+                            pos,
+                            ColumnNullable::create(std::move(dict_column),
+                                                   ColumnUInt8::create(dict_column->size(), 0)));
+                } else {
+                    block->get_by_position(pos).type = std::make_shared<DataTypeInt32>();
+                    block->replace_by_position(pos, std::move(dict_column));
+                }
+                is_dict_filter = true;
```
Comment (morningman) [inline be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:315]: Missing break.
And please add some comment to explain why using id, not name

Comment (kaka11chen) [reply be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:315]: ok

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM
