### PR TITLE
[BUG][Profile] Fixed the problem that BE's profile could not add chil…

### LINKED ISSUE #6267: [BUG] BE Profile add child profile won't add to first location
**To Reproduce**
```
 // for any exec_node
 runtime_profile()->add_child(TESTProfile, false, nullptr);
```
profile is 
```
> XXXNode:
          Profile1
          TESTProfile
          Profile2
```

**Expected behavior**
```
> XXXNode:
          TESTProfile
          Profile1
          Profile2
```

### PR DESCRIPTION
**Pull request by stdpain**
…d profile in the specified correct location

bug:
    runtime_profile()->add_child(build_phase_profile, false, nullptr);
    child profile will add to second location

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6267 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/util/runtime_profile.cpp [hunk 1]
```diff
@@ -297,15 +297,15 @@ RuntimeProfile* RuntimeProfile::create_child(const std::string& name, bool inden
...
     _child_map[child->_name] = child;
 
-    if (loc == NULL) {
+    if (loc == nullptr) {
         _children.push_back(std::make_pair(child, indent));
     } else {
         for (ChildVector::iterator it = _children.begin(); it != _children.end(); ++it) {
             if (it->first == loc) {
-                _children.insert(++it, std::make_pair(child, indent));
+                _children.insert(it++, std::make_pair(child, indent));
```
Comment (morningman) [inline be/src/util/runtime_profile.cpp:308]: Seems no need to plus? because we return directly.

Comment (stdpain) [reply be/src/util/runtime_profile.cpp]: Right! I have Fixed It

**Review by morningman — APPROVED** [review]
LGTM
