### PR TITLE
[cloud](Variant) Optimize FDB kv size for Variant rowsets and update schema on compaction

### LINKED ISSUE #33297: [Optimize] Optimize FDB kv size for Variant rowsets and update schema on compaction
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.1

### Issue 1: FDB Transaction Timeout with Variant in Cloud
Currently, Variant writes an `fdb kv` for each `rowset`'s `TabletSchema` upon `commit_rowset`. This approach is due to the schema's granularity being at the rowset level, with each rowset potentially having a unique schema. However, when the number of rowsets exceeds 1000, `get_rowset` operations may face FDB transaction timeouts due to large kv sizes (exceeding 100K), leading to read times over 10ms. To address this, there's a need to optimize the kv size to prevent timeouts, targeting a size reduction to <2k.

### Issue 2: Schema Not Updated on Compaction
The compaction process does not update the schema, potentially merging multiple rowset schemas into a new one without accurately reflecting the changes. This results in inconsistencies and incorrect schema representations in the output rowset.

## Proposed Fix
To reduce the space occupied by `TabletSchema`, which is largely consumed by the `column` and `index` fields, a dictionary compression method is proposed. By encoding these fields into dictionary keys, we can significantly decrease the storage space required. This involves modifications to the `RowsetMetaCloudPB` and the introduction of a `SchemaCloudDictionary` to manage the dictionary keys and ensure efficient storage utilization.

```
message RowsetMetaCloudPB {
  ...
  repeated int32 column_dict_key_list = 26;
  ...
}

message SchemaCloudDictionary {
  map<int32, ColumnPB> column_dict = 1;
  optional int64 current_column_index = 2;
  map<int32, TabletIndexPB> index_dict = 3;
  optional int64 current_index_index = 2;
}

```

### What You Expected?

optimize the size of schema kv for variant

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eldenmoon**
Currently, Variant writes an `fdb kv` for each `rowset`'s `TabletSchema` upon `commit_rowset`. This approach is due to the schema's granularity being at the rowset level, with each rowset potentially having a unique schema. However, when the number of rowsets exceeds 1000, `get_rowset` operations may face FDB transaction timeouts due to large kv sizes (exceeding 100K), leading to read times over 10ms. To address this, there's a need to optimize the kv size to prevent timeouts, targeting a size reduction to <2k.

The compaction process does not update the schema, potentially merging multiple rowset schemas into a new one without accurately reflecting the changes. This results in inconsistencies and incorrect schema representations in the output rowset.

To reduce the space occupied by `TabletSchema`, which is largely consumed by the `column` and `index` fields, a dictionary compression method is proposed. By encoding these fields into dictionary keys, we can significantly decrease the storage space required. This involves modifications to the `RowsetMetaCloudPB` and the introduction of a `SchemaCloudDictionary` to manage the dictionary keys and ensure efficient storage utilization.

```
message RowsetMetaCloudPB {
  ...
  repeated int32 column_dict_key_list = 26;
  ...
}

message SchemaCloudDictionary {
  map<int32, ColumnPB> column_dict = 1;
  optional int64 current_column_index = 2;
  map<int32, TabletIndexPB> index_dict = 3;
  optional int64 current_index_index = 2;
}

```

## Proposed changes

Issue Number: close #33297

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

File: cloud/src/recycler/recycler.cpp [hunk 1]
```diff
@@ -1151,13 +1151,19 @@ int InstanceRecycler::recycle_tablets(int64_t table_id, int64_t index_id, int64_
...
     if (partition_id <= 0) {
         // Delete schema kv of this index
         meta_schema_key({instance_id_, index_id, 0}, &schema_key_begin);
         meta_schema_key({instance_id_, index_id + 1, 0}, &schema_key_end);
         txn->remove(schema_key_begin, schema_key_end);
         LOG(WARNING) << "remove schema kv, begin=" << hex(schema_key_begin)
                      << " end=" << hex(schema_key_end);
+        meta_schema_pb_dictionary_key({instance_id_, index_id}, &schema_dict_key_begin);
+        meta_schema_pb_dictionary_key({instance_id_, index_id + 1}, &schema_dict_key_end);
+        txn->remove(schema_dict_key_begin, schema_dict_key_end);
```
Comment (w41ter) [inline cloud/src/recycler/recycler.cpp:1164]: There is only one key here, no need to remove the range.

File: be/src/cloud/pb_convert.cpp [hunk 2]
```diff
@@ -134,19 +137,55 @@ void doris_rowset_meta_to_cloud(RowsetMetaCloudPB* out, RowsetMetaPB&& in) {
...
+RowsetMetaPB cloud_rowset_meta_to_doris(RowsetMetaCloudPB&& in,
+                                        std::optional<SchemaCloudDictionary> dict) {
     RowsetMetaPB out;
-    cloud_rowset_meta_to_doris(&out, std::move(in));
+    cloud_rowset_meta_to_doris(&out, std::move(in), dict);
     return out;
 }
 
-void cloud_rowset_meta_to_doris(RowsetMetaPB* out, const RowsetMetaCloudPB& in) {
+static void fill_schema_with_dict(const RowsetMetaCloudPB& in, RowsetMetaPB* out,
```
Comment (w41ter) [inline be/src/cloud/pb_convert.cpp:154]: Move it into `MetaServiceImpl::get_rowset` so BE doesn't need to know the `SchemaCloudDictionary `.

**Review by w41ter — CHANGES_REQUESTED** [review]

File: be/src/cloud/pb_convert.cpp (hunk 2 above)
Comment (eldenmoon) [reply be/src/cloud/pb_convert.cpp:154]: @gavinchou  required, pls take a look

File: cloud/src/meta-service/keys.cpp [hunk 3]
```diff
@@ -312,6 +305,12 @@ void meta_pending_delete_bitmap_key(const MetaPendingDeleteBitmapInfo& in, std::
     encode_int64(std::get<1>(in), out);                      // table_id
 }
 
+void meta_schema_pb_dictionary_key(const MetaSchemaPBDictionaryInfo& in, std::string* out) {
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/keys.cpp:308]: done

File: cloud/src/recycler/recycler.cpp (hunk 1 above)
Comment (eldenmoon) [reply cloud/src/recycler/recycler.cpp]: done

File: be/src/cloud/pb_convert.cpp (hunk 2 above)
Comment (eldenmoon) [reply be/src/cloud/pb_convert.cpp]: done

**Comment by eldenmoon** [comment]
run buildall

File: cloud/src/meta-service/meta_service_schema.h [hunk 4]
```diff
@@ -30,4 +30,17 @@ void put_schema_kv(MetaServiceCode& code, std::string& msg, Transaction* txn,
 // Return true if parse success
 [[nodiscard]] bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema);
 
+// Writes schema dictionary metadata to RowsetMetaCloudPB
+[[nodiscard]] std::pair<MetaServiceCode, std::string> write_schema_dict(
+            const std::string& instance_id,
+            Transaction* txn,
+            RowsetMetaCloudPB* rowset_meta);
+
+// Writes schema dictionary metadata to RowsetMetaCloudPB
```
Comment (w41ter) [inline cloud/src/meta-service/meta_service_schema.h:39]: Read?

**Review by w41ter — COMMENTED** [review]
Reset LGTM

File: cloud/src/meta-service/meta_service_schema.h (hunk 4 above)
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.h]: fixed

**Comment by eldenmoon** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 5]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+                dict.set_current_index_dict_id(current_dict_id);
+                dict.mutable_index_dict()->emplace(current_dict_id, item);
+            }
+            add_dict_key_fn(current_dict_id);
+            reversed_dict[serialized_key] = current_dict_id;
+            // LOG(INFO) << "Add dict key = " << current_dict_id << " dict value = " << item.ShortDebugString();
+        }
+    }
+    if (result != nullptr) {
+        result->Swap(&none_ext_items);
```
Comment (xiaokang) [inline cloud/src/meta-service/meta_service_schema.cpp:192]: What's the purpose to replace columns/indexes by new ones without dict.

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 6]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
 }
 
+// Map item to dictionary key, and add key to rowset meta, if it is a new one, generate it and increase item id
+// Need to remove dynamic parts from original RowsetMeta's TabletSchema, to make fdb schema kv stable
+template<typename ItemPB>
+void process_dictionary(
+    SchemaCloudDictionary& dict,
+    const google::protobuf::Map<int32_t, ItemPB>& item_dict,
+    google::protobuf::RepeatedPtrField<ItemPB>* result,
+    RowsetMetaCloudPB* rowset_meta,
```
Comment (xiaokang) [inline cloud/src/meta-service/meta_service_schema.cpp:138]: rowset_meta is not used in this function.

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 7]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
     return buf.to_pb(schema);
 }
 
+// Map item to dictionary key, and add key to rowset meta, if it is a new one, generate it and increase item id
+// Need to remove dynamic parts from original RowsetMeta's TabletSchema, to make fdb schema kv stable
+template<typename ItemPB>
+void process_dictionary(
+    SchemaCloudDictionary& dict,
+    const google::protobuf::Map<int32_t, ItemPB>& item_dict,
```
Comment (xiaokang) [inline cloud/src/meta-service/meta_service_schema.cpp:136]: suggestion for more readable: rename to column_or_index_dict or add comment

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 8]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+    google::protobuf::RepeatedPtrField<ItemPB>* result,
```
Comment (xiaokang) [inline cloud/src/meta-service/meta_service_schema.cpp:137]: suggestion for more readable: rename to mutable_columns_or_indexes or add comment

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 9]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+    RowsetMetaCloudPB* rowset_meta,
+    const google::protobuf::RepeatedPtrField<ItemPB>& items,
```
Comment (xiaokang) [inline cloud/src/meta-service/meta_service_schema.cpp:139]: suggestion for more readable: rename to columns_or_indexes or add comment

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 10]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+              << " key=" << hex(dict_key) << " error=" << err;
+    if (err != TxnErrorCode::TXN_KEY_NOT_FOUND && err != TxnErrorCode::TXN_OK) {
+        // Handle retrieval error.
+        ss << "Failed to retrieve column pb dictionary, instance_id=" << instance_id
+           << " table_id=" << rowset_meta->index_id() << " key=" << hex(dict_key) << " error=" << err;
+        msg = ss.str();
+        code = cast_as<ErrCategory::READ>(err);
+        return {code, msg};
+    } 
+    if (err != TxnErrorCode::TXN_KEY_NOT_FOUND && !dict_val.to_pb(&dict)) {
```
Comment (xiaokang) [inline cloud/src/meta-service/meta_service_schema.cpp:221]: check TXN_OK directly

File: cloud/src/meta-service/meta_service_schema.cpp (hunk 5 above)
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:192]: clear extended columns/indexes to prevent writing them to fdb kv

File: cloud/src/meta-service/meta_service.cpp [hunk 11]
```diff
@@ -1080,14 +1081,11 @@ void MetaServiceImpl::commit_rowset(::google::protobuf::RpcController* controlle
...
-        if (rowset_meta.has_variant_type_in_schema()) {
-            // encodes schema in a seperate kv, since variant schema is volatile
-            schema_key = meta_rowset_schema_key(
-                    {instance_id, rowset_meta.tablet_id(), rowset_meta.rowset_id_v2()});
-        } else {
-            schema_key = meta_schema_key(
+        std::string schema_key = meta_schema_key(
                     {instance_id, rowset_meta.index_id(), rowset_meta.schema_version()});
+        if (rowset_meta.has_variant_type_in_schema()) {
+            std::tie(code, msg) = write_schema_dict(instance_id, txn.get(), &rowset_meta);
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service.cpp:1087]: no, they are in the same transaction, both using txn.get()

File: be/src/olap/rowset/segment_v2/segment.cpp [hunk 12]
```diff
@@ -413,10 +413,12 @@ Status Segment::_create_column_readers(const SegmentFooterPB& footer) {
     // init by column path
     for (uint32_t ordinal = 0; ordinal < _tablet_schema->num_columns(); ++ordinal) {
         auto& column = _tablet_schema->column(ordinal);
-        if (!column.has_path_info()) {
+        if (!column.has_path_info() && !column.is_variant_type()) {
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply be/src/olap/rowset/segment_v2/segment.cpp:416]: modified

File: cloud/src/meta-service/meta_service_schema.h [hunk 13]
```diff
@@ -30,4 +30,17 @@ void put_schema_kv(MetaServiceCode& code, std::string& msg, Transaction* txn,
 // Return true if parse success
 [[nodiscard]] bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema);
 
+// Writes schema dictionary metadata to RowsetMetaCloudPB
+[[nodiscard]] std::pair<MetaServiceCode, std::string> write_schema_dict(
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.h:34]: OK

File: cloud/src/meta-service/meta_service.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service.cpp:1087]: and commit in later logic

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 14]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+    google::protobuf::RepeatedPtrField<ColumnPB> sparse_columns;
+    for (auto& column_pb : *rowset_meta->mutable_tablet_schema()->mutable_column()) {
+        if (column_pb.type() == "VARIANT" && !column_pb.sparse_columns().empty()) {
+            // set parent_id for restore info
+            for (auto& sparse_col: *column_pb.mutable_sparse_columns()) {
+                sparse_col.set_parent_unique_id(column_pb.unique_id());
+            }
+            sparse_columns.Add(column_pb.sparse_columns().begin(), column_pb.sparse_columns().end());
+        }
+        column_pb.clear_sparse_columns();
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:238]: prevent write to fdb

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 15]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+        // Handle parse error.
+        code = MetaServiceCode::PROTOBUF_PARSE_ERR;
+        msg = fmt::format("Malformed tablet dictionary value, key={}", hex(dict_key));
+        return {code, msg};
+    }
+
+    // collect sparse columns and clear in parent column
+    google::protobuf::RepeatedPtrField<ColumnPB> sparse_columns;
+    for (auto& column_pb : *rowset_meta->mutable_tablet_schema()->mutable_column()) {
+        if (column_pb.type() == "VARIANT" && !column_pb.sparse_columns().empty()) {
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:231]: done

File: cloud/src/meta-service/meta_service_schema.cpp (hunk 7 above)
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:136]: maybe not only column or index will be processed

File: cloud/src/meta-service/meta_service_schema.cpp (hunk 8 above)
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:137]: maybe not only column or index will be processed

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 16]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+    std::string column_dict_key = meta_schema_pb_dictionary_key({instance_id, index_id});
+    ValueBuf dict_val;
+    auto err = cloud::get(txn, column_dict_key, &dict_val);
+    if (err != TxnErrorCode::TXN_OK && err != TxnErrorCode::TXN_KEY_NOT_FOUND) {
+        code = cast_as<ErrCategory::READ>(err);
+        ss << "internal error, failed to get dict ret=" << err;
+        msg = ss.str();
+        return {code, msg};
+    }
+    if (err == TxnErrorCode::TXN_OK && !dict_val.to_pb(&dict)) [[unlikely]] {
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:317]: the dict key list and dict itself will be ignored

File: cloud/src/meta-service/meta_service_schema.cpp (hunk 10 above)
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:221]: done

File: cloud/src/meta-service/meta_service_schema.cpp (hunk 9 above)
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:139]: comment added

File: cloud/src/meta-service/meta_service_schema.cpp [hunk 17]
```diff
@@ -119,4 +128,239 @@ bool parse_schema_value(const ValueBuf& buf, doris::TabletSchemaCloudPB* schema)
...
+    process_dictionary<doris::TabletIndexPB>(dict, dict.index_dict(),
+            rowset_meta->mutable_tablet_schema()->mutable_index(),
+                    rowset_meta, rowset_meta->tablet_schema().index(),
+                    index_filter, index_dict_adder);
+
+    // Write back modified dictionaries.
+    if (original_index_dict_id != dict.current_index_dict_id()
+            || original_column_dict_id != dict.current_column_dict_id()) {
+        // If dictionary was modified, serialize and save it.
+        std::string dict_key = meta_schema_pb_dictionary_key({instance_id, rowset_meta->index_id()});
```
[the remark this answers is not in the document]
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:271]: removed duplicated

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

File: cloud/src/meta-service/meta_service_schema.cpp
Comment (gavinchou) [inline cloud/src/meta-service/meta_service_schema.cpp:1]: all newly added code should be tested by UTs: line coverage 90%, func cov 100%, branch 90%

**Review by gavinchou — CHANGES_REQUESTED** [review]

File: cloud/src/meta-service/meta_service_schema.cpp
Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:1]: regression test could cover 90%+ line coverage func cov and branch

Comment (eldenmoon) [reply cloud/src/meta-service/meta_service_schema.cpp:1]: done

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM
