### PR TITLE
[Colocate] Fix bug that colocate group can not be redistributed after dropping a backend

### LINKED ISSUE #7019: [Bug] Colocate group can not redistributed after dropping a backend
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.0-rc01

### What's Wrong?

After dropping a backend. The colocation group can not be redistributed.
And also can not add partition to these colocated table because the Backend specified in colocation group does not exist

### What You Expected?

The colocation group can be redistributed.

### How to Reproduce?

Create a colocate table. Then drop a backend.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Mainly changes:
1. Fix #7019 
2. Add detail msg about why a colocate group is unstable.
3. Add more suggestion when upgrading Doris cluster.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #7019 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateTableIndex.java [hunk 1]
```diff
@@ -206,13 +207,14 @@ public void addBackendsPerBucketSeqByTag(GroupId groupId, Tag tag, List<List<Lon
         }
     }
 
-    public void markGroupUnstable(GroupId groupId, boolean needEditLog) {
+    public void markGroupUnstable(GroupId groupId, String reason, boolean needEditLog) {
```
Comment (yangzhg) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateTableIndex.java:210]: Using error codes or string constants may be better than literal values

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateTableIndex.java:210]: Error code is not necessary. Because currently this reason is only for human reading.
I tried to use string constants. But reason like:
`get unhealthy tablet %d in colocate table. status: %s`
is dynamic changed.
So not all reasons can be constants

**Review by yangzhg — APPROVED** [review]
LGTM
