### PR TITLE
[fix](planner)VecNotImplException thrown when query need rewrite and some slot cannot changed to nullable

### LINKED ISSUE #9588: [Bug] VecNotImplException thrown when query need rewrite and some slot cannot changed to nullable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

VecNotImplException thrown when query need rewrite and some slot cannot changed to nullable

### What You Expected?

query passed

### How to Reproduce?

could reproduced by:

```sql
create table test.tbl1
(k1 int, k2 int, v1 int)
distributed by hash(k1)
properties("replication_num" = "1");

explain select * from test.tbl1 t1 where (select count(*) from test.tbl1 t2 where t1.k1 = t2.k1) > 0;
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morrySnow**
…some slot cannot changed to nullable

# Proposed changes

Issue Number: close #9588

## Problem Summary:

Could reproduced by:

```sql
create table test.tbl1
(k1 int, k2 int, v1 int)
distributed by hash(k1)
properties("replication_num" = "1");

explain select * from test.tbl1 t1 where (select count(*) from test.tbl1 t2 where t1.k1 = t2.k1) > 0;
```

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/common/util/VectorizedUtil.java [hunk 1]
```diff
@@ -63,10 +58,14 @@ public static void switchToQueryNonVec() {
         if (connectContext == null) {
             return;
         }
-        Analyzer analyzer = connectContext.getExecutor().getAnalyzer();
-        if (analyzer == null) {
-            return;
+        SessionVariable sessionVariable = connectContext.getSessionVariable();
+        sessionVariable.setIsSingleSetVar(true);
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/common/util/VectorizedUtil.java:62]: Where is the declare of this var ?

Comment (EmmyMiao87) [reply fe/fe-core/src/main/java/org/apache/doris/common/util/VectorizedUtil.java:62]: Sorry, I didn't find this function just now

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
