### PR TITLE
[BUG] Fix Stream Load cost too much memory

### LINKED ISSUE #5874: [BUG] Stream Load Cost Too Much Memory When Call Function
**Describe the bug**

**To Reproduce**
1. create a table
2. use stream load and execute Expr Function such as cast to String or String Functions

Here was the Memory Cost Profile:
```
Dumping heap profile to /tmp/heap.dump.0001.heap (113 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0002.heap (1615 MB allocated cumulatively, 159 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0003.heap (2639 MB allocated cumulatively, 227 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0004.heap (3717 MB allocated cumulatively, 394 MB currently in use)
```

** how to fix it ? **
call free local alloced after load data

Here was the Memory Cost Profile:
```
Dumping heap profile to /tmp/heap.dump.0001.heap (1024 MB allocated cumulatively, 78 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0002.heap (2048 MB allocated cumulatively, 79 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0003.heap (3072 MB allocated cumulatively, 79 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0004.heap (4096 MB allocated cumulatively, 79 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0005.heap (5120 MB allocated cumulatively, 80 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0006.heap (6144 MB allocated cumulatively, 80 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0007.heap (7168 MB allocated cumulatively, 80 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0008.heap (8192 MB allocated cumulatively, 80 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0009.heap (9216 MB allocated cumulatively, 80 MB currently in use)
Dumping heap profile to /tmp/heap.dump.0010.heap (10240 MB allocated cumulatively, 80 MB currently in use)
```

### PR DESCRIPTION
**Pull request by stdpain**
## Proposed changes

will close #5874 

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [x] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5874 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/base_scanner.h [hunk 1]
```diff
@@ -88,6 +89,9 @@ class BaseScanner {
 	const std::vector<ExprContext*>& _pre_filter_ctxs;
 
     bool _strict_mode;
+
+    int32_t _line_counter;
+    const static constexpr int32_t RELEASE_CONTEXT_COUNTER = 1 << 5;
```
Comment (yangzhg) [inline be/src/exec/base_scanner.h:94]: add a comment this value is 32

File: be/src/olap/memtable.h [hunk 2]
```diff
@@ -104,6 +104,7 @@ class MemTable {
     // In this way, we can make MemTable::memory_usage() to be more accurate, and eventually
     // reduce the number of segment files that are generated by current load
     std::unique_ptr<MemPool> _table_mem_pool;
+    ObjectPool _agg_buffer_pool;
```
Comment (yangzhg) [inline be/src/olap/memtable.h:107]: add a comment，what is the different between buffer and object

**Review by morningman — APPROVED** [review]
LGTM
