### PR TITLE
[Bug-fix] Fix the replay error in stream load manager

### LINKED ISSUE #5729: [Bug] Fe cannot be restarted, when the stream load record manager takes effect
**Describe the bug**

The persistence logic for FetchStreamLoadRecord is wrong which will cause the metadata to fail to read.

**To Reproduce**
Version 0.14.8
1. execute stream load
2. stop fe
3. start fe
4. fe cannot be restarted with error:

```
2021-04-27 20:05:02,233 ERROR (replayer|80) [BDBJournalCursor.next():117] fail to read journal entity key=349360906, will exit
java.io.EOFException: null
        at java.io.DataInputStream.readBoolean(DataInputStream.java:244) ~[?:1.8.0_131]
        at org.apache.doris.load.StreamLoadRecordMgr$FetchStreamLoadRecord.read(StreamLoadRecordMgr.java:162) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.journal.JournalEntity.readFields(JournalEntity.java:525) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:115) [palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2478) [palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog$3.runOneCycle(Catalog.java:2267) [palo-fe.jar:3.4.0]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:3.4.0]
```

**Expected behavior**

Fe can be restarted normally.
The record of StreamLoadAudit could be replayed normally.

### PR DESCRIPTION
**Pull request by EmmyMiao87**
## Proposed changes

Fix the replay error in stream load manager

    The previous replay logic does not record the size of the map, which eventually resulted in EOF when reading the log.
    This pr replaces the replay logic directly with json.

    At the same time, the replay logic of image is supplemented.
    The pr ensure that the attributes 'lastStreamLoadTime' of backend can be correctly recorded in the image.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fixed #5729) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by caiconghui — DISMISSED** [review]
LGTM

File: be/src/http/action/stream_load.cpp [hunk 1]
```diff
@@ -163,7 +163,9 @@ void StreamLoadAction::handle(HttpRequest* req) {
     HttpChannel::send_reply(req, str);
 #ifndef BE_TEST
     str = ctx->prepare_stream_load_record(str);
-    _sava_stream_load_record(ctx, str);
```
Comment (caiconghui) [inline be/src/http/action/stream_load.cpp:166]: why prepare_stream_load_record outside enable judgement block

File: fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java [hunk 2]
```diff
@@ -121,13 +128,14 @@ public void replayFetchStreamLoadRecord(FetchStreamLoadRecord fetchStreamLoadRec
         for (Backend backend : backends.values()) {
             if (beIdToLastStreamLoad.containsKey(backend.getId())) {
                 long lastStreamLoadTime = beIdToLastStreamLoad.get(backend.getId());
-                LOG.info("Replay stream load bdbje. backend: {}, last stream load version: {}", backend.getHost(), lastStreamLoadTime);
+                LOG.info("Replay stream load bdbje. backend: {}, last stream load time: {}", backend.getHost(), lastStreamLoadTime);
```
Comment (caiconghui) [inline fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java:131]: what if disable stream load the value for lastStreamLoadTime will be?

File: be/src/http/action/stream_load.cpp (hunk 1 above)
Comment (EmmyMiao87) [reply be/src/http/action/stream_load.cpp:166]: changed

File: fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java (hunk 2 above)
Comment (EmmyMiao87) [reply fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java:131]: In fact, even if the collection process of be is disabled. 
The stream load record of fe will still obtain stream load information regularly. 
It’s just that every time you get it is empty.

In fact, FE can also add another variable to stop obtaining stream load record. 
But there are too many variables. 
To avoid using complexity. 
I did not add this switch to fe.

**Review by morningman — APPROVED** [review]
LGTM
