### PR TITLE
[Fix](load)Make insert timeout accurate in `show load` statistics 

### LINKED ISSUE #19940: [Enhancement] Make insert timeout accurate in `show load` statistics
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Run an `insert`, and then execute `show load` command, we could find that in `TaskInfo`, `timeout(s)` would always be 3600, regardless of the real timeout val.
```
mysql> show load\G;
*************************** 1. row ***************************
         JobId: 13003
         Label: orc_s32
         State: FINISHED
      Progress: Unknown id: 13003
          Type: INSERT
       EtlInfo: NULL
      TaskInfo: cluster:N/A; timeout(s):3600; max_filter_ratio:0.0
      ErrorMsg: NULL
    CreateTime: 2023-05-22 18:41:27
  EtlStartTime: 2023-05-22 18:41:27
 EtlFinishTime: 2023-05-22 18:41:27
 LoadStartTime: 2023-05-22 18:41:27
LoadFinishTime: 2023-05-22 18:45:54
           URL: 
    JobDetails: {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":0,"FileSize":0}
 TransactionId: 2003
  ErrorTablets: {}
          User: root
       Comment: 
```

### Solution

Actually, there are two problems to be solved: 
1. The `insert_load_default_timeout_second` should be consistent to the default val of `insert_timeout` session var.
2. The InsertLoadJob is created to record the finish state of an `insert` stmt. Set the timeout property correctly when created.

 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Bears0haunt**
# Proposed changes

Issue Number: close #19940 

## Problem summary

* The default val of `insert_timeout` will be the same as session var if it has not been modified
```
*************************** 1. row ***************************
         JobId: 10139
         Label: insert_89bbe1c60dc244f4_bf759e6305c8114b
         State: FINISHED
      Progress: Unknown id: 10139
          Type: INSERT
       EtlInfo: NULL
      TaskInfo: cluster:N/A; timeout(s):14400; max_filter_ratio:0.0
      ErrorMsg: NULL
    CreateTime: 2023-05-25 20:11:01
  EtlStartTime: 2023-05-25 20:11:01
 EtlFinishTime: 2023-05-25 20:11:01
 LoadStartTime: 2023-05-25 20:11:01
LoadFinishTime: 2023-05-25 20:11:01
           URL:
    JobDetails: {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":0,"FileSize":0}
 TransactionId: 2
  ErrorTablets: {}
          User: root
       Comment:
```

* After `show load` command , the `timeout(s)` will be correct  

```
mysql> set insert_timeout = 4800;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into example.example_tbl values (10000,"2017-10-01","北京",20,0,"2017-10-02 06:00:00",20,10,10);
Query OK, 1 row affected (0.04 sec)
{'label':'insert_c1f81d88105444f_8f015541ee992fe0', 'status':'VISIBLE', 'txnId':'3'}

mysql> show load\G;
*************************** 1. row ***************************
         JobId: 10140
         Label: insert_c1f81d88105444f_8f015541ee992fe0
         State: FINISHED
      Progress: Unknown id: 10140
          Type: INSERT
       EtlInfo: NULL
      TaskInfo: cluster:N/A; timeout(s):4800; max_filter_ratio:0.0
      ErrorMsg: NULL
    CreateTime: 2023-05-25 20:11:39
  EtlStartTime: 2023-05-25 20:11:39
 EtlFinishTime: 2023-05-25 20:11:39
 LoadStartTime: 2023-05-25 20:11:39
LoadFinishTime: 2023-05-25 20:11:39
           URL:
    JobDetails: {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":0,"FileSize":0}
 TransactionId: 3
  ErrorTablets: {}
          User: root
       Comment:
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Hastyshell — DISMISSED** [review]
LGTM

**Comment by Bears0haunt** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java [hunk 1]
```diff
@@ -415,7 +415,11 @@ private void initDefaultJobProperties() {
                 timeout = Config.broker_load_default_timeout_second;
                 break;
             case INSERT:
-                timeout = Config.insert_load_default_timeout_second;
+                if (ConnectContext.get() != null) {
```
Comment (lvshaokang) [inline fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java:418]: Generally LGTM
But it would be better if the code style can be optimized. Similar to this code, suggest remove redundant if..else
```suggestion
timeout = Optional.ofNullable(ConnectContext.get())
                    .map(ConnectContext::getExecTimeout)
                    .orElse(Config.insert_load_default_timeout_second)
```

File: fe/fe-common/src/main/java/org/apache/doris/common/Config.java [hunk 2]
```diff
@@ -452,7 +452,7 @@ public class Config extends ConfigBase {
 
     @ConfField(mutable = true, masterOnly = true, description = {"Insert load 的默认超时时间，单位是秒。",
             "Default timeout for insert load job, in seconds."})
-    public static int insert_load_default_timeout_second = 3600; // 1 hour
+    public static int insert_load_default_timeout_second = 14400; // 4 hour
```
Comment (CalvinKirs) [inline fe/fe-common/src/main/java/org/apache/doris/common/Config.java:456]: Documentation related has not been updated yet
https://doris.apache.org/docs/dev/data-operate/import/import-way/insert-into-manual/#fe-configuration

**Comment by Bears0haunt** [comment]
run buildall

**Comment by Bears0haunt** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Review by lvshaokang — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
