### PR TITLE
Fix MaterializedView select with CTE bug

### LINKED ISSUE #5164: MaterializedView select result is wrong when union all CTE
**Describe the bug**
```
2020-12-28 19:17:54,377 WARN (doris-mysql-nio-pool-1|151) [StmtExecutor.analyze():601] Analyze failed because
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878) ~[spark-dpp-1.0.0.jar:?]
        at org.apache.doris.planner.OlapScanNode.updateColumnType(OlapScanNode.java:260) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.OlapScanNode.updateScanRangeInfoByNewMVSelector(OlapScanNode.java:231) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.selectMaterializedView(SingleNodePlanner.java:796) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.selectMaterializedView(SingleNodePlanner.java:767) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.selectMaterializedView(SingleNodePlanner.java:807) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.selectMaterializedView(SingleNodePlanner.java:767) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.Planner.createPlanFragments(Planner.java:167) ~[dorisdb-fe.jar:?]
        at org.apache.doris.planner.Planner.plan(Planner.java:81) ~[dorisdb-fe.jar:?]
```

**To Reproduce**
```
create table sales_records(record_id int, seller_id int, store_id int, sale_date date, sale_amt bigint) distributed by hash(record_id) properties("replication_num" = "1");

create materialized view store_id as select store_id from sales_records;

insert into sales_records(record_id, seller_id, store_id, sale_date, sale_amt)
values(1, 1, 1, '2020-12-30',1);

with t as (
SELECT store_id as id , 'kks' as aaa, sum(seller_id) as seller, sum(sale_amt) as a FROM sales_records 
GROUP BY store_id
)

select id, t1 from(
select id, a as t1 from t
union all
select id, aaa as t1 from t
) k2;
```

### PR DESCRIPTION
**Pull request by kangkaisen**
Fix https://github.com/apache/incubator-doris/issues/5164

For different Analyzer scopes, the id for SelectStmt maybe the same, but the Analyzer instance always unique

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java [hunk 1]
```diff
@@ -86,7 +86,7 @@
 
     private final PlannerContext ctx_;
     private final ArrayList<ScanNode> scanNodes = Lists.newArrayList();
-    private Map<UUID, List<ScanNode>> selectStmtToScanNodes = Maps.newHashMap();
+    private Map<Analyzer, List<ScanNode>> selectStmtToScanNodes = Maps.newHashMap();
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:89]: Is the Analyzer of CTE same as outer query?

Comment (kangkaisen) [reply fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:89]: No. 
For SQL
```
select id, t1 from(
select id, a as t1 from t
union all
select id, aaa as t1 from t
) k2;
```
The analyzer instances for `select id, a as t1 from t` and `select id, aaa as t1 from t` are different.
Such as, The analyzer instances for `select id, a as t1 from t` is 6177, which ancestors are[6219,6220,6221],
The analyzer instances for `select id, aaa as t1 from t` is 6225, which ancestors are[6247,6220,6221].

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Hi, @kangkaisen , there are unused imports:
```
SingleNodePlanner.java:76:8: Unused import - java.util.UUID. [UnusedImports]
```

Please fix it first.

**Comment by kangkaisen** [comment]
> Hi, @kangkaisen , there are unused imports:
> 
> ```
> SingleNodePlanner.java:76:8: Unused import - java.util.UUID. [UnusedImports]
> ```
> 
> Please fix it first.

@morningman done

**Review by morningman — APPROVED** [review]
LGTM
