### PR TITLE
[fix](sleep) sleep with character const make be crash

### LINKED ISSUE #37327: [Bug] sleep function with character constant(such as 'a', '1.1') leads to be crash
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1

### What's Wrong?

`select sleep('1.1')` leads to be crash

### What You Expected?

just as 2.0version, be will not crash

### How to Reproduce?

Just execute `select sleep('1.1')`
图片

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/37327

Come from: #31689

After fix be will not crash any more.

```
mysql> select cast('1.1' as int);
+--------------------+
| cast('1.1' as INT) |
+--------------------+
|               NULL |
+--------------------+
1 row in set (0.04 sec)

mysql> select sleep('1.1');
+---------------------------+
| sleep(cast('1.1' as INT)) |
+---------------------------+
|                      NULL |
+---------------------------+
1 row in set (0.02 sec)

```

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by zhangstar333 — DISMISSED** [review]

File: be/src/vec/functions/function_utility.cpp [hunk 1]
```diff
@@ -74,19 +74,12 @@ class FunctionSleep : public IFunction {
```
Comment (zhiqiang-hhhh) [inline be/src/vec/functions/function_utility.cpp:74]: Could you please add some comment to explain why we not using default_impl for const? 
"Sleep function should not be executed during open stage, this will makes fargment preparint too long, so we do not use default impl."

**Comment by cambyzju** [comment]
run buildall

File: be/src/vec/functions/function_utility.cpp [hunk 2]
```diff
@@ -62,31 +62,26 @@ class FunctionSleep : public IFunction {
...
     bool use_default_implementation_for_nulls() const override { return false; }
 
+    // Sleep function should not be executed during open stage, this will makes fragment prepare
+    // waiting too long, so we do not use default impl.
     bool use_default_implementation_for_constants() const override { return false; }
 
     Status execute_impl(FunctionContext* context, Block& block, const ColumnNumbers& arguments,
                         size_t result, size_t input_rows_count) const override {
-        ColumnPtr& argument_column = block.get_by_position(arguments[0]).column;
+        const auto& argument_column =
```
Comment (zclllyybb) [inline be/src/vec/functions/function_utility.cpp:79]: use `unpack_if_const` may be better

**Review by yiguolei — APPROVED** [review]
LGTM

File: be/src/vec/functions/function_utility.cpp (hunk 2 above)
Comment (cambyzju) [reply be/src/vec/functions/function_utility.cpp:79]: there are already lots of convert_to_full_column_if_const used, maybe next time, we refractor all these used is better.

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]
