### PR TITLE
[Spark load][Bug] Fix column terminator for spark load

### LINKED ISSUE #4490: [Spark load][Bug] Spark load's column terminator is not consistent with Broker load
**Describe the bug**
For Broker load:

```
load label test_db.label13 
( 
    DATA INFILE("hdfs://my-hdfs-host:54310/user/doris/table4") 
    into table test_tbl
    COLUMNS TERMINATED BY "|" 
    (k1,k2,name,clicks)
 ) 
WITH BROKER "doris" 
(
    "username" = "test", 
    "password" = "test"
);
```

For spark load:

```
load label test_db.label13 
( 
    DATA INFILE ("hdfs://my-hdfs-host:54310/user/doris/table4") 
    into table test 
    COLUMNS TERMINATED BY "|" 
    (k1,k2,name,clicks ) 
) 
WITH RESOURCE "spark0";
```

They have the same table schema、same upstream data source. The former(broker load) run successfully, but the latter(spark load) report an error **"quality not good enough to cancel"**. And if you change the column terminator of spark load to "\\|" or "\\\\|", then it will run successfully.

**Expected behavior**
We should keep the column terminator's format of spark load consistent with that of broker load.

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

fix #4490 

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java [hunk 1]
```diff
@@ -502,7 +504,7 @@ public EtlFileGroup(SourceType sourceType, List<String> filePaths, List<String>
             this.filePaths = filePaths;
             this.fileFieldNames = fileFieldNames;
             this.columnsFromPath = columnsFromPath;
-            this.columnSeparator = columnSeparator;
+            this.columnSeparator = Strings.isNullOrEmpty(columnSeparator)?'\t': columnSeparator.charAt(0);
```
Comment (morningman) [inline fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java:507]:
```suggestion
            this.columnSeparator = Strings.isNullOrEmpty(columnSeparator) ? '\t' : columnSeparator.charAt(0);
```

File: fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java [hunk 2]
```diff
@@ -559,7 +558,14 @@ private void processRollupTree(RollupTreeNode rootNode,
         JavaRDD<Row> rowRDD = sourceDataRdd.flatMap(
                 record -> {
                     scannedRowsAcc.add(1);
-                    String[] attributes = record.split(fileGroup.columnSeparator);
+                    char sep = fileGroup.columnSeparator;
```
Comment (morningman) [inline fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java:561]: Make it execute only once.

**Review by morningman — APPROVED** [review]
LGTM
