### PR TITLE
[fix](executor) intersect operator takes too long time to execute

### LINKED ISSUE #10182: [Bug] intersect operator takes an unexpected long time to execute in some scenario
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

use tpch 1G data, and run the following sql:
select count(*) from ( select l1.l_linenumber, l1.l_shipdate, l1.l_comment from lineitem l1 order by l_orderkey limit 100000 intersect 
    select l2.l_linenumber, l2.l_comment, l2.l_shipdate from lineitem l2 order by l_orderkey limit 100000 intersect 
    select l3.l_linenumber, l3.l_comment, l3.l_shipdate from lineitem l3 order by l_orderkey limit 100000 ) tmp;

| count(*) |
|  ----  | 
|        0     |

1 row in set (10.46 sec)

### What You Expected?

should take much less time like bellow:
| count(*) |
|  ----  | 
|        0     |

1 row in set (0.36 sec)

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by starocean999**
# Proposed changes

Issue Number: close https://github.com/apache/incubator-doris/issues/10182

## Problem Summary:

After the first intersect operator, the hash table will be filled with matched and unmatched values. before doing the next intersect operation( assume there is one ), the hash table will be sweept in two ways:
1. if there is less than 1/4 cells are matched, the table would be shrinked by inserting the matched values into a new hash table and then deleting the old one
2. mark all unmached values as ZERO value to ensure these ZERO values can't be matched in the next intersect operation.

in case 2, there is a problem:
The original code iterate over all the hash table values, and set the unmatched ones to ZERO. But the iterator's operator++() method always check if the current value is ZERO. If it does, the iterator will be moved to the head of the container, and move forword step by step to find the next value( first NO-ZERO value ). So if changes the current value to ZERO before calling iterator's operator++ method, the iterator would always be moved to the head instead of move to the next value as we expected. So the code should be changed to move the iterator to next value, then set the unmatched cell to ZERO.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
could you elaborate on the cause of the problem? and please update title follow by [commit format specification](https://doris.apache.org/community/how-to-contribute/commit-format-specification.html)

File: be/src/vec/exec/vset_operation_node.h [hunk 1]
```diff
@@ -114,23 +114,36 @@ void VSetOperationNode::refresh_hash_table() {
 
                     arg.init_once();
                     auto& iter = arg.iter;
-                    for (; iter != arg.hash_table.end(); ++iter) {
+                    auto iter_end = arg.hash_table.end();
+                    decltype(arg.iter) iter_prev;
+                    for (; iter != iter_end;) {
```
Comment (BiteTheDDDDt) [inline be/src/vec/exec/vset_operation_node.h:119]: here can just use `while`

File: be/src/vec/exec/vset_operation_node.h [hunk 2]
```diff
@@ -114,23 +114,36 @@ void VSetOperationNode::refresh_hash_table() {
 
                     arg.init_once();
                     auto& iter = arg.iter;
-                    for (; iter != arg.hash_table.end(); ++iter) {
+                    auto iter_end = arg.hash_table.end();
+                    decltype(arg.iter) iter_prev;
```
Comment (BiteTheDDDDt) [inline be/src/vec/exec/vset_operation_node.h:118]: Maybe we can just declare `iter_prev` at inner loop.

Comment (starocean999) [reply be/src/vec/exec/vset_operation_node.h]: Done

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM
