### PR TITLE
[Enhancement] submit Baidu test cases

### LINKED ISSUE #22879: [Enhancement] Donate Baidu test cases
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

The Jenkins tasks (jenkins daily:https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/) execute internal test cases of Baidu. Now, these test cases are being submitted. The following is the description of these test cases.

### Testing framework

- python3 + pytest

### Testing dependencies

- mysql
- hdfs
- Python package installation:  pip install -r requirements.txt
- 3 be, create 3 replicas of tables
- 3 fe, some restart cases require 3 fe followers and an observer

### Configurations
The test configurations that need to be modified are as follows:

- var.sh
- deploy/env_config.py
- lib/palo_config.py
- lib/kafka_config.py
- qe/palo2/data/init_lateral_view.sh

### Test environment deployment
Place the compiled output in the deploy directory, configure the deploy/env_config.py file, and execute the following command:
```
cd deploy
python deploy.py
```

### Test data preparation
1. Data download
2. Place the data from the hdfs directory onto hdfs
3. Configure Kafka and prepare Kafka test data. Use the following command to create a Kafka topic (used in routine load-related cases):
```
cd lib
python kafka_config.py
```
4. Configure Canal and enable it
5. Initialize Doris & MySQL data (used in query cases)
```
source var.sh
cd deploy/qe
sh init_data.sh
sh init_mysql.sh
```
### Test execution commands
Execute functional tests: bash run_case.sh
Execute exception tests: bash run_restart_case.sh
### Test reports:
Support reports in both XML and HTML formats

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangy5**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/22879

this pr submits baidu test case

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zgxme** [comment]
Hi @zhangy5 , thanks for your contribution ! 
With the Baidu test cases, we found a few more serious issues:
  1. be out of core. 
  2. test result calibration issues, we are on going.
Similarly, there are some small optimisations in PR that need support from your side.

File: pytest/run_case.sh [hunk 1]
```diff
@@ -0,0 +1,325 @@
...
+    import Node
+    Node.check_cluster(fe_check=False)
+    '''
+}
+
+function pytest_execute ()
+{
+    case_file=$1
+    ls ${case_file}
+    pytest -sv --junit-xml="${REPORT_PATH}"/"${case_file%.py}".xml --html="${REPORT_PATH}"/"${case_file%.py}".html  "${case_file}" --tb=native 2>&1 > "${case_file%.py}".log
```
Comment (zgxme) [inline pytest/run_case.sh:68]: replace hear 
pytest -sv --junit-xml=$REPORT_PATH/${case_file%.py}.xml --html=$REPORT_PATH/${case_file%.py}.html  $case_file --tb=native 2>&1 | tee ${case_file%.py}.log

because we want collect test result from teamcity

File: pytest/run_case.sh [hunk 2]
```diff
@@ -0,0 +1,325 @@
...
+    sleep 1
+}
+
+function case_execute ()
+{
+    for case_file in "$@"
```
Comment (zgxme) [inline pytest/run_case.sh:74]: fix hear，that will cause some errors and incomplete suites we run.

` for case_file in $@`

File: pytest/run_case.sh (hunk 1 above)
Comment (zhangy5) [reply pytest/run_case.sh]: done

File: pytest/run_case.sh (hunk 2 above)
Comment (zhangy5) [reply pytest/run_case.sh]: done

**Comment by dataroaring** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM
