### PR TITLE
[fix](restapi) Unify Permission Requirements for Executing SHOW FRONTENDS/BACKENDS And NODE RestAPI

### LINKED ISSUE #50138: [Bug] privilege checking about node manager rest api
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.1.7 + Spark Doris Connector-25.0.1

### What's Wrong?

It will throw exception when calling `/rest/v2/manager/node/frontends` with non-admin user.

### What You Expected?

Would you mind removing the priv checker like `/api/backends`?

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhaorongsheng**
### What problem does this PR solve?

Issue Number: close #50138 

Problem Summary:

Unify Permission Requirements for Executing SHOW FRONTENDS/BACKENDS And NODE RestAPI. Make it as same as the privileges of system default database `information_schema`.

### Release note

None

### Check List (For Author)

- Test
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes.

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Review by yiguolei — DISMISSED** [review]

File: fe/fe-core/src/main/java/org/apache/doris/analysis/ShowBackendsStmt.java [hunk 1]
```diff
@@ -37,10 +39,10 @@ public ShowBackendsStmt() {
     public void analyze(Analyzer analyzer) throws UserException {
         super.analyze(analyzer);
 
-        if (!Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(), PrivPredicate.ADMIN)
-                && !Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(),
-                                                                          PrivPredicate.OPERATOR)) {
-            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR, "ADMIN/OPERATOR");
+        if (!Env.getCurrentEnv().getAccessManager().checkDbPriv(ConnectContext.get(),
+                InternalCatalog.INTERNAL_CATALOG_NAME, InfoSchemaDb.DATABASE_NAME, PrivPredicate.SELECT)) {
+            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR,
```
Comment (zddr) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/ShowBackendsStmt.java:44]: should use ERR_DB_ACCESS_DENIED_ERROR intead of ERR_SPECIFIC_ACCESS_DENIED_ERROR,otherwise, users will not know which database permissions are needed

File: fe/fe-core/src/main/java/org/apache/doris/analysis/ShowFrontendsStmt.java [hunk 2]
```diff
@@ -46,10 +48,10 @@ public String getDetailType() {
 
     @Override
     public void analyze(Analyzer analyzer) throws AnalysisException {
-        if (!Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(), PrivPredicate.ADMIN)
-                && !Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(),
-                                                                          PrivPredicate.OPERATOR)) {
-            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR, "ADMIN/OPERATOR");
+        if (!Env.getCurrentEnv().getAccessManager().checkDbPriv(ConnectContext.get(),
+                InternalCatalog.INTERNAL_CATALOG_NAME, InfoSchemaDb.DATABASE_NAME, PrivPredicate.SELECT)) {
+            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR,
```
Comment (zddr) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/ShowFrontendsStmt.java:53]: ditto

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowBackendsCommand.java [hunk 3]
```diff
@@ -57,10 +59,10 @@ public ShowResultSetMetaData getMetaData() {
 
     @Override
     public ShowResultSet doRun(ConnectContext ctx, StmtExecutor executor) throws Exception {
-        if (!Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(), PrivPredicate.ADMIN)
-                && !Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(),
-                                                                          PrivPredicate.OPERATOR)) {
-            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR, "ADMIN/OPERATOR");
+        if (!Env.getCurrentEnv().getAccessManager().checkDbPriv(ConnectContext.get(),
+                InternalCatalog.INTERNAL_CATALOG_NAME, InfoSchemaDb.DATABASE_NAME, PrivPredicate.SELECT)) {
+            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR,
```
Comment (zddr) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowBackendsCommand.java:64]: ditto

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowFrontendsCommand.java [hunk 4]
```diff
@@ -70,10 +72,10 @@ public ShowResultSetMetaData getMetaData() {
 
     @Override
     public ShowResultSet doRun(ConnectContext ctx, StmtExecutor executor) throws Exception {
-        if (!Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(), PrivPredicate.ADMIN)
-                && !Env.getCurrentEnv().getAccessManager().checkGlobalPriv(ConnectContext.get(),
-                                                                          PrivPredicate.OPERATOR)) {
-            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR, "ADMIN/OPERATOR");
+        if (!Env.getCurrentEnv().getAccessManager().checkDbPriv(ConnectContext.get(),
+                InternalCatalog.INTERNAL_CATALOG_NAME, InfoSchemaDb.DATABASE_NAME, PrivPredicate.SELECT)) {
+            ErrorReport.reportAnalysisException(ErrorCode.ERR_SPECIFIC_ACCESS_DENIED_ERROR,
```
Comment (zddr) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowFrontendsCommand.java:77]: ditto

File: fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/NodeAction.java [hunk 5]
```diff
@@ -312,7 +313,7 @@ public Object configurationInfo(HttpServletRequest request, HttpServletResponse
             @RequestParam(value = "type") String type,
             @RequestBody(required = false) ConfigInfoRequestBody requestBody) {
         executeCheckPassword(request, response);
-        checkGlobalAuth(ConnectContext.get().getCurrentUserIdentity(), PrivPredicate.ADMIN);
+        checkGlobalAuth(ConnectContext.get().getCurrentUserIdentity(), PrivPredicate.OPERATOR);
```
Comment (zddr) [inline fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/NodeAction.java:316]: admin or operator

**Review by zddr — COMMENTED** [review]
Modified pr Description Explaining the Behavioral Changes，such as Permission Requirements for Executing SHOW FRONTENDS

**Comment by zhaorongsheng** [comment]
@zddr  I have updated some codes. Would you mind reviewing it once again? Thanks~

**Review by zddr — APPROVED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Comment by zhaorongsheng** [comment]
run buildall

**Review by zddr — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
