### PR TITLE
[fix](remote)Fix bug for Cache Reader

### LINKED ISSUE #11627: [Bug] Fix bug for SubFileCache
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1

### What's Wrong?

FileCache can't write files for Remote storage.

### What You Expected?

FileCache can write files on local disk

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #11627

## Problem summary

Fix bug for Cache Reader

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

### CODE REVIEW

File: be/src/io/cache/whole_file_cache.cpp [hunk 1]
```diff
@@ -37,6 +37,16 @@ WholeFileCache::~WholeFileCache() {}
 
 Status WholeFileCache::read_at(size_t offset, Slice result, size_t* bytes_read) {
     if (_cache_file_reader == nullptr) {
+        std::lock_guard<std::shared_mutex> wrlock(_cache_lock);
```
Comment (yangzhg) [inline be/src/io/cache/whole_file_cache.cpp:40]: why create cache dir when read ？and why use shared_mutex here ？

**Review by yangzhg — APPROVED** [review]
LGTM
