### PR TITLE
[fix](merge-on-write) delete all rows with same key in all pre segments

### LINKED ISSUE #14994: [Bug] (merge-on-write) get many rows with same key from merge-on-write table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

导入一批包含相同key的数据，在普通unique table下，只返回一条，但是在打开了merge-on-write的unique table，却返回了两条

例子：
普通的unique table
```
MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_unique where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
1 row in set (0.04 sec)

MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_unique where l_orderkey in (5970000001,5979996005) and l_partkey in (75814607,197922326) and l_suppkey in (5814608,5422384) and l_linenumber in (1,4);
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
| 5979996005 | 197922326 |   5422384 |            4 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
2 rows in set (0.02 sec)
```
结果正确

merge-on-write的unique table
```
MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_write where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_61    |
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
2 rows in set (0.01 sec)

MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_write where l_orderkey in (5970000001,5979996005) and l_partkey in (75814607,197922326) and l_suppkey in (5814608,5422384) and l_linenumber in (1,4);
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_61    |
| 5979996005 | 197922326 |   5422384 |            4 |  01_61    |
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
| 5979996005 | 197922326 |   5422384 |            4 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
4 rows in set (0.00 sec)
```

结果错误，有主键相同的重复数据

### What You Expected?

查询merge-on-write的unique table，主键相同的数据只返回一行

### How to Reproduce?

创建merge-on-write的unique table
```
CREATE TABLE `lineitem_write` (
  `l_orderkey` bigint(20) NULL,
  `l_partkey` int(11) NULL,
  `l_suppkey` int(11) NULL,
  `l_linenumber` int(11) NULL,
  `l_quantity` decimal(15, 2) NULL,
  `l_extendedprice` decimal(15, 2) NULL,
  `l_discount` decimal(15, 2) NULL,
  `l_tax` decimal(15, 2) NULL,
  `l_returnflag` char(1) NULL,
  `l_linestatus` char(1) NULL,
  `l_shipdate` date NULL,
  `l_commitdate` date NULL,
  `l_receiptdate` date NULL,
  `l_shipinstruct` char(25) NULL,
  `l_shipmode` char(10) NULL,
  `l_comment` varchar(44) NULL
) ENGINE=OLAP
UNIQUE KEY(`l_orderkey`, `l_partkey`, `l_suppkey`, `l_linenumber`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`l_orderkey`, `l_partkey`, `l_suppkey`, `l_linenumber`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"enable_unique_key_merge_on_write" = "true",
"disable_auto_compaction" = "false"
);
```

导入数据1：
数据文件：
https://doris-agg-table-bug-1301087413.cos.ap-beijing.myqcloud.com/agg_table_bug/test_agg_table_data_1

这个数据中包含100w数据，其中每隔10000条表，有1条主键为 " 5970999942|130195832|5195859|1 " 的数据，并且l_comment值按序号递增的数据，一种有100条主键相同l_comment不同的行，以及另一组主键为" 5979996005|197922326|5422384|4 "的多行数据。

然后执行如下sql
```
MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_write where l_orderkey=5970000001 and l_partkey=75814607 and l_suppkey=5814608 and l_linenumber=1;
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_61    |
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
2 rows in set (0.01 sec)

MySQL [test]> select l_orderkey,l_partkey,l_suppkey,l_linenumber,l_comment from lineitem_write where l_orderkey in (5970000001,5979996005) and l_partkey in (75814607,197922326) and l_suppkey in (5814608,5422384) and l_linenumber in (1,4);
+------------+-----------+-----------+--------------+-----------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_comment |
+------------+-----------+-----------+--------------+-----------+
| 5970000001 |  75814607 |   5814608 |            1 |  00_61    |
| 5979996005 | 197922326 |   5422384 |            4 |  01_61    |
| 5970000001 |  75814607 |   5814608 |            1 |  00_100   |
| 5979996005 | 197922326 |   5422384 |            4 |  00_100   |
+------------+-----------+-----------+--------------+-----------+
4 rows in set (0.00 sec)
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #14994

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.92 seconds
 load time: 501 seconds
 storage size: 17123356933 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221211123805_clickbench_pr_61605.html

File: be/src/olap/tablet.cpp [hunk 1]
```diff
@@ -2044,19 +2048,26 @@ Status Tablet::calc_delete_bitmap(RowsetId rowset_id,
...
             // if has sequence col, we continue to compare the sequence_id of
             // all segments, util we find an existing key.
             continue;
+        } else if (st.ok() && !_schema->has_sequence_col()) {
+            // delete all rows with same key in all pre segments
+            if (!delete_bitmap->contains({rowset_id, loc->segment_id, version.first},
+                                         loc->row_id)) {
+                delete_bitmap->add({rowset_id, loc->segment_id, version.first}, loc->row_id);
+            }
+            continue;
```
Comment (liaoxin01) [inline be/src/olap/tablet.cpp:2070]: Don't need continue here? Just need to find the key in the previous segment, instead of traversing all segments for mow without sequence col.

File: be/src/olap/tablet.cpp [hunk 2]
```diff
@@ -1999,8 +1999,8 @@ Status Tablet::calc_delete_bitmap(RowsetId rowset_id,
                 RowLocation loc;
                 // first check if exist in pre segment
                 if (check_pre_segments) {
-                    auto st = _check_pk_in_pre_segments(pre_segments, *key, dummy_version,
-                                                        delete_bitmap, &loc);
+                    auto st = _check_pk_in_pre_segments(rowset_id, pre_segments, *key,
+                                                        dummy_version, delete_bitmap, &loc);
                     if (st.ok()) {
                         delete_bitmap->add({loc.rowset_id, loc.segment_id, dummy_version.first},
```
Comment (liaoxin01) [inline be/src/olap/tablet.cpp:2005]: Don't need this code, because already added in `_check_pk_in_pre_segments`.

File: be/src/olap/tablet.cpp (hunk 1 above)
Comment (nextdreamblue) [reply be/src/olap/tablet.cpp:2070]: that's rigth, i fix it

File: be/src/olap/tablet.cpp (hunk 2 above)
Comment (nextdreamblue) [reply be/src/olap/tablet.cpp:2005]: en, i fix _check_pk_in_pre_segments

File: be/src/olap/tablet.cpp (hunk 1 above)
Comment (nextdreamblue) [reply be/src/olap/tablet.cpp:2070]: 当时has_sequence_col的时候，这里还有bug，我统一改一下吧

File: be/src/olap/tablet.cpp [hunk 3]
```diff
@@ -2126,10 +2126,9 @@ Status Tablet::update_delete_bitmap(const RowsetSharedPtr& rowset, DeleteBitmapP
     for (const auto& to_del : rowset_ids_to_del) {
         delete_bitmap->remove({to_del, 0, 0}, {to_del, UINT32_MAX, INT64_MAX});
     }
-    if (!rowset_ids_to_add.empty()) {
```
Comment (liaoxin01) [inline be/src/olap/tablet.cpp:2129]: Why delete this line?

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by zhannngchen — DISMISSED** [review]
LGTM, Thanks for your contribution.

**Review by morningman — DISMISSED** [review]
lgtm

**Review by yiguolei — APPROVED** [review]
LGTM
