### PR TITLE
[fix](Nereids) fix fe folding constant of string functions and add more cases

### LINKED ISSUE #44666: [Bug] upgrading from 2.1.2->2.1.7 causes query result error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

- 2.1.7 (upgrading from 2.1.2)

### What's Wrong?

- 2.1.2 SUBSTRING_INDEX
```
mysql> select * from
(
	select 
				 SUBSTRING_INDEX(name, 'A', 1) t1,
				 LEFT(name, LOCATE('A', name)-1) t2,
				 name,
				 age,
				 code
	from
			(
				SELECT 
							 name,
							 age,
							 code
				FROM (
							SELECT '哈哈哈AAA' name, 20 age, '1' code
							UNION
							SELECT '哈哈哈AA+' name, 21 age, '2' code
							UNION
							SELECT '哈哈哈AA' name, 22 age, '3' code
							UNION
							SELECT '哈哈哈AA(2)' name, 23 age, '4' code
							UNION
							SELECT '哈哈哈AA-' name, 24 age, '5' code
						) a
			) b
) c
where t1 = '哈哈哈';
+--------+--------+-------------+-----+------+
| t1     | t2     | name        | age | code |
+--------+--------+-------------+-----+------+
| 哈哈哈 | 哈哈哈 | 哈哈哈AA-   |  24 | 5    |
| 哈哈哈 | 哈哈哈 | 哈哈哈AAA   |  20 | 1    |
| 哈哈哈 | 哈哈哈 | 哈哈哈AA+   |  21 | 2    |
| 哈哈哈 | 哈哈哈 | 哈哈哈AA    |  22 | 3    |
| 哈哈哈 | 哈哈哈 | 哈哈哈AA(2) |  23 | 4    |
+--------+--------+-------------+-----+------+
5 rows in set (0.17 sec)
```
- 2.1.7 SUBSTRING_INDEX
```
mysql> select * from
(
	select 
				 SUBSTRING_INDEX(name, 'A', 1) t1,
				 LEFT(name, LOCATE('A', name)-1) t2,
				 name,
				 age,
				 code
	from
			(
				SELECT 
							 name,
							 age,
							 code
				FROM (
							SELECT '哈哈哈AAA' name, 20 age, '1' code
							UNION
							SELECT '哈哈哈AA+' name, 21 age, '2' code
							UNION
							SELECT '哈哈哈AA' name, 22 age, '3' code
							UNION
							SELECT '哈哈哈AA(2)' name, 23 age, '4' code
							UNION
							SELECT '哈哈哈AA-' name, 24 age, '5' code
						) a
			) b
) c
where t1 = '哈哈哈';
+--------+--------+-------------+-----+------+
| t1     | t2     | name        | age | code |
+--------+--------+-------------+-----+------+
| 哈哈哈 | 哈哈哈 | 哈哈哈AA-   |  24 | 5    |
| 哈哈哈 | 哈哈哈 | 哈哈哈AA(2) |  23 | 4    |
| 哈哈哈 | 哈哈哈 | 哈哈哈AA+   |  21 | 2    |
+--------+--------+-------------+-----+------+
3 rows in set (0.10 sec)
```
we use `SUBSTRING_INDEX` in the production, now we have to use `LEFT+LOCATE` for replacement.

### What You Expected?

fix the query result bug

### How to Reproduce?

- comment [step](https://github.com/apache/doris/issues/44666#issuecomment-2505450130)

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
Issue Number: close https://github.com/apache/doris/issues/44666

Related PR: #40441 

Problem Summary:

- select substring_index('哈哈哈AAA','A', 1); 
String.split function has second parameter 'limit', which is default zero. When 'limit' is zero, it means it would remove trailing 
empty strings split of '哈哈哈AAA', which would be '哈哈哈' only. But what we expect is '哈哈哈', '','','' when part function is used by substring index. 
So we should change splitpart limit to -1 to enable trailing empty character in splitpart list

- reorganize fold constant of string functions in fe and add more cases

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java [hunk 1]
```diff
@@ -333,12 +346,14 @@ public static Expression instr(StringLikeLiteral first, StringLikeLiteral second
      * Executable arithmetic functions Ascii
      */
     @ExecFunction(name = "ascii")
-    public static Expression ascii(StringLikeLiteral first) {
+    public static Expression ascii(StringLikeLiteral first) throws UnsupportedEncodingException {
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java:349]: catch UnsupportedEncodingException and return original expression?

**Comment by LiBinfeng-01** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java [hunk 2]
```diff
@@ -208,63 +208,63 @@ public static Expression ltrimVarcharVarchar(StringLikeLiteral first, StringLike
...
+    public static Expression rtrim(StringLikeLiteral first) {
         return castStringLikeLiteral(first, trimImpl(first.getValue(), " ", false, true));
     }
 
     /**
      * Executable arithmetic functions rtrim
      */
     @ExecFunction(name = "rtrim")
-    public static Expression rtrimVarcharVarchar(StringLikeLiteral first, StringLikeLiteral second) {
+    public static Expression rtrimVarchar(StringLikeLiteral first, StringLikeLiteral second) {
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java:219]: why remove signature in name? and give it a meaningless name?

**Review by englefly — DISMISSED** [review]

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java (hunk 2 above)
Comment (LiBinfeng-01) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java:219]: because Signature in name is included by StringLikeLiteral, we need this signature before to indicate it is VarcharLiteral or StringLiteral. But now we can use StringlikeLiteral to include them all. Keep one in function to indicate the difference between  rtrim and rtrimVarchar

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Review by englefly — DISMISSED** [review]

**Review by morrySnow — COMMENTED** [review]
Many functions lack test cases for invisible characters and Unicode characters. The majority of functions are also missing test cases for empty strings and blank strings.

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 3]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select append_trailing_char_if_absent('hello', '1')")
+    testFoldConst("select append_trailing_char_if_absent('hello', 1)")
+    testFoldConst("select append_trailing_char_if_absent('hello', 'ab')")
+    testFoldConst("select append_trailing_char_if_absent('hello', NULL)")
     testFoldConst("select append_trailing_char_if_absent('it','a')")
-
+    testFoldConst("select append_trailing_char_if_absent(NULL, '!')")
+    testFoldConst("select append_trailing_char_if_absent('This is a very long string', '.')")
+    testFoldConst("select append_trailing_char_if_absent('Привет', '!')")
+    testFoldConst("select append_trailing_char_if_absent('こんにちは', '!')")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:48]: test some special char like `\n`, `\t` ...

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 4]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select ascii('こ')")
+    testFoldConst("select ascii('안')")
+    testFoldConst("select ascii('中')")
+    testFoldConst("select ascii(cast('1' as string))")
+    testFoldConst("select ascii(cast('a' as string))")
+    testFoldConst("select ascii(cast('A' as string))")
+    testFoldConst("select ascii(cast('!' as string))")
+    testFoldConst("select ascii(cast('こ' as string))")
+    testFoldConst("select ascii(cast('안' as string))")
+    testFoldConst("select ascii(cast('中' as string))")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:64]: test strings with a length greater than 1

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 5]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select concat_ws(NULL, [\"d\", \"is\"])")
     testFoldConst("select concat_ws(NULL, \"d\", \"is\")")
-    testFoldConst("select concat_ws(\"or\", \"d\", NULL,\"is\")")
+    testFoldConst("select concat_ws(\"or\", [\"d\", \"\",\"is\"])")
     testFoldConst("select concat_ws(\"or\", [\"d\", \"is\"])")
-    testFoldConst("select concat_ws(NULL, [\"d\", \"is\"])")
+    testFoldConst("select concat_ws(\"or\", \"d\", \"is\")")
     testFoldConst("select concat_ws(\"or\", [\"d\", NULL,\"is\"])")
-    testFoldConst("select concat_ws(\"or\", [\"d\", \"\",\"is\"])")
+    testFoldConst("select concat_ws(\"or\", \"d\", NULL,\"is\")")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:119]: test empty array

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 6]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select elt(2, \"hello\", \"doris\")")
+    testFoldConst("select elt(3, cast('hello' as string), cast('doris' as string))")
+    testFoldConst("select elt(3, \"hello\", \"doris\")")
 
+    // ends_with
+    testFoldConst("select ends_with(cast('Hello doris' as string), cast('doris' as string))")
     testFoldConst("select ends_with(\"Hello doris\", \"doris\")")
-    testFoldConst("select ends_with(\"Hello doris\", \"Hello\")")
-
+    testFoldConst("select ends_with(\"こんにちは世界！안녕하세요 세계\", \"안녕하세요 세계\")")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:135]: test `NULL`, substring longer than origin str

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 7]
```diff
@@ -16,763 +16,646 @@
...
     testFoldConst("select find_in_set(\"d\", \"a,b,c\")")
     testFoldConst("select find_in_set(null, \"a,b,c\")")
-    testFoldConst("select find_in_set(\"a\", null)")
-
+    testFoldConst("select find_in_set(NULL, cast('a,b,c' as string))")
+    testFoldConst("SELECT find_in_set('A', '哈哈哈AAA')")
+    testFoldConst("SELECT find_in_set('哈','哈哈哈AAA')")
+    testFoldConst("SELECT find_in_set(' ','哈哈哈AAA')")
+    testFoldConst("SELECT find_in_set('','哈哈哈AAA')")
+    testFoldConst("SELECT find_in_set(',','a,')")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:164]: 1. the second param not separate by `'`
2. the first param has `'`

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 8]
```diff
@@ -16,763 +16,646 @@
...
     testFoldConst("select instr(\"abc\", \"d\")")
     testFoldConst("select instr(\"abc\", null)")
+    testFoldConst("select instr(cast('abc' as string), cast('b' as string))")
+    testFoldConst("select instr(cast('abc' as string), cast('d' as string))")
+    testFoldConst("select instr(cast('abc' as string), NULL)")
+    testFoldConst("select instr(cast('Hello' as string), cast('World' as string))")
+    testFoldConst("select instr(cast('Hello World' as string), cast('World' as string))")
+    testFoldConst("select instr('foobar', '')")
+    testFoldConst("select instr('Hello', 'World')")
+    testFoldConst("select instr('Hello World', 'World')")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:212]: test the first parameter is empty

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 9]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select left(CAST('good morning' AS STRING), NULL)")
+    testFoldConst("select left(cast('Hello' as string), 10)")
+    testFoldConst("select left(cast('Hello doris' as string), 5)")
+    testFoldConst("select left(CAST('Hello doris' AS STRING), 5)")
+    testFoldConst("select left(cast('Hello World' as string), 5)")
+    testFoldConst("select left(CAST(NULL AS STRING), 1)")
+    testFoldConst("select left(\"good morning\", 120)")
+    testFoldConst("select left(\"good morning\", -5)")
+    testFoldConst("select left(\"good morning\", NULL)")
+    testFoldConst("select left('Hello', 10)")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:234]: test the second parameter is `0`

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 10]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select null_or_empty(\"a\")")
+    testFoldConst("select null_or_empty(cast('a' as string))")
+    testFoldConst("select null_or_empty(cast('' as string))")
+    testFoldConst("select null_or_empty(null)")
+    testFoldConst("select null_or_empty(NULL)")
+    testFoldConst("select null_or_empty('\b')")
+    testFoldConst("select null_or_empty(' \b')")
+    
+    // overlay
+    testFoldConst("select overlay('abcdef', '123', 3, 2)")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:335]: the `overlay` syntax is `VARCHAR Overlay (VARCHAR str, INT pos, INT len, VARCHAR newstr)`, the test case set the run parameter for it

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 11]
```diff
@@ -16,763 +16,646 @@
...
+    
+    // replace
+    testFoldConst("select replace(cast('Hello World' as string), '', cast('Everyone' as string))")
+    testFoldConst("select replace(cast('Hello World' as string), cast('World' as string), '')")
+    testFoldConst("select replace(cast('Hello World' as string), cast('World' as string), cast('Everyone' as string))")
+    testFoldConst("select replace(cast('https://doris.apache.org:9090' as string), cast(':9090' as string), cast('' as string))")
+    testFoldConst("select replace(cast('https://doris.apache.org:9090' as string), cast('' as string), cast('new_str' as string))")
+    testFoldConst("select replace('Hello World', '', 'Everyone')")
+    testFoldConst("select replace('Hello World', 'World', '')")
+    testFoldConst("select replace('Hello World', 'World', 'Everyone')")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:370]: test the old string parameter is a Regular expression syntax string,  like '.*'

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 12]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select right(cast('Hello World' as string), 5)")
+    testFoldConst("select right(CAST(NULL AS STRING), 1)")
+    testFoldConst("select right(\"good morning\", NULL)")
+    testFoldConst("select right('Hello', 10)")
+    testFoldConst("select right(\"Hello doris\", 120)")
+    testFoldConst("select right(\"Hello doris\", 5)")
+    testFoldConst("select right(\"Hello doris\",5)")
+    testFoldConst("select right(\"Hello doris\", -6)")
+    testFoldConst("select right('Hello World', 5)")
+    testFoldConst("select right(NULL, 1)")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:395]: test second parameter is 0

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 13]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select space(-5)")
+    testFoldConst("select space(5)")
+    testFoldConst("select space(0)")
+
+    // split_by_string
+    testFoldConst("select split_by_string('::', 'abc')")
+    testFoldConst("select split_by_string('a::b::c', '::')")
+    testFoldConst("select split_by_string(cast('a::b::c' as string), cast('::' as string))")
+    testFoldConst("select split_by_string(cast('abc' as string), cast('::' as string))")
+    testFoldConst("select split_by_string('上海天津北京杭州', '北')")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:423]: split_by_string('abccccc ', 'c')

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 14]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select sub_replace(CAST('doris' AS STRING), CAST('***' AS STRING), 1, 2)")
+    testFoldConst("select sub_replace(CAST('doris' AS STRING), CAST('***' AS STRING), 1, 2)")
+    testFoldConst("select sub_replace(CAST('this is origin str' AS STRING), CAST('NEW-STR' AS STRING), 1)")
+    testFoldConst("select sub_replace(CAST('this is origin str' AS STRING), CAST('NEW-STR' AS STRING), 1)")
+    testFoldConst("select sub_replace(\"doris\",\"***\",1,2)")
+    testFoldConst("select sub_replace(\"doris\",\"***\",1,2)")
+    testFoldConst("select sub_replace(\"this is origin str\",\"NEW-STR\",1)")
+    testFoldConst("select sub_replace(\"this is origin str\",\"NEW-STR\",1)")
+    testFoldConst("select sub_replace(CAST('doris' AS STRING), CAST('***' AS STRING), -1, 2)")
+    testFoldConst("select sub_replace(\"上海天津北京杭州\", \"天津\", 3, 4)")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:531]: len parameter larger than the origin string length

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 15]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select unhex('GHIJ')")
+    testFoldConst("select unhex(NULL)")
+    testFoldConst("select unhex(NULL)")
+    testFoldConst("select upper(cast('Hello World' as string))")
+    testFoldConst("select upper('Hello World')")
+
+    // url_decode url_encode
+    testFoldConst("select url_decode(cast('http%3A%2F%2Fwww.apache.org%2Flicenses%2FLICENSE-2.0' as string))")
+    testFoldConst("select url_decode('http%3A%2F%2Fwww.apache.org%2Flicenses%2FLICENSE-2.0')")
+    testFoldConst("select url_encode('http://www.apache.org/licenses/LICENSE-2.0')")
```
Comment (aytrack) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:658]: invalid url

**Comment by LiBinfeng-01** [comment]
run buildall

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 16]
```diff
@@ -16,763 +16,669 @@
...
+    testFoldConst("select elt(2, 'hello', 'doris')")
+    testFoldConst("select elt(3, cast('hello' as string), cast('doris' as string))")
+    testFoldConst("select elt(3, 'hello', 'doris')")
+    testFoldConst("select c1, c2, elt(c1, c2) from (select number as c1, 'varchar' as c2 from numbers('number'='5') where number > 0) a")
 
+    // ends_with
+    testFoldConst("select ends_with(cast('Hello doris' as string), cast('doris' as string))")
+    testFoldConst("select ends_with('Hello doris', 'doris')")
+    testFoldConst("select ends_with('こんにちは世界！안녕하세요 세계', '안녕하세요 세계')")
+    testFoldConst("select ends_with('안녕하세요 세계こんにちは世界！', 'こんにちは世界！')")
```
Comment (morrySnow) [inline regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:138]: only one parameter end with blank

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 17]
```diff
@@ -16,763 +16,646 @@
...
-
+    
+    // append_trailing_char_if_absent
+    testFoldConst("select append_trailing_char_if_absent('', '!')")
+    testFoldConst("select append_trailing_char_if_absent(12345, '!')")
+    testFoldConst("select append_trailing_char_if_absent(12345, '!')")
     testFoldConst("select append_trailing_char_if_absent('a','c')")
     testFoldConst("select append_trailing_char_if_absent('ac','c')")
+    testFoldConst("select append_trailing_char_if_absent(cast('a' as string), cast('c' as string))")
+    testFoldConst("select append_trailing_char_if_absent(cast('ac' as string), cast('c' as string))")
```
[the remark this answers is not in the document]
Comment (LiBinfeng-01) [reply regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:29]: cast to string type and make stringliteral differ with varchar literal

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 18]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select append_trailing_char_if_absent('h', '!')")
+    testFoldConst("select append_trailing_char_if_absent('hello!', '!')")
+    testFoldConst("select append_trailing_char_if_absent('hello', '😊')")
+    testFoldConst("select append_trailing_char_if_absent('hello', ' ')")
+    testFoldConst("select append_trailing_char_if_absent('hello', ' ')")
```
[the remark this answers is not in the document]
Comment (LiBinfeng-01) [reply regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy]: removed

File: regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy [hunk 19]
```diff
@@ -16,763 +16,646 @@
...
+    testFoldConst("select append_trailing_char_if_absent('hello', '!')")
+    testFoldConst("select append_trailing_char_if_absent('hello', '')")
+    testFoldConst("select append_trailing_char_if_absent('hello', '?')")
```
[the remark this answers is not in the document]
Comment (LiBinfeng-01) [reply regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy:36]: removed

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Review by aytrack — APPROVED** [review]
LGTM
