### PR TITLE
[Vectorized][Bug] fix bug of coalesce function

### LINKED ISSUE #7825: [Vectorized][Bug] coalesce function get wrong data when result type is int/decimal type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Vectorized mode

### What's Wrong?

select coalesce(col,999) from table;
when col is int or decimal type,  will get wrong data;

### What You Expected?

right result

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes

Issue Number: close #7825 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/columns/column_complex.h [hunk 1]
```diff
@@ -63,6 +63,12 @@ class ColumnComplexType final : public COWHelper<IColumn, ColumnComplexType<T>>
 
     void insert_default() override { data.push_back(T()); }
 
+    void insert_many_defaults(size_t length) override {
```
Comment (HappenLee) [inline be/src/vec/columns/column_complex.h:66]: try use resize

File: be/src/vec/columns/column_string.h [hunk 2]
```diff
@@ -203,6 +203,15 @@ class ColumnString final : public COWHelper<IColumn, ColumnString> {
         offsets.push_back(offsets.back() + 1);
     }
 
+    void insert_many_defaults(size_t length) override {
+        size_t chars_old_size = chars.size();
+        chars.resize(chars_old_size + length);
+        memset(chars.data() + chars_old_size, 0, length);
+        for (size_t i = 0; i < length; i++) {
```
Comment (HappenLee) [inline be/src/vec/columns/column_string.h:210]: try to simd the code

**Review by HappenLee — COMMENTED** [review]
some little problem

**Review by HappenLee — APPROVED** [review]
LGTM
