### PR TITLE
[Bug] Fix the bug of bucket shuffle join cause error paln

### LINKED ISSUE #6171: [Bug] Error plan in bucket shuffle join
**Describe the bug**
create table and load data
```
create table T_DORIS_A
(
ID bigint not null,
APPLY_CRCL bigint(19)
)ENGINE=OLAP
UNIQUE KEY(`ID`)
COMMENT "T_DORIS_A"
DISTRIBUTED BY HASH(`ID`) BUCKETS 32
PROPERTIES(
"replication_num"="1",
"in_memory"="false",
"storage_format"="V2"
);

create table T_DORIS_B
(
ID bigint not null,
FACTOR_FIN_VALUE decimal(19,2),
PRJT_ID bigint(19)
)ENGINE=OLAP
UNIQUE KEY(`ID`)
COMMENT "T_DORIS_B"
DISTRIBUTED BY HASH(`ID`) BUCKETS 32
PROPERTIES(
"replication_num"="1",
"in_memory"="false",
"storage_format"="V2"
);

create table T_DORIS_C
(
ID bigint not null
)ENGINE=OLAP
UNIQUE KEY(`ID`)
COMMENT "T_DORIS_C"
DISTRIBUTED BY HASH(`ID`) BUCKETS 32
PROPERTIES(
"replication_num"="1",
"in_memory"="false",
"storage_format"="V2"
);

create table T_DORIS_D
(
ID bigint not null,
LIMIT_ID bigint(19),
CORE_ID bigint(19)
)ENGINE=OLAP
UNIQUE KEY(`ID`)
COMMENT "T_DORIS_D"
DISTRIBUTED BY HASH(`ID`) BUCKETS 32
PROPERTIES(
"replication_num"="1",
"in_memory"="false",
"storage_format"="V2"
);

create table T_DORIS_E
(
ID bigint not null,
SHARE_ID bigint,
SPONSOR_ID bigint
)ENGINE=OLAP
UNIQUE KEY(`ID`)
COMMENT "T_DORIS_E"
DISTRIBUTED BY HASH(`ID`) BUCKETS 32
PROPERTIES(
"replication_num"="1",
"in_memory"="false",
"storage_format"="V2"
);
```

**To Reproduce**
check query paln 
```
desc SELECT B.FACTOR_FIN_VALUE, D.limit_id FROM T_DORIS_A A     LEFT JOIN T_DORIS_B B ON B.PRJT_ID = A.ID     LEFT JOIN T_DORIS_C C ON A.apply_crcl = C.id     JOIN T_DORIS_D D ON C.ID = D.CORE_ID order by B.FACTOR_FIN_VALUE, D.limit_id desc;
```

T_DORIS_C and T_DORIS_D should not be bucket shuffle join, but we got it.

```
|   6:HASH JOIN                                                                    |
|   |  join op: INNER JOIN (BUCKET_SHUFFLE)                                             |
|   |  hash predicates:                                                            |
|   |  colocate: false, reason: The src data has been redistributed                |
|   |  equal join conjunct: `C`.`ID` = `D`.`CORE_ID`                               |
|   |                                                                              |
|   |----10:EXCHANGE                                                               |
|   |                                                                              |
|   4:HASH JOIN                                                                    |
|   |  join op: LEFT OUTER JOIN (BROADCAST)                                        |
|   |  hash predicates:                                                            |
|   |  colocate: false, reason: Tables are not in the same group                   |
|   |  equal join conjunct: `A`.`apply_crcl` = `C`.`id`                            |
|   |                                                                              |
|   |----9:EXCHANGE                                                                |
|   |                                                                              |
|   2:HASH JOIN                                                                    |
|   |  join op: LEFT OUTER JOIN (BUCKET_SHUFFLE)                                   |
|   |  hash predicates:                                                            |
|   |  colocate: false, reason: Tables are not in the same group                   |
|   |  equal join conjunct: `A`.`ID` = `B`.`PRJT_ID`                               |
|   |                                                                              |
|   |----8:EXCHANGE                                                                |
|   |                                                                              |
|   0:OlapScanNode                                                                 |
|      TABLE: T_DORIS_A                                                            |
|      PREAGGREGATION: OFF. Reason: No AggregateInfo                               |
|      partitions=1/1                                                              |
|      rollup: T_DORIS_A                                                           |
|      tabletRatio=32/32                                                           |
|      tabletList=71030,71032,71034,71036,71038,71040,71042,71044,71046,71048 ...  |
|      cardinality=9884                                                            |
|      avgRowSize=5.156718                                                         |
|      numNodes=1       
```
**Expected behavior**

The right query paln should be:
```
|   6:HASH JOIN                                                                    |
|   |  join op: INNER JOIN (BROADCAST)                                             |
|   |  hash predicates:                                                            |
|   |  colocate: false, reason: The src data has been redistributed                |
|   |  equal join conjunct: `C`.`ID` = `D`.`CORE_ID`                               |
|   |                                                                              |
|   |----10:EXCHANGE                                                               |
|   |                                                                              |
|   4:HASH JOIN                                                                    |
|   |  join op: LEFT OUTER JOIN (BROADCAST)                                        |
|   |  hash predicates:                                                            |
|   |  colocate: false, reason: Tables are not in the same group                   |
|   |  equal join conjunct: `A`.`apply_crcl` = `C`.`id`                            |
|   |                                                                              |
|   |----9:EXCHANGE                                                                |
|   |                                                                              |
|   2:HASH JOIN                                                                    |
|   |  join op: LEFT OUTER JOIN (BUCKET_SHUFFLE)                                   |
|   |  hash predicates:                                                            |
|   |  colocate: false, reason: Tables are not in the same group                   |
|   |  equal join conjunct: `A`.`ID` = `B`.`PRJT_ID`                               |
|   |                                                                              |
|   |----8:EXCHANGE                                                                |
|   |                                                                              |
|   0:OlapScanNode                                                                 |
|      TABLE: T_DORIS_A                                                            |
|      PREAGGREGATION: OFF. Reason: No AggregateInfo                               |
|      partitions=1/1                                                              |
|      rollup: T_DORIS_A                                                           |
|      tabletRatio=32/32                                                           |
|      tabletList=71030,71032,71034,71036,71038,71040,71042,71044,71046,71048 ...  |
|      cardinality=9884                                                            |
|      avgRowSize=5.156718                                                         |
|      numNodes=1  
```

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Fix the bug #6171 

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6171) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java [hunk 1]
```diff
@@ -683,9 +678,14 @@ private boolean canBucketShuffleJoin(HashJoinNode node, PlanNode leftRoot,
         DistributionInfo leftDistribution = leftScanNode.getOlapTable().getDefaultDistributionInfo();
 
         if (leftDistribution instanceof HashDistributionInfo) {
+            // use the table_name + '-' + column_name as check condition
             List<Column> leftDistributeColumns = ((HashDistributionInfo) leftDistribution).getDistributionColumns();
+            List<String> leftDistributeColumnNames = Lists.newArrayList();
+            for (Column col : leftDistributeColumns) {
+                leftDistributeColumnNames.add(leftTable.getName() + "-" + col.getName());
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java:685]: used to "."

File: fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java [hunk 2]
```diff
@@ -696,18 +696,21 @@ private boolean canBucketShuffleJoin(HashJoinNode node, PlanNode leftRoot,
...
 
-                SlotDescriptor leftSlot = lhsJoinExpr.unwrapSlotRef().getDesc();
-
-                leftJoinColumns.add(leftSlot.getColumn());
-                rightExprs.add(rhsJoinExpr);
+                SlotRef leftSlot = lhsJoinExpr.unwrapSlotRef();
+                if (leftSlot.getTable() instanceof OlapTable) {
+                    // table name in SlotRef is not the really name. `select * from test as t`
+                    // table name in SlotRef is `t`, but here we need is `test`.
+                    leftJoinColumnNames.add(leftSlot.getTable().getName() + "-" + leftSlot.getColumnName());
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java:703]: used to '"."

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
