### PR TITLE
[Doris On ES][Bug-fix] fix boolean predicate pushdown manner

### LINKED ISSUE #4989: [Doris On ES][Bug] Doris On Es Boolean Field Push Down error
**Describe the bug**
When I create an ES external and use a Boolean field, `where` if this field is used, the query for ES will report an error.

[42000][1064] errCode = 2, detailMessage = Failed to connect to ES server, errmsg is: The requested URL returned error: 400 Bad Request

**To Reproduce**
1. CREATE
EXTERNAL TABLE `es_dwd_student_stat` (
  `userId` varchar(255) NULL COMMENT "用户id",
  `courseId` bigint(20) NULL COMMENT "课程id",
  `groupId` bigint(20) NULL COMMENT "组id",
  `syncedAt` datetime NULL COMMENT "同步时间",
  `deleted` boolean NULL COMMENT "是否删除"
) ENGINE=ELASTICSEARCH

2. select * from es_dwd_student_stat where deleted=true;

**Expected behavior**
deleted push down should be true

**Version**
 - Version 0.13.11

### PR DESCRIPTION
**Pull request by wuyunfeng**
## Proposed changes

Test Data:

```
CREATE EXTERNAL TABLE `bool_test` (
  `k1` int NULL COMMENT "",
  `k2` boolean NULL COMMENT ""
) ENGINE=ELASTICSEARCH
PROPERTIES (
"hosts" = "http://host:ip",
"user" = "root",
"password" = "root",
"index" = "bool_test",
"type" = "doc"
); 
```

```
MySQL [es]> select * from bool_test;
+------+------+
| k1   | k2   |
+------+------+
|    1 |    1 |
|    2 |    0 |
|    3 |    1 |
|    4 |    0 |
+------+------+
```

Process `boolean` field predicate be consistent with `mysql` grammar. such as:

```
MySQL [es]> select * from bool_test where k2 = true;
+------+------+
| k1   | k2   |
+------+------+
|    1 |    1 |
|    3 |    1 |
+------+------+
```

```
MySQL [es]> select * from bool_test where k2 = false;
+------+------+
| k1   | k2   |
+------+------+
|    2 |    0 |
|    4 |    0 |
+------+------+
```

```
MySQL [es]> select * from bool_test where k2 = 2;
Empty set (0.089 sec)
```

```
MySQL [es]> select * from bool_test where k2 = 0;
+------+------+
| k1   | k2   |
+------+------+
|    2 |    0 |
|    4 |    0 |
+------+------+
```

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

DOE user should know: This PR just process `=` predicate for `boolean` type column

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

File: be/src/exec/es/es_query_builder.cpp [hunk 1]
```diff
@@ -50,19 +50,39 @@ void ESQueryBuilder::to_json(rapidjson::Document* document, rapidjson::Value* qu
...
 
 TermQueryBuilder::TermQueryBuilder(const std::string& field, const std::string& term)
-        : _field(field), _term(term) {}
+        : _field(field), _term(term), _match_none(false) {}
 
 TermQueryBuilder::TermQueryBuilder(const ExtBinaryPredicate& binary_predicate)
-        : _field(binary_predicate.col.name), _term(binary_predicate.value.to_string()) {}
+        : _field(binary_predicate.col.name), _match_none(false) {
+        if (binary_predicate.col.type.type == PrimitiveType::TYPE_BOOLEAN) {
+            int val = atoi(binary_predicate.value.to_string().c_str());
```
Comment (chaoyli) [inline be/src/exec/es/es_query_builder.cpp:58]: use StringParse::string_to_int instead

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: be/src/exec/es/es_query_builder.cpp (hunk 1 above)
Comment (wuyunfeng) [reply be/src/exec/es/es_query_builder.cpp:58]: I think this is ok

**Review by chaoyli — APPROVED** [review]
