### PR TITLE
[Bug] Fix multi broker load bug

### LINKED ISSUE #5544: [Bug] Failed to execute multi load
**Describe the bug**
`show load` shows:

```
Couldn\'t open transport for 127.0.0.1:0 (socket open() error: Connection refused),
```

### PR DESCRIPTION
**Pull request by xxiao2018**
## Proposed changes

The storage type of broker desc should be set due to the type of load job

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have created an issue on (Fix #5544 ) and described the bug/feature there in detail

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/BrokerDesc.java [hunk 1]
```diff
@@ -60,7 +60,11 @@ public BrokerDesc(String name, Map<String, String> properties) {
         if (this.properties == null) {
             this.properties = Maps.newHashMap();
         }
-        this.storageType = StorageBackend.StorageType.BROKER;
+        if (this.name.equalsIgnoreCase(BrokerDesc.MULTI_LOAD_BROKER)) {
```
Comment (yangzhg) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/BrokerDesc.java:63]:
```suggestion
        if (this.name.equalsIgnoreCase(BrokerDesc.MULTI_LOAD_BROKER)) {
        if (isMultiLoadBroker()) {
```

**Review by morningman — APPROVED** [review]
LGTM
The FE UT bug has been fixed in #5541
