### PR TITLE
[Bug] fix string type length limit error && add runtime filter decimal support

### LINKED ISSUE #8281: [Bug] fix string type length limit error && add runtime filter decimal support
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

1. fix string type length limit error
2. add runtime filter decimal support
3. add support bitmap/hll on case when

### What You Expected?

fix

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes
@HappenLee 
Issue Number: close #8281 #8262

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/core/block.cpp [hunk 1]
```diff
@@ -720,12 +720,9 @@ Status Block::serialize(PBlock* pblock, size_t* uncompressed_bytes, size_t* comp
     // serialize data values
     allocated_buf->resize(content_uncompressed_size);
     char* buf = allocated_buf->data();
-    char* start_buf = buf;
     for (const auto& c : *this) {
         buf = c.type->serialize(*(c.column), buf);
     }
-    CHECK(content_uncompressed_size == (buf - start_buf))
```
Comment (morningman) [inline be/src/vec/core/block.cpp:727]: why remove this?

**Review by HappenLee — APPROVED** [review]
LGTM
