### PR TITLE
[Bug](case function) do not crash if prepare failed

### LINKED ISSUE #15112: [Bug] BE crash when prepare failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

*** Aborted at 1671095251 (unix time) try "date -d @1671095251" if you are using GNU date ***
*** Current BE git commitID: 44a3745f0 ***
*** SIGABRT unkown detail explain (@0xb46) received by PID 2886 (TID 0x7f3a2905d700) from PID 2886; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/common/signal_handler.h:420
 1# 0x00007F3C0EFE05D0 in /lib64/libpthread.so.0
 2# raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x0000555950E29749 in /root/smartbi-test/output/be/lib/doris_be
 5# 0x0000555950E1ED5D in /root/smartbi-test/output/be/lib/doris_be
 6# google::LogMessage::SendToLog() in /root/smartbi-test/output/be/lib/doris_be
 7# google::LogMessage::Flush() in /root/smartbi-test/output/be/lib/doris_be
 8# google::LogMessageFatal::~LogMessageFatal() in /root/smartbi-test/output/be/lib/doris_be
 9# doris::vectorized::VExprContext::fn_context(int) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/exprs/vexpr_context.h:52
10# doris::vectorized::VCaseExpr::close(doris::RuntimeState*, doris::vectorized::VExprContext*, doris_udf::FunctionContext::FunctionStateScope) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/exprs/vcase_expr.cpp:79
11# doris::vectorized::VExprContext::close(doris::RuntimeState*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/exprs/vexpr_context.cpp:74
12# doris::vectorized::VExpr::close(std::vector<doris::vectorized::VExprContext*, std::allocator<doris::vectorized::VExprContext*> > const&, doris::RuntimeState*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/exprs/vexpr.cpp:238
13# doris::vectorized::VSortExecExprs::close(doris::RuntimeState*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/common/sort/vsort_exec_exprs.cpp:79
14# doris::vectorized::VSortNode::release_resource(doris::RuntimeState*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/exec/vsort_node.cpp:159
15# doris::ExecNode::close(doris::RuntimeState*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/exec/exec_node.cpp:318
16# doris::vectorized::VSortNode::close(doris::RuntimeState*) at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/vec/exec/vsort_node.cpp:168
17# doris::PlanFragmentExecutor::close() at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:666
18# doris::PlanFragmentExecutor::~PlanFragmentExecutor() at /mnt/disk1/liyuanyuan/smartbi-or-select/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:74

### What You Expected?

return Status instead of crash

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gabriel39**
# Proposed changes

Issue Number: close #15112

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/exprs/vcase_expr.cpp [hunk 1]
```diff
@@ -73,13 +73,6 @@ Status VCaseExpr::open(RuntimeState* state, VExprContext* context,
 
 void VCaseExpr::close(RuntimeState* state, VExprContext* context,
                       FunctionContext::FunctionStateScope scope) {
-    if (scope == doris_udf::FunctionContext::FRAGMENT_LOCAL) {
```
Comment (HappenLee) [inline be/src/vec/exprs/vcase_expr.cpp:76]: better do `new` operator in function_case.h prepare function

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.53 seconds
 load time: 471 seconds
 storage size: 17123356837 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221215122524_clickbench_pr_63990.html

**Review by yiguolei — APPROVED** [review]
LGTM
