### PR TITLE
[fix](func) Fix precision loss in ST_GeometryFromWKB coordinate parsing

### LINKED ISSUE #46619: [Bug] function ST_GeometryFromWKB result diff between doris and postgis
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.7

### What's Wrong?

function ST_GeometryFromWKB result diff between doris and postgis.
for example:
select st_astext(ST_GeometryFromWKB('01010000208A11000068270210774C5D40B8DECA334C3B4240'))
result:
POINT (1.461652102e-231 3.34424828009e-59)

but postgis:
select ST_asText('01010000208A11000068270210774C5D40B8DECA334C3B4240')
result:
POINT(117.194767000297 36.46326301008)

### What You Expected?

return the same as postgis result
POINT(117.194767000297 36.46326301008)

### How to Reproduce?

select st_astext(ST_GeometryFromWKB('01010000208A11000068270210774C5D40B8DECA334C3B4240'))

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by felixwluo**
### What problem does this PR solve?

Issue Number: close #46619

Root Cause:
```
1. Unnecessary floating-point number conversions in coordinate handling:
   1.1 converting double to string using absl::StrFormat
   1.2 converting string back to double using std::stod
each conversion caused precision loss.

2. Byte order handling issue in WKB parsing:
    2.1 using machine endian before properly reading WKB byte order flag
    2.2 this caused incorrect interpretation of coordinate values
```

Solution:
```
1. Remove unnecessary coordinate value conversions:
    1.1 directly use S2LatLng's degrees() value without string formatting
    1.2 increase output precision in print_s2point to 15 digits

2. Fix WKB byte order handling:
    2.1 read byte order flag first
    2.2 set correct byte order before parsing coordinates
```

Result:
 before:
 ```
 POINT (1.461652102e-231 3.34424828009e-59)
 ```
 after:
 ```
 POINT(117.194767000297 36.46326301008)
 ```

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

File: be/src/geo/geo_types.cpp [hunk 1]
```diff
@@ -316,13 +326,23 @@ bool GeoPoint::decode(const void* data, size_t size) {
 }
 
 double GeoPoint::x() const {
-    //Accurate to 13 decimal places
-    return std::stod(absl::StrFormat("%.13f", S2LatLng::Longitude(*_point).degrees()));
+    double value = S2LatLng::Longitude(*_point).degrees();
+    // Handle values very close to integers
+    double rounded = round(value);
+    if (std::abs(value - rounded) < 1e-13) { // 使用更大的阈值
```
Comment (HappenLee) [inline be/src/geo/geo_types.cpp:332]: please use english, thank you

Comment (felixwluo) [reply be/src/geo/geo_types.cpp]: done

**Comment by zclllyybb** [comment]
I will review this PR later

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run cloud_p0

File: be/src/geo/wkb_parse.cpp [hunk 2]
```diff
@@ -122,108 +122,169 @@ WkbParseContext* WkbParse::read(std::istream& is, WkbParseContext* ctx) {
...
-        shape.reset(readLine(ctx).release());
-        break;
-    case wkbType::wkbPolygon:
-        shape.reset(readPolygon(ctx).release());
-        break;
-    default:
+        uint32_t typeInt = ctx->dis.readUnsigned();
+
+        // Check if geometry has SRID
+        bool has_srid = (typeInt & 0x20000000) != 0;
```
Comment (zclllyybb) [inline be/src/geo/wkb_parse.cpp:181]: for magic numbers, we should define it as constexpr variable with comment giving its source and explaining what does it do

**Comment by felixwluo** [comment]
run buildall

File: be/src/geo/wkb_parse.cpp (hunk 2 above)
Comment (felixwluo) [reply be/src/geo/wkb_parse.cpp]: done

**Comment by felixwluo** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM
