### PR TITLE
[Bug](exec) fix intersections/differences bug

### LINKED ISSUE #34633: [Bug] When performing consecutive intersections/differences of multiple tables,SQL result is error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2/2.0.3/master etc.

### What's Wrong?

When performing consecutive intersections/differences of multiple tables, if the nullable attribute of a column in the left table is set to false, and the left table contains zero values while the right table contains null values, the result is incorrect. 
sql like this :
image
image

The correct result is the opposite of that.

### What You Expected?

this bug's reason I've found ,but due to changes in different versions, hope someone experienced can fix it.

### How to Reproduce?

just execute the sql 

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Issue Number: close #34633

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

File: be/src/vec/exec/vset_operation_node.cpp [hunk 1]
```diff
@@ -427,19 +419,12 @@ Status VSetOperationNode<is_intersect>::extract_build_column(Block& block,
...
-            }
-
-        } else {
-            raw_ptrs[i] = column;
+        if (_build_not_ignore_null[i]) {
+            block.get_by_position(result_col_id).column =
+                    make_nullable(block.get_by_position(result_col_id).column);
         }
+        const auto* column = block.get_by_position(result_col_id).column.get();
+        raw_ptrs[i] = column;
```
Comment (Gabriel39) [inline be/src/vec/exec/vset_operation_node.cpp:427]:
```suggestion
        raw_ptrs[i] = block.get_by_position(result_col_id).column.get();
```

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]
