### PR TITLE
[optimize] push down predicate past two phase aggregate

### LINKED ISSUE #9476: [Bug] where predicate can not be pushed down when querying logic view
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

```
create table tbl1(k1 int, v1 int) distributed by hash(k1) buckets 1 properties("replication_num" = "1");
create view tblv1 as select k1, sum(v1) from tbl1 group by 1;
create view tblv2 as select k1, count(distinct v1) from tbl1 group by 1;
```
1. For query
```
select * from tblv1 where k1 =1;
```
the  `k1=1` can be pushed down to scan node.

2. For query
```
select * from tblv2 where k1 =1;
```
the  `k1=1` can NOT be pushed down to scan node.

### What You Expected?

For both query, where predicate can be pushed down to scan node.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #9476

## Problem Summary:

Push down predicate past aggregate cannot push down predicate past 2 phase aggregate.

origin plan is like this:
```
second phase agg (conjuncts on olap scan node tuples)
|
first phase agg
|
olap scan node
```
should be optimized to
```
second phase agg
|
first phase agg
|
olap scan node (conjuncts on olap scan node tuples)
```

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java [hunk 1]
```diff
@@ -1029,7 +1029,6 @@ private PlanNode createSelectPlan(SelectStmt selectStmt, Analyzer analyzer, long
             }
 
             for (int i = 1; i < selectStmt.getTableRefs().size(); ++i) {
-                TableRef outerRef = selectStmt.getTableRefs().get(i - 1);
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:1032]: remove unused local variable

File: fe/fe-core/src/test/java/org/apache/doris/planner/PushDownPredicateTest.java [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+import java.util.List;
+
+/**
+ * Test Push down predicate on aggregate and window function.
+ */
+public class PushDownPredicateTest extends TestWithFeService {
```
Comment (morningman) [inline fe/fe-core/src/test/java/org/apache/doris/planner/PushDownPredicateTest.java:32]: I think we can move this test to PlannerTest. To save FE start time when running UT.

File: fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java [hunk 3]
```diff
@@ -343,15 +343,15 @@ private PlanNode addUnassignedConjuncts(
         // Gather unassigned conjuncts and generate predicates to enfore
         // slot equivalences for each tuple id.
         List<Expr> conjuncts = analyzer.getUnassignedConjuncts(root);
-        for (TupleId tid : tupleIds) {
-            // TODO(zc)
-            // analyzer.createEquivConjuncts(tid, conjuncts);
-        }
+        // for (TupleId ignored : tupleIds) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:346]: Remove all of these unused code

File: fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java [hunk 4]
```diff
@@ -2363,8 +2396,16 @@ private List<Expr> getPredicatesBoundedByGroupbysSourceExpr(List<Expr> predicate
 
             boolean isAllSlotReferingGroupBys = true;
             for (SlotId slotId : slotIds) {
-                final SlotDescriptor slotDesc = analyzer.getDescTbl().getSlotDesc(slotId);
-                Expr sourceExpr = slotDesc.getSourceExprs().get(0);
+
+                Expr sourceExpr = new SlotRef(analyzer.getDescTbl().getSlotDesc(slotId));
+                while (sourceExpr instanceof SlotRef) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:2401]: Why adding this unnest logic? Could you add an example in code to explain?

Comment (morrySnow) [reply fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:2400]: add comment

File: fe/fe-core/src/test/java/org/apache/doris/planner/PushDownPredicateTest.java (hunk 2 above)
Comment (morrySnow) [reply fe/fe-core/src/test/java/org/apache/doris/planner/PushDownPredicateTest.java]: done

**Review by morningman — APPROVED** [review]
LGTM
