### PR TITLE
[chore] Fix unhandled exceptions thrown by stoi on streamload

### LINKED ISSUE #48859: [Bug] be does not handle timeout out of range for streamload
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

A streamload with timeout beyonds int32 results a core dump.

### What You Expected?

handle timeout beyonds int32 without a coredump.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tech-Circle-48**
### What problem does this PR solve?

Issue Number: close #48859

Related PR: #xxx

Problem Summary:
fixes the issue where providing a timeout value exceeding the range of int32 causes a core dump during streamload.

The root cause is that the timeout value parsed using std::stoi() can throw a std::out_of_range exception if the value exceeds int32 limits, which wasn't handled correctly.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Tech-Circle-48** [comment]
run buildall

**Comment by hello-stephen** [comment]
# BE UT Coverage Report
Increment line coverage `0.00% (0/28)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/db3f51196b1e05b8a8aa2c603ffaae5c9ba3c73b_db3f51196b1e05b8a8aa2c603ffaae5c9ba3c73b/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/db3f51196b1e05b8a8aa2c603ffaae5c9ba3c73b_db3f51196b1e05b8a8aa2c603ffaae5c9ba3c73b/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage | 51.33% (13736/26760) |
| Line Coverage     | 40.69% (119617/293960) |
| Region Coverage   | 39.42% (60941/154613) |
| Branch Coverage   | 34.22% (30588/89392) |

**Comment by Tech-Circle-48** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Tech-Circle-48** [comment]
run buildall

**Comment by Tech-Circle-48** [comment]
run buildall

**Comment by Tech-Circle-48** [comment]
run buildall

**Comment by hello-stephen** [comment]
# BE UT Coverage Report
Increment line coverage `0.00% (0/30)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/39c15cc5f6d0bcdc0bbc2996d6e1a51be7a3def0_39c15cc5f6d0bcdc0bbc2996d6e1a51be7a3def0/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/39c15cc5f6d0bcdc0bbc2996d6e1a51be7a3def0_39c15cc5f6d0bcdc0bbc2996d6e1a51be7a3def0/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage | 53.15% (14421/27132) |
| Line Coverage     | 42.02% (124986/297475) |
| Region Coverage   | 40.82% (63840/156391) |
| Branch Coverage   | 35.46% (32105/90534) |

File: be/src/http/action/adjust_log_level.cpp [hunk 1]
```diff
@@ -38,8 +38,18 @@ std::tuple<std::string, int, int> handle_request(HttpRequest* req) {
     };
     const auto& module = parse_param("module");
     const auto& level = parse_param("level");
-    int new_level = std::stoi(level);
-    return std::make_tuple(module, google::SetVLOGLevel(module.c_str(), new_level), new_level);
+    try {
+        int new_level = std::stoi(level);
```
Comment (morningman) [inline be/src/http/action/adjust_log_level.cpp:42]: I searched the code base and find there are a lot `std::stoi`.
So I suggest to extract a method, like `safe_stoi()` to handle this,
so we don't need to catch these exception everywhere.

**Comment by morningman** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by Tech-Circle-48** [comment]
run buildall

**Comment by hello-stephen** [comment]
# BE Regression P0 && UT Coverage Report
Increment line coverage `0.00% (0/44)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/49714_1dd04affc731e356b1a5a8ccd2c0034c8acf9925_merge/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/49714_1dd04affc731e356b1a5a8ccd2c0034c8acf9925_merge/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage |                    |
| Line Coverage     |                    |
| Region Coverage   |                    |
| Branch Coverage   |                    |

**Comment by hello-stephen** [comment]
# BE UT Coverage Report
Increment line coverage `0.00% (0/44)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/1dd04affc731e356b1a5a8ccd2c0034c8acf9925_1dd04affc731e356b1a5a8ccd2c0034c8acf9925/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/1dd04affc731e356b1a5a8ccd2c0034c8acf9925_1dd04affc731e356b1a5a8ccd2c0034c8acf9925/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage | 53.59% (14548/27147) |
| Line Coverage     | 42.44% (126307/297601) |
| Region Coverage   | 41.23% (64517/156485) |
| Branch Coverage   | 35.83% (32456/90588) |

**Comment by hello-stephen** [comment]
# BE Regression P0 && UT Coverage Report
Increment line coverage `0.00% (0/44)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/49714_1dd04affc731e356b1a5a8ccd2c0034c8acf9925_merge/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/49714_1dd04affc731e356b1a5a8ccd2c0034c8acf9925_merge/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage |                    |
| Line Coverage     |                    |
| Region Coverage   |                    |
| Branch Coverage   |                    |

**Comment by hello-stephen** [comment]
# BE Regression P0 && UT Coverage Report
Increment line coverage `0.00% (0/44)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/49714_1dd04affc731e356b1a5a8ccd2c0034c8acf9925_merge/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/49714_1dd04affc731e356b1a5a8ccd2c0034c8acf9925_merge/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage |                    |
| Line Coverage     |                    |
| Region Coverage   |                    |
| Branch Coverage   |                    |

**Review by morningman — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — COMMENTED** [review]
LGTM
