### PR TITLE
[fix](multi-catalog)support bit type and hidden mc secret key

### LINKED ISSUE #24019: When showing the catalog of max compute, the key did not mask
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

When showing the catalog of max compute, the key did not mask 

show create catalog mc ；

 mc.secret_key and mc.access_key not mask.

### What You Expected?

 mc.secret_key or mc.access_key   mask.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

support max compute bit type and mask mc secret key
bool type will use bit arrow vector
should mask secret key: close https://github.com/apache/doris/issues/24019

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

File: fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeColumnValue.java [hunk 1]
```diff
@@ -83,8 +84,8 @@ private void skippedIfNull() {
     @Override
     public boolean getBoolean() {
         skippedIfNull();
-        TinyIntVector tinyIntCol = (TinyIntVector) column;
-        return tinyIntCol.get(idx++) > 0;
+        BitVector bitCol = (BitVector) column;
```
Comment (morningman) [inline fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeColumnValue.java:87]: Please explain why using bitvector here?
and what about tinyint?

Comment (wsjz) [reply fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeColumnValue.java:87]: bool type is bind to bit vector
tinyint type  bind to tinyint vector, it can work

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM
