### PR TITLE
[BUG] Ensure that the correct lead/lag function is selected

### LINKED ISSUE #4730: [lead/lag will cause BE down]
**Describe the bug**
query with lead or lag will cause some be down

**To Reproduce**
`  select lead(last_stage_id, 1, null) over (
                        partition by student_id
                        order by
                            paid_date_time
                    ) as next_stage_id,
                    lead(is_refund_order, 1, null) over (
                        partition by student_id
                        order by
                            paid_date_time
                    ) as next_is_refund_order,
                    lead(consumption, 1, null) over (
                        partition by student_id
                        order by
                            paid_date_time
                    ) as next_consumption,
                    lead(paid_date_time, 1, null) over (
                        partition by student_id
                        order by
                            paid_date_time
                    ) as next_paid_date_time
from xxxx`
**Expected behavior**
exec normally

### PR DESCRIPTION
**Pull request by HangyuanLiu**
FIX #4730 
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java [hunk 1]
```diff
@@ -334,11 +334,17 @@ private void analyzeBuiltinAggFunction(Analyzer analyzer) throws AnalysisExcepti
...
                         throw new AnalysisException(
                                 "The default parameter (parameter 3) of LAG must be a constant: "
                                         + this.toSql());
                     }
+                    getChild(1).type = Type.BIGINT;
+                    //To ensure that the correct function is selected,the third parameter
+                    //of the lead function must be consistent with the first parameter
+                    if (!getChild(2).type.matchesType(getChild(0).type) && !getChild(2).type.matchesType(Type.NULL)) {
+                        getChild(2).type = getChild(0).type;
+                    }
```
Comment (imay) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java:347]: You should call uncheckCastTo to change child's type.

File: fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java [hunk 2]
```diff
@@ -334,11 +334,17 @@ private void analyzeBuiltinAggFunction(Analyzer analyzer) throws AnalysisExcepti
                 throw new AnalysisException(fnName.getFunction() + " only used in analytic function");
             } else {
                 if (children.size() > 2) {
-                    if (!getChild(2).isConstant()) {
+                    if (!getChild(1).isConstant() || !getChild(2).isConstant()) {
```
Comment (imay) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java:337]: Should change the warning log

**Review by imay — CHANGES_REQUESTED** [review]

**Review by imay — APPROVED** [review]
LGTM
