### PR TITLE
[Bug] fix core dump on minmax_filter with decimal type

### LINKED ISSUE #8380: [Bug] fix core dump on minmax_filter with decimal type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```cpp
start time: 2022年 03月 07日 星期一 16:45:23 CST
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0307 16:45:23.564831 13352 env.cpp:46] Env init successfully.
Minidump created at: /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/minidump/fdbac494-2ca6-4a14-92c2958e-a6d9a153.dmp
*** Aborted at 1646642730 (unix time) try "date -d @1646642730" if you are using GNU date ***
PC: @     0x564a1bca5d41 doris::MinMaxNumFunc<>::insert()
*** SIGSEGV (@0x0) received by PID 13352 (TID 0x7f5495f6c700) from PID 0; stack trace: ***
    @     0x564a1dad7042 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f54f35ff920 (unknown)
    @     0x564a1bca5d41 doris::MinMaxNumFunc<>::insert()
    @     0x564a1bcc324d doris::HashJoinNode::open()
    @     0x564a1bec3484 doris::PlanFragmentExecutor::open_internal()
    @     0x564a1bec4745 doris::PlanFragmentExecutor::open()
    @     0x564a1bea7265 doris::FragmentExecState::execute()
    @     0x564a1beabada doris::FragmentMgr::_exec_actual()
    @     0x564a1beb724c std::_Function_handler<>::_M_invoke()
    @     0x564a1c141299 doris::ThreadPool::dispatch_thread()
    @     0x564a1c13667f doris::Thread::supervise_thread()
    @     0x7f54f33b7851 start_thread
    @     0x7f54f36b467d clone
    @                0x0 (unknown)
```

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #8380

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exprs/minmax_predicate.h [hunk 1]
```diff
@@ -42,9 +42,14 @@ class MinMaxNumFunc : public MinMaxFuncBase {
...
     MinMaxNumFunc() = default;
     ~MinMaxNumFunc() = default;
-    virtual void insert(const void* data) {
-        if (data == nullptr) return;
-        const T val_data = *reinterpret_cast<const T*>(data);
+    void insert(const void* data) override {
+        if (data == nullptr) {
+            return;
+        }
+
```
Comment (HappenLee) [inline be/src/exprs/minmax_predicate.h:49]: only core when int128_t, so maybe constexpr + sizeof.
and add comment

**Review by HappenLee — APPROVED** [review]
LGTM
