### PR TITLE
[fix](editLog) add sufficient replay logic and edit log for altering light schema change

### LINKED ISSUE #18732: [Bug] support altering the property "light_schema_change" for the old tables cause rename colunm fail
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master d2efc619b0aa4c18c290044bc53a5ef83d37f6b1

### What's Wrong?

Exception in schema_change_p0/test_rename_column.groovy(line 67):

    sql """ALTER TABLE ${tableName} SET ("light_schema_change" = "true");"""

    qt_select """ SELECT * FROM ${tableName} order by user_id ASC, last_visit_date """

    // rename key column
    sql """ ALTER table ${tableName} RENAME COLUMN  user_id new_user_id """

    sql """ sync """

    qt_select """ SELECT * FROM ${tableName} order by new_user_id DESC, last_visit_date """
^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^

    qt_desc """ desc ${tableName} """

    sql """
        INSERT INTO ${tableName} VALUES
                (3, '2017-10-01', 'Beijing', 10, 1, '2020-01-01', '2020-01-01', '2020-01-01', 1, 32, 22)
        """
    qt_select """ SELECT * FROM ${tableName} order by new_user_id DESC, last_visit_date """

    // rename value column

Exception:
java.sql.SQLSyntaxErrorException: errCode = 2, detailMessage = Unknown column 'new_user_id' in 'table list'

### What You Expected?

test_rename_column.groovy regression case can work well

### How to Reproduce?

1、Build a 3 fe and 3 be cluster 
2、use follower's ip regression-conf.groovy jdbcUrl(take care not master's ip) 
3、run regression-test p0 case `test_rename_column.groovy`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

Issue Number: close #18732

## Problem summary

As title.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java [hunk 1]
```diff
@@ -79,7 +80,16 @@ public void enableLightSchemaChange() throws DdlException {
         final Map<Long, PFetchColIdsRequest> params = initParams();
         final PFetchColIdsResponse response = callForColumnIds(params);
         updateTableMeta(response);
-        modifyTableProperty();
+        writeEditLog(response);
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java:83]: It is unnecessary add a function `writeEditLog()` here

File: fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java [hunk 2]
```diff
@@ -79,7 +80,16 @@ public void enableLightSchemaChange() throws DdlException {
...
+    }
+
+    /**
+     * replay logic for alter LSC
+     *
+     * @param response will be set in edit log
+     */
+    public void replayAlterLSC(PFetchColIdsResponse response) throws DdlException {
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java:91]: It is unnecessary add a function replayAlterLSC here

File: fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java [hunk 3]
```diff
@@ -238,14 +248,14 @@ private void updateTableMeta(PFetchColIdsResponse response) throws DdlException
...
         // write table property
         olapTable.setEnableLightSchemaChange(true);
+    }
+
+    private void writeEditLog(PFetchColIdsResponse response) {
         //write edit log
-        ModifyTablePropertyOperationLog info = new ModifyTablePropertyOperationLog(db.getId(), olapTable.getId(),
-                olapTable.getTableProperty().getProperties());
-        Env.getCurrentEnv().getEditLog().logAlterLightSchemaChange(info);
+        final AlterLSCOperationLog operationLog = new AlterLSCOperationLog(
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java:257]: AlterLSCOperationLog operationLog -> AlterLightSchemaChangeInfo info

File: fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java [hunk 4]
```diff
@@ -1894,6 +1895,20 @@ private void enableLightSchemaChange(Database db, OlapTable olapTable) throws Dd
         alterLSCHelper.enableLightSchemaChange();
     }
 
+    public void replayAlterLSC(AlterLSCOperationLog info) throws MetaNotFoundException {
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java:1898]: `replayAlterLSC` -> `replayAlterLightSchemaChange`,   the abbreviation `LSC ` is not CamelCase

File: fe/fe-core/src/main/java/org/apache/doris/persist/AlterLSCOperationLog.java [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+    @SerializedName(value = "dbId")
+    private Long dbId;
+
+    @SerializedName(value = "tableId")
+    private Long tableId;
+
+    @SerializedName(value = "indexIds")
+    private List<Long> indexIds;
+
+    @SerializedName(value = "colNameToIds")
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/persist/AlterLSCOperationLog.java:48]: how about  put  `indexIds` and `colNameToIds` into a map? don't use PFetchColIdsResponse here

File: fe/fe-core/src/main/java/org/apache/doris/persist/AlterLSCOperationLog.java [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+import com.google.gson.annotations.SerializedName;
+
+import java.io.DataInput;
+import java.io.DataOutput;
+import java.io.IOException;
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Map;
+
+public class AlterLSCOperationLog implements Writable {
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/persist/AlterLSCOperationLog.java:37]: Don't use the abbreviation `LSC`,  it's not CamelCase style in java

**Comment by TangSiyang2001** [comment]
run compile

**Comment by TangSiyang2001** [comment]
run arm

File: fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java [hunk 7]
```diff
@@ -79,7 +80,16 @@ public void enableLightSchemaChange() throws DdlException {
         final Map<Long, PFetchColIdsRequest> params = initParams();
         final PFetchColIdsResponse response = callForColumnIds(params);
         updateTableMeta(response);
```
Comment (SWJTU-ZhangLei) [inline fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java:82]: 1、make `updateTableMeta(response)`  like this updateTableMeta(AlterLightSchemaChangeInfo info) so that it can be reused in replay

File: fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java (hunk 1 above)
Comment (TangSiyang2001) [reply fe/fe-core/src/main/java/org/apache/doris/alter/AlterLSCHelper.java:83]: I think we could keep `writeEditLog()` here so that we can omit the writeEditLog related logic in replay process, and just use `updateTableMeta()` then.

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p1

**Comment by TangSiyang2001** [comment]
run p1

**Comment by TangSiyang2001** [comment]
run p1

**Comment by TangSiyang2001** [comment]
run p1

**Comment by TangSiyang2001** [comment]
run p1

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM
