### PR TITLE
[fix](forward) Avoid endless forward execution

### LINKED ISSUE #7334: [Bug] show frontends cause FE oom
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

`show frontends` or `show backends` cause FE oom.
This because:

1. For some other reason, there is no valid Master FE.
2. `show frontends` will forward to master FE, but Master FE is not ready, so it try to forward again.
3. Endless forward cause OOM

### What You Expected?

Return error when master FE is not ready.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Close related #7334 (replace it with issue number if it exists).

1. Fix bug describe in #7334
2. Fix error of `CurrentConnected` fields in `show frontends` result.
3. Add more FAQ

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java [hunk 1]
```diff
@@ -90,7 +92,12 @@ public static void getFrontendsInfo(Catalog catalog, List<List<String>> infos) {
         List<Pair<String, Integer>> allFeHosts = convertToHostPortPair(allFe);
         List<Pair<String, Integer>> helperNodes = catalog.getHelperNodes();
 
-        Pair<String, Integer> selfNode = Catalog.getCurrentCatalog().getSelfNode();
+        // Because the `shwo frontend` stmt maybe forwarded from other FE.
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java:95]:
```suggestion
        // Because the `show frontend` stmt maybe forwarded from other FE.
```

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java [hunk 2]
```diff
@@ -182,12 +185,15 @@ public ConnectContext(SocketChannel channel) {
     public boolean isTxnModel() {
         return txnEntry != null && txnEntry.isTxnModel();
     }
+
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:188]: When can you not change the format of these non-modified lines ？？

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
