### PR TITLE
[fix][compaction] Rowset::end_version null pointer

### LINKED ISSUE #9371: [Bug] Compaction Rowset::end_version null pointer
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

image

#0  0x0000561edfab5b14 in std::__shared_ptr<doris::RowsetMeta, (__gnu_cxx::_Lock_policy)2>::get (this=0x88)
    at /var/local/ldb-toolchain/include/c++/11/bits/shared_ptr_base.h:1291
#1  0x0000561edfab15c2 in std::__shared_ptr_access<doris::RowsetMeta, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get (this=0x88)
    at /var/local/ldb-toolchain/include/c++/11/bits/shared_ptr_base.h:990
#2  0x0000561edfaadcd4 in std::__shared_ptr_access<doris::RowsetMeta, (__gnu_cxx::_Lock_policy)2, false, false>::operator-> (this=0x88)
    at /var/local/ldb-toolchain/include/c++/11/bits/shared_ptr_base.h:984
#3  0x0000561edfaab5a4 in doris::Rowset::end_version (this=0x0) at /root/doris-release/be/src/olap/rowset/rowset.h:142
#4  0x0000561edfbb66cb in doris::Compaction::do_compaction_impl (this=0x561f52eeabb0, permits=5) at /root/doris-release/be/src/olap/compaction.cpp:141
#5  0x0000561edfbb55e0 in doris::Compaction::do_compaction (this=0x561f52eeabb0, permits=5) at /root/doris-release/be/src/olap/compaction.cpp:56
#6  0x0000561edfbbe116 in doris::CumulativeCompaction::execute_compact_impl (this=0x561f52eeabb0) at /root/doris-release/be/src/olap/cumulative_compaction.cpp:75
#7  0x0000561edfbb5475 in doris::Compaction::execute_compact (this=0x561f52eeabb0) at /root/doris-release/be/src/olap/compaction.cpp:45
#8  0x0000561edfae5ed4 in doris::Tablet::execute_compaction (this=0x561f060c9410, compaction_type=doris::CUMULATIVE_COMPACTION)
    at /root/doris-release/be/src/olap/tablet.cpp:1406
#9  0x0000561edfa82381 in operator() (__closure=0x561f4892d9b0) at /root/doris-release/be/src/olap/olap_server.cpp:570
#10 0x0000561edfa85728 in std::__invoke_impl<void, doris::StorageEngine::_submit_compaction_task(doris::TabletSharedPtr, doris::CompactionType)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:61
#11 0x0000561edfa84aca in std::__invoke_r<void, doris::StorageEngine::_submit_compaction_task(doris::TabletSharedPtr, doris::CompactionType)::<lambda()>&>(struct {...} &) (
    __fn=...) at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:111
#12 0x0000561edfa840b3 in std::_Function_handler<void(), doris::StorageEngine::_submit_compaction_task(doris::TabletSharedPtr, doris::CompactionType)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:291
#13 0x0000561edfeb640c in std::function<void ()>::operator()() const (this=0x561f4e1a72d8) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:560
#14 0x0000561ee01aafe8 in doris::FunctionRunnable::run (this=0x561f4e1a72d0) at /root/doris-release/be/src/util/threadpool.cpp:45

### What You Expected?

win

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #9371

## Problem Summary:

After compaction, get tablet max version rowset returns null.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/compaction.cpp [hunk 1]
```diff
@@ -136,7 +136,12 @@ Status Compaction::do_compaction_impl(int64_t permits) {
     int64_t current_max_version;
     {
         std::shared_lock rdlock(_tablet->get_header_lock());
-        current_max_version = _tablet->rowset_with_max_version()->end_version();
```
Comment (yiguolei) [inline be/src/olap/compaction.cpp:139]: when will rowset_with_max_version == nullptr?

Comment (xinyiZzz) [reply be/src/olap/compaction.cpp:139]: This seems to happen in two cases:
1. The tablet has no rowset.
2. The version of max version rowset no longer exists in the tablet.

In fact, I did not carefully analyze why it occurs. Because other `tablet->rowset_with_max_version()` all compare whether the return value is null, so I also compare here :)

Comment (yiguolei) [reply be/src/olap/compaction.cpp:139]: 1. The tablet should not have rowset because when the table is created BE will add 0-1 rowset to the tablet.
2. I think we should be careful with this case... Maybe should deep dive some code.

Comment (xinyiZzz) [reply be/src/olap/compaction.cpp:139]: > 1. The tablet should not have rowset because when the table is created BE will add 0-1 rowset to the tablet.
> 2. I think we should be careful with this case... Maybe should deep dive some code.

I agree, these two cases are not normal, maybe the tablet was deleted during compaction, or invalid?

At present this is the previous solution, there may be a better way.

**Review by yiguolei — APPROVED** [review]
LGTM
