### PR TITLE
[Fix](Nerids) fix dup key for pull predicate from project children

### LINKED ISSUE #15310: [Fix](Nerids) fix dup key for pull predicate from project children #15292
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

for example：

```sql
select * from student join (select sid as id1, sid as id2, grade from score) s on student.id = s.id1 where s.id1 > 1
```
Exception :
org.apache.doris.common.NereidsException: Duplicate key (deptno#3 + 1) (attempted merging values deptno#6 and expr_deptno#11)

In `InferPredicates`, we need pull predicates from project children then use `sid` replace `id1`. 
In our code, use alias name as key, use expression as value to build map. Obviously, `sid` has two alias name(id1,id2) so throw  `Duplicate key` exception.

### What You Expected?

correct

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qzsee**
# Proposed changes

Issue Number: close #15310

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.73 seconds
 load time: 643 seconds
 storage size: 17122894768 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221222133433_clickbench_pr_67393.html

**Comment by morrySnow** [comment]
please add some commit msg to explain this bug and add UT or regression test

File: fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/logical/InferPredicatesTest.java [hunk 1]
```diff
@@ -533,4 +533,29 @@ public void inferPredicatesTest21() {
                     )
                 );
     }
+
+    /**
+     * test for #15310
+     */
+    @Test
+    public void inferPredicatesTest22() {
```
Comment (morrySnow) [inline fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/logical/InferPredicatesTest.java:541]: nit: change all cast name to meaningful name in next PR please~

**Review by morrySnow — APPROVED** [review]
