### PR TITLE
[Fix] Remove trailing spaces in broker_scanner. Make it consistent with hive and trino behavior.

### LINKED ISSUE #9257: [Bug] Doesn't trim the trailing spaces while querying hive external table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

When search hive external table, doris doesn't trim the trailing spaces, but hive does. This leads to different query result of doris and hive.
For example, we have a table with 2 columns:
id, varchar(10);
name, varchar(10);
And the data file in HDFS for hive is：
```
id1 |name1
id2 |name2
```
Notice that id1 and id2 are followed by a space.

In hive, we can get id1, name1 after running:
`select * from *** where id='id1',`
But get empty result set in doris. In doris, we need to run: ( a space after 'id1')
`select * from *** where id='id1 '`

### What You Expected?

Get the same query result with hive while querying Hive external table. 

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Jibing-Li**
[BUG][Hive External Table]Remove trailing spaces in broker_scanner. Make it consistent with hive and trino behavior.

# Proposed changes

Issue Number: close [#9257](https://github.com/apache/incubator-doris/issues/9257)

## Problem Summary:

Hive and trino/presto would automatically trim the trailing spaces but Doris doesn't. This would cause different query result with hive. 

Describe the overview of changes.
Trim trailing spaces in broker scanner.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (No Need) It has been tested manually.
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — CHANGES_REQUESTED** [review]
This may change the default behavior of loading data, if user data do have tailing space.

File: fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java [hunk 1]
```diff
@@ -442,6 +444,9 @@ public class SessionVariable implements Serializable, Writable {
     @VariableMgr.VarAttr(name = ENABLE_PROJECTION)
     private boolean enableProjection = false;
 
+    @VariableMgr.VarAttr(name = TRIM_TAILING_SPACES_FOR_EXTERNAL_TABLE_QUERY)
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java:447]:
```suggestion
    @VariableMgr.VarAttr(name = TRIM_TAILING_SPACES_FOR_EXTERNAL_TABLE_QUERY, needForward = true)
```

**Review by morningman — APPROVED** [review]
LGTM
