### PR TITLE
[Bug][Load][Json] #4124 Load json format with stream load failed

### LINKED ISSUE #4124: [Bug][Load][Json] Load json format with stream load failed
**Describe the bug**
if the json data is larger than 4096 bytes, the data will be truncated, making it impossible to obtain the json data completely

**To Reproduce**
Load a large json file with stream load

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Stream load should read all the data completely before parsing the json.
And also add a new BE config `streaming_load_max_batch_read_mb`
to limit the data size when loading json data.

Fix the bug of loading empty json array `[]`

Add doc to explain some certain case of loading json format data.

Fix: #4124

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have create an issue on #4124, and have described the bug/feature there in detail
- [x] Commit messages in my PR start with the related issues ID, like "#4071 Add pull request template to doris project"
- [x] Compiling and unit tests pass locally with my changes
- [x] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

File: be/src/common/config.h [hunk 1]
```diff
@@ -303,11 +303,14 @@ namespace config {
     CONF_Int64(load_data_reserve_hours, "4");
     // log error log will be removed after this time
     CONF_mInt64(load_error_log_reserve_hours, "48");
-    // Deprecated, use streaming_load_max_mb instead
-    // CONF_Int64(mini_load_max_mb, "2048");
     CONF_Int32(number_tablet_writer_threads, "16");
 
+    // The maximum amount of data that can be processed by a stream load
```
Comment (wuyunfeng) [inline be/src/common/config.h:308]: a stream load can process 10G by default?

File: be/src/http/action/stream_load.cpp [hunk 2]
```diff
@@ -234,11 +234,19 @@ Status StreamLoadAction::_on_header(HttpRequest* http_req, StreamLoadContext* ct
...
             std::stringstream ss;
             ss << "unknown data format, format=" << http_req->header(HTTP_FORMAT_KEY);
             return Status::InternalError(ss.str());
         }
+
+        size_t max_body_bytes = config::streaming_load_max_batch_size_mb * 1024 * 1024;
+        if (ctx->format == TFileFormatType::FORMAT_JSON) {
+            if (ctx->body_bytes > max_body_bytes) {
+                std::stringstream ss;
+                ss << "body exceed max size of json format: " << ctx->body_bytes << ", limit: " << max_body_bytes;
```
Comment (wuyunfeng) [inline be/src/http/action/stream_load.cpp:246]: the size of this batch exceed the max size of json type data
```suggestion
                ss << "the size of this batch exceed the max size [" << max_body_bytes << "]  of json type data " << " data [ " << ctx->body_bytes << " ] "
```
And I suggest you should truncate the logged `body_bytes` such as just show 1024 byte

File: be/src/common/config.h (hunk 1 above)
Comment (morningman) [reply be/src/common/config.h:308]: Actually, this default value is too big for a stream load.
But I am not going to modify this to avoid some user troubles.

File: be/src/http/action/stream_load.cpp (hunk 2 above)
Comment (morningman) [reply be/src/http/action/stream_load.cpp:246]: OK

**Review by yangzhg — APPROVED** [review]
LGTM
