### PR TITLE
[fix](Nereids) Fix ClassCastException when HAVING clause contains subquery

### LINKED ISSUE #58937: [Bug] [Nereids] NullLiteral cast to Slot error in HAVING subquery
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-4.0.1-rc02-791725594d

### What's Wrong?

When I run sql using Having clause with subquery filter, it will throw exception:

SQL Error [1105] [HY000]: errCode = 2, detailMessage = class org.apache.doris.nereids.trees.expressions.literal.NullLiteral cannot be cast to class org.apache.doris.nereids.trees.expressions.Slot (org.apache.doris.nereids.trees.expressions.literal.NullLiteral and org.apache.doris.nereids.trees.expressions.Slot are in unnamed module of loader 'app')

### What You Expected?

This should ran success as 3.x

### How to Reproduce?

1. create test table
`create table test (period varchar(10))`

2. insert data
`insert into test values('202501')`
 
3. run query
`select period from test group by period HAVING COUNT(DISTINCT period) = (SELECT COUNT(DISTINCT period) FROM test WHERE period IN ('202501') )`

4. got error: 

SQL Error [1105] [HY000]: errCode = 2, detailMessage = class org.apache.doris.nereids.trees.expressions.literal.NullLiteral cannot be cast to class org.apache.doris.nereids.trees.expressions.Slot (org.apache.doris.nereids.trees.expressions.literal.NullLiteral and org.apache.doris.nereids.trees.expressions.Slot are in unnamed module of loader 'app')

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by felixwluo**
### What problem does this PR solve?

usercase
Issue Number: close #58937

Come from this PR: https://github.com/apache/doris/pull/46401

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by felixwluo** [comment]
run buildall

**Review by cambyzju — DISMISSED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java [hunk 1]
```diff
@@ -425,6 +425,7 @@ public void computeUnique(DataTrait.Builder builder) {
         }
         DataTrait childFd = child(0).getLogicalProperties().getTrait();
         ImmutableSet<Slot> groupByKeys = groupByExpressions.stream()
+                .filter(s -> s instanceof Slot)
```
Comment (yujun777) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java]: think about group by  a + random(),     a + b,    100 + 1000,  null

Comment (yujun777) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java]: 1) if any group by expression containsUniqueFunctions，  not unique;
2) otherwise extract all the slots from the group by expressions into a set,  for each group by key,  groupByKeys.addAll(key.getInputSlots()), check then

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java [hunk 2]
```diff
@@ -460,6 +461,7 @@ public void computeUniform(DataTrait.Builder builder) {
             return;
         }
         ImmutableSet<Slot> groupByKeys = groupByExpressions.stream()
+                .filter(s -> s instanceof Slot)
```
Comment (yujun777) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java]: need consider  the above example

**Comment by felixwluo** [comment]
run buildall

**Comment by hello-stephen** [comment]
# FE Regression Coverage Report
Increment line coverage `  71.43% (20/28)` :tada:
[Increment coverage report](http://coverage.selectdb-in.cc/coverage/58978_34e6de950016af63aa2dc64adecd3f865664fa71_merge_fe/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/58978_34e6de950016af63aa2dc64adecd3f865664fa71_merge_fe/report/index.html)

**Comment by hello-stephen** [comment]
# FE Regression Coverage Report
Increment line coverage `  71.43% (20/28)` :tada:
[Increment coverage report](http://coverage.selectdb-in.cc/coverage/58978_8f63e72fb969e848db1b9cc7712e0e66b30ffaa6_merge_fe/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/58978_8f63e72fb969e848db1b9cc7712e0e66b30ffaa6_merge_fe/report/index.html)

**Comment by hello-stephen** [comment]
# FE Regression Coverage Report
Increment line coverage `  71.43% (20/28)` :tada:
[Increment coverage report](http://coverage.selectdb-in.cc/coverage/58978_8f63e72fb969e848db1b9cc7712e0e66b30ffaa6_merge_fe/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/58978_8f63e72fb969e848db1b9cc7712e0e66b30ffaa6_merge_fe/report/index.html)

**Comment by felixwluo** [comment]
run p0

**Comment by felixwluo** [comment]
run buildall

**Comment by hello-stephen** [comment]
# FE Regression Coverage Report
Increment line coverage `  71.43% (20/28)` :tada:
[Increment coverage report](http://coverage.selectdb-in.cc/coverage/58978_138e793695dac7fb6cc80c0356d32545754e1108_merge_fe/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/58978_138e793695dac7fb6cc80c0356d32545754e1108_merge_fe/report/index.html)

**Comment by felixwluo** [comment]
run external

**Review by feiniaofeiafei — APPROVED** [review]

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Comment by hello-stephen** [comment]
# FE UT Coverage Report
Increment line coverage `  71.43% (20/28)` :tada:
[Increment coverage report](http://coverage.selectdb-in.cc/coverage/58978_138e793695dac7fb6cc80c0356d32545754e1108/fe_increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/58978_138e793695dac7fb6cc80c0356d32545754e1108/fe_report/index.html)

**Comment by hello-stephen** [comment]
# FE Regression Coverage Report
Increment line coverage `  71.43% (20/28)` :tada:
[Increment coverage report](http://coverage.selectdb-in.cc/coverage/58978_138e793695dac7fb6cc80c0356d32545754e1108_merge_fe/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/58978_138e793695dac7fb6cc80c0356d32545754e1108_merge_fe/report/index.html)
