### PR TITLE
[fix](tracing) fix tracing in the new scan node does not meet expectations

### LINKED ISSUE #14149: [Bug] Tracing in the scan node does not meet expectations
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2

### What's Wrong?

When I execute a sql, a lot of spans named `scanner::scan` and `vscannode::get_next` are generated, and one of them `scanner::scan` does not join the expected tracing but generates a separate tracing.
```
select c.id, c.name, p.age, p.phone, c.date, c.cost from cost c join people p on c.id = p.id where p.age > 20 order by c.id limit 10;
```
截屏2022-11-10 12 14 04
截屏2022-11-10 12 15 17

### What You Expected?

as expected

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #14149

- Remove unexpected tracing, like 'vscanner::scan'
- Merge span vscnnode::get_next

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.29 seconds
 load time: 477 seconds
 storage size: 17178792631 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221110085639_clickbench_pr_43308.html

File: be/src/vec/exec/scan/vscan_node.cpp [hunk 1]
```diff
@@ -85,7 +84,7 @@ Status VScanNode::prepare(RuntimeState* state) {
 Status VScanNode::open(RuntimeState* state) {
     _input_tuple_desc = state->desc_tbl().get_tuple_descriptor(_input_tuple_id);
     _output_tuple_desc = state->desc_tbl().get_tuple_descriptor(_output_tuple_id);
-    START_AND_SCOPE_SPAN_IF(state->enable_profile(), state->get_tracer(), "VScanNode::open");
+    START_AND_SCOPE_SPAN(state->get_tracer(), span, "VScanNode::open");
```
Comment (morningman) [inline be/src/vec/exec/scan/vscan_node.cpp:87]: Why not using `START_AND_SCOPE_SPAN_IF`?

**Review by morningman — APPROVED** [review]
LGTM
