### PR TITLE
[BUG] fix information_schema.columns results not correctly on vec engine

### LINKED ISSUE #9597: [Bug] Some query results from information_schema.columns are incorrect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev 1.0.1

### What's Wrong?

MySQL [testdb]> show databases;
+--------------------+
| Database           |
+--------------------+
| abc                |
| testdb           |
...

MySQL [testdb]> select table_schema,table_name from information_schema.columns where table_schema='abc';
Empty set (0.05 sec)

### What You Expected?

The result of following query is not empty.
select table_schema,table_name from information_schema.columns where table_schema='abc'; 

### How to Reproduce?

Still have not...

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
# Proposed changes

Issue Number: close #9597

## Problem Summary:
There are two bugs in function VSchemaScanNode::get_next:
1. first loop we clean columns by columns.clear(), next loop columns.empty() is true, then filter_block will not be called and makes the results wrong.
2. if all rows filtered by filter_block, `block->columns() > 0 and block->rows() == 0`, next loop we should not call `block->insert` again, we should reuse the column.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
3. Has unit tests been added: (Yes/No/No Need)
4. Has document been added or modified: (Yes/No/No Need)
5. Does it need to update dependencies: (Yes/No)
6. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/exec/vschema_scan_node.cpp [hunk 1]
```diff
@@ -69,12 +69,14 @@ Status VSchemaScanNode::get_next(RuntimeState* state, vectorized::Block* block,
     if (!_is_init) return Status::InternalError("used before initialize.");
     RETURN_IF_ERROR(exec_debug_action(TExecNodePhase::GETNEXT));
     RETURN_IF_CANCELLED(state);
-    bool mem_reuse = block->mem_reuse();
-    DCHECK(block->rows() == 0);
     std::vector<vectorized::MutableColumnPtr> columns(_slot_num);
     bool schema_eos = false;
 
     do {
+        bool mem_reuse = block->mem_reuse();
```
Comment (morningman) [inline be/src/vec/exec/vschema_scan_node.cpp:76]: For  mysql and odbc scan node, why we don't need to move this line in the loop?

**Review by morningman — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM
