### PR TITLE
[BUG] Using attachement strategy of brpc to send packet with big size.

### LINKED ISSUE #4238: Big packet will send failed on BRPC
```
W0731 21:36:10.921273  3404 data_stream_sender.cpp:141] failed to send brpc batch, error=Host is down, error_text=[E110]Fail to connect Socket{id=256 addr=172.26.92.139:8760} (0x0x7cd4000): Connection timed out [R1][E112]Not connec
ted to 172.26.92.139:8760 yet, server_id=256 [R2][E112]Not connected to 172.26.92.139:8760 yet, server_id=256 [R3][E112]Not connected to 172.26.92.139:8760 yet, server_id=256
W0731 21:36:10.921330  3404 data_stream_sender.cpp:141] failed to send brpc batch, error=Host is down, error_text=[E110]Fail to connect Socket{id=256 addr=172.26.92.139:8760} (0x0x7cd4000): Connection timed out [R1][E112]Not connec
ted to 172.26.92.139:8760 yet, server_id=256 [R2][E112]Not connected to 172.26.92.139:8760 yet, server_id=256 [R3][E112]Not connected to 172.26.92.139:8760 yet, server_id=256
I0731 21:36:11.014581  3512 socket.cpp:2260] Checking Socket{id=256 addr=172.26.92.139:8760} (0x7cd4000)
I0731 21:36:11.015164  3555 socket.cpp:2322] Revived Socket{id=256 addr=172.26.92.139:8760} (0x7cd4000)
```

### PR DESCRIPTION
**Pull request by chaoyli**
BRPC send packet should serialize it first and then send it.
If we send one batch with big size, it will encounter a connection failed.
So we can use attachment strategy to bypass the problem and eliminate
the serialization cost.

### CODE REVIEW

File: be/src/common/config.h [hunk 1]
```diff
@@ -519,6 +519,8 @@ namespace config {
     CONF_Int64(brpc_max_body_size, "209715200");
     // Max unwritten bytes in each socket, if the limit is reached, Socket.Write fails with EOVERCROWDED
     CONF_Int64(brpc_socket_max_unwritten_bytes, "67108864");
+    // If batch size large than brpc_attachment_threashold, use attachment instead
```
Comment (imay) [inline be/src/common/config.h:522]:
```suggestion
    // If batch size is larger than brpc_attachment_threshold, use attachment instead
```
I have a question, why not use threshold directly for all the packets?

File: be/src/runtime/data_stream_sender.cpp [hunk 2]
```diff
@@ -270,12 +277,7 @@ Status DataStreamSender::Channel::add_row(TupleRow* row) {
 }
 
 Status DataStreamSender::Channel::send_current_batch(bool eos) {
-    {
-        SCOPED_TIMER(_parent->_serialize_batch_timer);
-        int uncompressed_bytes = _batch->serialize(&_pb_batch);
-        COUNTER_UPDATE(_parent->_bytes_sent_counter, RowBatch::get_batch_size(_pb_batch));
-        COUNTER_UPDATE(_parent->_uncompressed_bytes_counter, uncompressed_bytes);
-    }
+    _parent->serialize_batch(_batch.get(), &_pb_batch, 1);
```
Comment (imay) [inline be/src/runtime/data_stream_sender.cpp:280]: why delete origin timer and counter?

File: be/src/runtime/data_stream_sender.cpp [hunk 3]
```diff
@@ -227,7 +227,14 @@ Status DataStreamSender::Channel::send_batch(PRowBatch* batch, bool eos) {
     }
 
     _brpc_request.set_eos(eos);
-    if (batch != nullptr) {
+    if (batch != nullptr && RowBatch::get_batch_size(*batch) > config::brpc_socket_max_unwritten_bytes) {
+        std::string* tuple_data_to_attachment = batch->release_tuple_data();
```
Comment (imay) [inline be/src/runtime/data_stream_sender.cpp:231]: Will this variable will cause memory leak?

**Review by imay — CHANGES_REQUESTED** [review]

**Review by imay — APPROVED** [review]
LGTM
