### PR TITLE
[Bug][RoutineLoad] Avoid TOO_MANY_TASKS error

### LINKED ISSUE #6340: [Bug][RoutineLoad] TOO_MANY_TASKS error
**Describe the bug**

Routine load job will meet TOO_MANY_TASKS errors occasionally.
And I found it is because after the transaction being committed, the task will call `kafka->commit()` to commit the offset.
But it is a blocking method, so that is kafka server has some problem, it may block for a long time.
But the task is considered as FINISHED on FE after the  transaction being committed, but the task actually not finished due 
to the blocking `commit` method.

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Use `commitAsync` to commit offset to kafka, instread of using `commitSync`, which may block for a long time.
Also assign a group.id to routine load if user not specified "property.group.id" property, so that all consumer of
this job will use same group.id instead of a random id for each consume task.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #6340) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
#6306 will cause BE crash in DEBUG mode, remove this service will fix that bug.

**Comment by EmmyMiao87** [comment]
Please add a issue link

File: fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java [hunk 1]
```diff
@@ -344,30 +345,54 @@ public long getMinTaskBeId(String clusterName) throws LoadException {
...
             }
-            if (idleTaskNum > 0) {
-                return true;
+
+            // 2. The given BE id does not have available slots, find a BE with min tasks
+            updateBeIdToMaxConcurrentTasks();
+            int idleTaskNum = 0;
+            long resultBeId = -1L;
+            int maxIdleSlotNum = 0;
+            for (Long beId : beIdsInCluster) {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java:380]: This logic is consistent with manager's getMinTaskBeId function logic

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java:380]: i merged the 2 methods to avoid call getBeCurrentTasksNumMap twice

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
