### PR TITLE
[fix][refactor](broker load) refactor the scheduling logic of broker load

### LINKED ISSUE #7367: [Enhancement] Refactor the logic of broker load scheduler
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

## What is wrong?

The current Broker Load execution is divided into two stages, `pending` and `loading`.
The pending phase is responsible for obtaining file information, and the loading phase is responsible for executing the load.

These two stages are run by two thread pools. The current submission logic may cause the actual execution time of the task to be inconsistent with the user's perception.

For example, the user submits a broker load and check its status as `LOADING`. But in fact, the job may not start execution, but wait for scheduling.

## Solution

The new design scheme is as follows:

The `desired_max_waiting_jobs` parameter is used to control the number of broker load jobs running in the cluster.
When the number of jobs exceeds this threshold, reject the new job directly.

The newly submitted job is in the `PENDING` state. Only after the pending task is successfully submitted to the pending task thread pool will the job actually start (for example, to do "begin txn").
If the submission is not successful, continue to wait.

The queue of the loading task thread pool is infinite, that is, the loading task thread pool will unconditionally accept loading tasks generated after the pending task ends.
Because the number of jobs running in the cluster has been controlled by the pending task thread pool.

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. Refactor the scheduling logic of broker load. Details see #7367 
2. Fix bug that loadedBytes in SHOW LOAD result is wrong.
3. Cancel the thread of LoadTimeoutChecker
   Now for PENDING load jobs, there will be no timeout. And the timeout of a load job
   start when pending load task is scheduled.
4. Fix a bug that the loading task is never submitted to the pool.
   The logic of BlockedPolicy is wrong. We should make sure the task is submitted to the pool,
   or the RejectedExecutionException should be thrown.
5. Now the transaction of a load job will begin in pending task, instead of when submitting the job.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #7367) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 1]
```diff
@@ -582,14 +580,19 @@ private Catalog(boolean isCheckpointCatalog) {
         this.tabletScheduler = new TabletScheduler(this, systemInfo, tabletInvertedIndex, stat, Config.tablet_rebalancer_type);
         this.tabletChecker = new TabletChecker(this, systemInfo, tabletScheduler, stat);
 
+        // The pendingLoadTaskScheduler's queue size should not less than Config.desired_max_waiting_jobs.
+        // So that we can guarantee that all submitted load jobs can be scheduled without being starved.
         this.pendingLoadTaskScheduler = new MasterTaskExecutor("pending_load_task_scheduler", Config.async_pending_load_task_pool_size,
-                Config.async_pending_load_task_pool_size, !isCheckpointCatalog);
+                Config.desired_max_waiting_jobs, !isCheckpointCatalog);
+        // The loadingLoadTaskScheduler's queue size is unlimited, so that it can receive all loading tasks
+        // created after pending tasks finish. And don't worry about the high concurrency, because the
```
Comment (caiconghui) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:588]: pending task cost less time than loading task. so my idea is that if load task thread pool is full, not submit task of not started job, for that once start job and still no resource to execute loading task, the job will wait to be timeout, not because of slow running but absent of thread resource.

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:588]: OK. I changed. Now when submit a broker load job to the thread pool, I will check if there are available worker thread in `loading_load_task_pool`

File: docs/zh-CN/administrator-guide/load-data/broker-load-manual.md [hunk 2]
```diff
@@ -469,6 +469,18 @@ LoadFinishTime: 2019-07-27 11:50:16
         注意：一般用户的环境可能达不到 10M/s 的速度，所以建议超过 500G 的文件都进行文件切分，再导入。
         
         ```
+        
+### 作业调度
+
+系统会限制一个集群内，正在运行的 Broker Load 作业数量，以防止同时运行过多的 Load 作业。
+
+首先， FE 的配置参数：`desired_max_waiting_jobs` 会限制一个集群内，正在运行（作业状态为 PENDING 或 LOADING）的 Broker Load 作业数量。默认为 100。如果超过这个阈值，新提交的作业将会被直接拒绝。
```
Comment (caiconghui) [inline docs/zh-CN/administrator-guide/load-data/broker-load-manual.md:477]:
```suggestion
首先， FE 的配置参数：`desired_max_waiting_jobs` 会限制一个集群内，未开始和正在运行（作业状态为 PENDING 或 LOADING）的 Broker Load 作业数量。默认为 100。如果超过这个阈值，新提交的作业将会被直接拒绝。
```

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 3]
```diff
@@ -582,14 +580,19 @@ private Catalog(boolean isCheckpointCatalog) {
...
+        // concurrency is limited by Config.desired_max_waiting_jobs and Config.async_loading_load_task_pool_size.
         this.loadingLoadTaskScheduler = new MasterTaskExecutor("loading_load_task_scheduler", Config.async_loading_load_task_pool_size,
-                Config.async_loading_load_task_pool_size / 5, !isCheckpointCatalog);
+                Integer.MAX_VALUE, !isCheckpointCatalog);
+
         this.loadJobScheduler = new LoadJobScheduler();
         this.loadManager = new LoadManager(loadJobScheduler);
         this.streamLoadRecordMgr = new StreamLoadRecordMgr("stream_load_record_manager", Config.fetch_stream_load_record_interval_second * 1000);
-        this.loadTimeoutChecker = new LoadTimeoutChecker(loadManager);
```
Comment (caiconghui) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:592]: why remove this checker?

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:592]: This checker is no logger needed. Because now the timeout is only calculated when the task is actually executed.
So for now, if a job is in pending state, it will never be cleared.

And the length limit of the pending queue will ensure that there will not be too many pending jobs

File: docs/zh-CN/administrator-guide/load-data/broker-load-manual.md (hunk 2 above)
Comment (morningman) [reply docs/zh-CN/administrator-guide/load-data/broker-load-manual.md]: done

**Review by caiconghui — APPROVED** [review]
LGTM
