### PR TITLE
[BUG] Fixed the materialized number of resultExprs/constExprs and output slot of Union Node is inconsistent.

### LINKED ISSUE #6327: [Bug] BE crash when query union and join
**Describe the bug**
```
SELECT a.x FROM
(SELECT '01' x UNION all SELECT '02') a
INNER JOIN
(SELECT '01' x UNION all SELECT '02') b
```

BE crash:

```
*** Aborted at 1627349345 (unix time) try "date -d @1627349345" if you are using GNU date ***
PC: @          0x1566534 doris::Tuple::materialize_exprs<>()
*** SIGSEGV (@0x0) received by PID 73779 (TID 0x7f3007765700) from PID 0; stack trace: ***
    @          0x20c7d52 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f306926d1d0 (unknown)
    @          0x1566534 doris::Tuple::materialize_exprs<>()
    @          0x1a9818b doris::UnionNode::materialize_exprs()
    @          0x1a9622c doris::UnionNode::get_next_const()
    @          0x1a96bc2 doris::UnionNode::get_next()
    @          0x1559293 doris::PlanFragmentExecutor::get_next_internal()
    @          0x15599e9 doris::PlanFragmentExecutor::open_internal()
    @          0x155e1cf doris::PlanFragmentExecutor::open()
    @          0x14d3e1e doris::FragmentExecState::execute()
    @          0x14d7486 doris::FragmentMgr::_exec_actual()
    @          0x14dec9b std::_Function_handler<>::_M_invoke()
    @          0x1649866 doris::ThreadPool::dispatch_thread()
    @          0x1643ca4 doris::Thread::supervise_thread()
    @     0x7f3069262f84 start_thread
    @     0x7f3069052ddf __GI___clone
```

**Version**
trunk

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes
fix #6327
#### First case
```
SELECT a.x FROM
(SELECT '01' x) a 
INNER JOIN
(SELECT '01' x UNION all SELECT '02') b
```
The length of the tnode.union_node.const_expr_lists obtained by BE UnionNode is not equal to the length of the materialized slots of the tuple.
In UnionNode::prepare, DCHECK_EQ(exprs.size(), _tuple_desc->slots().size()); will prompt.

#### Second case
```
SELECT a.x 
FROM (SELECT '01' x) a 
INNER JOIN 
(SELECT C_CUSTKEY from CUSTOMER 
UNION all 
SELECT C_CUSTKEY from CUSTOMER) b;
```
materializedResultExprs is empty when new DataPartition() in new setOperationFragment().

### The reason for materialized number of resultExprs/constExprs and output slot of Union Node is inconsistent:
The reason is that select stmt and on-clause does not contain the slot of the union node on the build side of Join, so no slot in the union node tuple is materialized during sql parse.

After the union node on the join build side is created, when calling SetOperationNode::init(), it will decide which resultExprs/constExprs to put into the materializedResultExprs/materializedConstExprs according to the materialized slot, because no slot is materialized in the union node tuple, So materializedResultExprs/materializedConstExprs is empty.

After the join node itself is created, the materializeTableResultForCrossJoinOrCountStar() method is called to ensure that at least one slot of the join build side node tuple is materialized, so the slot corresponding to `x` in the union node tuple is materialized.

Under normal circumstances, will call SetOperationNode::init() again at the end of createSetOperationNodeFragment() to update materializedResultExprs/materializedConstExprs. to ensure that eventually the resultExprs/constExprs and the corresponding output slot have the same materialized state.

In the first case, because the slot of the union node only has constants, `setOperationNode.getChildren().isEmpty()=true`, will not call SetOperationNode::init() again at the end of createSetOperationNodeFragment(), resulting in the number of materialized slots being different from the number of materializedConstExprs.

In the second case, new setOperationFragment() before calling SetOperationNode::init() again

### Solution
Moved computePassthrough() and the materialized position of resultExprs/constExprs from this.init to this.finalize, and will not call SetOperationNode::init() again at the end of createSetOperationNodeFragment().

#### Reasons for move computePassthrough():
Because the byteSize of the tuple corresponding to OlapScanNode is updated after singleNodePlanner.createSingleNodePlan() and before singleNodePlan.finalize(), calling computePassthrough() in SetOperationNode::init() may not be able to accurately determine whether the child is pass through. In the previous logic , Will call SetOperationNode::init() again at the end of createSetOperationNodeFragment().

#### Reasons for move materialized position of resultExprs/constExprs:
Because the output slot is materialized at various positions in the planner stage, this is to ensure that eventually the resultExprs/constExprs and the corresponding output slot have the same materialized state.
And the order of materialized resultExprs must be the same as the order of children adjusted by computePassthrough(), so resultExprs materialized must be placed after computePassthrough().

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6327) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java [hunk 1]
```diff
@@ -1838,6 +1837,11 @@ public PlanNode createJoinNode(Analyzer analyzer, PlanNode outer, PlanNode inner
      */
     private PlanNode createJoinNode(Analyzer analyzer, PlanNode outer, TableRef innerRef,
                                     SelectStmt selectStmt) throws UserException {
+	// Before creating a build node, ensure that all required slots are materialized,
+        // even if slots that are not needed by Statement outside.
+        // Otherwise, when select stmt and on-clause does not contain the Slot of the Union Node on the right side of Join,
+        // it will cause an error, see Doris-6380.
+	materializeTableResultForCrossJoinOrCountStar(innerRef, analyzer);
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:1844]: Changing the order is not a good way

Comment (xinyiZzz) [reply fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java]: I understand to ensure that resultExprs/constExprs and the corresponding output slot are materialized in the same state.
The output slot is materialized at various positions in the planner stage.
So I moved the materialized position of resultExprs/constExprs from this.init to this.finalize.

File: fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java [hunk 2]
```diff
@@ -125,6 +126,62 @@ public void addChild(PlanNode node, List<Expr> resultExprs) {
...
+            Preconditions.checkState(exprList.size() == slots.size());
+            List<Expr> newExprList = Lists.newArrayList();
+            for (int i = 0; i < exprList.size(); ++i) {
+                if (slots.get(i).isMaterialized()) {
+                    newExprList.add(exprList.get(i));
+                }
+            }
+            materializedConstExprLists_.add(newExprList);
+        }
+        super.finalize(analyzer);
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java:182]: The super function is generally placed on the first line

File: fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java [hunk 3]
```diff
@@ -125,6 +126,62 @@ public void addChild(PlanNode node, List<Expr> resultExprs) {
         return materializedConstExprLists_;
     }
 
+    @Override
+    public void finalize(Analyzer analyzer) throws UserException {
+        // In Doris-6380, moved computePassthrough() and the materialized position of resultExprs/constExprs from this.init()
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java:131]: please add some unit test

File: fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java (hunk 2 above)
Comment (xinyiZzz) [reply fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java:182]: OK

File: fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java (hunk 3 above)
Comment (xinyiZzz) [reply fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java:131]: wait wait

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
The unit test failed

**Review by morningman — APPROVED** [review]
LGTM
