### PR TITLE
[Vectorized][Bug] This pr main fix the bug:

### LINKED ISSUE #7869: [Vectorized][Bug] Mem Leak in agg/unique table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

vectorized

### What's Wrong?

mem leak

### What You Expected?

not mem leak

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #7869 #7870 #7872

## Problem Summary:

1. mem leak in vcollect iter
2. query slow in agg table limit 10
3. query slow in ssb q4,q5,q6

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (Yes)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/columns/column_string.cpp [hunk 1]
```diff
@@ -292,6 +292,7 @@ ColumnPtr ColumnString::replicate(const Offsets& replicate_offsets) const {
 
 void ColumnString::reserve(size_t n) {
     offsets.reserve(n);
+    chars.reserve(n * 5);
```
Comment (morningman) [inline be/src/vec/columns/column_string.cpp:295]: why multi 5? add comment to explain, or define it as a variable.

Comment (HappenLee) [reply be/src/vec/columns/column_string.cpp:295]: This is a mistake. In fact, it is `n`

**Review by morningman — APPROVED** [review]
LGTM
