### PR TITLE
[bugfix](jdbc catalog) refresh catalog close jdbcclient

### LINKED ISSUE #27263: [Bug] Catalog connections not released
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.2-rc05-ae923f7

### What's Wrong?

CREATE CATALOG `adb_mysql` PROPERTIES (
"user" = "xxx",
"type" = "jdbc",
"password" = "XXX",
"jdbc_url" = "jdbc:mysql://xxx.ads.aliyuncs.com:3306?socketTimeout=600000",
"driver_url" = "file:///opt/lib/mysql-connector-java-5.1.49.jar",
"driver_class" = "com.mysql.jdbc.Driver"
);

Doris catalog connects to adb, and after running for a period of time, the number of connections increases to over 200.
(Call the adb API to obtain data on the number of connections)

 jmap -histo:live 3893933 > 1.jmap
[1.jmap.zip](https://github.com/apache/doris/files/13406097/1.jmap.zip)

### What You Expected?

Normal number of connections

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #27263

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run p0

**Comment by liugddx** [comment]
run feut:

**Comment by liugddx** [comment]
run feut

**Comment by liugddx** [comment]
run feut

File: fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java [hunk 1]
```diff
@@ -291,6 +291,7 @@ public void setUninitialized(boolean invalidCache) {
         this.objectCreated = false;
         this.initialized = false;
         this.invalidCacheInInit = invalidCache;
+        onClose();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java:294]: This should be called only when Catalog is dropped.
For refresh, we need another method

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run p0

**Comment by liugddx** [comment]
run pipelinex_p0

**Comment by liugddx** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java [hunk 2]
```diff
@@ -67,6 +67,12 @@ public void checkProperties() throws DdlException {
         }
     }
 
+    @Override
+    public void onRefresh(boolean invalidCache) {
+        super.onRefresh(invalidCache);
+        onClose();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java:73]: Should not call `onClose()`, it will remove the accessController

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by liugddx** [comment]
run pipelinex_p0

**Comment by liugddx** [comment]
run p0

**Review by zy-kkk — APPROVED** [review]
