### PR TITLE
[fix](load) fix bug that NodeChannel can not be destroyed ontime

### LINKED ISSUE #8704: [Bug] routine load return too many task error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

This bug may cause sevaral errors:
1.  lots of `FragmentMgr cancel worker going to cancel timeout fragment` in be.INFO
2. Routine load return TOO_MANY_TASKS error
3. pstack shows lots of thread blocked in `doris::stream_load::NodeChannel::~NodeChannel`

### What You Expected?

The above error should not happen

### How to Reproduce?

occasionally

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #8704 

## Problem Summary:

After the ReusableClosure is reset, we can not call join() method, or it will blocked forever.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/tablet_sink.cpp [hunk 1]
```diff
@@ -504,7 +504,6 @@ void NodeChannel::try_send_batch(RuntimeState* state) {
         }
     }
 
-    _add_batch_closure->reset();
```
Comment (morningman) [inline be/src/exec/tablet_sink.cpp:507]: For reviewer:
if call reset() here, the cancel() may be called after it.

**Review by yangzhg — APPROVED** [review]
LGTM
