### PR TITLE
[Bug] Fix that the partitions of a dynamic-partitioned table has not been created at the time of load or insert

### LINKED ISSUE #4657: [Bug] The load will stuck in Loading phase when the table is a dynamic-partitioned-table
**Describe the bug**
The load will stuck in Loading phase when the table is a new created dynamic-partitioned-table

**To Reproduce**
1. create a dynamic-partitioned-table
```
CREATE TABLE `test3` (
  `k1` int(11) NULL COMMENT "",
  `k2` date NULL COMMENT "",
  `k3` int(11) SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
()
DISTRIBUTED BY HASH(`k1`) BUCKETS 10
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "3",
"dynamic_partition.buckets" = "5",
);
```
2. start to load data into test3

```
insert into test3 values (20200924,'2019-10-10',100);
```

or

```
load label test_db.label3 
( 
data infile ("hdfs://host:port/path/to/data/table3") into table test3 
COLUMNS TERMINATED BY "|" 
(k1, k2, k3) 
) with broker "doris";
```

3. An error will report in insert statement and the load will stuck in loading phase.

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Fix #4657 

when a dynamic partitioned table is created, it will take some time to create the partitions. A exception needs to be thrown when users try to load data into this table, otherwise the load will stuck in loading phase all the time.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinghuayu007** [comment]
this bug has been fixed at PR: https://github.com/apache/incubator-doris/pull/4621

File: fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java [hunk 1]
```diff
@@ -182,6 +182,13 @@ public String getTimezone() {
             }
         }
 
+        // If this is a dynamic partitioned table, it will take some time to create the partition after the
+        // table is created, a exception needs to be thrown here
+        if (partitionIds.isEmpty()) {
+            throw new LoadException("data cannot be inserted into table with emtpy partition. " +
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java:188]: It is best to guide users in the prompt to wait for a while because of dynamic partitioning

**Review by morningman — DISMISSED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java (hunk 1 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java:188]: I agree. I think we can change the error msg like:
```
data cannot be inserted into table with emtpy partition... Use `SHOW PARTITIONS FROM tbl` to see the currenty partitions of this table. 
```

And also change the msg in error code `ERR_EMPTY_PARTITION_IN_TABLE`

Comment (xy720) [reply fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java]: ok. I will change the error msg.

**Review by morningman — APPROVED** [review]
LGTM
