### PR TITLE
[bugfix]json_length() BE crash fix

### LINKED ISSUE #32124: [Bug] json_length() function causes BE crash
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.5-rc01-204fde9 & master & 2.1

### What's Wrong?

when execute built in function
`select json_length('abc','$.k1')`
BE crashed
图片

I understand this parameter is not right, but this causes BE crashed, which is not robust.

### What You Expected?

BE NOT crash but throws exception

### How to Reproduce?

just execute
`select json_length('abc','$.k1')`
图片

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rohitrs1983**
## Proposed changes

Issue Number: close #32124 

MySQL [(none)]> select json_length('abc','$.k1');
+------------------------------------------+
| json_length('abc', '$.k1') |
+------------------------------------------+
|                                     NULL |
+------------------------------------------+
1 row in set (0.109 sec)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/functions/function_jsonb.cpp [hunk 1]
```diff
@@ -1097,10 +1097,15 @@ struct JsonbLengthUtil {
                 }
             }
             auto jsonb_value = jsonb_data_column->get_data_at(i);
+            if (UNLIKELY(jsonb_value.size == 0)) {
+                null_map->get_data()[i] = 1;
+                res->insert_data(nullptr, 0);
+                continue;
```
Comment (yiguolei) [inline be/src/vec/functions/function_jsonb.cpp:1103]: please add the test case in the issue to regression test

Comment (rohitrs1983) [reply be/src/vec/functions/function_jsonb.cpp]: updated. added regression test case.

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by cambyzju** [comment]
@rohitrs1983 could you also fix this problem on branch-2.0 ?

**Comment by xiaokang** [comment]
@rohitrs1983 I've picked it to branch-2.0 as #32484
