### PR TITLE
[fix] group by with two NULL rows after left join

### LINKED ISSUE #9544: [Bug] After left join,  there are two rows of the same key after group by
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0-rc03

### What's Wrong?

image

### What You Expected?

result one row

### How to Reproduce?

```sql
CREATE TABLE `left_table`
(
    `id`        text NULL COMMENT "",
    `device_id` text NULL COMMENT ""
) ENGINE = OLAP UNIQUE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES (
"replication_allocation" = "tag.location.default: 2",
"in_memory" = "false",
"storage_format" = "V2"
);

insert into left_table values ('1', '1'),('2', '2'), ('3', '3'), ('4', '4');

CREATE TABLE `right_table`
(
    `device_id`   text NULL COMMENT "",
    `device_name` text NULL COMMENT ""
) ENGINE = OLAP UNIQUE KEY(`device_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`device_id`) BUCKETS 4
PROPERTIES (
"replication_allocation" = "tag.location.default: 2",
"in_memory" = "false",
"storage_format" = "V2"
);

insert into right_table values ('1', 'device_name1'), ('3', null);

select count(left_table.device_id), rt.device_name
from left_table
         left join right_table rt
                   on left_table.device_id = rt.device_id
where rt.device_name is null
group by rt.device_name
order by rt.device_name nulls first
```

### Anything Else?

merge #8822 code

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
# Proposed changes

Issue Number: close #9544

## Problem Summary:

Describe the overview of changes.

The reason in the issue is:
In vec engine, if value is appended by left join, null value equals 2, it is different with normal null value(1).
So there are two rows `NULL` after `group by`.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/columns/column_nullable.cpp [hunk 1]
```diff
@@ -102,7 +102,10 @@ StringRef ColumnNullable::serialize_value_into_arena(size_t n, Arena& arena,
     static constexpr auto s = sizeof(arr[0]);
 
     auto pos = arena.alloc_continue(s, begin);
-    memcpy(pos, &arr[n], s);
+    // Value of `NULL` may be 1 or JOIN_NULL_HINT, we serialize both to 1.
+    // Because we need same key for both `NULL` values while processing `group by`.
+    UInt8* val = reinterpret_cast<UInt8*>(pos);
+    *val = (arr[n] ? 1 : 0);
```
Comment (yiguolei) [inline be/src/vec/columns/column_nullable.cpp:109]: Could you please add regression test for this case?

Comment (cambyzju) [reply be/src/vec/columns/column_nullable.cpp:109]: done

**Review by HappenLee — APPROVED** [review]
LGTM
