### PR TITLE
[Bug] Fix bug that tablet meta lock twice

### LINKED ISSUE #4111: [Bug] BE crash when doing clone
**Describe the bug**
The meta lock of a tablet is double locked when doing clone task.

This bug is introduced by #4061

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

The tablet meta lock may already be hold before calling
`generate_tablet_meta_copy()`, so we need provide a unlocked
version of `generate_tablet_meta_copy()`.
This bug  is introduced by #4061 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have create an issue on Fix #4111
- [ ] Commit messages in my PR start with the related issues ID, like "#4071 Add pull request template to doris project"
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I have updated the document
- [ ] Any dependent changes have been merged

### CODE REVIEW

File: be/src/olap/tablet.h [hunk 1]
```diff
@@ -222,6 +222,8 @@ class Tablet : public BaseTablet {
     void build_tablet_report_info(TTabletInfo* tablet_info);
 
     void generate_tablet_meta_copy(TabletMetaSharedPtr new_tablet_meta) const;
+    // caller should hold the _meta_load before calling this method
```
Comment (caiconghui) [inline be/src/olap/tablet.h:225]:
```suggestion
    // caller should hold the _meta_lock before calling this method
```

Comment (morningman) [reply be/src/olap/tablet.h]: done

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
