### PR TITLE
Avoid duplicate column when adding slot in empty tuple

### LINKED ISSUE #4900: The duplicate slot maybe produce by planner when select constant stmt
**Describe the bug**
The duplicate slot maybe produce by planner when select constant stmt

```select 1 from test where k1=1```
A slot will be added in tuple when tuple's materialized slots is empty.

```
select 1, k1 from test where k1=1
```

But k1 is duplicated with the column k1 in where clause.
This will cause the predicate to be incorrectly pushed down to the storage engine when the query is executed.

### PR DESCRIPTION
**Pull request by EmmyMiao87**
Fixed #4900

## Proposed changes

When the supplementary column already exists in the tuple, this column is directly materialized instead of adding a new slot.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #4900), and have described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

### CODE REVIEW

**Review by HappenLee — APPROVED** [review]

**Comment by HappenLee** [comment]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java [hunk 1]
```diff
@@ -1473,7 +1473,7 @@ private Expr rewritePredicate(Analyzer analyzer, Expr oldPredicate, Expr leftChi
 
         if (oldPredicate instanceof InPredicate) {
             InPredicate oldIP = (InPredicate) oldPredicate;
-            InPredicate ip =  new InPredicate(leftChild, oldIP.getListChildren(), oldIP.isNotIn());
+            InPredicate ip = new InPredicate(leftChild, oldIP.getListChildren(), oldIP.isNotIn());
```
Comment (wuyunfeng) [inline fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java:1476]:
```suggestion
            InPredicate inPredicate = new InPredicate(leftChild, oldIP.getListChildren(), oldIP.isNotIn());
```

**Review by wuyunfeng — APPROVED** [review]
LGTM
