### PR TITLE
[Bug][AuditPlugin] Fix bug that length of query stmt in audit should less than limit.

### LINKED ISSUE #3443: [Bug][FE_PLUGIN] Audit Plugin load error when statement contains Chinese and more long than 2048 chars
**Describe the bug**
When one of statements contains Chinese and more long than 2048 chars, audit plugin cannot record them.

**To Reproduce**
1. install audit plugin
2. execute statement which contains Chinese and more long than 2048 chars
3. See error in fe.log:

```
2020-04-30 14:40:40,179 INFO 204 [DorisStreamLoader.loadBatch():138] AuditLoader plugin load with label: audit_20200330_024040, response code: 200, msg: OK, content: {    "TxnId": 11016,    "Label": "audit_20200330_024040",    "Status": "Fail",    "Message": "too many filtered rows",    "NumberTotalRows": 36,    "NumberLoadedRows": 28,    "NumberFilteredRows": 8,    "NumberUnselectedRows": 0,    "LoadBytes": 28355,    "LoadTimeMs": 10,    "ErrorURL": "http://xxx:8040/api/_load_error_log?file=__shard_1/error_log_insert_stmt_3f469ea29683c88f-503432c906d08da1_3f469ea29683c88f_503432c906d08da1"}
```

**Expected behavior**
Load finished.

**Screenshots**
411588232451_ pic_hd

**Desktop (please complete the following information):**
 - OS: Centos7
 - Version: 0.12.8 release

### PR DESCRIPTION
**Pull request by morningman**
Use `String.getBytes().length` instead of `String.length()` to get the real byte length of a string.
Fix: #3443 

Also fix the typo of `max_filter_ratio` in audit log plugin.

### CODE REVIEW

File: fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java [hunk 1]
```diff
@@ -143,8 +143,9 @@ private void assembleAudit(AuditEvent event) {
         auditBuffer.append(event.isQuery ? 1 : 0).append("\t");
         auditBuffer.append(event.feIp).append("\t");
         // trim the query to avoid too long
-        int maxLen = Math.min(2048, event.stmt.length());
-        String stmt = event.stmt.substring(0, maxLen).replace("\t", " ");
+        // use `getBytes().length` to get real byte length
+        int maxLen = Math.min(2000, event.stmt.getBytes().length);
```
Comment (imay) [inline fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java:147]: Could you replace `2000` with a configuration or a `static final` variable?

Comment (morningman) [reply fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java]: done

**Review by kangkaisen — APPROVED** [review]
+1， LGTM
