### PR TITLE
[improvement][fix](insert)(replay) support SHOW LAST INSERT stmt and fix json replay bug

### LINKED ISSUE #8354: [Bug] restart FE failed duo to invalid cast
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

When starting FE, error in fe.out:

```
java.io.IOException: failed to read session variable: java.lang.Long cannot be cast to java.lang.Integer
        at org.apache.doris.qe.SessionVariable.readFromJson(SessionVariable.java:1025)
        at org.apache.doris.qe.SessionVariable.readFields(SessionVariable.java:981)
        at org.apache.doris.qe.VariableMgr.read(VariableMgr.java:312)
        at org.apache.doris.catalog.Catalog.loadGlobalVariable(Catalog.java:1902)
        at org.apache.doris.common.MetaReader.read(MetaReader.java:89)
        at org.apache.doris.catalog.Catalog.loadImage(Catalog.java:1618)
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:848)
        at org.apache.doris.PaloFe.start(PaloFe.java:125)
        at org.apache.doris.PaloFe.main(PaloFe.java:63)
```

### What You Expected?

works well

### How to Reproduce?

This bug is introduced from #8319

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #8354

## Problem Summary:

1. support SHOW LAST INSERT
    In the current implementation, the insert operation returns a json string to describe the result information
    of the insert. But this information is in the session track field of the mysql protocol,
    and it is difficult to obtain programmatically.

    Therefore, I provide a new syntax `show last insert` to explicitly obtain the result of the latest insert operation,
    and return a normal query result set to facilitate the user to obtain the result information of the insert.

2. the `ReturnRows` field in fe.audit.log of insert operation will be set to the loaded row num of the insert.

3.  Fix a bug described in #8354 

## Checklist(Required)

1. Does it affect the original behavior: (No)
3. Has unit tests been added: (No Need)
4. Has document been added or modified: (Yes)
5. Does it need to update dependencies: (No)
6. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/ShowLastInsertStmt.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+                    .addColumn(new Column("Label", ScalarType.createVarchar(128)))
+                    .addColumn(new Column("Database", ScalarType.createVarchar(128)))
+                    .addColumn(new Column("Table", ScalarType.createVarchar(128)))
+                    .addColumn(new Column("TransactionStatus", ScalarType.createVarchar(64)))
+                    .addColumn(new Column("LoadedRows", ScalarType.createVarchar(128)))
+                    .addColumn(new Column("FilteredRows", ScalarType.createVarchar(128)))
+                    .build();
+
+    @Override
+    public void analyze(Analyzer analyzer) {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/ShowLastInsertStmt.java:38]: check priv ？

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/ShowLastInsertStmt.java:38]: No need to check priv here. Bacause `show last insert` can only view the insert result of current session.
So if user does not have priv to insert, than there is no result to show.

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
