### PR TITLE
[fix](having-clause) having clause do not works correct with same alias name

### LINKED ISSUE #15142: [Bug] having clause with same alias name do not work
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

latest

### What's Wrong?

`> select id,sum(v1) v,sum(v2) v2 from test_d group by id having (v2>1);`
`ERROR 1105 (HY000): errCode = 2, detailMessage = HAVING clause not produced by aggregation output (missing from GROUP BY clause?): (`v2` > 1)`

### What You Expected?

fix

### How to Reproduce?

1. create table 
```
CREATE TABLE `test_d` (
  `id` int(11) NULL,
  `v1` bigint(20) NULL,
  `v2` bigint(20) NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

2. insert data
`insert into test_d values(1,1,1),(2,2,2),(2,3,3);`

3. wrong sql:
```
> select id,sum(v1) v,sum(v2) v2 from test_d group by id having (v2>4);
ERROR 1105 (HY000): errCode = 2, detailMessage = HAVING clause not produced by aggregation output (missing from GROUP BY clause?): (`v2` > 4)
```

4. correct sql:
```
> select id,sum(v1) v,sum(v2) v2 from test_d group by id having (v2>4 AND v>0);
+------+------+------+
| id   | v    | v2   |
+------+------+------+
|    2 |    5 |    5 |
+------+------+------+
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
# Proposed changes

Issue Number: close #15142

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.36 seconds
 load time: 645 seconds
 storage size: 17123050502 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221216152051_clickbench_pr_64549.html

**Comment by morningman** [comment]
please add regression test

**Comment by cambyzju** [comment]
> please add regression test

done

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java [hunk 1]
```diff
@@ -989,18 +989,36 @@ private void analyzeAggregation(Analyzer analyzer) throws AnalysisException {
              *                     (select min(k1) from table b where a.key=b.k2);
              * TODO: the a.key should be replaced by a.k1 instead of unknown column 'key' in 'a'
              */
+
+            // according to mysql
+            // having clause should use column name inside group by clause, prior to alias.
+            // case1: having clause use column name table.v1, because v1 inside group by clause
+            //     select id, sum(v1) v1 from table group by id,v1 having(v1>1);
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:996]: MySQL's behavior is very strange. according to sql standard, `having` should filter the data after `Aggregate`. So the slot in `having` should always bind on the output of `Aggregate`, in other words, the alias name.
Since doris has many different from the behavior of MySQL. Here we should follow the SQL standard instead of MySQL for a more understandable syntax.

Comment (cambyzju) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:996]: > MySQL's behavior is very strange. according to sql standard, `having` should filter the data after `Aggregate`. So the slot in `having` should always bind on the output of `Aggregate`, in other words, the alias name. Since doris has many different from the behavior of MySQL. Here we should follow the SQL standard instead of MySQL for a more understandable syntax.

1. accord to SQL standard, having clause do not support alias name;
2. Doris always say "compatible with MySQL protocol", lots of SQL keeps Mysql way;
3. Before this pr, we already try to following MySQL way. But the old implement has two problem:
- one is, only consider has GROUP BY or NOT, not consider slots inside GROUP BY or not;
- the other is, try whole HAVING expr, do consider part slots have alias, part slots do not;

So if we want to follow SQL standard, we should better forbid alias name in HAVING clause.
But old users will confused, because the behavior changes too large.

**Review by yangzhg — APPROVED** [review]
LGTM
