### PR TITLE
[fix](storage)bloom filter support ColumnDict

### LINKED ISSUE #9138: [Bug] be core dump at bloom_filter_predicate.h:121 due to null pointer
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev-1.0.1

### What's Wrong?

be core dump. ubsan reported:

`/root/regression/incubator-doris/be/src/olap/bloom_filter_predicate.h:121:49: runtime error: member call on null pointer of type 'const struct PredicateColumnType'
    #0 0x55a95a2490af in doris::BloomFilterColumnPredicate<(doris::PrimitiveType)15>::evaluate(doris::vectorized::IColumn&, unsigned short*, unsigned short*) const /root/
regression/incubator-doris/be/src/olap/bloom_filter_predicate.h:121
    #1 0x55a9609d28b1 in doris::segment_v2::SegmentIterator::_evaluate_short_circuit_predicate(unsigned short*, unsigned short*) /root/regression/incubator-doris/be/src/o
lap/rowset/segment_v2/segment_iterator.cpp:879
    #2 0x55a9609d6407 in doris::segment_v2::SegmentIterator::next_batch(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/olap/rowset/segment_v2/segment_iterator.cpp:978
    #3 0x55a95a566094 in doris::BetaRowsetReader::next_block(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/olap/rowset/beta_rowset_reader.cpp:193
    #4 0x55a9621f5442 in doris::vectorized::VCollectIterator::Level0Iterator::next(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:215
    #5 0x55a9621ff76a in doris::vectorized::VCollectIterator::Level1Iterator::_normal_next(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:366
    #6 0x55a9621ffdec in doris::vectorized::VCollectIterator::Level1Iterator::_normal_next(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:375
    #7 0x55a9621f6a40 in doris::vectorized::VCollectIterator::Level1Iterator::next(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:264
    #8 0x55a9621f2f52 in doris::vectorized::VCollectIterator::next(doris::vectorized::Block*) /root/regression/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:165
    #9 0x55a9622108e0 in doris::vectorized::BlockReader::_direct_next_block(doris::vectorized::Block*, doris::MemPool*, doris::ObjectPool*, bool*) /root/regression/incubator-doris/be/src/vec/olap/block_reader.cpp:175
    #10 0x55a96221cf02 in doris::vectorized::BlockReader::next_block_with_aggregation(doris::vectorized::Block*, doris::MemPool*, doris::ObjectPool*, bool*) /root/regression/incubator-doris/be/src/vec/olap/block_reader.h:49
    #11 0x55a9610580c3 in doris::vectorized::VOlapScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) /root/regression/incubator-doris/be/src/vec/exec/volap_scanner.cpp:55
    #12 0x55a96101d069 in doris::vectorized::VOlapScanNode::scanner_thread(doris::vectorized::VOlapScanner*) /root/regression/incubator-doris/be/src/vec/exec/volap_scan_node.cpp:216
    #13 0x55a96103f7b2 in void std::__invoke_impl<void, void (doris::vectorized::VOlapScanNode::*&)(doris::vectorized::VOlapScanner*), doris::vectorized::VOlapScanNode*&, doris::vectorized::VOlapScanner*&>(std::__invoke_memfun_deref, void (doris::vectorized::VOlapScanNode::*&)(doris::vectorized::VOlapScanner*), doris::vectorized::VOlapSca:
`

### What You Expected?

work normal

### How to Reproduce?

tpcds q60
`WITH   ss AS (    SELECT      i_item_id    , sum(ss_ext_sales_price) total_sales    FROM      store_sales    , date_dim    , customer_address    , item    WHERE (i_item_id IN (       SELECT i_item_id       FROM         item       WHERE (i_category IN ('Music'))    ))       AND (ss_item_sk = i_item_sk)       AND (ss_sold_date_sk = d_date_sk)       AND (d_year = 1998)       AND (d_moy = 9)       AND (ss_addr_sk = ca_address_sk)       AND (ca_gmt_offset = -5)    GROUP BY i_item_id ) , cs AS (    SELECT      i_item_id    , sum(cs_ext_sales_price) total_sales    FROM      catalog_sales    , date_dim    , customer_address    , item    WHERE (i_item_id IN (       SELECT i_item_id       FROM         item       WHERE (i_category IN ('Music'))    ))       AND (cs_item_sk = i_item_sk)       AND (cs_sold_date_sk = d_date_sk)       AND (d_year = 1998)       AND (d_moy = 9)       AND (cs_bill_addr_sk = ca_address_sk)       AND (ca_gmt_offset = -5)    GROUP BY i_item_id ) , ws AS (    SELECT      i_item_id    , sum(ws_ext_sales_price) total_sales    FROM      web_sales    , date_dim    , customer_address    , item    WHERE (i_item_id IN (       SELECT i_item_id       FROM         item       WHERE (i_category IN ('Music'))    ))       AND (ws_item_sk = i_item_sk)       AND (ws_sold_date_sk = d_date_sk)       AND (d_year = 1998)       AND (d_moy = 9)       AND (ws_bill_addr_sk = ca_address_sk)       AND (ca_gmt_offset = -5)    GROUP BY i_item_id ) SELECT   i_item_id , sum(total_sales) total_sales FROM   (    SELECT *    FROM      ss UNION ALL    SELECT *    FROM      cs UNION ALL    SELECT *    FROM      ws )  tmp1 GROUP BY i_item_id ORDER BY i_item_id ASC, total_sales ASC LIMIT 100`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangbo**
# Proposed changes

Issue Number: close #9138

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/columns/column_dictionary.h [hunk 1]
```diff
@@ -106,6 +107,7 @@ class ColumnDictionary final : public COWHelper<IColumn, ColumnDictionary<T>> {
     void clear() override {
         _codes.clear();
         _dict_code_converted = false;
+        _dict.clear_hash_values();
```
Comment (zenoyang) [inline be/src/vec/columns/column_dictionary.h:110]: `hash_values` only needs to be calculated once.
If `clear_hash_values` is called here, the hash of the dictionary values needs to be calculated once for each call to  `SegmentIterator::next_batch`.

Comment (wangbo) [reply be/src/vec/columns/column_dictionary.h:110]: ```convert_dict_codes_if_necessary``` may change code order, so we need to reset every time.
Of course, we can solve it but may introduce additional complexity.
I didn't see the significant performance improvement in tpcds-q60, this may need further research.
Currently I prefer to keep status quo.

File: be/src/exprs/bloomfilter_predicate.h [hunk 2]
```diff
@@ -65,6 +65,10 @@ class BlockBloomFilterAdaptor {
         return _bloom_filter->find(Slice(data, len));
     }
 
+    bool test_uint32_t(uint32_t data) const {
```
Comment (HappenLee) [inline be/src/exprs/bloomfilter_predicate.h:68]: should refactor code of `test_bytes` and `test_uint32_t` use template to make code clear.

File: be/src/vec/columns/column_dictionary.h [hunk 3]
```diff
@@ -297,6 +307,23 @@ class ColumnDictionary final : public COWHelper<IColumn, ColumnDictionary<T>> {
             return -1;
         }
 
+        inline StringValue& get_value(T code) { return _dict_data[code]; }
+        
+        inline void generate_hash_values() {
+            if (_hash_values.size() == 0) {
+                _hash_values.reserve(_dict_data.size());
```
Comment (HappenLee) [inline be/src/vec/columns/column_dictionary.h:314]: why not `resize` and `_hash_values[i] = HashUtil::murmur_hash3_32(sv.ptr, sv.len, 0);`

Comment (wangbo) [reply be/src/vec/columns/column_dictionary.h:314]: It looks no difference.
Is there any benefit to your approach?

Comment (HappenLee) [reply be/src/vec/columns/column_dictionary.h:314]: 1. less code
2. more quickly. each time you push back need to do `_size ++`

Comment (wangbo) [reply be/src/vec/columns/column_dictionary.h:314]: 👌🏻

**Comment by Toms1999** [comment]
let me seesee

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
@wangbo please rebase the master to pass the check

**Review by morningman — APPROVED** [review]
