### PR TITLE
Fix DATA_TYPE in information_schema.columns is not compatible to mysql meta

### LINKED ISSUE #4647: [BUG] DATA_TYPE in information_schema.columns is not compatible to mysql meta
**Describe the bug**

DATA_TYPE in information_schema.columns is not compatible to mysql meta

**To Reproduce**
select * from information_schema.columns

**Expected behavior**
the result of data_type is (int, decimal, char, varchar, ...)，but doris data_type is (int(11), varchar(20), ...)
Excess number will affect some BI systems or upper system can't get right type

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## Proposed changes

FIX:#4647

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/schema_scanner/schema_columns_scanner.cpp [hunk 1]
```diff
@@ -93,6 +93,41 @@ Status SchemaColumnsScanner::start(RuntimeState *state) {
...
+            return "int";
+        case TPrimitiveType::BIGINT:
+            return "bigint";
+        case TPrimitiveType::LARGEINT:
+            return "bigint unsinged";
+        case TPrimitiveType::FLOAT:
+            return "float";
+        case TPrimitiveType::DOUBLE:
+            return "double";
+        case TPrimitiveType::VARCHAR:
```
Comment (EmmyMiao87) [inline be/src/exec/schema_scanner/schema_columns_scanner.cpp:114]: How to display the length of varchar?

Comment (HangyuanLiu) [reply be/src/exec/schema_scanner/schema_columns_scanner.cpp:114]: the varchar has length display in COLUMN_TYPE, NOT DATA_TYPE

**Review by kangkaisen — APPROVED** [review]
+1
