### PR TITLE
[Bug] Cancel the query if OlapScanner prepare failed

### LINKED ISSUE #4001: [Bug] BE crash in OlapScanner
**Describe the bug**
```
#0  data_dir (this=0x0) at /doris/core/be/src/olap/base_tablet.h:82
#1  scan_disk (this=0x260ba240) at /doris/core/be/src/exec/olap_scanner.h:86
#2  doris::OlapScanNode::start_scan_thread (this=this@entry=0x4135d000, state=state@entry=0x15c97800) at /doris/core/be/src/exec/olap_scan_node.cpp:686
#3  0x0000000001600aa1 in doris::OlapScanNode::start_scan (this=this@entry=0x4135d000, state=state@entry=0x15c97800) at /doris/core/be/src/exec/olap_scan_node.cpp:373
#4  0x0000000001601609 in doris::OlapScanNode::get_next (this=0x4135d000, state=0x15c97800, row_batch=0x7f9a83f5f350, eos=0x7f9a83f5f278) at /doris/core/be/src/exec/olap_scan_node.cpp:204
#5  0x00000000015edf9e in doris::TopNNode::open (this=0x3c296000, state=0x15c97800) at /doris/core/be/src/exec/topn_node.cpp:107
#6  0x00000000011723c4 in doris::PlanFragmentExecutor::open_internal (this=this@entry=0x3c2973b0) at /doris/core/be/src/runtime/plan_fragment_executor.cpp:275
#7  0x0000000001172d49 in doris::PlanFragmentExecutor::open (this=this@entry=0x3c2973b0) at /doris/core/be/src/runtime/plan_fragment_executor.cpp:259
#8  0x00000000010f2c0e in doris::FragmentExecState::execute (this=0x3c297340) at /doris/core/be/src/runtime/fragment_mgr.cpp:212
#9  0x00000000010f3c85 in doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) (this=0x509d500, exec_state=..., cb=...)
    at /doris/core/be/src/runtime/fragment_mgr.cpp:399
#10 0x00000000010fba34 in operator() (a2=<error reading variable: access outside bounds of object referenced via synthetic pointer>, a1=..., p=<optimized out>, this=<optimized out>)
    at /doris/thirdparty/installed/include/boost/bind/mem_fn_template.hpp:280
#11 operator()<boost::_mfi::mf2<void, doris::FragmentMgr, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)> >, boost::_bi::list0> (a=<synthetic pointer>, f=..., this=<optimized out>)
    at /doris/thirdparty/installed/include/boost/bind/bind.hpp:398
#12 operator() (this=<optimized out>) at /doris/thirdparty/installed/include/boost/bind/bind.hpp:1294
#13 boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, boost::_mfi::mf2<void, doris::FragmentMgr, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)> >, boost::_bi::list3<boost::_bi::value<doris::FragmentMgr*>, boost::_bi::value<std::shared_ptr<doris::FragmentExecState> >, boost::_bi::value<std::function<void (doris::PlanFragmentExecutor*)> > > >, void>::invoke(boost::detail::function::function_buffer&) (function_obj_ptr=...)
    at /doris/thirdparty/installed/include/boost/function/function_template.hpp:159
#14 0x00000000010bd00a in operator() (this=0x7f9a83f5f838) at /doris/thirdparty/installed/include/boost/function/function_template.hpp:759
#15 doris::PriorityThreadPool::work_thread (this=0x509d580, thread_id=<optimized out>) at /doris/core/be/src/util/priority_thread_pool.hpp:138
#16 0x0000000001c8436d in thread_proxy ()
#17 0x00007f9ad98481c3 in start_thread () from /gcc/lib64/libpthread.so.0
#18 0x00007f9ad927712d in clone () from /gcc/lib64/libc.so.6
```

**Debug**
This is because tablet does not exist, so that olap scanner prepare failed.
But we didn't check the return status of prepare(), so the following method (scanner->scan_disk()) may visit some 
uninitialized fields in olap scanner, such as `_tablet`, which cause BE crash.

### PR DESCRIPTION
**Pull request by morningman**
Fix #4001

### CODE REVIEW

File: be/src/exec/olap_scan_node.cpp [hunk 1]
```diff
@@ -681,7 +681,11 @@ Status OlapScanNode::start_scan_thread(RuntimeState* state) {
             }
             OlapScanner* scanner = new OlapScanner(
                 state, this, _olap_scan_node.is_preaggregation, _need_agg_finalize, *scan_range, scanner_ranges);
+            // add scanner to pool before doing prepare.
+            // so that scanner can be automatically deconstructed if prepare failed.
             _scanner_pool->add(scanner);
```
Comment (wutiangan) [inline be/src/exec/olap_scan_node.cpp:686]: It doesn't matter whether you add the scanner to the pool before or after doing prepare.
if you put scanner preparing before add the scanner_pool，the scanner will be decontruced.

**Review by yangzhg — APPROVED** [review]
LGTM

File: be/src/exec/olap_scan_node.cpp (hunk 1 above)
Comment (morningman) [reply be/src/exec/olap_scan_node.cpp:686]: Why? the `scanner` here is created by `new` operator. How can it be deconstructed automatically?

**Review by wutiangan — APPROVED** [review]
