### PR TITLE
[Bug] Missing error tablet list when close_wait return error

### LINKED ISSUE #9417: [Bug] Error for close_wait() is lost for data loading
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.09

### What's Wrong?

In function close_wait() of delta_writer.cpp, if _flush_token->wait() return an error, it will not be returned to front.
Because in PInternalServiceImpl::tablet_writer_add_batch, _exec_env->load_channel_mgr()->add_batch(*request, response); will not return an error, but only return error_tablets. However error_tablets in close_wait() is not returned.

### What You Expected?

close_wait() will return error tablets when error returned.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #9417

## Problem Summary:

In function close_wait() of delta_writer.cpp, if _flush_token->wait() return an error, it will not be returned to front.
Because in PInternalServiceImpl::tablet_writer_add_batch, _exec_env->load_channel_mgr()->add_batch(*request, response); will not return an error, but only return error_tablets. However error_tablets in close_wait() is not returned.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/delta_writer.cpp [hunk 1]
```diff
@@ -321,7 +322,13 @@ Status DeltaWriter::close_wait(google::protobuf::RepeatedPtrField<PTabletInfo>*
     }
 
     // return error if previous flush failed
-    RETURN_NOT_OK(_flush_token->wait());
+    Status s = Status::OK();
```
Comment (morningman) [inline be/src/olap/delta_writer.cpp:325]:
```suggestion
    Status s = _flush_token->wait();
    if (!s.ok()) {
    ...
    }
```

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]

**Review by morningman — APPROVED** [review]
