### PR TITLE
[fix](delete) fix delete from bug which can get wrong result

### LINKED ISSUE #17145: [Bug] will get wrong result when have delete predicates
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

当通过delete from 来删除某个行的时候，如果使用与删除条件相同的列去进行查询的时候，会产生把不该删的行也过滤掉的情况。
这种情况与使用delete predicates去过滤zone map的page有关。

例子：
建表sql
```
CREATE TABLE `test111` (
  `k1` bigint(20) NULL,
  `k2` largeint(40) NULL,
  `k3` largeint(40) NULL
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false"
);
```

导入数据和查询
```
MySQL [test]> truncate table test111;
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> 
MySQL [test]> insert into test111 values(0,1,11),(0,1,22),(0,1,33),(0,1,44),(0,1,55),(0,1,66),(0,1,77),(0,1,88),(0,1,99),(0,1,100),(0,1,101),(0,1,102),(0,1,11),(0,1,122),(0,1,133),(0,1,144),(0,1,155),(0,1,166),(0,1,177),(0,1,188),(0,1,199),(0,1,200),(0,1,201),(0,1,202);
Query OK, 24 rows affected (0.04 sec)
{'label':'insert_a6a4918318c24917_92243984d913b406', 'status':'VISIBLE', 'txnId':'11041'}

MySQL [test]> 
MySQL [test]> delete from test111 where k2=1 and k3=11;
Query OK, 0 rows affected (0.02 sec)
{'label':'delete_c80835e3-3c0a-405f-9284-b0b0edad080a', 'status':'VISIBLE', 'txnId':'11042'}

MySQL [test]> 
MySQL [test]> select k2,k3 from test111;
+------+------+
| k2   | k3   |
+------+------+
| 1    | 22   |
| 1    | 33   |
| 1    | 44   |
| 1    | 55   |
| 1    | 66   |
| 1    | 77   |
| 1    | 88   |
| 1    | 99   |
| 1    | 100  |
| 1    | 101  |
| 1    | 102  |
| 1    | 122  |
| 1    | 133  |
| 1    | 144  |
| 1    | 155  |
| 1    | 166  |
| 1    | 177  |
| 1    | 188  |
| 1    | 199  |
| 1    | 200  |
| 1    | 201  |
| 1    | 202  |
+------+------+
22 rows in set (0.02 sec)

MySQL [test]> 
MySQL [test]> select k2,k3 from test111 where k2=1;
Empty set (0.00 sec)

```

在上边的例子中，使用k2和k3列一同去删除某一个行数据，select * 的时候返回的正确结果显示数据已经被删除，还剩下其余的22条数据
但是我使用k2作为查询条件时，确没有返回任何结果

更多的例子见  Reproduce。

经过分析，这个问题与删除条件有多个，但是查询条件使用了删除列，然后在使用zone map和delete predicates来选择和淘汰page时有关。
像上边的例子，应该是两个删除条件都满足的行来被过滤掉，但是在现在的代码中，这两个逻辑成了或关系，只要有page满足一个条件，就会整个page都过滤掉，导致不满足另外一个删除列条件的行也不能读取

另外如果使用相同列去作为删除条件，也有类似情况，应该是与的场景，都按或处理的，导致并不是满足所有删除条件的page被过滤掉了，从而产生了错误的结果。

### What You Expected?

返回正确的结果

### How to Reproduce?

```
CREATE TABLE `test111` (
  `k1` bigint(20) NULL,
  `k2` largeint(40) NULL,
  `k3` largeint(40) NULL
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false"
);

MySQL [test]> truncate table test111;
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> 
MySQL [test]> insert into test111 values(0,1,11),(0,1,22),(0,1,33),(0,1,44),(0,1,55),(0,1,66),(0,1,77),(0,1,88),(0,1,99),(0,1,100),(0,1,101),(0,1,102),(0,1,11),(0,1,122),(0,1,133),(0,1,144),(0,1,155),(0,1,166),(0,1,177),(0,1,188),(0,1,199),(0,1,200),(0,1,201),(0,1,202);
Query OK, 24 rows affected (0.04 sec)
{'label':'insert_a6a4918318c24917_92243984d913b406', 'status':'VISIBLE', 'txnId':'11041'}

MySQL [test]> 
MySQL [test]> delete from test111 where k2=1 and k3=11;
Query OK, 0 rows affected (0.02 sec)
{'label':'delete_c80835e3-3c0a-405f-9284-b0b0edad080a', 'status':'VISIBLE', 'txnId':'11042'}

MySQL [test]> 
MySQL [test]> select k2,k3 from test111;
+------+------+
| k2   | k3   |
+------+------+
| 1    | 22   |
| 1    | 33   |
| 1    | 44   |
| 1    | 55   |
| 1    | 66   |
| 1    | 77   |
| 1    | 88   |
| 1    | 99   |
| 1    | 100  |
| 1    | 101  |
| 1    | 102  |
| 1    | 122  |
| 1    | 133  |
| 1    | 144  |
| 1    | 155  |
| 1    | 166  |
| 1    | 177  |
| 1    | 188  |
| 1    | 199  |
| 1    | 200  |
| 1    | 201  |
| 1    | 202  |
+------+------+
22 rows in set (0.02 sec)

MySQL [test]> 
MySQL [test]> select k2,k3 from test111 where k2=1;
Empty set (0.00 sec)

MySQL [test]> 
MySQL [test]> delete from test111 where k2!=0 and k3=22;
Query OK, 0 rows affected (0.04 sec)
{'label':'delete_95ad73aa-43ae-498d-b310-972303ed19a4', 'status':'VISIBLE', 'txnId':'11044'}

MySQL [test]> 
MySQL [test]> select k2,k3 from test111;
+------+------+
| k2   | k3   |
+------+------+
| 1    | 33   |
| 1    | 44   |
| 1    | 55   |
| 1    | 66   |
| 1    | 77   |
| 1    | 88   |
| 1    | 99   |
| 1    | 100  |
| 1    | 101  |
| 1    | 102  |
| 1    | 122  |
| 1    | 133  |
| 1    | 144  |
| 1    | 155  |
| 1    | 166  |
| 1    | 177  |
| 1    | 188  |
| 1    | 199  |
| 1    | 200  |
| 1    | 201  |
| 1    | 202  |
+------+------+
21 rows in set (0.01 sec)

MySQL [test]> 
MySQL [test]> select k2,k3 from test111 where k2!=0;
Empty set (0.02 sec)

MySQL [test]> 
MySQL [test]> delete from test111 where k2=1 and k3 >= 11 and k3 <=200;
Query OK, 0 rows affected (0.03 sec)
{'label':'delete_ac8851d1-a69d-44f3-b349-7a258a9eeb93', 'status':'VISIBLE', 'txnId':'11046'}

MySQL [test]> 
MySQL [test]> select k2,k3 from test111;
+------+------+
| k2   | k3   |
+------+------+
| 1    | 201  |
| 1    | 202  |
+------+------+
2 rows in set (0.01 sec)

MySQL [test]> 
MySQL [test]> select k2,k3 from test111 where k3 = 201;
Empty set (0.01 sec)

MySQL [test]> 
MySQL [test]> truncate table test111;
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> 
MySQL [test]> insert into test111 values(0,1,11),(0,1,22),(0,1,33),(0,1,44),(0,1,55),(0,1,66),(0,1,77),(0,1,88),(0,1,99),(0,1,100),(0,1,101),(0,1,102),(0,1,11),(0,1,122),(0,1,133),(0,1,144),(0,1,155),(0,1,166),(0,1,177),(0,1,188),(0,1,199),(0,1,200),(0,1,201),(0,1,202);
Query OK, 24 rows affected (0.03 sec)
{'label':'insert_97bbcb5c4ce5449c_b7316dbe6e5a6d0f', 'status':'VISIBLE', 'txnId':'11048'}

MySQL [test]> 
MySQL [test]> delete from test111 where k2=1 and k3 <=202 and k3 >= 33;
Query OK, 0 rows affected (0.02 sec)
{'label':'delete_16073c70-9caf-4be2-85f3-f4ea9be4330f', 'status':'VISIBLE', 'txnId':'11049'}

MySQL [test]> 
MySQL [test]> select k2,k3 from test111;
+------+------+
| k2   | k3   |
+------+------+
| 1    | 11   |
| 1    | 22   |
+------+------+
2 rows in set (0.00 sec)

MySQL [test]> 
MySQL [test]> select k2,k3 from test111 where k3 = 11;
Empty set (0.01 sec)

```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #17145

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

File: be/src/olap/rowset/segment_v2/segment_iterator.cpp [hunk 1]
```diff
@@ -379,7 +379,9 @@ Status SegmentIterator::_get_row_ranges_from_conditions(RowRanges* condition_row
         DCHECK(_opts.col_id_to_predicates.count(cid) > 0);
         RETURN_IF_ERROR(_column_iterators[_schema.unique_id(cid)]->get_row_ranges_by_zone_map(
                 _opts.col_id_to_predicates[cid].get(),
-                _opts.col_id_to_del_predicates.count(cid) > 0
+                _opts.col_id_to_del_predicates.size() == 1 &&
```
Comment (yiguolei) [inline be/src/olap/rowset/segment_v2/segment_iterator.cpp:382]: If user send to delete predicates:
1. delete where a = 1
2. delete where a = 2

In this pr, the delete predicate will take no effect?

File: regression-test/suites/delete_p0/test_zone_map_delete.groovy [hunk 2]
```diff
@@ -54,4 +54,77 @@ suite("test_zone_map_delete") {
...
+    ) ENGINE=OLAP
+    AGGREGATE KEY(`k1`, `k2`, `k3`)
+    COMMENT 'OLAP'
+    DISTRIBUTED BY HASH(`k1`) BUCKETS 1
+    PROPERTIES (
+    "replication_allocation" = "tag.location.default: 1",
+    "in_memory" = "false",
+    "storage_format" = "V2",
+    "light_schema_change" = "true",
+    "disable_auto_compaction" = "false"
```
Comment (yiguolei) [inline regression-test/suites/delete_p0/test_zone_map_delete.groovy:73]: I  think should disable auto compaction, then p0 could produce stable result. If disable auto compaction == false, the rowset maybe merged.

File: be/src/olap/rowset/segment_v2/segment_iterator.cpp (hunk 1 above)
Comment (yiguolei) [inline be/src/olap/rowset/segment_v2/segment_iterator.cpp:382]: Add a comment here to explain these conditions. For example, why check size == 1

Comment (nextdreamblue) [reply be/src/olap/rowset/segment_v2/segment_iterator.cpp:382]: 理论上，如果是两次独立的删除，比如delete from table where a=1; delete from table where a=2;其实这个地方应该可以使用的，但是目前的代码，是把所有不同版本的delete predicates和不同列的delete predicates都放到一起了，失去了版本信息、失去了谓词间可能是and的关系，统一弱化成了delete predicates都是独立的，有一个delete predicates满足条件，就把page都去掉。
这个pr的修改方式，就是在当前代码的基础上，当只有一个delete predicate的时候才能保证后续淘汰page的正确性，所以这里一律加了 == 1的判断才传递delete predicates。
如果要把不同版本的delete predicates和不同列的delete predicates作为完整和严谨的逻辑去判断page，需要修改的设计就有点多了，目前的方案算是一种优先解决bug的思路，后续可以进一步把delete predicates这块加速zoom判断进行page淘汰的逻辑完善，提高delete predicates使用的场景。

Comment (nextdreamblue) [reply be/src/olap/rowset/segment_v2/segment_iterator.cpp:382]: ok, i add a comment

**Comment by nextdreamblue** [comment]
run buildall

File: be/src/olap/rowset/segment_v2/segment_iterator.cpp [hunk 3]
```diff
@@ -379,7 +379,15 @@ Status SegmentIterator::_get_row_ranges_from_conditions(RowRanges* condition_row
         DCHECK(_opts.col_id_to_predicates.count(cid) > 0);
         RETURN_IF_ERROR(_column_iterators[_schema.unique_id(cid)]->get_row_ranges_by_zone_map(
                 _opts.col_id_to_predicates[cid].get(),
-                _opts.col_id_to_del_predicates.count(cid) > 0
+                // 理论上，如果是两次独立的删除，比如delete from table where a=1; delete from table where a=2;其实这个地方应该可以使用的;
+                // 但是目前的代码，是把所有不同版本的delete predicates和不同列的delete predicates都放到一起了，失去了版本信息、失去了谓词间可能是and的关系，
+                // 统一弱化成了delete predicates都是独立的，有一个delete predicates满足条件，就把page都去掉。
+                // 这个pr的修改方式，就是在当前代码的基础上，当只有一个delete predicate的时候才能保证后续淘汰page的正确性，所以这里一律加了 == 1的判断才传递delete predicates。
+                // 如果要把不同版本的delete predicates和不同列的delete predicates作为完整和严谨的逻辑去判断page，需要修改的设计就有点多了，
+                // 目前的方案算是一种优先解决bug的思路，后续可以进一步把delete predicates这块加速zone判断进行page淘汰的逻辑完善，提高delete predicates使用的场景。
```
Comment (wangbo) [inline be/src/olap/rowset/segment_v2/segment_iterator.cpp:387]: Please compact the comment and in English.
For example:
```
Currently, one transaction can only support one delete condition for page filtering.
Following case is allowed:
delete from table1 where a=1;
delete from table1 where a=2;
Following case is not allowed, because one transaction has more than on delete condition:
delete from table1 where a=1 and b = 2;
This may cause bug when you query table1 with a=1;
You can refer #17145 for more details.
```

Comment (nextdreamblue) [reply be/src/olap/rowset/segment_v2/segment_iterator.cpp:387]: > Please compact the comment and in English. For example:
> 
> ```
> Currently, one transaction can only support one delete condition for page filtering.
> Following case is allowed:
> delete from table1 where a=1;
> delete from table1 where a=2;
> Following case is not allowed, because one transaction has more than on delete condition:
> delete from table1 where a=1 and b = 2;
> This may cause bug when you query table1 with a=1;
> You can refer #17145 for more details.
> ```

thanks bro, you are my hero

**Comment by nextdreamblue** [comment]
run buildall

File: be/src/olap/rowset/segment_v2/segment_iterator.cpp [hunk 4]
```diff
@@ -379,7 +379,17 @@ Status SegmentIterator::_get_row_ranges_from_conditions(RowRanges* condition_row
         DCHECK(_opts.col_id_to_predicates.count(cid) > 0);
         RETURN_IF_ERROR(_column_iterators[_schema.unique_id(cid)]->get_row_ranges_by_zone_map(
                 _opts.col_id_to_predicates[cid].get(),
-                _opts.col_id_to_del_predicates.count(cid) > 0
+                // Currently, one transaction can only support one delete condition for page filtering.
```
Comment (wangbo) [inline be/src/olap/rowset/segment_v2/segment_iterator.cpp:382]: It seems that when delete condition only contains OR predicates, page filter can work correctly here.
So this pr is a quick fix, it may cause some case performance degradation.
I think it's better to add a todo here.

File: regression-test/suites/delete_p0/test_zone_map_delete.groovy [hunk 5]
```diff
@@ -54,4 +54,77 @@ suite("test_zone_map_delete") {
...
+
+    sql """ delete from ${tableName} where k2 is null and k3=00;"""
+
+    qt_sql """ select k2,k3 from ${tableName};"""
+
+    qt_sql """ select k2,k3 from ${tableName} where k2 is null;"""
+
+    sql """delete from ${tableName} where k2 is not null and k3=11;"""
+
+    qt_sql """select k2,k3 from ${tableName};"""
```
Comment (wangbo) [inline regression-test/suites/delete_p0/test_zone_map_delete.groovy:90]: You'd better add ```order by``` in query sql.

File: be/src/olap/rowset/segment_v2/segment_iterator.cpp (hunk 4 above)
Comment (nextdreamblue) [reply be/src/olap/rowset/segment_v2/segment_iterator.cpp:382]: ok, i add a todo

File: regression-test/suites/delete_p0/test_zone_map_delete.groovy (hunk 5 above)
Comment (nextdreamblue) [reply regression-test/suites/delete_p0/test_zone_map_delete.groovy:90]: it is better, lei fix it

**Review by wangbo — DISMISSED** [review]
LGTM

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM
