### PR TITLE
[Compile] fix compile error in gcc10

### LINKED ISSUE #5293: [compile] compile error in gcc10
**Describe the bug**
Compile Error In GCC10

### PR DESCRIPTION
**Pull request by stdpain**
## Proposed changes
will close #5293

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [*] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes

## Further comments

Fix compile error in gcc 10

### CODE REVIEW

File: be/src/olap/hll.h [hunk 1]
```diff
@@ -21,6 +21,7 @@
 #include <math.h>
 #include <stdio.h>
 
+#include <string>
```
Comment (yangzhg) [inline be/src/olap/hll.h:24]: pay attention to the order of include,
string should under set

Comment (stdpain) [reply be/src/olap/hll.h]: fixed

**Review by yangzhg — APPROVED** [review]
LGTM
