### PR TITLE
[fix][mem tracker] Fix MemTracker null pointer in vectorized

### LINKED ISSUE #8920: [Bug] `ThreadMemTrackerMgr::update_tracker` null pointer in vectorized
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

#0  doris::MemTracker::id (this=0x0) at /root/doris-release/be/src/runtime/mem_tracker.h:405
#1  doris::ThreadMemTrackerMgr::update_tracker<false> (mem_tracker=..., this=0x55691c7cb600) at /root/doris-release/be/src/runtime/thread_mem_tracker_mgr.h:180
#2  doris::SwitchThreadMemTracker<false>::SwitchThreadMemTracker (in_task=false, mem_tracker=..., this=0x7f81cf0cf860) at /root/doris-release/be/src/runtime/thread_context.h:281
#3  doris::SwitchThreadMemTracker<false>::SwitchThreadMemTracker (in_task=false, mem_tracker=..., this=0x7f81cf0cf860) at /root/doris-release/be/src/runtime/thread_context.h:266
#4  doris::vectorized::VExprContext::prepare (this=0x55692b6d2960, state=state@entry=0x556938766000, row_desc=..., tracker=...) at /root/doris-release/be/src/vec/exprs/vexpr_context.cpp:44
#5  0x00005569154e7c78 in doris::vectorized::VExpr::prepare (ctxs=..., state=state@entry=0x556938766000, row_desc=..., tracker=...) at /var/local/ldb-toolchain/include/c++/11/bits/stl_vector.h:1061
#6  0x00005569160c972d in doris::stream_load::VOlapTableSink::prepare (this=0x55693550d000, state=0x556938766000) at /root/doris-release/be/src/vec/sink/vtablet_sink.cpp:47

### What You Expected?

win

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #8920

Fix ThreadMemTrackerMgr::update_tracker null pointer and some details. 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/sink/vtablet_sink.cpp [hunk 1]
```diff
@@ -43,10 +43,11 @@ Status VOlapTableSink::init(const TDataSink& sink) {
 }
 
 Status VOlapTableSink::prepare(RuntimeState* state) {
+    RETURN_IF_ERROR(OlapTableSink::prepare(state));
     // Prepare the exprs to run.
     RETURN_IF_ERROR(vectorized::VExpr::prepare(_output_vexpr_ctxs, state, _input_row_desc,
                                                _expr_mem_tracker));
-    return OlapTableSink::prepare(state);
+    return Status::OK();
```
Comment (morningman) [inline be/src/vec/sink/vtablet_sink.cpp:50]: Why no need to call `OlapTableSink::prepare(state);`?

Comment (xinyiZzz) [reply be/src/vec/sink/vtablet_sink.cpp:50]: image
Changed location because `mem_tracker` is initialized in `OlapTableSink::prepare`.
Testing found no effect on logic.

**Review by morningman — APPROVED** [review]
LGTM
