### PR TITLE
Switch SpringBoot built-in container to jetty

### LINKED ISSUE #6148: [Bugfix]HTTP v2 version stream load importing large data files will cause connection reset problems
For the http v2 version of stream load, the problem of connection reset will occur when importing large data files. After investigation, it is confirmed that it is the problem of the content tomcat container's implementation of 307 temporary redirection.
solution:
Switch the built-in web container of http v2 SpringBoot to jetty. After testing, this problem can be solved well.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by hf200012**
Switch SpringBoot built-in container to jetty

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #6148 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/httpv2/HttpServer.java [hunk 1]
```diff
@@ -63,11 +73,18 @@ public void start(String dorisHome) {
...
         properties.put("spring.http.encoding.enabled", true);
         properties.put("spring.http.encoding.force", true);
-        properties.put("spring.servlet.multipart.max-file-size", this.maxFileSize);
-        properties.put("spring.servlet.multipart.max-request-size", this.maxRequestSize);
+        //enable jetty config
+        properties.put("server.jetty.acceptors", this.acceptors);
+        properties.put("server.jetty.max-http-post-size", this.maxHttpPostSize);
+        properties.put("server.jetty.selectors", this.selectors);
+        //Worker thread pool is not set by default, set according to your needs
+        if(this.workers <= 0) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/httpv2/HttpServer.java:81]:
```suggestion
        if(this.workers > 0) {
```

File: fe/fe-core/src/main/java/org/apache/doris/common/Config.java [hunk 2]
```diff
@@ -326,10 +326,26 @@
...
+     */
+    @ConfField public static int jetty_server_acceptors = 2;
+    @ConfField public static int jetty_server_selectors = 4;
+    @ConfField public static int jetty_server_workers = 0;
+    /**
+     * jetty Maximum number of bytes in put or post method,default:2G
      */
-    @ConfField public static String http_max_file_size = "100MB";
-    @ConfField public static String http_max_request_size = "100MB";
+    @ConfField public static int jetty_server_max_http_post_size = 2 * 1024 * 1024 * 1024;
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/common/Config.java:348]: `jetty_server_max_http_post_size` is only for UploadAction, which is used for user to upload demo data from Web UI. So the file size should be small. I think the default 100MB is enough, otherwise, the user may upload large file to occupy the FE node's disk.

Comment (hf200012) [reply fe/fe-core/src/main/java/org/apache/doris/common/Config.java:348]: ok

**Review by morningman — APPROVED** [review]
LGTM
