### PR TITLE
FE ssl certificates are of various formats #26039

### LINKED ISSUE #26039: [Bug] FE ssl certificates are of various formats
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

FE ssl certificate type is PKCS12 not allow user to defined various type

### What You Expected?

Allow user to define other ssl certificate  encrypt type

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LuGuangming**
## Proposed changes
FE ssl certificates support other type set param ssl_trust_store_type, default is PKCS12
Issue Number: close #26039

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-common/src/main/java/org/apache/doris/common/Config.java [hunk 1]
```diff
@@ -1918,6 +1918,12 @@ public class Config extends ConfigBase {
     @ConfField(mutable = false, masterOnly = false)
     public static boolean ssl_force_client_auth = false;
 
+    /**
+     * ssl connection needs to authenticate client's certificate store type.
+     */
+    @ConfField(mutable = false, masterOnly = false)
+    public static String ssl_trust_store_type = "PKCS12";
```
Comment (yiguolei) [inline fe/fe-common/src/main/java/org/apache/doris/common/Config.java:1925]: add document to explain this variable

Comment (LuGuangming) [reply fe/fe-common/src/main/java/org/apache/doris/common/Config.java:1925]: > add document to explain this variable
done

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by hf200012 — APPROVED** [review]
