### PR TITLE
[Bug](Vectorzed alter table)modify schema change cast validate

### LINKED ISSUE #11709: [Enhancement] Schema change behavior diff of row-based and vectorized
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

1. date format support:

```sql
CREATE TABLE s267d_modify_test_modify_varchar_to_date_wrong_format_db.s5292_modify_test_modify_varchar_to_date_wrong_format_tb ( k1 INT NOT NULL, k2 VARCHAR(4096) NOT NULL, k3 VARCHAR(4096) NOT NULL, v1 FLOAT SUM NOT NULL, v2 DECIMAL(20,7) SUM NOT NULL ) AGGREGATE KEY(k1,k2,k3) PARTITION BY RANGE(k1) ( PARTITION partition_a VALUES LESS THAN ("5"), PARTITION partition_b VALUES LESS THAN ("30"), PARTITION partition_c VALUES LESS THAN ("100"), PARTITION partition_d VALUES LESS THAN ("500"), PARTITION partition_e VALUES LESS THAN ("1000"), PARTITION partition_f VALUES LESS THAN ("2000"), PARTITION partition_g VALUES LESS THAN MAXVALUE ) DISTRIBUTED BY HASH(k1, k2) BUCKETS 13

insert into s5292_modify_test_modify_varchar_to_date_wrong_format_tb values(1,"1","202001011200",1,1)

ALTER TABLE s267d_modify_test_modify_varchar_to_date_wrong_format_db.s5292_modify_test_modify_varchar_to_date_wrong_format_tb MODIFY COLUMN k3 date

select 1, 1, cast("2020-01-01" as date), 1, 1.0
```

2. interger cast overflow:

```sql
CREATE TABLE s9f1f_e_modify_test_modify_varchar_to_number_overflow_db.sd013_e_modify_test_modify_varchar_to_number_overflow_tb ( k1 INT NOT NULL, k2 VARCHAR(4096) NOT NULL, k3 VARCHAR(4096) NOT NULL, k4 VARCHAR(4096) NOT NULL, k5 VARCHAR(4096) NOT NULL, k6 VARCHAR(4096) NOT NULL, k7 VARCHAR(4096) NOT NULL, k8 VARCHAR(4096) NOT NULL, k9 VARCHAR(4096) NOT NULL, v1 FLOAT SUM NOT NULL, v2 DECIMAL(20,7) SUM NOT NULL ) AGGREGATE KEY(k1,k2,k3,k4,k5,k6,k7,k8,k9) PARTITION BY RANGE(k1) ( PARTITION partition_a VALUES LESS THAN ("5"), PARTITION partition_b VALUES LESS THAN ("30"), PARTITION partition_c VALUES LESS THAN ("100"), PARTITION partition_d VALUES LESS THAN ("500"), PARTITION partition_e VALUES LESS THAN ("1000"), PARTITION partition_f VALUES LESS THAN ("2000"), PARTITION partition_g VALUES LESS THAN MAXVALUE ) DISTRIBUTED BY HASH(k1, k2) BUCKETS 3

insert into sd013_e_modify_test_modify_varchar_to_number_overflow_tb values(1, "1", "1", "1", "2147483648", "1", "1", "1", "1", 1, 1)

ALTER TABLE s9f1f_e_modify_test_modify_varchar_to_number_overflow_db.sd013_e_modify_test_modify_varchar_to_number_overflow_tb MODIFY COLUMN k5 INT

```

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #11709

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: regression-test/suites/schema_change/test_number_overflow.groovy [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+        def process = showConfigCommand.toString().execute()
+        int code = process.waitFor()
+        String err = IOGroovyMethods.getText(new BufferedReader(new InputStreamReader(process.getErrorStream())));
+        String out = process.getText()
+        logger.info("Show config: code=" + code + ", out=" + out + ", err=" + err)
+        assertEquals(code, 0)
+        def configList = parseJson(out.trim())
+        assert configList instanceof List
+
+        boolean disableAutoCompaction = true
```
Comment (Gabriel39) [inline regression-test/suites/schema_change/test_number_overflow.groovy:55]: `disableAutoCompaction` is not used.

File: regression-test/suites/schema_change/test_number_overflow.groovy [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+            } else {
+                sleep(2000)
+                if (max_try_time < 1){
+                        assertEquals(3,4)
+                }
+            }
+        }
+
+    } finally {
+        //try_sql("DROP TABLE IF EXISTS ${tableName}")
```
Comment (Gabriel39) [inline regression-test/suites/schema_change/test_number_overflow.groovy:92]:
```suggestion
        try_sql("DROP TABLE IF EXISTS test_number_overflow")
```

**Review by yiguolei — APPROVED** [review]
LGTM
