### PR TITLE
[MySQL Compatibility 1/4][Bug] Fix bug that set sql_mode with concat() function failed

### LINKED ISSUE #4358: [Bug] set sql_mode with concat() function failed.
**Describe the bug**

`set sql_mode = concat(@@sql_mode, "STRICT_TRANS_TABLES");`
This stmt should work, but it failed with error:

` Set statement does't support computing expr:concat(@@sql_mode, 'STRICT_TRANS_TABLES')`

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Support `set sql_mode = concat(@@sql_mode, "STRICT_TRANS_TABLES");`

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have create an issue on (Fix #4358), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/ExpressionFunctions.java [hunk 1]
```diff
@@ -96,6 +98,14 @@ public Expr evalExpr(Expr constExpr) {
                     return constExpr;
                 }
             }
+        } else if (constExpr instanceof SysVariableDesc) {
+            try {
+                VariableMgr.fillValue(ConnectContext.get().getSessionVariable(), (SysVariableDesc) constExpr);
+                return ((SysVariableDesc) constExpr).getLiteralExpr();
+            } catch (AnalysisException e) {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/ExpressionFunctions.java:105]: Why not just throw the exception to the user?

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/ExpressionFunctions.java:105]: This method is used for constant folding rules. If it fails, it will directly return to the original expression, and other processes will handle this error.

**Review by kangkaisen — APPROVED** [review]
+1

**Comment by fengyunhe** [comment]
BUT still failed for this (when I use SAP DataService to connect Doris ):

`SET SESSION sql_mode = (SELECT CONCAT(@@sql_mode,',ANSI_QUOTES'));`
