### PR TITLE
[fix](planner)Fix colocate query failed

### LINKED ISSUE #16458: [Bug] Query same tablet but hits different rollup should not use colocate join
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Query failed when join same table with different rollup.

### What You Expected?

Create table A;
Add rollup A_1 for A;
Add rollup A_2 for A;
select
(select xx from A) t1
join
(select xx from A) t2
Make t1 and t2 hits different rollup, query may failed when rollup A_1 and A_2 not locates in the same host.

### How to Reproduce?

_No response_

### Anything Else?

No

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangbo**
# Proposed changes

Issue Number: close #16458

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wangbo** [comment]
I will add regression test later.

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.31 seconds
 load time: 474 seconds
 storage size: 17170930960 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230207043049_clickbench_pr_91164.html

**Review by morrySnow — DISMISSED** [review]

File: fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java [hunk 1]
```diff
@@ -557,6 +557,12 @@ private boolean dataDistributionMatchEqPredicate(List<BinaryPredicate> eqJoinPre
                 cannotReason.add(DistributedPlanColocateRule.COLOCATE_GROUP_IS_NOT_STABLE);
                 return false;
             }
+        } else {
+            // query same table but hit different rollup, colocate join should be disable
+            if (leftRoot.getSelectedIndexId() != rightRoot.getSelectedIndexId()) {
+                cannotReason.add(DistributedPlanColocateRule.QUERY_SAME_TABLE_BUT_HIT_DIFF_ROLLUP);
+                return false;
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java:564]: if table is a colocate table, it could do colocate join with itself when group is stable

**Comment by wangbo** [comment]
UT DistributedPlannerTest.testBroadcastJoinCostThreshold is fixed.
Add more reg test.

File: fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java [hunk 2]
```diff
@@ -321,6 +321,10 @@ public void useBaseIndexId() {
         this.selectedIndexId = olapTable.getBaseIndexId();
     }
 
+    public long getSelectedIndexId() {
```
Comment (cambyzju) [inline fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java:324]: add `@Override` ?

Comment (wangbo) [reply fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java:324]: ```getSelectedIndexId``` only exists in ```OlapScanNode```.

**Review by yiguolei — APPROVED** [review]
LGTM
