### PR TITLE
Fix duplicate code for PropertyAnalyzer.analyzeDataProperty()

### LINKED ISSUE #10189: [Feature] Fix duplicate code for PropertyAnalyzer.analyzeDataProperty()
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

PropertyAnalyzer.analyzeDataProperty(Map<String, String> properties, final DataProperty oldDataProperty) has something not suitable.
Parameter oldDataProperty is the old DataProperty, properties should be used to replace some of its members.
If properties has no some members, old ones need to be left, but not be set to default value.
Function modifyPartitionsProperty() uses analyzeDataProperty(), but create a new DataProperty again, it is duplicate.

### Use case

Remove duplicate code from modifyPartitionsProperty() and realize them in analyzeDataProperty().

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #10189

## Problem Summary:

PropertyAnalyzer.analyzeDataProperty(Map<String, String> properties, final DataProperty oldDataProperty) has something not suitable.
Parameter oldDataProperty is the old DataProperty, properties should be used to replace some of its members.
If properties has no some members, old ones need to be left, but not be set to default value.
Function modifyPartitionsProperty() uses analyzeDataProperty(), but create a new DataProperty again, it is duplicate.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java [hunk 1]
```diff
@@ -109,16 +109,23 @@ public class PropertyAnalyzer {
...
         }
 
-        TStorageMedium storageMedium = null;
-        long cooldownTimeStamp = DataProperty.MAX_COOLDOWN_TIME_MS;
-        String remoteStorageResourceName = "";
-        long remoteCooldownTimeStamp = DataProperty.MAX_COOLDOWN_TIME_MS;
+        TStorageMedium storageMedium = oldDataProperty.getStorageMedium();
+        long cooldownTimeStamp = oldDataProperty.getCooldownTimeMs();
+        String remoteStorageResourceName = oldDataProperty.getRemoteStorageResourceName();
+        long remoteCooldownTimeStamp = oldDataProperty.getRemoteCooldownTimeMs();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java:128]: Should we change the logic in line 161?
```
if (!hasCooldown && !hasMedium) {
    return oldDataProperty;
}
```

**Review by morningman — DISMISSED** [review]
LGTM, and please rebase the code to fix the conflict

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM
