### PR TITLE
[Compile][Refactor] fix some warning in gcc higher than 7

### LINKED ISSUE #5546: [Compile] Some compile warning in gcc > 8
**Describe the bug**
clearing an object of type 'struct ' with no trivial copy-assignment; use assignment or value-initialization instead

class should convert to pod type:
```
decimal12_t
uint24_t
doris::OLAPIndexFixedHeader
```

**Expected behavior**
no warning here

**Additional context**

### PR DESCRIPTION
**Pull request by stdpain**
make decimal12_t as a pod type

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [x] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5546 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/decimal12.h [hunk 1]
```diff
@@ -156,6 +139,8 @@ struct decimal12_t {
     int32_t fraction;
 } __attribute__((packed));
 
+static_assert(std::is_trivial<decimal12_t>::value, "decimal12_t should be a pod type");
```
Comment (yangzhg) [inline be/src/olap/decimal12.h:142]: use POD

**Review by yangzhg — APPROVED** [review]
LGTM
