### PR TITLE
[Bug] Fix bucket shuffle bug when left table is without any data

### LINKED ISSUE #5964: [Bug] When two tables are without any data, bucket shuffle will cause query timeout
**Describe the bug**
**Bucket shuffle join** is a algorithm of joining two tables.  Left table is distrubuted by a column. Right table sends the data to the left table for joining operation. It reduces the network cost. But when two table is withou any data. Bucket shuffle join will query timeout.

**To Reproduce**
1. create two table:

CREATE TABLE `dynamic_partition2` (
  `k1` bigint(20) NULL COMMENT "",
  `k2` int(11) NULL COMMENT "",
  `k3` smallint(6) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
(PARTITION p20201219 VALUES [("20201219"), ("20201220")),
PARTITION p20201220 VALUES [("20201220"), ("20201221")),
PARTITION p20201221 VALUES [("20201221"), ("20201222")),
PARTITION p20201222 VALUES [("20201222"), ("20201223")),
PARTITION p20201223 VALUES [("20201223"), ("20201224")),
PARTITION p20201224 VALUES [("20201224"), ("20201225")),
PARTITION p20201225 VALUES [("20201225"), ("20201226")),
PARTITION p20201226 VALUES [("20201226"), ("20201227")),
PARTITION p20201227 VALUES [("20201227"), ("20201228")),
PARTITION p20201228 VALUES [("20201228"), ("20201229")),
PARTITION p20201229 VALUES [("20201229"), ("20201230")),
PARTITION p20201230 VALUES [("20201230"), ("20201231")),
PARTITION p20201231 VALUES [("20201231"), ("20210101")))
DISTRIBUTED BY HASH(`k2`) BUCKETS 32
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "group1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-6",
"dynamic_partition.end" = "6",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "1",
"dynamic_partition.buckets" = "32",
"in_memory" = "false",
"storage_format" = "V2"
);

CREATE TABLE `dynamic_partition_bucket2` (
  `k1` bigint(20) NULL COMMENT "",
  `k2` int(11) NULL COMMENT "",
  `k3` smallint(6) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
(PARTITION p20201219 VALUES [("20201219"), ("20201220")),
PARTITION p20201220 VALUES [("20201220"), ("20201221")),
PARTITION p20201221 VALUES [("20201221"), ("20201222")),
PARTITION p20201222 VALUES [("20201222"), ("20201223")),
PARTITION p20201223 VALUES [("20201223"), ("20201224")),
PARTITION p20201224 VALUES [("20201224"), ("20201225")),
PARTITION p20201225 VALUES [("20201225"), ("20201226")),
PARTITION p20201226 VALUES [("20201226"), ("20201227")),
PARTITION p20201227 VALUES [("20201227"), ("20201228")),
PARTITION p20201228 VALUES [("20201228"), ("20201229")),
PARTITION p20201229 VALUES [("20201229"), ("20201230")),
PARTITION p20201230 VALUES [("20201230"), ("20201231")),
PARTITION p20201231 VALUES [("20201231"), ("20210101")))
DISTRIBUTED BY HASH(`k2`, `k3`) BUCKETS 32
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "group3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-6",
"dynamic_partition.end" = "6",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "1",
"dynamic_partition.buckets" = "32",
"in_memory" = "false",
"storage_format" = "V2"
);

2. do not insert any data into two tables
3. enable bucket shuffle join
`set enable_bucket_shuffle_join=true`
4. execute a sql
select * from dynamic_partition2 a join dynamic_partition_bucket2 b on a.k2 = b.k2 where a.k1=20201218;

5. see the error
2021-06-03 16-48-29屏幕截图

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by xinghuayu007**
## Proposed changes

For #5964.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix  #5964) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java [hunk 1]
```diff
@@ -837,7 +837,10 @@ private void computeFragmentExecParams() throws Exception {
                 int bucketSeq = 0;
                 int bucketNum = bucketShuffleJoinController.getFragmentBucketNum(destFragment.getFragmentId());
                 TNetworkAddress dummyServer = new TNetworkAddress("0.0.0.0", 0);
-
+                if (destParams.instanceExecParams.size() == 1 && destParams.instanceExecParams.get(0).bucketSeqSet.isEmpty()) {
```
Comment (HappenLee) [inline fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java:840]: Pleaase add some comment here，It means left table is empty(). To correct bucket shuffle join, so need give a fake bucekt num to help left instance close() right. Thank you !

File: fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java [hunk 2]
```diff
@@ -837,7 +837,12 @@ private void computeFragmentExecParams() throws Exception {
                 int bucketSeq = 0;
                 int bucketNum = bucketShuffleJoinController.getFragmentBucketNum(destFragment.getFragmentId());
                 TNetworkAddress dummyServer = new TNetworkAddress("0.0.0.0", 0);
-
+		        // when left table is empty, it's bucketset is empty.
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java:840]: Pay attention to indentation

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
