### PR TITLE
[Bug](catalog) Fix fetching information_schema table timed out(#17692)

### LINKED ISSUE #17692: [Bug] 如果有联不通的catalog，information_schema里面的一些表就查不了了
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2

### What's Wrong?

如果有联不通的catalog，information_schema里面的一些表就查不了了。
企业微信截图_9f287425-76ff-45ca-b7bc-7918b51351db

### What You Expected?

可以对 information_schema里面的一些表进行正常查询，哪怕有无效的 catalog 信息

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yuxuan-luo**
# Proposed changes

Issue Number: close #17692 

## Problem summary

Describe your changes.

## Checklist(Required)

* [] Does it affect the original behavior
* [] Has unit tests been added
* [] Has document been added or modified
* [] Does it need to update dependencies
* [X] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yuxuan-luo** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java [hunk 1]
```diff
@@ -240,6 +240,20 @@ public List<String> getDbNames() {
         return listDatabaseNames(null);
     }
 
+    @Override
+    public List<String> getDbNamesOrEmpty() {
+        if (initialized) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java:245]: it is strange because in `getDbNames()`, it will try to initialize it and then get databases.
if we add `if (initialized)` here, it will not do initialization anymore.

Comment (yuxuan-luo) [reply fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java:245]: > 

Because we don't want to initialize when querying the information_schema table, an uninitialized catalog can easily cause the query to time out

**Comment by yuxuan-luo** [comment]
run buildall

**Comment by yuxuan-luo** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM
