### PR TITLE
[Bug][Vectorized] fix vcast expr input wrong row number

### LINKED ISSUE #9519: [Bug][Vectorized] fix vcast expr input wrong row number
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

`block.rows()` just return the first column's row number, sometime the block‘s column have diffrent row number with other column, then cast expr will get wrong result.

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #9519

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/core/block.cpp [hunk 1]
```diff
@@ -151,6 +151,13 @@ void Block::insert(ColumnWithTypeAndName&& elem) {
     data.emplace_back(std::move(elem));
 }
 
+void Block::insert_and_resize(ColumnWithTypeAndName&& elem) {
+    index_by_name.emplace(elem.name, data.size());
+    // usualy elem.column always is const column, so we just clone it.
+    elem.column = elem.column->clone_resized(std::max(rows(), size_t(1)));
```
Comment (HappenLee) [inline be/src/vec/core/block.cpp:157]: 1. `clone_resized` will cause some data loss
2. `clone_resized` will cause the `memcpy, new, delete`. 
I don't think it should be a member function

File: be/src/vec/exprs/vexpr.h [hunk 2]
```diff
@@ -33,10 +33,19 @@ namespace vectorized {
 
 class VExpr {
 public:
+    // resize inserted param column to make sure column size equal to block.rows()
+    // and return param column index
+    static size_t insert_param(Block* block, ColumnWithTypeAndName&& elem) {
+        // usualy elem.column always is const column, so we just clone it.
+        elem.column = elem.column->clone_resized(std::max(block->rows(), size_t(1)));
```
Comment (HappenLee) [inline be/src/vec/exprs/vexpr.h:40]: not do `std::max` here

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM
