### PR TITLE
[fix](meta) show partitions with Limit for external HMS tables (27835)

### LINKED ISSUE #27834: [Enhancement](datalake)(meta) Limit/Where/Orderby doesnt work for SHOW PARITIONS on hive tables
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Show partitions for HMS catalog doesnt supports Limit / Where / Order by, but also doesnt gives error when specified incorrectly.

### Solution

This enhancement shall extend existing logic to include 

1. Limit/Offset
2. Where [partition name only] [equal operator and like operator]
3. Order by [partition name only]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes
**This enhancement shall extend existing logic for SHOW PARTITIONS FROM <HMS tables> to include: -**
- Limit/Offset
- Where [partition name only] [equal operator and like operator]
- Order by [partition name only]

Issue Number: close #27834

**Sample output:**
ShowPartitions

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Comment by morningman** [comment]
Could you please add regression test cases for this feature?
you can refer to: https://doris.apache.org/community/developer-guide/regression-testing#e2e-test-with-external-data-sources to start to hive docker, and write test cases like:

regression-test/suites/external_table_p0/hive/test_prepare_hive_data_in_case.groovy

**Comment by Nitin-Kashyap** [comment]
> Could you please add regression test cases for this feature? you can refer to: https://doris.apache.org/community/developer-guide/regression-testing#e2e-test-with-external-data-sources to start to hive docker, and write test cases like:
> 
> regression-test/suites/external_table_p0/hive/test_prepare_hive_data_in_case.groovy

fixed

**Review by morningman — APPROVED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java [hunk 1]
```diff
@@ -1691,28 +1692,53 @@ private void handleShowMaxComputeTablePartitions(ShowPartitionsStmt showStmt) {
...
         String dbName = ClusterNamespace.getNameFromFullName(showStmt.getTableName().getDb());
 
         List<String> partitionNames;
         LimitElement limit = showStmt.getLimitElement();
-        if (limit != null && limit.hasLimit()) {
-            // only limit is valid on Hive
+        Map<String, Expr> filterMap = showStmt.getFilterMap();
+        List<OrderByPair> orderByPairs = showStmt.getOrderByPairs();
+
+        if (limit != null && limit.hasLimit() && limit.getOffset() == 0
```
Comment (wsjz) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java:1705]: I wonder if we can throw an exception if offset > 0

File: fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java [hunk 2]
```diff
@@ -1691,28 +1692,53 @@ private void handleShowMaxComputeTablePartitions(ShowPartitionsStmt showStmt) {
...
+            rows.sort(Comparator.comparing(x -> x.get(0)));
+        }
+
+        if (limit != null && limit.hasLimit()) {
+            int beginIndex = (int) limit.getOffset();
+            int endIndex = (int) (beginIndex + limit.getLimit());
+            if (endIndex > rows.size()) {
+                endIndex = rows.size();
+            }
+            rows = rows.subList(beginIndex, endIndex);
```
Comment (wsjz) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java:1740]: The above limit has already been limited, and if you limit it again, the final limit will be less than expected. For example, if offset is 5 and limit is 10, then 10 rows will be extracted from hive according to your logic, and the result obtained by sublist will only be 5 rows starting from 5. But we need 10 rows

File: fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java [hunk 3]
```diff
@@ -1691,28 +1692,53 @@ private void handleShowMaxComputeTablePartitions(ShowPartitionsStmt showStmt) {
...
-            // only limit is valid on Hive
+        Map<String, Expr> filterMap = showStmt.getFilterMap();
+        List<OrderByPair> orderByPairs = showStmt.getOrderByPairs();
+
+        if (limit != null && limit.hasLimit() && limit.getOffset() == 0
+                && (orderByPairs == null || !orderByPairs.get(0).isDesc())) {
+            // hmsClient returns unordered partition list, hence if offset > 0 cannot pass limit
             partitionNames = catalog.getClient()
-                    .listPartitionNames(dbName, showStmt.getTableName().getTbl(), limit.getLimit());
+                .listPartitionNames(dbName, showStmt.getTableName().getTbl(), limit.getLimit());
```
Comment (wsjz) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java:1709]:
```suggestion
                .listPartitionNames(dbName, showStmt.getTableName().getTbl(), limit.getLimit() + limit.getOffset());
```

Comment (Nitin-Kashyap) [reply fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java:1709]: this will not have meaning given that **getOffset() == 0** checked above.

its done so because, hmsClient may return unordered result and with offset might not return meaningful output

File: fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java (hunk 2 above)
Comment (Nitin-Kashyap) [reply fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java:1740]: we dont limit when offset > 0

**Review by wsjz — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM
