### PR TITLE
fix concurrent synchorinzation problem in NodeChannel::try_send_batch

### LINKED ISSUE #8725: [Bug] be core dump at NodeChannel::try_send_batch
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev-1.0.0

### What's Wrong?

```
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007f2db1eff859 in __GI_abort () at abort.c:79
#6  0x000000000accdb1a in google::DumpStackTraceAndExit () at src/utilities.cc:160
#7  0x000000000acc5463 in google::LogMessage::Fail () at src/logging.cc:1650
#8  google::LogMessage::SendToLog (this=<optimized out>) at src/logging.cc:1607
#9  0x000000000acc596a in google::LogMessage::Flush (this=0x7f2c8bc91e68) at src/logging.cc:1476
#10 0x000000000acc91ff in google::LogMessageFatal::~LogMessageFatal (this=0x7f2c8bc91e68) at src/logging.cc:2226
#11 0x000000000ae3e9d1 in brpc::BaiduStreamingLogHandler (level=<optimized out>, filename=0xd8c613f "./google/protobuf/repeated_field.h", line=1323, 
    message=...) at /root/regression/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/brpc/global.cpp:308
#12 0x000000000afeecde in google::protobuf::internal::LogMessage::Finish() ()
#13 0x000000000b01cf22 in google::protobuf::RepeatedField<long>::Mutable(int) ()
#14 0x000000000b01dfc1 in google::protobuf::RepeatedField<long>::MergeFrom(google::protobuf::RepeatedField<long> const&) ()
#15 0x0000000005aa4905 in doris::PTabletWriterAddBatchRequest::MergeFrom (this=0x7f2c8bc92478, from=...)
    at /root/regression/incubator-doris/gensrc/build/gen_cpp/internal_service.pb.cc:4965
#16 0x0000000005aa50ad in doris::PTabletWriterAddBatchRequest::CopyFrom (this=0x7f2c8bc92478, from=...)
    at /root/regression/incubator-doris/gensrc/build/gen_cpp/internal_service.pb.cc:5011
#17 0x00000000064c1440 in doris::PTabletWriterAddBatchRequest::operator= (this=0x7f2c8bc92478, from=...)
    at /root/regression/incubator-doris/be/../gensrc/build/gen_cpp/internal_service.pb.h:1756
#18 0x00000000064b161a in std::pair<std::unique_ptr<doris::RowBatch, std::default_delete<doris::RowBatch> >, doris::PTabletWriterAddBatchRequest>::operator= (this=0x7f2c8bc92470, __p=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_pair.h:409
#19 0x00000000064894ef in doris::stream_load::NodeChannel::try_send_batch (this=0x618001216c90)
    at /root/regression/incubator-doris/be/src/exec/tablet_sink.cpp:465
#20 0x00000000064d6cdd in std::__invoke_impl<void, void (doris::stream_load::NodeChannel::*&)(), doris::stream_load::NodeChannel*&> (
    __f=@0x60300d508f20: (void (doris::stream_load::NodeChannel::*)(doris::stream_load::NodeChannel * const)) 0x6488d70 <doris::stream_load::NodeChannel::try_send_batch()>, __t=@0x60300d508f30: 0x618001216c90)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
#21 0x00000000064d6ba2 in std::__invoke<void (doris::stream_load::NodeChannel::*&)(), doris::stream_load::NodeChannel*&> (
    __fn=@0x60300d508f20: (void (doris::stream_load::NodeChannel::*)(doris::stream_load::NodeChannel * const)) 0x6488d70 <doris::stream_load::NodeChannel::try_send_batch()>, __args=@0x60300d508f30: 0x618001216c90)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
```

### What You Expected?

do not core dump

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dataroaring**
The patch fixes two problems.
1. Memory order problem accessing _last_patch_processed_finished and in_flight, actually _last_patch_processed_finished is redudant, so the patch removes it.
2. synchorization in join on cid.

Fix for https://github.com/apache/incubator-doris/issues/8725.

# Proposed changes

Issue Number: close #8725 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/tablet_sink.cpp [hunk 1]
```diff
@@ -458,8 +458,37 @@ int NodeChannel::try_send_and_fetch_status(RuntimeState* state,
...
+    // https://en.cppreference.com/w/cpp/atomic/memory_order
+    // Here we should cmp_exchange _last_patch_processed_finished before reading
+    // packet_in_flight because try_send_patch sets packet_in_flight before
+    // _last_patch_processed_finished.
+    // If we read _add_batch_closure before cmp_exchange _last_patch_processed_finished,
+    // then somting bad would happend. e.g.
+    // |----------------------------------------------------------------------------
+    // | Thread try_send_and_fetch_status  | Thread try_send_batch                  |
+    // |-----------------------------------------------------------------------------
+    // | read packet_in_flight false       | before seting packet_in_flight         |
```
Comment (morningman) [inline be/src/exec/tablet_sink.cpp:479]:
```suggestion
    // | read packet_in_flight false       | before setting packet_in_flight         |
```

Comment (morningman) [reply be/src/exec/tablet_sink.cpp:479]: So this may trigger `DCHECK(!_pending_batches.empty());` in `NodeChannel::try_send_batch`?

Comment (dataroaring) [reply be/src/exec/tablet_sink.cpp:479]: yep

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
please do not merge this patch, the patch brings other problems.

**Comment by dataroaring** [comment]
Please do not merge this patch, I have not tested it thoroughly.

**Review by morningman — APPROVED** [review]
LGTM
