### PR TITLE
Forbidden float column in short key

### LINKED ISSUE #3811: The be core when float column in short key
**Describe the bug**
If user create a table with the float column as the short key, the be will core during query.

The core log is following:
```
#0  0x00000000017cd4f5 in encode_ascending (this=<optimized out>, buf=0x7f7f78d11270, index_size=<optimized out>, value=0x4f57ba06) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/key_coder.h:54
54    /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/key_coder.h: No such file or directory.
(gdb) bt
#0  0x00000000017cd4f5 in encode_ascending (this=<optimized out>, buf=0x7f7f78d11270, index_size=<optimized out>, value=0x4f57ba06) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/key_coder.h:54
#1  encode_ascending (this=0x402243f0, this=0x402243f0, buf=0x7f7f78d11270, value=0x4f57ba06) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/field.h:247
#2  doris::encode_key<doris::RowCursor, true> (buf=buf@entry=0x7f7f78d11270, row=..., num_keys=<optimized out>) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/short_key_index.h:106
#3  0x00000000017cd8a7 in doris::segment_v2::SegmentWriter::append_row<doris::RowCursor> (this=0x2dc2efc0, row=...) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/rowset/segment_v2/segment_writer.cpp:93
#4  0x0000000001051b43 in doris::BetaRowsetWriter::_add_row<doris::RowCursor> (this=0x38652140, row=...) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/rowset/beta_rowset_writer.cpp:96
#5  0x00000000017a18ee in doris::RowBlockMerger::merge (this=this@entry=0x7f7f78d114a0, row_block_arr=..., rowset_writer=0x38652140, merged_rows=merged_rows@entry=0x7f7f78d11410) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/schema_change.cpp:624
#6  0x00000000017a4d07 in doris::SchemaChangeWithSorting::_internal_sorting (this=this@entry=0x541a2540, row_block_arr=..., version=..., version_hash=version_hash@entry=644415376492288932, new_tablet=..., new_rowset_type=new_rowset_type@entry=doris::BETA_ROWSET,
    segments_overlap=doris::NONOVERLAPPING, rowset=0x7f7f78d11640) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/schema_change.cpp:1163
#7  0x00000000017a6122 in doris::SchemaChangeWithSorting::process (this=0x541a2540, rowset_reader=..., new_rowset_writer=0x38653180, new_tablet=..., base_tablet=...) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/schema_change.cpp:1052
#8  0x00000000017a75d6 in doris::SchemaChangeHandler::_convert_historical_rowsets (sc_params=...) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/schema_change.cpp:1717
#9  0x00000000017aa809 in doris::SchemaChangeHandler::_do_process_alter_tablet_v2 (this=this@entry=0x7f7f78d11ba0, request=...) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/schema_change.cpp:1387
#10 0x00000000017ab8b6 in doris::SchemaChangeHandler::process_alter_tablet_v2 (this=this@entry=0x7f7f78d11ba0, request=...) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/schema_change.cpp:1216
#11 0x00000000017e7cd4 in doris::EngineAlterTabletTask::execute (this=0x7f7f78d11e00) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/task/engine_alter_tablet_task.cpp:39
#12 0x0000000000ea7711 in doris::StorageEngine::execute_task (this=0x538a780, task=task@entry=0x7f7f78d11e00) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/olap/storage_engine.cpp:909
#13 0x00000000015975e1 in doris::TaskWorkerPool::_alter_tablet (this=this@entry=0x6dd5d40, worker_pool_this=worker_pool_this@entry=0x6dd5d40, agent_task_req=..., signature=signature@entry=193750, task_type=task_type@entry=doris::TTaskType::ALTER,
    finish_task_request=finish_task_request@entry=0x7f7f78d11ed0) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/agent/task_worker_pool.cpp:514
#14 0x00000000015980a9 in doris::TaskWorkerPool::_alter_tablet_worker_thread_callback (arg_this=0x6dd5d40) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/agent/task_worker_pool.cpp:466
#15 0x00007f7ffe8651c3 in start_thread () from /opt/compiler/gcc-4.8.2/lib64/libpthread.so.0
#16 0x00007f7ffe29412d in clone () from /opt/compiler/gcc-4.8.2/lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by EmmyMiao87**
When the user does not specify the key column, doris will automatically supplement the key column.
However, doris does not support float or double as the key column, so when adding the key column, doris should avoid setting those column as the key column.

The CreateMaterailizedView, AddRollup and CreateDuplicateTable need to forbidden float column in short key.
If the float column is directly encountered during the supplement process, the subsequent columns are all value columns.
If the first column is float or double, Doris will throw the exception.

Fixed #3811

Change-Id: Ib66d9355acefcd8f281906bcb7b4dd684319ff08

### CODE REVIEW

**Comment by chaoyli** [comment]
Create table will forbidden float/double

File: fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java [hunk 1]
```diff
@@ -235,6 +236,9 @@ private void analyzeOrderByClause() throws AnalysisException {
                     if (mvColumnItem.getAggregationType() != null) {
                         break;
                     }
+                    if (mvColumnItem.getType().isFloatingPointType()) {
+                        throw new AnalysisException("Float or double can not used as a key, use decimal instead.");
```
Comment (morningman) [inline fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java:240]:
```suggestion
                        throw new AnalysisException("Float or double can not used as a sort key, use decimal instead.");
```

File: fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java [hunk 2]
```diff
@@ -255,10 +259,15 @@ private void analyzeOrderByClause() throws AnalysisException {
                 MVColumnItem mvColumnItem = mvColumnItemList.get(i);
                 Expr resultColumn = selectStmt.getResultExprs().get(i);
                 keyStorageLayoutBytes += resultColumn.getType().getStorageLayoutBytes();
-                if ((i + 1) <= FeConstants.shortkey_max_column_count
-                        || keyStorageLayoutBytes < FeConstants.shortkey_maxsize_bytes) {
+                if ((!mvColumnItem.getType().isFloatingPointType())
```
Comment (morningman) [inline fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java:262]: We should be break if we met a floating point type column. The following case will get wrong result in your logic:

`k1 int, k2 float, k3 int`

**Review by morningman — CHANGES_REQUESTED** [review]

File: fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java (hunk 2 above)
Comment (EmmyMiao87) [reply fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java:262]: Why?

**Comment by EmmyMiao87** [comment]
> Create table will forbidden float/double

Already forbidden

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM
