### PR TITLE
[Bug][SQL] Fix bug that query failed when SQL contains Union and Colocate join

### LINKED ISSUE #4841: [Bug][SQL] query failed with Union and Colocate Join
**Describe the bug**
Query failed with error like:
`failed to get tablet. tablet_id=26846, with schema_hash=398972982, reason=tablet does not exist`

SQL looks like:

`select a join b union select c join d`;

And both a/b and c/d are colocate join.

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

SQL like:
`select a join b union select c join d`;

if both a/b and c/d are colocate join, the query may failed with error like:

`failed to get tablet. tablet_id=26846, with schema_hash=398972982, reason=tablet does not exist`

This is because when assigning exec host for fragment, the planner failed to distinguish which scan nodes
belong to the certain fragment. So it may choose the wrong host for scan range.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [] I have create an issue on (Fix #4841), and have described the bug/feature there in detail

### CODE REVIEW

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java [hunk 1]
```diff
@@ -1140,17 +1141,26 @@ private long getScanRangeLength(final TScanRange scanRange) {
 
     private void computeColocateJoinInstanceParam(PlanFragmentId fragmentId, int parallelExecInstanceNum, FragmentExecParams params) {
         Map<Integer, TNetworkAddress> bucketSeqToAddress = fragmentIdToSeqToAddressMap.get(fragmentId);
```
Comment (HappenLee) [inline fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java:1143]: Maybe `bucketSeqToScanRang` should be a map like `fragmentIdToSeqToAddressMap` to solve this problem is a
better understanding  way？

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java:1143]: I will leave it when refactoring them.
