### PR TITLE
Fix wrong query result when column value is Null

### LINKED ISSUE #343: Critical bug: query result is wrong when Column is Null
**Describe the bug**
The query result is wrong.

**To Reproduce**
1 create table
```
CREATE TABLE `test_wrong_result` (
  `a` int(11),
  `b` tinyint(4),
  `c` tinyint(4),
  `d` bigint(20)
) ENGINE=OLAP
DUPLICATE KEY(`a`, `b`, `c`,  `d`)
DISTRIBUTED BY HASH(`d`) BUCKETS 10;
```

2 load the data
```
3001	3	\N	1090050
```

3 query
```
SELECT c FROM test_wrong_result WHERE a = 3001 and b = 3 and d = 1090050;
```

**Expected behavior**
The query result should be NULL, not Empty set.

### PR DESCRIPTION
**Pull request by kangkaisen**
Fix [343](https://github.com/apache/incubator-doris/issues/343)

The root cause for [343](https://github.com/apache/incubator-doris/issues/343) is ScanKey is wrong.
```
I1122 18:12:51.577086 21470 olap_scan_node.cpp:380] BuildScanKey
I1122 18:12:51.579259 21470 olap_common.h:200] ScanKeys:
I1122 18:12:51.579268 21470 olap_common.h:203] ScanKey=[3001,3,-128,1090050 : 3001,3,-128,1090050]
I1122 18:12:51.579274 21470 olap_common.h:203] ScanKey=[3001,3,-127,1090050 : 3001,3,-127,1090050]
I1122 18:12:51.579279 21470 olap_common.h:203] ScanKey=[3001,3,-126,1090050 : 3001,3,-126,1090050]


I1122 18:12:51.580550 21470 olap_common.h:203] ScanKey=[3001,3,126,1090050 : 3001,3,126,1090050]
I1122 18:12:51.580555 21470 olap_common.h:203] ScanKey=[3001,3,127,1090050 : 3001,3,127,1090050]
```
So we should add null to ScanKey when ColumnValueRange convert_to_fixed_value.

I will add a test case to olap_common_test  tomorrow

### CODE REVIEW

File: be/src/exec/olap_common.h [hunk 1]
```diff
@@ -662,6 +662,8 @@ Status OlapScanKeys::extend_scan_key(ColumnValueRange<T>& range) {
         return Status::OK;
     }
 
+    bool _has_converted = false;
```
Comment (imay) [inline be/src/exec/olap_common.h]: Only member variable's name starts with '_', so change it to `has_converted`

**Review by imay — CHANGES_REQUESTED** [review]
Good patch first.

```
CREATE TABLE `test_wrong_result` (
  `a` int(11),
  `b` tinyint(4),
  `c` tinyint(4),
  `d` bigint(20)
) ENGINE=OLAP
DUPLICATE KEY(`a`, `b`, `c`,  `d`)
DISTRIBUTED BY HASH(`d`) BUCKETS 10;
```

```
SELECT c FROM test_wrong_result WHERE a = 3001 and b = 3 and d = 1090050;
```

There is something you miss. For your example query, there is no range filter for column `c`, your patch can work in right way. If there is filter for column `c` like `c > 1` or `c <=1`, your patch works in a  wrong way. Because when column `c` has any range filter,  rows whose `c` column's value is `null` would not to be selected. 

So, before you assign `has_converted` to true, you have to check more conditions.

File: be/src/exec/olap_common.h (hunk 1 above)
Comment (kangkaisen) [reply be/src/exec/olap_common.h]: OK

**Comment by kangkaisen** [comment]
@imay I think if there is filter for column c like c > 1 or c <=1, which will mean c could not be null.

**Comment by chaoyli** [comment]
@kangkaisen I think you are right. When c has predicate, it should not scan NULL data in SQL semantics.

**Comment by kangkaisen** [comment]
When I try running the olap_common_test, there are a lot of compiling errors. I found recently some commits didn't update olap_common_test at the same time.

So I think we should start a new issue to fix olap_common_test compiling error, and then I will add test cases to olap_common_test.

**Comment by kangkaisen** [comment]
This is the olap_common_test issue: [346](https://github.com/apache/incubator-doris/issues/346)

**Comment by imay** [comment]
> @imay I think if there is filter for column c like c > 1 or c <=1, which will mean c could not be null.

@kangkaisen Yes, c could not be null, however your change will add null to scan_keys

**Comment by kangkaisen** [comment]
> > @imay I think if there is filter for column c like c > 1 or c <=1, which will mean c could not be null.
> 
> @kangkaisen Yes, c could not be null, however your change will add null to scan_keys

@imay Hi, I think this patch won't add null to C column scan_keys.  If c = 1 or c > 1, the code won't goto this branch
```
    } else {
        if (range.is_fixed_value_convertible() && _is_convertible) {
            if (_begin_scan_keys.empty()) {
                if (range.get_convertible_fixed_value_size() < config::doris_max_scan_key_num) {
                    range.convert_to_fixed_value();
                    has_converted = true;
                }
            } else {
                if (range.get_convertible_fixed_value_size() * _begin_scan_keys.size()
                        < config::doris_max_scan_key_num) {
                    range.convert_to_fixed_value();
                    has_converted = true;
                }
            }
        }
```

**Comment by imay** [comment]
> > > @imay I think if there is filter for column c like c > 1 or c <=1, which will mean c could not be null.
> > 
> > 
> > @kangkaisen Yes, c could not be null, however your change will add null to scan_keys
> 
> @imay Hi, I think this patch won't add null to C column scan_keys. If c = 1 or c > 1, the code won't goto this branch
> 
> ```
>     } else {
>         if (range.is_fixed_value_convertible() && _is_convertible) {
>             if (_begin_scan_keys.empty()) {
>                 if (range.get_convertible_fixed_value_size() < config::doris_max_scan_key_num) {
>                     range.convert_to_fixed_value();
>                     has_converted = true;
>                 }
>             } else {
>                 if (range.get_convertible_fixed_value_size() * _begin_scan_keys.size()
>                         < config::doris_max_scan_key_num) {
>                     range.convert_to_fixed_value();
>                     has_converted = true;
>                 }
>             }
>         }
> ```

If `c < 0` and its `ColumnValueRange.is_fixed_value_range` will return false, then this branch will be executed

**Comment by kangkaisen** [comment]
@imay I see. I am sorry. I will update the commit.

**Comment by kangkaisen** [comment]
Update the commit.

**Review by imay — APPROVED** [review]
lgtm
