### PR TITLE
[test](storage)duplicate model storage layer regression-test

### LINKED ISSUE #9284: [Enhancement] Add regression test for storage later
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Add regression test for storage later
Test duplicate table.
### Solution

Add regression test for storage later

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangbo**
# Proposed changes

Issue Number: close #9284

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_int.groovy [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+    sql "insert into ${table1} values(1,2,3,4)"
+    sql "insert into ${table1} values(13,21,22,16)"
+    sql "insert into ${table1} values(13,14,15,16)"
+    sql "insert into ${table1} values(17,18,19,20)"
+    sql "insert into ${table1} values(1,2,3,4)"
+    sql "insert into ${table1} values(13,21,22,16)"
+    sql "insert into ${table1} values(13,14,15,16)"
+    sql "insert into ${table1} values(17,18,19,20)"
+    sql "insert into ${table1} values(5,6,7,8)"
+    sql "insert into ${table1} values(5,6,7,8)"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_int.groovy:52]: suggest insert into multiple rows in a sql

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_int_nullable.groovy [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+    sql "insert into ${table1} values(13,21,22,16)"
+    sql "insert into ${table1} values(13,14,15,16)"
+    sql "insert into ${table1} values(13,21,22,16)"
+    sql "insert into ${table1} values(17,18,19,20)"
+    sql "insert into ${table1} values(17,18,19,20)"
+    sql "insert into ${table1} values(null,21,null,23)"
+    sql "insert into ${table1} values(22,null,24,25)"
+    sql "insert into ${table1} values(26,27,null,29)"
+    sql "insert into ${table1} values(5,6,7,8)"
+    sql "insert into ${table1} values(5,6,7,8)"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_int_nullable.groovy:56]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_varchar.groovy [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+"storage_format" = "V2"
+)
+    """
+
+    sql "insert into ${table1} values('a1','a2','a3','a4')"
+    sql "insert into ${table1} values('b1','b2','b3','b4')"
+    sql "insert into ${table1} values('c1','f1','d3','f4')"
+    sql "insert into ${table1} values('c1','c2','c3','c4')"
+    sql "insert into ${table1} values('d1','d2','d3','d4')"
+    sql "insert into ${table1} values('e1','e2','e3','e4')"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_varchar.groovy:47]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_varchar_nullable.groovy [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+    """
+    sql "insert into ${table1} values(null,'qie3','yy','lj')"
+    sql "insert into ${table1} values(null,'hehe',null,'lala')"
+    sql "insert into ${table1} values('beijing','xuanwu','wugui',null)"
+    sql "insert into ${table1} values('beijing','fengtai','fengtai1','fengtai2')"
+    sql "insert into ${table1} values('beijing','chaoyang','wangjing','donghuqu')"
+    sql "insert into ${table1} values('shanghai','hehe',null,'haha')"
+    sql "insert into ${table1} values('tengxun','qie','gg','lj')"
+    sql "insert into ${table1} values('tengxun2','qie',null,'lj')"
+
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_basic_varchar_nullable.groovy:48]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_date.groovy [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+"replication_allocation" = "tag.location.default: 1",
+"in_memory" = "false",
+"storage_format" = "V2"
+)
+    """
+
+    sql "insert into ${table1} values(1, '2021-04-01', '2021-04-02', '2021-04-03')"
+    sql "insert into ${table1} values(1, '2021-03-01', '2021-03-02', '2021-03-03')"
+    sql "insert into ${table1} values(1, '2021-02-01', '2021-02-02', '2021-02-03')"
+    sql "insert into ${table1} values(1, '2021-01-01', '2021-01-02', '2021-01-03')"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_date.groovy:44]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_date_nullable.groovy [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+"storage_format" = "V2"
+)
+
+    """
+
+    sql "insert into ${table1} values(1, '2021-04-01', '2021-04-02', '2021-04-03')"
+    sql "insert into ${table1} values(1, '2021-03-01', '2021-03-02', '2021-03-03')"
+    sql "insert into ${table1} values(1, '2021-02-01', '2021-02-02', '2021-02-03')"
+    sql "insert into ${table1} values(1, '2021-01-01', '2021-01-02', '2021-01-03')"
+    sql "insert into ${table1} values(null, '2021-05-01', 'null', '2021-04-03')"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_date_nullable.groovy:46]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_decimal.groovy [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+"in_memory" = "false",
+"storage_format" = "V2"
+)
+    """
+
+    sql "insert into ${table1} values(1.1,2.2,2.3,3.4)"
+    sql "insert into ${table1} values(1.1,1.2,1.3,1.4)"
+    sql "insert into ${table1} values(2.1,2.2,2.3,2.4)"
+    sql "insert into ${table1} values(3.1,3.2,3.3,3.4)"
+    sql "insert into ${table1} values(4.1,4.2,4.3,4.4)"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_decimal.groovy:45]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_decimal_nullable.groovy [hunk 8]
```diff
@@ -0,0 +1,125 @@
...
+"storage_format" = "V2"
+)
+    """
+
+    sql "insert into ${table1} values(1.1,1.2,1.3,1.4)"
+    sql "insert into ${table1} values(1.1,2.2,2.3,3.4)"
+    sql "insert into ${table1} values(2.1,2.2,2.3,2.4)"
+    sql "insert into ${table1} values(3.1,3.2,3.3,3.4)"
+    sql "insert into ${table1} values(4.1,4.2,4.3,4.4)"
+    sql "insert into ${table1} values(null,2,null,4)"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_decimal_nullable.groovy:46]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_mixed_type.groovy [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+"storage_format" = "V2"
+)
+    """
+
+    sql "insert into ${table1} values(1,2,3.1,4.2,5.3,5.4,'a1','a2')"
+    sql "insert into ${table1} values(2,3,4.1,5.2,6.3,7.4,'b1','b2')"
+    sql "insert into ${table1} values(3,4,5.1,6.2,7.3,8.4,'c1','c2')"
+    sql "insert into ${table1} values(4,5,6.1,7.2,8.3,9.4,'d1','d2')"
+    sql "insert into ${table1} values(5,6,5.1,8.2,6.3,11.4,'e1','e2')"
+    sql "insert into ${table1} values(5,6,7.1,8.2,9.3,10.4,'d1','e2')"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_mixed_type.groovy:51]: ditto

File: regression-test/suites/data_model/duplicate/storage/test_dup_tab_mixed_type_nullable.groovy [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+)
+"""
+
+    sql "insert into ${table1} values(1,2,3.1,4.2,5.3,5.4,'a1','a2')"
+    sql "insert into ${table1} values(2,3,4.1,5.2,6.3,7.4,'b1','b2')"
+    sql "insert into ${table1} values(3,4,5.1,6.2,7.3,8.4,'c1','c2')"
+    sql "insert into ${table1} values(4,5,6.1,7.2,8.3,9.4,'d1','d2')"
+    sql "insert into ${table1} values(5,6,7.1,8.2,9.3,10.4,'d1','e2')"
+    sql "insert into ${table1} values(5,6,5.1,8.2,6.3,11.4,'e1','e2')"
+    sql "insert into ${table1} values(null,7,null,8,null,9,null,'e3')"
```
Comment (924060929) [inline regression-test/suites/data_model/duplicate/storage/test_dup_tab_mixed_type_nullable.groovy:51]: ditto

**Comment by 924060929** [comment]
LGTM

**Review by 924060929 — APPROVED** [review]
