### PR TITLE
[fix] (remote) fix bug for storage policy

### LINKED ISSUE #11596: [Bug] fix bug for storage policy
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1

### What's Wrong?

cooldown get a core when pick_candidate_rowsets_to_base_compaction return 0

### What You Expected?

Don't core

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #11596

## Problem summary

fix bug for storage policy

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/storage_policy_mgr.cpp [hunk 1]
```diff
@@ -62,6 +62,7 @@ void StoragePolicyMgr::periodic_put(const std::string& name, const StoragePolicy
             s3_conf.max_connections = policy->s3_max_conn;
             s3_conf.request_timeout_ms = policy->s3_request_timeout_ms;
             s3_conf.connect_timeout_ms = policy->s3_conn_timeout_ms;
+            s3_conf.bucket = policy->bucket;
```
Comment (platoneko) [inline be/src/olap/storage_policy_mgr.cpp:65]: Both `s3_conf.prefix = policy->root_path;`

File: be/src/olap/compaction.cpp [hunk 2]
```diff
@@ -303,6 +303,9 @@ Status Compaction::find_longest_consecutive_version(std::vector<RowsetSharedPtr>
 }
 
 Status Compaction::check_version_continuity(const std::vector<RowsetSharedPtr>& rowsets) {
+    if (rowsets.size() == 0) {
```
Comment (platoneko) [inline be/src/olap/compaction.cpp:306]: `if (rowsets.empty())` is better

**Review by morningman — APPROVED** [review]
LGTM
