### PR TITLE
[fix](grouping sets) columns in grouping sets should not be in selectstmt‘s AggFunc

### LINKED ISSUE #12273: [Bug] Grouping sets cause BE Core or return wrong results
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

chunk

### What's Wrong?

Users use grouping sets unreasonably and get wrong results.
If a column appears in both the `select list` and `aggregate function`, an error will be returned:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = column: `LO_REVENUE` cannot both in select list and aggregate functions when using GROUPING SETS/CUBE/ROLLUP, please use union instead.
```
However, if there are two expressions in the select, the error will not be recognized, and the wrong result will be obtained (vectorization is not turned on), or BE Core (vectorization is turned on)

### What You Expected?

Report an error directly instead of returning an incorrect result, or cause BE Core.

### How to Reproduce?

SSB flat table: lineorder_flat
```
SELECT
    count(P_CATEGORY),
    (LO_ORDERDATE DIV 10000) AS year,
    P_BRAND
FROM lineorder_flat
WHERE P_CATEGORY = 'MFGR#12' AND S_REGION = 'AMERICA' and (LO_ORDERDATE DIV 10000) = 1996
GROUP BY
grouping sets ((year),(P_BRAND),(P_CATEGORY))
```
The above error will return: `column: `LO_REVENUE` cannot both in select list and aggregate functions when using GROUPING SETS/CUBE/ROLLUP, please use union instead.`, which is expected.

```sql
SELECT
    count(P_CATEGORY) / count(P_CATEGORY),
    (LO_ORDERDATE DIV 10000) AS year,
    P_BRAND
FROM lineorder_flat
WHERE P_CATEGORY = 'MFGR#12' AND S_REGION = 'AMERICA' and (LO_ORDERDATE DIV 10000) = 1996
GROUP BY
grouping sets ((year),(P_BRAND),(P_CATEGORY))
```
The above sql, if vectorization is not enabled, returns an error result:
```sql
+-------------------------------------------+------+-----------+
| count(`P_CATEGORY`) / count(`P_CATEGORY`) | year | P_BRAND   |
+-------------------------------------------+------+-----------+
|                                      NULL | NULL | MFGR#125  |
|                                      NULL | NULL | MFGR#1239 |
|                                      NULL | NULL | MFGR#1224 |
|                                      NULL | NULL | MFGR#1215 |
|                                      NULL | NULL | MFGR#126  |
|                                      NULL | NULL | MFGR#1227 |
|                                      NULL | NULL | MFGR#1216 |
|                                         1 | NULL | NULL      |
|                                      NULL | NULL | MFGR#1232 |
|                                      NULL | 1996 | NULL      |
|                                      NULL | NULL | MFGR#1231 |
|                                      NULL | NULL | MFGR#1233 |
|                                      NULL | NULL | MFGR#1230 |
|                                      NULL | NULL | MFGR#1225 |
|                                      NULL | NULL | MFGR#1238 |
|                                      NULL | NULL | MFGR#124  |
|                                      NULL | NULL | MFGR#1214 |
|                                      NULL | NULL | MFGR#1226 |
|                                      NULL | NULL | MFGR#127  |
|                                      NULL | NULL | MFGR#1217 |
|                                      NULL | NULL | MFGR#1237 |
|                                      NULL | NULL | MFGR#1218 |
|                                      NULL | NULL | MFGR#1229 |
|                                      NULL | NULL | MFGR#1234 |
|                                      NULL | NULL | MFGR#128  |
|                                      NULL | NULL | MFGR#1240 |
|                                      NULL | NULL | MFGR#1221 |
|                                      NULL | NULL | MFGR#1210 |
|                                      NULL | NULL | MFGR#1222 |
|                                      NULL | NULL | MFGR#123  |
|                                      NULL | NULL | MFGR#1213 |
|                                      NULL | NULL | MFGR#121  |
|                                      NULL | NULL | MFGR#1220 |
|                                      NULL | NULL | MFGR#1211 |
|                                      NULL | NULL | MFGR#122  |
|                                      NULL | NULL | MFGR#1223 |
|                                      NULL | NULL | MFGR#1212 |
|                                      NULL | NULL | MFGR#1236 |
|                                      NULL | NULL | MFGR#1219 |
|                                      NULL | NULL | MFGR#129  |
|                                      NULL | NULL | MFGR#1235 |
|                                      NULL | NULL | MFGR#1228 |
+-------------------------------------------+------+-----------+
42 rows in set (2 min 43.05 sec)
```

If vectorization is turned on, it results in BE Core:
```
*** Current BE git commitID: 0c5b4ec ***
*** SIGABRT unkown detail explain (@0x2d290) received by PID 184976 (TID 0x7fe984d78700) from PID 184976; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/yangzheng13/workspace/incubator-doris/be/src/common/signal_handler.h:420
 1# 0x00007FE9C9CAD400 in /lib64/libc.so.6
 2# gsignal in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# __gnu_cxx::__verbose_terminate_handler() [clone .cold] in /root/yangzheng13/workspace/incubator-doris/output/be-release/lib/doris_be
 5# __cxxabiv1::__terminate(void (*)()) in /root/yangzheng13/workspace/incubator-doris/output/be-release/lib/doris_be
 6# 0x00007FE9D4020391 in /root/yangzheng13/workspace/incubator-doris/output/be-release/lib/doris_be
 7# 0x00007FE9D40204E5 in /root/yangzheng13/workspace/incubator-doris/output/be-release/lib/doris_be
 8# doris::vectorized::throwFromErrno(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) at /root/yangzheng13/workspace/incubator-doris/be/src/vec/common/exception.cpp:115
 9# Allocator<false, false>::alloc(unsigned long, unsigned long) [clone .isra.0] at /root/yangzheng13/workspace/incubator-doris/be/src/vec/common/allocator.h:170
10# void doris::vectorized::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::realloc<>(unsigned long) at /root/yangzheng13/workspace/incubator-doris/be/src/vec/common/pod_array.h:153
11# doris::vectorized::ColumnString::insert_range_from(doris::vectorized::IColumn const&, unsigned long, unsigned long) [clone .part.0] at /root/yangzheng13/workspace/incubator-doris/be/src/vec/columns/column_string.cpp:79
12# doris::vectorized::VRepeatNode::get_repeated_block(doris::vectorized::Block*, int, doris::vectorized::Block*) at /root/yangzheng13/workspace/incubator-doris/be/src/vec/exec/vrepeat_node.cpp:114
13# doris::vectorized::VRepeatNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/yangzheng13/workspace/incubator-doris/be/src/vec/exec/vrepeat_node.cpp:193
14# doris::vectorized::AggregationNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/yangzheng13/workspace/incubator-doris/be/src/vec/exec/vaggregation_node.cpp:464
15# doris::PlanFragmentExecutor::get_vectorized_internal(doris::vectorized::Block**) at /root/yangzheng13/workspace/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:336
16# doris::PlanFragmentExecutor::open_vectorized_internal() at /root/yangzheng13/workspace/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:284
17# doris::PlanFragmentExecutor::open() at /root/yangzheng13/workspace/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:239
18# doris::FragmentExecState::execute() at /root/yangzheng13/workspace/incubator-doris/be/src/runtime/fragment_mgr.cpp:246
19# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) at /root/yangzheng13/workspace/incubator-doris/be/src/runtime/fragment_mgr.cpp:499
20# std::_Function_handler<void (), doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:291
21# doris::ThreadPool::dispatch_thread() at /root/yangzheng13/workspace/incubator-doris/be/src/util/threadpool.cpp:548
22# doris::Thread::supervise_thread(void*) at /root/yangzheng13/workspace/incubator-doris/be/src/util/thread.cpp:426
23# start_thread in /lib64/libpthread.so.0
24# clone in /lib64/libc.so.6
```

### Anything Else?

none

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zenoyang**
# Proposed changes

Issue Number: close #12273 
Fix grouping sets cause be core or return wrong results.

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by spaces-X** [comment]
It seems that i got the exact same error couple months ago, but the fix pr #10120 has not been merged into master yet.

I think the recurrence rate of the current bug is quite high, and I hope that a short-term fix can be merged to master rather than waiting for the new query optimizer's implement.

**Review by spaces-X — DISMISSED** [review]
LGTM

**Review by spaces-X — DISMISSED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java [hunk 1]
```diff
@@ -444,13 +444,18 @@ public void analyze(Analyzer analyzer) throws UserException {
             }
         }
         if (groupByClause != null && groupByClause.isGroupByExtension()) {
+            ArrayList<Expr> aggFnExprList = new ArrayList<>();
             for (SelectListItem item : selectList.getItems()) {
-                if (item.getExpr() instanceof FunctionCallExpr && item.getExpr().fn instanceof AggregateFunction) {
+                aggFnExprList.clear();
+                getAggregateFnExpr(item.getExpr(), aggFnExprList);
+                if (!aggFnExprList.isEmpty()) {
```
Comment (starocean999) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:451]: this is more clear and simple:
`for (Expr aggFnExpr : aggFnExprList) {
    for (Expr expr : groupByClause.getGroupingExprs()) {
        ....
    }
}`

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java [hunk 2]
```diff
@@ -1966,6 +1971,16 @@ private boolean checkGroupingFn(Expr expr) {
         return false;
     }
 
+    private void getAggregateFnExpr(Expr expr, ArrayList<Expr> aggFnExprList) {
+        if (expr instanceof FunctionCallExpr && expr.fn instanceof AggregateFunction) {
+            aggFnExprList.add(expr);
+        } else if (expr.getChildren() != null && expr.getChildren().size() > 0) {
```
Comment (starocean999) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:1977]: remove else if (expr.getChildren() != null && expr.getChildren().size() > 0) call `            for (Expr child : expr.getChildren()) {
                getAggregateFnExpr(child, aggFnExprList);
            }` directly

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java (hunk 1 above)
Comment (zenoyang) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java]: done

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java (hunk 2 above)
Comment (zenoyang) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java]: Thanks for the reminder, I have modified it, but I have kept `else if (expr.getChildren() != null)`, otherwise it may cause NullPointerException.

**Review by yiguolei — APPROVED** [review]
LGTM
