### PR TITLE
[fix](Nereids) add logical project to prevent extra wrong column

### LINKED ISSUE #30264: [Bug] Nereids planner output a wrong extra column
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Nereids planner output a wrong extra column

### What You Expected?

No wrong extra column

### How to Reproduce?

```sql
create table t123(tm varchar(20))  ENGINE=OLAP
DUPLICATE KEY(tm)
COMMENT "OLAP"
DISTRIBUTED BY HASH(tm) BUCKETS  auto
PROPERTIES (
    "replication_num" = "1"
);
insert into t123 values('a');

with cte1 as(select * from t123)
select tm  from cte1 group by tm
having tm > (select  'Apple');
```

we get:
```
+------+---------+
| tm   | 'Apple' |
+------+---------+
| a    | Apple   |
+------+---------+
```

we want get:

```
+------+
| tm   |
+------+
| a    |
+------+
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by iwanttobepowerful**
## Proposed changes

Issue Number: close #30264

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java [hunk 1]
```diff
@@ -140,6 +140,13 @@ public List<Rule> buildRules() {
                                 .filter(s -> !(s instanceof MarkJoinSlotReference))
                                 .collect(ImmutableList.toImmutableList()), newFilter);
                     } else {
+                        if (applyPlan instanceof LogicalProject) {
```
Comment (starocean999) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java:143]: I think the better way to do this is using old filter's output to create a new project node on top of current result root plan

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java [hunk 2]
```diff
@@ -410,6 +417,9 @@ private LogicalPlan addApply(SubqueryExpr subquery, LogicalPlan childPlan,
                         ? ImmutableList.of(subquery.getQueryPlan().getOutput().get(0)) : ImmutableList.of())
                     .build();
 
+        if (subqueryToMarkJoinSlot.get(subquery).isPresent() || needAddScalarSubqueryOutputToProjects) {
```
Comment (starocean999) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java:420]: if using filter's output to create a new top project, this is not needed

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java (hunk 1 above)
Comment (starocean999) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java:143]: try replace 
```
if (conjuncts.stream().flatMap(c -> c.children().stream())
                            .anyMatch(MarkJoinSlotReference.class::isInstance)) {
    return new LogicalProject<>(applyPlan.getOutput().stream()
            .filter(s -> !(s instanceof MarkJoinSlotReference))
            .collect(ImmutableList.toImmutableList()), newFilter);
} else {
    return newFilter;
}
```
with
```
return new LogicalProject<>(filter.getOutput().stream()
                            .collect(ImmutableList.toImmutableList()), newFilter);
```

**Review by starocean999 — APPROVED** [review]
LGTM

**Review by jackwener — APPROVED** [review]
