### PR TITLE
[Bug] Regularly clean up old DeleteInfos in the DeleteHandler

### LINKED ISSUE #6447: [Bug] DeleteInfos in the DeleteHandler will never be deleted
**Describe the bug**
DeleteInfos in the DeleteHandler will never be deleted, taking up too much memory and metadata storage.
When users use a large number of delete statements, FE metadata parsing problems will occur, resulting in failure to restart all FEs due to load image failure. 
An error is reported when starting FE:
```
java.lang.IllegalArgumentException: capacity < 0: (-2144832511 < 0)
  at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
  at java.base/java.nio.CharBuffer.allocate(CharBuffer.java:347)
  at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:809)
  at org.apache.doris.common.io.Text.decode(Text.java:362)
  at org.apache.doris.common.io.Text.decode(Text.java:341)
  at org.apache.doris.common.io.Text.readString(Text.java:416)
  at org.apache.doris.load.DeleteHandler.read(DeleteHandler.java:687)
  at org.apache.doris.catalog.Catalog.loadDeleteHandler(Catalog.java:1879)
  at org.apache.doris.catalog.Catalog.loadImage(Catalog.java:1530)
  at org.apache.doris.catalog.Catalog.initialize(Catalog.java:772)
  at org.apache.doris.PaloFe.start(PaloFe.java:109)
  at org.apache.doris.PaloFe.main(PaloFe.java:60)
```

**To Reproduce**
1. Execute the "show delete" statement to see all the historical deleted information
2. When there are too many deleteInfo, load image error when restarting FE, and FE cannot be started

**Expected behavior**
1. According to the `delete_info_keep_max_second` configuration, clean up the old deleteInfo
2. Support pagination to read metadata text when load image

**Environment**
 - OS: Centos7
 - Version: Doris branch-0.13

### PR DESCRIPTION
**Pull request by zenoyang**
## Proposed changes
fix https://github.com/apache/incubator-doris/issues/6447
1. FE master regularly triggers the remove operation
2. After the master completes the removal of deleteInfo, it is synchronized to the Follower through editlog for remove
3. When the DeleteInfo creation time is longer than the current time, it will be cleaned up, which is determined by the `delete_info_keep_max_second` configuration

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Hi @zenoyang thanks for your PR. This is indeed a problem.
But there some thing that you need to know:

1. The `labelCleaner` thread is running on all FEs, each FE will clean its own `deleteInfos`. So don't need to write a edit log `OP_REMOVE_OLD_DELETE_INFO` to "tell" other FE to clean the delete infos.

2. Once the `labelCleaner` thread cleans the delete infos on each FE. What we need to take care is to clean the delete infos in meta replay logic. Eg, after calling `DeleteHandler.read()` method, we should clean the delete info actively, so that the meta image won't contains expired delete infos.

This logic is a bit convoluted. If you don't understand something, welcome to communicate.

**Comment by zenoyang** [comment]
> Hi @zenoyang thanks for your PR. This is indeed a problem.
> But there some thing that you need to know:
> 
> 1. The `labelCleaner` thread is running on all FEs, each FE will clean its own `deleteInfos`. So don't need to write a edit log `OP_REMOVE_OLD_DELETE_INFO` to "tell" other FE to clean the delete infos.
> 2. Once the `labelCleaner` thread cleans the delete infos on each FE. What we need to take care is to clean the delete infos in meta replay logic. Eg, after calling `DeleteHandler.read()` method, we should clean the delete info actively, so that the meta image won't contains expired delete infos.
> 
> This logic is a bit convoluted. If you don't understand something, welcome to communicate.

**Comment by zenoyang** [comment]
I submitted a new code to fix the previous problem. Please review it when you have time. ^_^  @morningman

File: fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java [hunk 1]
```diff
@@ -709,6 +745,51 @@ public void write(DataOutput out) throws IOException {
 
     public static DeleteHandler read(DataInput in) throws IOException {
         String json = Text.readString(in);
-        return GsonUtils.GSON.fromJson(json, DeleteHandler.class);
+        DeleteHandler deleteHandler = GsonUtils.GSON.fromJson(json, DeleteHandler.class);
+        deleteHandler.removeOldDeleteInfos();
```
Comment (xy720) [inline fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java:749]: Hi, there is problem in here. When we are load image, we shouldn't write the editLog, or else replayRemoveOldDeleteInfos() method will triggered after loading image immediately.

File: fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java [hunk 2]
```diff
@@ -709,6 +745,51 @@ public void write(DataOutput out) throws IOException {
...
+        return deleteHandler;
+    }
+
+    /**
+     * FE Master timing, or when any FE replay meta triggers DeleteInfo cleanup
+     */
+    public void removeOldDeleteInfos() {
+        Timestamp timestamp = new Timestamp();
+        removeOldDeleteInfos(timestamp);
+        Catalog.getCurrentCatalog().getEditLog().logRemoveOldDeleteInfos(timestamp);
```
Comment (xy720) [inline fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java:759]: I think you can add a judgment here that when Fe is loading image, it will not execute this line.

Comment (zenoyang) [reply fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java]: It has been fixed, please review it again, thank you very much : )

When the master or follower FE loads the image when it starts, old deleteInfos will not clean up and generate editlog.
FE Master timing or checkpoint loading image, trigger DeleteInfo cleanup.

**Review by xy720 — DISMISSED** [review]
LGTM

**Review by morningman — COMMENTED** [review]
Your implementation can ensure consistency, but this approach is a bit complicated. We should minimize unnecessary state maintenance.

So I suggest to follow the logic of `labelCleaner`, and each FE cleans up its own deleteInfo. Regarding the issue of consistency, you can forward the `show delete` statement to the master FE for execution, so that we can get consistent results.

Regarding the forwarding logic, you can refer to the `getRedirectStatus` method of `ShowLoadStmt.java`

**Review by morningman — APPROVED** [review]
LGTM
