### PR TITLE
[Enhancement](doris-future) Support "REGR_" aggregation functions (PART II)

### LINKED ISSUE #38975: [Enhancement](doris-future) Support "REGR_" aggregation functions (PART II)
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

We are going to support all regression functions in pg. You can see them in https://www.postgresql.org/docs/16/functions-aggregate.html with `regr_` prefix. And considring the difficulty of this task, it will be nice for community as "good first issue".

In this issue, you should implement function `regr_intercept` and `regr_slope`

If you'd like to work on it, please comment to let me know. I'll help you to achieve this.

### Solution

you can found an example of implementation of a aggregate function [here](https://github.com/apache/doris/pull/33265)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yoruet**
## Proposed changes

Issue Number: close #38975

```sql
mysql> select * from test;
+------+------+------+
| id   | x    | y    |
+------+------+------+
|    1 |   18 |   13 |
|    3 |   12 |    2 |
|    5 |   10 |   20 |
|    2 |   14 |   27 |
|    4 |    5 |    6 |
+------+------+------+
5 rows in set (0.07 sec)

mysql> select regr_slope(y,x) , regr_intercept(y,x) from test;
+--------------------+----------------------+
| regr_slope(y, x)   | regr_intercept(y, x) |
+--------------------+----------------------+
| 0.6853448275862069 |    5.512931034482759 |
+--------------------+----------------------+
1 row in set (0.15 sec)

```

### CODE REVIEW

File: be/src/vec/aggregate_functions/aggregate_function_regr_slope.h [hunk 1]
```diff
@@ -0,0 +1,167 @@
...
+        sum_of_x_mul_y += value_x * value_y;
+        sum_of_x_squared += value_x * value_x;
+        count += 1;
+    }
+};
+
+template <typename T, typename Data>
+struct RegrSlopeData : AggregateFunctionRegrSlopeData<T> {
+    void insert_result_into(IColumn& to) const {
+        auto& col = assert_cast<ColumnFloat64&, TypeCheckOnRelease::DISABLE>(to);
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:118]: `assert_cast<ColumnNullable&>`, type check on release should be open.

File: be/src/vec/aggregate_functions/aggregate_function_regr_slope.h [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+        col.get_data().push_back(this->get_slope_result());
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:119]: `get_slope_result` would return `Nan` in some situation, but doris does not support Nan, we should get NULL. So result type should be ColumnNullable

**Review by zhiqiang-hhhh — CHANGES_REQUESTED** [review]

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 3]
```diff
@@ -0,0 +1,169 @@
...
+        sum_of_x_mul_y += value_x * value_y;
+        sum_of_x_squared += value_x * value_x;
+        count += 1;
+    }
+};
+
+template <typename T, typename Data>
+struct RegrInterceptData : AggregateFunctionRegrInterceptData<T> {
+    void insert_result_into(IColumn& to) const {
+        auto& col = assert_cast<ColumnFloat64&, TypeCheckOnRelease::DISABLE>(to);
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:120]: assert_cast<ColumnNullable&>

**Review by zhiqiang-hhhh — CHANGES_REQUESTED** [review]

**Comment by zhiqiang-hhhh** [comment]
@Yoruet Null property of `regr_slope` and `regr_intercept ` should be `AlwaysNullable` on FE, so need to do some modification on be.

File: be/src/vec/aggregate_functions/aggregate_function_regr_slope.h (hunk 2 above)
Comment (Yoruet) [reply be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:119]: Does this mean that we have decided to only support Nullable results?

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h (hunk 3 above)
Comment (Yoruet) [reply be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:120]: In fact, when I use assert_cast<ColumnNullable&>, the assertion fails and the program crashes when I try to cast "to" from ColumnVector<double> to ColumnNullable.

Comment (zhiqiang-hhhh) [reply be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:120]: @Yoruet Because type on FE is not correct. You should make these two functions AlwaysNullable, so that planner will give you a ColumnNullable.

File: be/src/vec/aggregate_functions/aggregate_function_regr_slope.h (hunk 2 above)
Comment (zhiqiang-hhhh) [reply be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:119]: @Yoruet  Yes.

**Comment by zhiqiang-hhhh** [comment]
@Yoruet You can take this pr https://github.com/apache/doris/pull/40945 as a reference.

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrIntercept.java [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+
+import com.google.common.base.Preconditions;
+import com.google.common.collect.ImmutableList;
+
+import java.util.List;
+
+/**
+ * AggregateFunction 'regr_intercept'.
+ */
+public class RegrIntercept extends NullableAggregateFunction
```
Comment (zhiqiang-hhhh) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrIntercept.java:44]: https://github.com/apache/doris/blob/b6d210284654712aa0f248172ed7322eb862fd73/fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Kurt.java#L42

Should be AlwaysNullable

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.cpp [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+
+namespace doris::vectorized {
+template <template <typename> class NameData, template <typename, typename> class Data,
+          template <typename> class AggregateFunctionRegrData>
+AggregateFunctionPtr create_function_regr(const String& name, const DataTypes& argument_types,
+                                          const bool result_is_nullable) {
+    WhichDataType which(remove_nullable(argument_types[0]));
+#define DISPATCH(TYPE)                                                                        \
+    if (which.idx == TypeIndex::TYPE)                                                         \
+        return creator_without_type::create<AggregateFunctionRegrFunc<                        \
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.cpp:36]: https://github.com/apache/doris/blob/b6d210284654712aa0f248172ed7322eb862fd73/be/src/vec/aggregate_functions/aggregate_function_skew.cpp#L36

`create_ignore_null` since we need to handle input of ColumnNullable by hand when result is AlwayNullable.

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 6]
```diff
@@ -0,0 +1,169 @@
...
+            return;
+        }
+        sum_x += rhs.sum_x;
+        sum_y += rhs.sum_y;
+        sum_of_x_mul_y += rhs.sum_of_x_mul_y;
+        sum_of_x_squared += rhs.sum_of_x_squared;
+        count += rhs.count;
+    }
+
+    void add(const IColumn* column_y, const IColumn* column_x, size_t row_num) {
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:104]: https://github.com/apache/doris/blob/b6d210284654712aa0f248172ed7322eb862fd73/be/src/vec/aggregate_functions/aggregate_function_statistic.h#L82

We need to process ColumnNullable by our self after AlwaysNullable. Remember to skip Null value.

**Comment by zhiqiang-hhhh** [comment]
@Yoruet I add more comments with detail information.

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+        sum_of_x_mul_y += value_x * value_y;
+        sum_of_x_squared += value_x * value_x;
+        count += 1;
+    }
+};
+
+template <typename TX, typename TY>
+struct RegrInterceptFuncTwoArg {
+    using TypeX = TX;
+    using TypeY = TY;
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:103]: `using TypeY = TX` or `using Type = T`

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 8]
```diff
@@ -0,0 +1,189 @@
...
+    using Data = AggregateFunctionRegrInterceptData<Float64>;
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:104]: maybe `using Data = AggregateFunctionRegrInterceptData<T>;`

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 9]
```diff
@@ -0,0 +1,189 @@
...
+
+    DataTypePtr get_return_type() const override {
+        return make_nullable(std::make_shared<DataTypeFloat64>());
+    }
+
+    void add(AggregateDataPtr __restrict place, const IColumn** columns, ssize_t row_num,
+             Arena*) const override {
+        if constexpr (NullableInput) {
+            const ColumnNullable& y_column_nullable =
+                    assert_cast<const ColumnNullable&>(*columns[0]);
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:136]: add `TypeCheckOnRelease::Disable` since add function will be called on each row

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 10]
```diff
@@ -0,0 +1,189 @@
...
+            const ColumnNullable& x_column_nullable =
+                    assert_cast<const ColumnNullable&>(*columns[1]);
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:138]: `TypeCheckOnRelease::Disable`

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 11]
```diff
@@ -0,0 +1,189 @@
...
+            bool y_null = y_column_nullable.is_null_at(row_num);
+            bool x_null = x_column_nullable.is_null_at(row_num);
+            if (y_null || x_null) {
+                return;
+            } else {
+                TY y_value = assert_cast<const YInputCol&>(y_column_nullable.get_nested_column())
+                                        .get_data()[row_num];
+                TX x_value = assert_cast<const XInputCol&>(x_column_nullable.get_nested_column())
+                                        .get_data()[row_num];
+                this->data(place).add(static_cast<Float64>(y_value), static_cast<Float64>(x_value));
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:148]: 1. No need to do static_cast after type argument is changed
2. why does position of y and x is changed?

Comment (Yoruet) [reply be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:148]: Because I refer to the parameter order of this webpage https://www.postgresql.org/docs/16/functions-aggregate.html

**Review by zhiqiang-hhhh — CHANGES_REQUESTED** [review]
Null value is not processed correctly.

**Comment by Yoruet** [comment]
> Null value is not processed correctly.

Can you provide corresponding test samples to me

**Comment by zhiqiang-hhhh** [comment]
> > Null value is not processed correctly.
> 
> Can you provide corresponding test samples to me

@Yoruet You can try test case added in this pr https://github.com/Yoruet/doris/pull/1 on regr_slope

**Comment by Yoruet** [comment]
> > > Null value is not processed correctly.
> > 
> > 
> > Can you provide corresponding test samples to me
> 
> @Yoruet You can try test case added in this pr [Yoruet#1](https://github.com/Yoruet/doris/pull/1) on regr_slope



> > > Null value is not processed correctly.
> > 
> > 
> > Can you provide corresponding test samples to me
> 
> @Yoruet You can try test case added in this pr [Yoruet#1](https://github.com/Yoruet/doris/pull/1) on regr_slope

I compared the data in the test_regr_intercept.out file with that in https://dbfiddle.uk/MmKrIU9r, and it seems that there is nothing wrong. Can you provide more detailed information?

**Comment by zhiqiang-hhhh** [comment]
> > > > Null value is not processed correctly.
> > > 
> > > 
> > > Can you provide corresponding test samples to me
> > 
> > 
> > @Yoruet You can try test case added in this pr [Yoruet#1](https://github.com/Yoruet/doris/pull/1) on regr_slope
> 
> > > > Null value is not processed correctly.
> > > 
> > > 
> > > Can you provide corresponding test samples to me
> > 
> > 
> > @Yoruet You can try test case added in this pr [Yoruet#1](https://github.com/Yoruet/doris/pull/1) on regr_slope
> 
> @zhiqiang-hhhh I compared the data in the test_regr_intercept.out file with that in https://dbfiddle.uk/MmKrIU9r, and it seems that there is nothing wrong. Can you provide more detailed information?

The reason test_regr_intercept is correct is that I re-write the implementation of regr_itercept in that PR (I created that pull request on your branch to give you an example on how to fix regr_itercept).

You can compare the code I submitted with your implementation of regr_itercept, and do fix on regr_slope in a same way.

**Comment by Yoruet** [comment]
> > > > > Null value is not processed correctly.
> > > > 
> > > > 
> > > > Can you provide corresponding test samples to me
> > > 
> > > 
> > > @Yoruet You can try test case added in this pr [Yoruet#1](https://github.com/Yoruet/doris/pull/1) on regr_slope
> > 
> > 
> > > > > Null value is not processed correctly.
> > > > 
> > > > 
> > > > Can you provide corresponding test samples to me
> > > 
> > > 
> > > @Yoruet You can try test case added in this pr [Yoruet#1](https://github.com/Yoruet/doris/pull/1) on regr_slope
> > 
> > 
> > @zhiqiang-hhhh I compared the data in the test_regr_intercept.out file with that in https://dbfiddle.uk/MmKrIU9r, and it seems that there is nothing wrong. Can you provide more detailed information?
> 
> The reason test_regr_intercept is correct is that I re-write the implementation of regr_itercept in that PR (I created that pull request on your branch to give you an example on how to fix regr_itercept).
> 
> You can compare the code I submitted with your implementation of regr_itercept, and do fix on regr_slope in a same way.

Thanks for your help,and I have modified regr_slope in the same way

File: regression-test/suites/nereids_function_p0/agg_function/test_regr_slope.groovy [hunk 12]
```diff
@@ -0,0 +1,141 @@
+// Licensed to the Apache Software Foundation (ASF) under one
```
Comment (zhiqiang-hhhh) [inline regression-test/suites/nereids_function_p0/agg_function/test_regr_slope.groovy:1]: move this file to query_p0/aggregate

File: regression-test/suites/query_p0/aggregate/test_regr_intercept.groovy [hunk 13]
```diff
@@ -0,0 +1,217 @@
+// Licensed to the Apache Software Foundation (ASF) under one
```
Comment (zhiqiang-hhhh) [inline regression-test/suites/query_p0/aggregate/test_regr_intercept.groovy:1]: Apply test case in this file to `regr_slope`

File: regression-test/data/nereids_function_p0/agg_function/test_regr_intercept.out [hunk 14]
```diff
@@ -0,0 +1,25 @@
+-- This file is automatically generated. You should know what you did if you want to edit this
```
Comment (zhiqiang-hhhh) [inline regression-test/data/nereids_function_p0/agg_function/test_regr_intercept.out:1]: remove this file

File: fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrSlope.java [hunk 15]
```diff
@@ -0,0 +1,107 @@
...
+import com.google.common.base.Preconditions;
+import com.google.common.collect.ImmutableList;
+
+import java.util.List;
+
+/**
+ * AggregateFunction 'regr_slope'.
+ */
+
+public class RegrSlope extends NullableAggregateFunction
```
Comment (zhiqiang-hhhh) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrSlope.java:44]: extends `AggregateFunction`, implements `AlwaysNullable`, same with regr_intercept.

**Review by zhiqiang-hhhh — CHANGES_REQUESTED** [review]
Make implementation of regr_slope same with regr_intecept.

File: be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h [hunk 16]
```diff
@@ -0,0 +1,201 @@
...
+        count = 0;
+    }
+
+    Float64 get_intercept_result() const {
+        Float64 denominator = count * sum_of_x_squared - sum_x * sum_x;
+        if (count < 2 || denominator == 0.0) {
+            return std::numeric_limits<Float64>::quiet_NaN();
+        }
+        Float64 slope = (count * sum_of_x_mul_y - sum_x * sum_y) / denominator;
+        return (sum_y - slope * sum_x) / count;
```
Comment (zhiqiang-hhhh) [inline be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:77]: this is the only difference between regr_intercept with regr_slope ?

Comment (Yoruet) [reply be/src/vec/aggregate_functions/aggregate_function_regr_intercept.h:77]: yes

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
We need todo a refactor on all `REGR_` like agg functions, to make code simple. These agg functions have same structure.
eg. https://github.com/apache/doris/pull/39187

**Comment by Yoruet** [comment]
> We need todo a refactor on all `REGR_` like agg functions, to make code simple. These agg functions have same structure. eg. #39187

only regr_slope and regr_intercept

> We need todo a refactor on all `REGR_` like agg functions, to make code simple. These agg functions have same structure. eg. #39187

Does it include only regr_slope and regr_intercept or does it include other regr_ functions such as regr_sxx

**Comment by zhiqiang-hhhh** [comment]
> > We need todo a refactor on all `REGR_` like agg functions, to make code simple. These agg functions have same structure. eg. #39187
> 
> Does it include only regr_slope and regr_intercept or does it include other regr_ functions such as regr_sxx

This is just a comment to remind us to do a refactor in the future, does not means we need to do refactor in this pr.

**Comment by HappenLee** [comment]
@Yoruet please add doc in https://github.com/apache/doris-website thank you very mush

**Comment by Yoruet** [comment]
> @Yoruet please add doc in https://github.com/apache/doris-website thank you very mush

I have already pr the doc.plz check it

File: be/src/vec/aggregate_functions/aggregate_function_regr_slope.h [hunk 17]
```diff
@@ -0,0 +1,200 @@
+// Licensed to the Apache Software Foundation (ASF) under one
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:1]: better union the slope and intercept the code，seems only one struct and use template can do the work

Comment (Yoruet) [reply be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:1]: ok, I will union them later. but there is a quesion that what should I name the file that union the slope and intercept function.

File: be/src/vec/aggregate_functions/aggregate_function_regr_slope.h [hunk 18]
```diff
@@ -0,0 +1,200 @@
...
+#include "vec/core/field.h"
+#include "vec/core/types.h"
+#include "vec/data_types/data_type.h"
+#include "vec/data_types/data_type_nullable.h"
+#include "vec/data_types/data_type_number.h"
+#include "vec/io/io_helper.h"
+namespace doris::vectorized {
+
+template <typename T>
+struct AggregateFunctionRegrSlopeData {
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_regr_slope.h:40]: `AggregateFunctionRegrSlopeData` and `AggregateFunctionRegrInterceptData` should be sub class

File: be/src/vec/aggregate_functions/aggregate_function_regr_union.h [hunk 19]
```diff
@@ -0,0 +1,221 @@
...
+        sum_x += value_x;
+        sum_y += value_y;
+        sum_of_x_mul_y += value_x * value_y;
+        sum_of_x_squared += value_x * value_x;
+        count += 1;
+    }
+};
+
+template <typename T>
+struct RegrSlopeFunc {
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_regr_union.h:93]: better code:
```
template <typename T>
struct RegrSlopeFunc ：  AggregateFunctionRegrData<T>
```

File: be/src/vec/aggregate_functions/aggregate_function_regr_union.h [hunk 20]
```diff
@@ -0,0 +1,217 @@
...
+        }
+        Float64 slope =
+                (this->count * this->sum_of_x_mul_y - this->sum_x * this->sum_y) / denominator;
+        return slope;
+    }
+};
+
+template <typename T>
+struct RegrInterceptFunc : AggregateFunctionRegrData<T> {
+    using Type = T;
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_regr_union.h:110]: useless code delete

File: be/src/vec/aggregate_functions/aggregate_function_regr_union.h [hunk 21]
```diff
@@ -0,0 +1,217 @@
...
+        count += 1;
+    }
+};
+
+template <typename T>
+struct RegrSlopeFunc : AggregateFunctionRegrData<T> {
+    using Type = T;
+    static constexpr const char* name = "regr_slope";
+
+    Float64 get_result() const {
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_regr_union.h:97]: should add a function call `get_slope`  in `AggregateFunctionRegrData`
```
double get_slope() const {
   Float64 denominator = this->count * this->sum_of_x_squared - this->sum_x * this->sum_x;
        if (this->count < 2 || denominator == 0.0) {
            return std::numeric_limits<Float64>::quiet_NaN();
        }
        return
                (this->count * this->sum_of_x_mul_y - this->sum_x * this->sum_y) / denominator;
}
```

the `get_result()` call `get_slope`

File: be/src/vec/aggregate_functions/aggregate_function_regr_union.h [hunk 22]
```diff
@@ -0,0 +1,217 @@
...
+        return slope;
+    }
+};
+
+template <typename T>
+struct RegrInterceptFunc : AggregateFunctionRegrData<T> {
+    using Type = T;
+    static constexpr const char* name = "regr_intercept";
+
+    Float64 get_result() const {
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_regr_union.h:113]: if auto slope = get_slope()； 
if is_nan(slope) 
return slope 
else 
return (this->sum_y - slope * this->sum_x) / this->count;
```

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
run buildall
