### PR TITLE
[Bug] Fix Tuple is null predicate may cause be cores

### LINKED ISSUE #6462: [Bug] Tuple is null predicate may cause be cores
**To Reproduce**

1. create table medal_new

```
CREATE TABLE `medal_new` (
  `event_day` date NOT NULL ,
  `uid` varchar(128) NULL DEFAULT "" ,
  `medal_level` varchar(5000) NULL DEFAULT "" 
) ENGINE=OLAP
DUPLICATE KEY(`event_day`, `uid`, `medal_level`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`uid`) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);
```

2. execute sql

```
SELECT a.event_day, a.medal_level
	, SUM(COUNT(t.uid)) OVER (PARTITION BY a.medal_level ORDER BY a.event_day) AS cum_medal_user_cnt
FROM (
	SELECT event_day, medal_level
	FROM medal_new
) a
LEFT JOIN (
        SELECT 1 AS line, event_day, medal_level, uid
        FROM medal_new
) t
ON t.event_day = a.event_day AND t.medal_level = a.medal_level
GROUP BY a.event_day, a.medal_level
```

**Expected behavior**
Successfully execute.

**Screenshots**

Be coredump:

```
#0  0x0000000001491696 in operator bool (this=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_bvector.h:916
#1  operator* (this=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_bvector.h:348
#2  operator[] (__n=<optimized out>, this=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_bvector.h:918
#3  doris::RowDescriptor::tuple_is_nullable (this=this@entry=0x16943c78, tuple_idx=384727376) at ../src/runtime/descriptors.cpp:358
#4  0x00000000012346d7 in doris::TupleIsNullPredicate::prepare(doris::RuntimeState*, doris::RowDescriptor const&, doris::ExprContext*) () at ../src/exprs/tuple_is_null_predicate.cpp:39
#5  0x000000000120784c in doris::ExprContext::prepare(doris::RuntimeState*, doris::RowDescriptor const&, std::shared_ptr<doris::MemTracker> const&) () at ../src/exprs/expr_context.cpp:61
#6  0x00000000011fda8e in doris::Expr::prepare(std::vector<doris::ExprContext*, std::allocator<doris::ExprContext*> > const&, doris::RuntimeState*, doris::RowDescriptor const&, std::shared_ptr<doris::MemTracker> const&) ()
    at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_vector.h:1061
#7  0x00000000019d5226 in doris::SortExecExprs::prepare(doris::RuntimeState*, doris::RowDescriptor const&, doris::RowDescriptor const&, std::shared_ptr<doris::MemTracker> const&) () at ../src/exec/sort_exec_exprs.cpp:52
#8  0x0000000001a8405a in doris::SpillSortNode::prepare(doris::RuntimeState*) () at ../src/exec/exec_node.h:179
#9  0x00000000019b0d41 in doris::ExecNode::prepare(doris::RuntimeState*) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_vector.h:1043
#10 0x0000000001ac2dac in doris::AnalyticEvalNode::prepare(doris::RuntimeState*) () at ../src/exec/analytic_eval_node.cpp:142
#11 0x00000000019b0d41 in doris::ExecNode::prepare(doris::RuntimeState*) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_vector.h:1043
#12 0x0000000001a98338 in doris::PartitionedAggregationNode::prepare(doris::RuntimeState*) () at ../src/exec/partitioned_aggregation_node.cc:188
#13 0x000000000154eeba in doris::PlanFragmentExecutor::prepare(doris::TExecPlanFragmentParams const&, doris::QueryFragmentsCtx const*) () at /home/disk4/xuyang/work/baidu/bdg/doris/thirdparty-gcc10/installed/include/boost/smart_ptr/scoped_ptr.hpp:109
#14 0x00000000014c6ebe in doris::FragmentExecState::prepare (this=this@entry=0x16ef8000, params=...) at ../src/runtime/fragment_mgr.cpp:228
#15 0x00000000014caea2 in doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>) () at ../src/runtime/fragment_mgr.cpp:606
#16 0x00000000014ccb12 in doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/std_function.h:87
#17 0x000000000159409e in doris::PInternalServiceImpl<doris::PBackendService>::_exec_plan_fragment (this=this@entry=0x731f680, ser_request=...) at ../src/runtime/exec_env.h:117
#18 0x000000000159419f in doris::PInternalServiceImpl<doris::PBackendService>::exec_plan_fragment (this=0x731f680, cntl_base=<optimized out>, request=<optimized out>, response=0x161fd660, done=0x169b0c80)
    at /home/disk4/xuyang/work/baidu/bdg/doris/thirdparty-gcc10/installed/include/google/protobuf/arenastring.h:231
#19 0x000000000217b1b7 in brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) () at ../src/brpc/policy/http_rpc_protocol.cpp:1484
#20 0x00000000021485d7 in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x1622f210) at ../src/brpc/input_messenger.cpp:135
#21 0x000000000214949e in operator() (last_msg=0x1622f210, this=<synthetic pointer>) at ../src/brpc/input_messenger.cpp:141
#22 ~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/unique_ptr.h:360
#23 brpc::InputMessenger::OnNewMessages(brpc::Socket*) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/unique_ptr.h:354
#24 0x00000000021f19fe in brpc::Socket::ProcessEvent(void*) () at ../src/brpc/socket.cpp:1017
#25 0x000000000229a25f in bthread::TaskGroup::task_runner(long) () at ../src/bthread/task_group.cpp:296
#26 0x000000000228b661 in bthread_make_fcontext () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_iterator.h:953
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

```
#0  0x0000000001491696 in operator bool (this=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_bvector.h:916
#1  operator* (this=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_bvector.h:348
#2  operator[] (__n=<optimized out>, this=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_bvector.h:918
#3  doris::RowDescriptor::tuple_is_nullable (this=this@entry=0x16943c78, tuple_idx=384727376) at ../src/runtime/descriptors.cpp:358
#4  0x00000000012346d7 in doris::TupleIsNullPredicate::prepare(doris::RuntimeState*, doris::RowDescriptor const&, doris::ExprContext*) () at ../src/exprs/tuple_is_null_predicate.cpp:39
#5  0x000000000120784c in doris::ExprContext::prepare(doris::RuntimeState*, doris::RowDescriptor const&, std::shared_ptr<doris::MemTracker> const&) () at ../src/exprs/expr_context.cpp:61
#6  0x00000000011fda8e in doris::Expr::prepare(std::vector<doris::ExprContext*, std::allocator<doris::ExprContext*> > const&, doris::RuntimeState*, doris::RowDescriptor const&, std::shared_ptr<doris::MemTracker> const&) ()
    at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_vector.h:1061
#7  0x00000000019d5226 in doris::SortExecExprs::prepare(doris::RuntimeState*, doris::RowDescriptor const&, doris::RowDescriptor const&, std::shared_ptr<doris::MemTracker> const&) () at ../src/exec/sort_exec_exprs.cpp:52
#8  0x0000000001a8405a in doris::SpillSortNode::prepare(doris::RuntimeState*) () at ../src/exec/exec_node.h:179
#9  0x00000000019b0d41 in doris::ExecNode::prepare(doris::RuntimeState*) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_vector.h:1043
#10 0x0000000001ac2dac in doris::AnalyticEvalNode::prepare(doris::RuntimeState*) () at ../src/exec/analytic_eval_node.cpp:142
#11 0x00000000019b0d41 in doris::ExecNode::prepare(doris::RuntimeState*) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_vector.h:1043
#12 0x0000000001a98338 in doris::PartitionedAggregationNode::prepare(doris::RuntimeState*) () at ../src/exec/partitioned_aggregation_node.cc:188
#13 0x000000000154eeba in doris::PlanFragmentExecutor::prepare(doris::TExecPlanFragmentParams const&, doris::QueryFragmentsCtx const*) () at /home/disk4/xuyang/work/baidu/bdg/doris/thirdparty-gcc10/installed/include/boost/smart_ptr/scoped_ptr.hpp:109
#14 0x00000000014c6ebe in doris::FragmentExecState::prepare (this=this@entry=0x16ef8000, params=...) at ../src/runtime/fragment_mgr.cpp:228
#15 0x00000000014caea2 in doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>) () at ../src/runtime/fragment_mgr.cpp:606
#16 0x00000000014ccb12 in doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/std_function.h:87
#17 0x000000000159409e in doris::PInternalServiceImpl<doris::PBackendService>::_exec_plan_fragment (this=this@entry=0x731f680, ser_request=...) at ../src/runtime/exec_env.h:117
#18 0x000000000159419f in doris::PInternalServiceImpl<doris::PBackendService>::exec_plan_fragment (this=0x731f680, cntl_base=<optimized out>, request=<optimized out>, response=0x161fd660, done=0x169b0c80)
    at /home/disk4/xuyang/work/baidu/bdg/doris/thirdparty-gcc10/installed/include/google/protobuf/arenastring.h:231
#19 0x000000000217b1b7 in brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) () at ../src/brpc/policy/http_rpc_protocol.cpp:1484
#20 0x00000000021485d7 in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x1622f210) at ../src/brpc/input_messenger.cpp:135
#21 0x000000000214949e in operator() (last_msg=0x1622f210, this=<synthetic pointer>) at ../src/brpc/input_messenger.cpp:141
#22 ~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/unique_ptr.h:360
#23 brpc::InputMessenger::OnNewMessages(brpc::Socket*) () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/unique_ptr.h:354
#24 0x00000000021f19fe in brpc::Socket::ProcessEvent(void*) () at ../src/brpc/socket.cpp:1017
#25 0x000000000229a25f in bthread::TaskGroup::task_runner(long) () at ../src/bthread/task_group.cpp:296
#26 0x000000000228b661 in bthread_make_fcontext () at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/stl_iterator.h:953
```

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6462 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exprs/tuple_is_null_predicate.cpp [hunk 1]
```diff
@@ -36,8 +36,10 @@ Status TupleIsNullPredicate::prepare(RuntimeState* state, const RowDescriptor& r
     // Resolve tuple ids to tuple indexes.
     for (int i = 0; i < _tuple_ids.size(); ++i) {
         int32_t tuple_idx = row_desc.get_tuple_idx(_tuple_ids[i]);
-        if (row_desc.tuple_is_nullable(tuple_idx)) {
-            _tuple_idxs.push_back(tuple_idx);
+        if (tuple_idx != RowDescriptor::INVALID_IDX) {
```
Comment (morningman) [inline be/src/exprs/tuple_is_null_predicate.cpp:39]: Why there is INVALID_IDX?

**Comment by EmmyMiao87** [comment]
Please add some unite test.
Could you please give a example query of this bug

**Review by xy720 — COMMENTED** [review]
Sql case have been added in issue. You can have a view. @EmmyMiao87 .

File: fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java [hunk 2]
```diff
@@ -338,4 +344,28 @@ public void testAccessingVisibleColumnWithoutPartition() throws Exception {
...
+        StmtExecutor stmtExecutor = new StmtExecutor(ctx, sql);
+        stmtExecutor.execute();
+        Assert.assertNotNull(stmtExecutor.planner());
+        Planner planner = stmtExecutor.planner();
+        List<PlanFragment> fragments = planner.getFragments();
+        Assert.assertTrue(fragments.size() > 0);
+        PlanNode node = fragments.get(0).getPlanRoot().getChild(0);
+        Assert.assertTrue(node.getChildren().size() > 0);
+        Assert.assertTrue(node instanceof SortNode);
+        SortNode sortNode = (SortNode) node;
```
Comment (EmmyMiao87) [inline fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java:363]: check ```sortTupleSlotExprs_```

Comment (xy720) [reply fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java:363]: ok, done.

**Review by morningman — APPROVED** [review]
LGTM
