### PR TITLE
[fix](alter-job) Missing alter job when doing checkpoint image

### LINKED ISSUE #9330: [Bug] alter job is missing in iamge
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

in #8030, we removed lots of code about old meta data in FE, 
But the logic of saveAlterJob was modified incorrectly. Cause the alter job to be lost in the image.
But this may not bring data problems, the analysis is as follows:

### Case 1. Do checkpoint before job is finished.
* [image: alter job(pending)]: The job information is lost, but the data is not changed. Like nothing happened.
* [image: alter job(pending)] + [editlog: alter job(waiting_txn)]: The information in the pending stage is lost, but there is still complete job information in the edit log, and the execution can continue.

### Case 2. Do checkpoint after job is finished.
* [image: alter job(finished)]: Modifications to metadata are already stored in the image, the only thing missing is the job history.

So this error does not result in a data error.
But it remains a potential risk.

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #9330

## Problem Summary:

This bug is introduced from #8030

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Nod)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 1]
```diff
@@ -2113,6 +2109,13 @@ public long saveAlterJob(CountingDataOutputStream dos, long checksum) throws IOE
 
     public long saveAlterJob(CountingDataOutputStream dos, long checksum, JobType type) throws IOException {
         Map<Long, AlterJobV2> alterJobsV2 = Maps.newHashMap();
```
Comment (xy720) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:2111]:
```suggestion
        Map<Long, AlterJobV2> alterJobsV2;
```

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java]: done

**Review by xy720 — APPROVED** [review]
LGTM
