### PR TITLE
fix NPE in SysVariableDesc::equal

### LINKED ISSUE #7701: [Bug]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.1-rc09

### What's Wrong?

multiple select system variables like

 select @@storage_engine,@@storage_engine;

return 

ERROR 1064 (HY000): errCode = 2, detailMessage = Unexpected exception: null

### What You Expected?

it should display two columns 

### How to Reproduce?

_No response_

### Anything Else?

block using jetbrains datagrip

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GoGoWen**
# Proposed changes

Issue Number: close #7701

## Problem Summary:

no

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SysVariableDesc.java [hunk 1]
```diff
@@ -189,6 +189,15 @@ public boolean equals(Object obj) {
...
+
+        if (literalExpr != null) {
+            return literalExpr.equals(((SysVariableDesc) obj).getLiteralExpr());
+        } else {
+            if (((SysVariableDesc) obj).getLiteralExpr() == null) {
+                return true;
+            } else {
+                return false;
+            }
+        }
```
Comment (adonis0147) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SysVariableDesc.java:201]: You can just type the following code to achieve the same effect.

```Java
Objects.equals(literalExpr, ((SysVariableDesc) obj).getLiteralExpr());
```

Besides, don't forget `import java.util.Objects;`.

Comment (GoGoWen) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SysVariableDesc.java]: nice, done

**Review by morningman — APPROVED** [review]
LGTM
