### PR TITLE
[Bug] Fix some bugs(rewrite rule/symbol transport) of `like predicate`

### LINKED ISSUE #8769: [Bug] Fix some bug of like predicate
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

There have multiple problems of predicate like.
1. predicate like will core dump on vectorized engine, because lack prepare/close symbol.
2. rewrite rule of predicate like support int type only cast slotref, other type(etc. literal/function call) not work as well.
3. rewrite rule not work on fold const value. 

### What You Expected?

fix it.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #8769

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by EmmyMiao87** [comment]
Pay attention to the PR title

File: fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java [hunk 1]
```diff
@@ -311,7 +310,6 @@ public GlobalState(Catalog catalog, ConnectContext context) {
             rules.add(RewriteDateLiteralRule.INSTANCE);
             rules.add(RewriteEncryptKeyRule.INSTANCE);
             rules.add(RewriteAliasFunctionRule.INSTANCE);
-            rules.add(RewriteLikePredicateRule.INSTANCE);
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java:314]: Is it ok for 'non-vec' without any be changed ?

Comment (BiteTheDDDDt) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java:314]: > Is it ok for 'non-vec' without any be changed ?

I searched and deleted all code whitch use  `RewriteLikePredicateRule`.

Comment (EmmyMiao87) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java:314]: I understand that the reason why FE added this rule before is PR because the direct execution of non-vectorized code will make mistakes.
If only changing FE but not BE, will the non-vectorized code now go wrong?

**Comment by EmmyMiao87** [comment]
There is no problem with the code, but due to new suites, it is necessary to wait for the framework pr #8792 to be merged before merging this pr.

**Comment by EmmyMiao87** [comment]
Please fix the test conflict ~

**Comment by EmmyMiao87** [comment]
There are many cases failed. Please check it ~

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
