### PR TITLE
[fix] (schema change) Fix BE crash after schema change int column to varchar column(#8073)

### LINKED ISSUE #8073: [Bug] BE crashed after altering int field to string
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-0.14
branch-0.15 df2c7563b08e94801daeb4370a1627886dbc3d34

### What's Wrong?

after alter schema, changing bigint column to string (release 0.14) or varchar (release 0.15), be is down.

### What You Expected?

safely alter schema:
`alter table table_1 modify column b varchar(1);`

### How to Reproduce?

1. create a table `table_1`
```
CREATE TABLE `table_1` ( 
    `a` bigint(20) NULL COMMENT "主键", 
    `b` int(11) NULL COMMENT "", 
ENGINE=OLAP UNIQUE KEY(`a`) COMMENT "" 
DISTRIBUTED BY HASH(`a`) BUCKETS 8 
PROPERTIES ( 
    "replication_num" = "1", 
    "in_memory" = "false", 
    "storage_format" = "V2"
);
```
2. load data into `table_1` ( 10000 tuples)
3. `alter table table_1 modify column b varchar(1);`
4. BE crashed.

### Anything Else?

with a few tuples, eg. 10 tuples, after altering schema, BE still alive, but results of `select * from table_1`  are messed.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jacktengg**
# Proposed changes

Issue Number: close #8073 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java [hunk 1]
```diff
@@ -386,6 +386,14 @@ public void checkSchemaChangeAllowed(Column other) throws DdlException {
             throw new DdlException("Can not change " + getDataType() + " to " + other.getDataType());
         }
 
+        if (type.isNumericType() && other.type.isStringType()) {
+            Integer lSize = type.getColumnStringRepSize();
+            Integer rSize = other.type.getColumnStringRepSize();
+            if (rSize < lSize) {
+                throw new DdlException("Can not change from wider type to narrower type");
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java:393]: Add more detail info in error msg, such as column name, lSize, rSize.
So that user can easy debugging.

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java [hunk 2]
```diff
@@ -659,6 +659,36 @@ public Integer getColumnSize() {
         }
     }
 
+    /**
+     * For schema change, convert data type to string,
+     * get the size of string representation
+     */
+    public Integer getColumnStringRepSize() {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java:666]: I think the BE side also needs to have a self-defense mechanism to ensure that when the FE does not judge the length correctly, it will not cause the BE to crash?

Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java:666]: Not use integer, use int is ok

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java [hunk 3]
```diff
@@ -659,6 +659,36 @@ public Integer getColumnSize() {
...
+            return size;
+        }
+        ScalarType t = (ScalarType) this;
+        switch (t.getPrimitiveType()) {
+            case CHAR:
+            case VARCHAR:
+            case STRING:
+                return t.getLength();
+            default:
+                return null;
```
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java:688]: It is better to throw exception here?

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java (hunk 1 above)
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java:393]: BE should also have a similar mechanism to check the type length during a schema change. It should fail the alter task in BE not crash.

**Review by morningman — APPROVED** [review]
LGTM
