### PR TITLE
[Bug] [Vectorized] add padding when load char type data

### LINKED ISSUE #9733: [Bug] [Vectorized] add padding when load char type data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Now we write char type data miss padding phase.

### What You Expected?

fix

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #9733

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/olap/olap_data_convertor.cpp [hunk 1]
```diff
@@ -372,6 +372,21 @@ Status OlapBlockDataConvertor::OlapColumnDataConvertorChar::convert_to_olap() {
 
     assert(column_string);
 
+    size_t rows = column_string->size();
+    if (column_string->chars_size() != _length * rows) {
+        _column = vectorized::ColumnString::create();
+        auto padded_column =
+                assert_cast<vectorized::ColumnString*>(_column->assume_mutable().get());
+        padded_column->resize(rows);
```
Comment (cambyzju) [inline be/src/vec/olap/olap_data_convertor.cpp:380]:
```suggestion
        padded_column->reserve(rows);
```

File: be/src/vec/olap/olap_data_convertor.h [hunk 2]
```diff
@@ -99,8 +102,41 @@ class OlapBlockDataConvertor {
...
+            // Check sum of data length, including terminating zero.
+            return column->size() * (padding_length + 1) != column->chars.size();
+        }
+
+        static void insert_data_padded(ColumnString* column, StringRef str, size_t padding_length) {
+            const size_t old_size = column->chars.size();
+            const size_t data_size = old_size + str.size;
+            const size_t full_size = old_size + padding_length + 1;
+
+            column->chars.resize(full_size);
```
Comment (HappenLee) [inline be/src/vec/olap/olap_data_convertor.h:115]: not do the work in `insert_data_padded`

File: be/src/vec/olap/olap_data_convertor.h [hunk 3]
```diff
@@ -99,8 +102,41 @@ class OlapBlockDataConvertor {
...
+                memcpy(column->chars.data() + old_size, str.data, str.size);
+            }
+            memset(column->chars.data() + data_size, 0, full_size - data_size);
+        }
+
+        static ColumnPtr clone_and_padding(const ColumnString* input, size_t padding_length) {
+            auto column = vectorized::ColumnString::create();
+            auto padded_column =
+                    assert_cast<vectorized::ColumnString*>(column->assume_mutable().get());
+            padded_column->reserve(input->size());
```
Comment (HappenLee) [inline be/src/vec/olap/olap_data_convertor.h:128]: resize/memset chars `column->size() * (padding_length + 1)`
resize offsets `column->size()`

**Review by HappenLee — APPROVED** [review]
LGTM
