### PR TITLE
[Bug] Fix bug that new coming routine load tasks are rejected all the time and report TOO_MANY_TASK error

### LINKED ISSUE #9162: [Bug] New coming routine load tasks are always rejected and report TOO_MANY_TASK error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

latest version

### What's Wrong?

Routine load task cannot be submitted to any backends.
It looks like all backend's task pools are full.

Fe log:
failed to submit task. error code: TOO_MANY_TASKS, msg: 47cbfcef3f7a436b-a591c509911788b0.

Be log:
[routine_load_task_executor.cpp:138] too many tasks in thread pool. reject task: 47cbfcef3f7a436b-a591c509911788b0, job id: 207405, queue size: 0, current tasks num: 10

### What You Expected?

Act normal.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xy720**
# Proposed changes

Issue Number: close #9162 

## Problem Summary:

This bug is caused by the data consumer group which is get by the routine load task.
Sometimes, the kafka's begin offsets is not set by Fe, so that 0 data consumer will be assigned in the data consumer group.
Then the routine load task will be stuck in data consumer group's start_all function, and the fragment corresponding to this task will never be closed.
As the result, this routine load task will never be removed from task pool so that the task pool will full soon and reject any new coming routine load task.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by qidaye — DISMISSED** [review]
LGTM

File: be/src/runtime/routine_load/data_consumer_pool.cpp [hunk 1]
```diff
@@ -67,12 +67,18 @@ Status DataConsumerPool::get_consumer_grp(StreamLoadContext* ctx,
                 "PAUSE: Currently only support consumer group for Kafka data source");
     }
     DCHECK(ctx->kafka_info);
+    DCHECK(ctx->kafka_info->begin_offset.size() > 0);
```
Comment (morningman) [inline be/src/runtime/routine_load/data_consumer_pool.cpp:70]: `DCHECK` means it must `> 0`;
So there should not be `consumer_num < 1`.

Why the begin offset is empty? Is it normal?

Comment (xy720) [reply be/src/runtime/routine_load/data_consumer_pool.cpp:70]: In the create statement example below, you can see 
The user didn't specify the custom partitions.
So that 1、Fe will get all kafka partitions from server in routine load's scheduler.
The user set the default offset by datetime.
So that 2、Fe will get kafka offset by time from server in routine load's scheduler.

When 1 is success, meanwhile 2 is failed, the progress of this routine load may not contains any partitions and offsets.
Nevertheless, since newCurrentKafkaPartition which is get by kafka server may be always equal to currentKafkaPartitions, the wrong progress will never be updated.

**Review by xy720 — COMMENTED** [review]
I have found a example create statement that may cause this problem.

CREATE ROUTINE LOAD iaas.dws_nat ON dws_nat 
WITH APPEND PROPERTIES ( 
"desired_concurrent_number"="2", 
"max_batch_interval" = "20", 
"max_batch_rows" = "400000", 
"max_batch_size" = "314572800", 
"format" = "json", 
"max_error_number" = "0" 
) 
FROM KAFKA ( 
"kafka_broker_list" = "xxxx:xxxx", 
"kafka_topic" = "nat_nsq", 
"property.kafka_default_offsets" = "2022-04-19 13:20:00"
)

**Review by xy720 — COMMENTED** [review]
During the schedule process, the following error is reported in the step of getting offset for time in KafkaUtil.

483755220206e935b91415336458ca62

File: be/src/runtime/routine_load/data_consumer_pool.cpp (hunk 1 above)
Comment (morningman) [reply be/src/runtime/routine_load/data_consumer_pool.cpp:70]: I think we should let the task fail directly if `ctx->kafka_info->begin_offset.size() == 0`, so that it can be easier to find error.

Comment (xy720) [reply be/src/runtime/routine_load/data_consumer_pool.cpp]: Ok. Now the task will fail in get_consumer_grp method if the size of begin_offset is equal to 0.

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

File: be/src/runtime/routine_load/data_consumer_pool.cpp [hunk 2]
```diff
@@ -68,11 +68,17 @@ Status DataConsumerPool::get_consumer_grp(StreamLoadContext* ctx,
     }
     DCHECK(ctx->kafka_info);
 
+    if (ctx->kafka_info->begin_offset.size() == 0) {
+        return Status::InternalError(
```
Comment (pengxiangyu) [inline be/src/runtime/routine_load/data_consumer_pool.cpp:72]: This is not an error, if a pipe has not data for a long time, it will write a lot of error logs.
Check it before call get_consumer_grp maybe better. Otherwise check return value and don't write warning log each time.

**Review by pengxiangyu — CHANGES_REQUESTED** [review]
