### PR TITLE
[fix](bloom filter)Fix drop column with bloom filter

### LINKED ISSUE #41368: [Bug] drop column with bloom filter error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.


### Version

master

### What's Wrong?

When drop a column which has bloom filter, the column is dropped, but the bloom filter info are not dropped.

### What You Expected?

Drop column and the bloom filter is dropped too.

### How to Reproduce?

```
mysql> create table table1 (
    ->     k1 INT,
    ->     c1 varchar(10),
    -> ) duplicate key(k1) distributed by hash(k1) buckets 1
    -> properties(
    ->     "replication_num" = "1",
    ->     "bloom_filter_columns" = "c1"
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql>
mysql> alter table table1 drop column c1;
Query OK, 0 rows affected (0.01 sec)

mysql> show create table table1;
+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| table1 | CREATE TABLE `table1` (
  `k1` int NULL
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"bloom_filter_columns" = "",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"binlog.enable" = "false",
"binlog.ttl_seconds" = "86400",
"binlog.max_bytes" = "9223372036854775807",
"binlog.max_history_nums" = "9223372036854775807",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
); |
+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #41368

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java [hunk 1]
```diff
@@ -430,6 +430,18 @@ private boolean processDropColumn(DropColumnClause alterClause, OlapTable olapTa
...
+            Set<String> bfCols = olapTable.getCopiedBfColumns();
+            if (bfCols != null) {
+                Set<String> newBfCols = new HashSet<>();
+                for (String bfCol : bfCols) {
+                    if (!bfCol.equalsIgnoreCase(dropColName)) {
+                        newBfCols.add(bfCol);
+                    }
+                }
+                olapTable.setBloomFilterInfo(newBfCols, olapTable.getBfFpp());
+            }
```
Comment (airborne12) [inline fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java:443]: may be this can be better
```
Set<String> bfCols = olapTable.getCopiedBfColumns();
if (bfCols != null) {
    Set<String> newBfCols = bfCols.stream()
                                  .filter(bfCol -> !bfCol.equalsIgnoreCase(dropColName))
                                  .collect(Collectors.toSet());
    olapTable.setBloomFilterInfo(newBfCols, olapTable.getBfFpp());
}
```
