### PR TITLE
[fix](catalog) fix data_sub/data_add func pushdown in jdbcscan

### LINKED ISSUE #30692: [Bug] sql解析错误， FUNCTION isoc.days_sub does not exist
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

select DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) +7 DAY),'%Y-%m-%d'), DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 1 DAY),'%Y-%m-%d');
这条sql这样子跑可执行正确；date_sub可以识别成函数
image

这样子写则无法识别函数：
SELECT count(distinct iot_id) as sum from mysql_160.isoc.t_isoc_asset_black_list_day_count 
where date>=DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) +7 DAY),'%Y-%m-%d')
and date<=  DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 1 DAY),'%Y-%m-%d')
image

这样子写可以正常执行：
SELECT count(distinct iot_id) as sum from mysql_160.isoc.t_isoc_asset_black_list_day_count 
image

### What You Expected?

解决该问题

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #30692

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcFunctionPushDownRule.java [hunk 1]
```diff
@@ -168,9 +171,48 @@ private static String replaceFunctionNameIfNecessary(String func, Predicate<Stri
...
                 functionCallExpr.setFnName(FunctionName.createBuiltinName(newFunc));
-                func = functionCallExpr.getFnName().getFunction();
             }
         }
-        return func;
+    }
+
+    // Function used to convert nereids planner's function to old planner's function
+    private static Expr replaceGenericFunctionExpr(FunctionCallExpr functionCallExpr, String func) {
+        Map<String, String> supportedTimeUnits = Maps.newHashMap();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcFunctionPushDownRule.java:180]: This should a static field?

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcFunctionPushDownRule.java (hunk 1 above)
Comment (zy-kkk) [reply fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcFunctionPushDownRule.java:180]: replaceGenericFunctionExpr is static because it processes based on parameters without requiring object state, and it's used in static contexts where non-static methods cannot be called directly.

**Review by morningman — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
