### PR TITLE
[Bug][Alter] Cancel the alter job if database has been dropped

### LINKED ISSUE #4087: [Bug] Schema change job is not cancelled after database being dropped.
18561594639681_ pic_hd

### PR DESCRIPTION
**Pull request by morningman**
Cancel the alter job in WAITING_TXN state if database has been dropped
Fix: #4087

### CODE REVIEW

File: fe/src/main/java/org/apache/doris/clone/TabletScheduler.java [hunk 1]
```diff
@@ -879,9 +880,14 @@ private void deleteReplicaInternal(TabletSchedCtx tabletCtx, Replica replica, St
             throw new SchedException(Status.SCHEDULE_FAILED, "set watermark txn " + nextTxnId);
         } else if (replica.getState() == ReplicaState.DECOMMISSION && replica.getWatermarkTxnId() != -1) {
             long watermarkTxnId = replica.getWatermarkTxnId();
-            if (!Catalog.getCurrentGlobalTransactionMgr().isPreviousTransactionsFinished(watermarkTxnId,
-                    tabletCtx.getDbId(), Lists.newArrayList(tabletCtx.getTblId()))) {
-                throw new SchedException(Status.SCHEDULE_FAILED, "wait txn before " + watermarkTxnId + " to be finished");
+            try {
+                if (!Catalog.getCurrentGlobalTransactionMgr().isPreviousTransactionsFinished(watermarkTxnId,
+                        tabletCtx.getDbId(), Lists.newArrayList(tabletCtx.getTblId()))) {
+                    throw new SchedException(Status.SCHEDULE_FAILED,
```
Comment (wuyunfeng) [inline fe/src/main/java/org/apache/doris/clone/TabletScheduler.java:886]: `SchedExcepition` looks so stranger...

**Review by wuyunfeng — DISMISSED** [review]
I left some minor comment, but this looks good to me.

File: fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java [hunk 2]
```diff
@@ -238,17 +238,25 @@ public void finishTransaction(long dbId, long transactionId, Set<Long> errorRepl
     }
 
     /**
-     * check if there exists a load job before the endTransactionId have all finished
+     * check if there exists a load job before the endTransactionId have all
```
Comment (wuyunfeng) [inline fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java:241]:
```suggestion
     * Check whether a load job already exists before the `endTransactionId` contains all `TransactionId` related with this load job.
```

File: fe/src/main/java/org/apache/doris/clone/TabletScheduler.java (hunk 1 above)
Comment (morningman) [reply fe/src/main/java/org/apache/doris/clone/TabletScheduler.java:886]: bear it! LOL

**Review by wuyunfeng — APPROVED** [review]

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
