### PR TITLE
[Bug] Fix bug of core local value

### LINKED ISSUE #4452: [Bug] core problem when load json data, when the jsonpaths not inappropriate with table column
**Describe the bug**
There have a table：
```
CREATE TABLE `json_table` (
  `k1` tinyint(4) NULL COMMENT "",
  `k2` smallint(6) NULL COMMENT "",
  `k3` int(11) NULL COMMENT "",
  `k4` bigint(20) NULL COMMENT "",
  `k5` datetime NULL COMMENT "",
  `v6` decimal(20, 7) SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 15
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);
```

if we load the data do not include `v6`, will core sometime

```
curl --location-trusted -u test:test_passwd -H "format: json" -H "jsonpaths:[\"$.k1\", \"$.k2\", \"$.k3\", \"$.k4\", \"$.k5\"]" -T json_object_basic.json http://localhost:8086/api/test/json_table/_stream_load
```

### LINKED ISSUE #4522: [Bug] BE crash when restarting
**Describe the bug**

```
*** Aborted at 1599045887 (unix time) try "date -d @1599045887" if you are using GNU date ***
PC: @          0x25ed67b tcmalloc::ThreadCache::ReleaseToCentralCache()
*** SIGSEGV (@0x0) received by PID 52721 (TID 0x7fa015be2700) from PID 0; stack trace: ***
    @     0x7fa01b032470 (unknown)
    @          0x25ed67b tcmalloc::ThreadCache::ReleaseToCentralCache()
    @          0x25eda05 tcmalloc::ThreadCache::ListTooLong()
    @          0x1175021 std::vector<>::_M_default_append()
    @          0x11753bc doris::CoreDataAllocatorImpl<>::get_or_create()
    @           0xebea5d doris::BaseTablet::BaseTablet()
    @           0xe560e9 doris::Tablet::Tablet()
    @           0xe56535 doris::Tablet::create_tablet_from_meta()
    @           0xe6c259 doris::TabletManager::load_tablet_from_meta()
    @           0xe4de26 _ZNSt17_Function_handlerIFbllRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEZN5doris7DataDir4loadEvEUlliS7_E0_E9_M_invokeERKSt9_Any_dataOlSG_S7_
    @           0xe7e396 _ZNSt17_Function_handlerIFbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_EZN5doris17TabletMetaManager16traverse_headersEPNS9_8OlapMetaERKSt8functionIFbllS7_EES7_EUlS7_S7_E_E9_M_invokeERKSt9_Any_dataS7_S7_
    @           0xedd3b8 doris::OlapMeta::iterate()
    @           0xe7c358 doris::TabletMetaManager::traverse_headers()
    @           0xe51cee doris::DataDir::load()
    @           0xe36969 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5doris13StorageEngine14load_data_dirsERKSt6vectorIPNS3_7DataDirESaIS7_EEEUlvE_EEEEE6_M_runEv
    @          0x26ed17f execute_native_thread_routine
    @     0x7fa01ade71c3 start_thread
    @     0x7fa01b0e412d __clone
```

This problem will only appear when BE has a lot of tablets, because #4428 introduces tablet-level metrics.
This will result in a large number of core local values. The previous code logic is generating core local values,
and the corresponding data structures are not protected by locks, which leads to memory access errors.

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

When creating core local value from CoreDataAllocator,
A lock is needed to protect the modification of _blocks.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have create an issue on (Fix #4522), and have described the bug/feature there in detail

### CODE REVIEW

File: be/src/util/core_local.cpp [hunk 1]
```diff
@@ -61,6 +65,7 @@ class CoreDataAllocatorImpl : public CoreDataAllocator {
     }
 private:
     static constexpr int ELEMENTS_PER_BLOCK = BLOCK_SIZE / ELEMENT_BYTES;
+    SpinLock _lock; // lock to protect the modification of _blocks
```
Comment (chaoyli) [inline be/src/util/core_local.cpp:68]: CoreData is to bind data to cpu to eliminate the lock.
If add a lock, it's design is meaningless.

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: be/src/util/core_local.cpp (hunk 1 above)
Comment (morningman) [reply be/src/util/core_local.cpp:68]: This is only used when creating the core local value (by calling `get_or_create()` of `CoreDataAllocatorImpl`).
And when creating the value, there is nothing to do with "cpu-bind".

The so called "cpu-bind" operation happens when accessing the `CoreLocalValue`,
not related to `CoreDataAllocatorImpl`

Comment (chaoyli) [reply be/src/util/core_local.cpp:68]: OK, I have no problem.

**Review by chaoyli — APPROVED** [review]
