### PR TITLE
[Bug] Fix bug that call frontend service failed when rpc_timeout is equal with publish_timeout

### LINKED ISSUE #5565: [Bug] we may see call frontend service failed when rpc_timeout is equal with publish_timeout
**Describe the bug**
when rpc_timeout is equal with publish_timeout，we may see that call frontend service failed  when cluster publish transaction timeout, and then program will try to rollback transaction and user will retry stream load again, which will bring the cluster more pressure

**To Reproduce**
1. put many stream loads at the same time

**Expected behavior**
if publish transaction timeout, we should return publis timeout instead of call frontend service failed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

This PR is to fix bug that call frontend service failed when rpc_timeout is equal with publish_timeout and fix some small issue with log

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5565 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java [hunk 1]
```diff
@@ -94,9 +94,9 @@ public TMasterResult finishTask(TFinishTaskRequest request) {
         // check task status
         // retry task by report process
         TStatus taskStatus = request.getTaskStatus();
-        LOG.debug("get task report: {}", request.toString());
+        LOG.debug("get task report: {}", request);
```
Comment (stdpain) [inline fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java:97]: It's a better way to use 
```java
if (LOG.isDebugEnabled()) {
    LOG.debug("get task report: {}", request);
}
```

Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java]: ok

File: fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java [hunk 2]
```diff
@@ -822,7 +822,7 @@ private boolean loadTxnCommitImpl(TLoadTxnCommitRequest request) throws UserExce
             throw new UserException("unknown database, database=" + dbName);
         }
 
-        long timeoutMs = request.isSetThriftRpcTimeoutMs() ? request.getThriftRpcTimeoutMs() : 5000;
+        long timeoutMs = request.isSetThriftRpcTimeoutMs() ? request.getThriftRpcTimeoutMs() / 2 : 5000;
```
Comment (acelyc111) [inline fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java:825]: could you please explain why divide by 2?

Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java:825]: This is an experience value, here we just ensure that the rpc_timeout value is larger enough than  timeoutMs  to keep timeout setting consistent with before, to reduce the "call frontend service failed error" occur times. But I think there is still some improvement we can do that we should compute the left time that  timeoutMillis minus commit time cost to improve the  Probability of publish timeout instead of "call frontend service failed" when commit or publish version performance is poor

**Review by morningman — APPROVED** [review]
LGTM
