### PR TITLE
[Broker Load] Ignore empty file when file format is parquet or orc.

### LINKED ISSUE #4812: [Load] Error when reading empty Parquet or Orc files
**Describe the bug**
Doris can not read empty Parquet or Orc files when doing load. So these empty file should be skipped.

Error:
`type:LOAD_RUN_FAIL; msg:ParseError : Invalid column selected _col0`

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

We can not read empty parquet or orc format file. So we should skip them
when doing broker load.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have create an issue on (Fix #4812), and have described the bug/feature there in detail

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java [hunk 1]
```diff
@@ -77,18 +77,32 @@ private void getAllFileStatus() throws UserException {
...
+                        if (LOG.isDebugEnabled()) {
+                            LOG.debug(new LogBuilder(LogKey.LOAD_JOB, callback.getCallbackId())
+                                    .add("file_status", fstatus).build());
+                        }
                     }
                 }
+                fileStatusList.add(filteredFileStatuses);
                 tableTotalFileSize += groupFileSize;
-                tableTotalFileNum += fileStatuses.size();
+                tableTotalFileNum += fileNum;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java:103]: `filteredFileStatuses.size` seems equal `fileNum`, we could remove fileNum.

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java]: Removed

**Review by kangkaisen — APPROVED** [review]
+1
