### PR TITLE
[enhancement](timeout) fix set timeout failure and simplify timeout logic

### LINKED ISSUE #17544: [Bug] session variables query_timeout and insert_timeout lose effect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

As seen, both query_timeout and insert_timeout lose effect.
```
mysql> set query_timeout = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> set insert_timeout = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into lineorder select * from lineorder limit 10000000;
Query OK, 10000000 rows affected (8.89 sec)
{'label':'insert_a8fd968e3bf14732_a11221493ff412d2', 'status':'VISIBLE', 'txnId':'19'}

mysql> select * from lineorder limit 1000000;
1000000 rows in set (2.65 sec)
```
The certain info is that both the session variables are modified sucessfully.
```
mysql> select @@session.query_timeout;
+-----------------+
| @@query_timeout |
+-----------------+
|               1 |
+-----------------+
1 row in set (0.01 sec)

mysql> select @@session.insert_timeout;
+------------------+
| @@insert_timeout |
+------------------+
|                1 |
+------------------+
1 row in set (0.00 sec)
```

### What You Expected?

The timeout execution should come out with a timeout result. 

### How to Reproduce?

1. Set query_timeout and insert_timeout to a small val.
2. Do a slow queries or insert.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

Issue Number: close #17544

## Problem summary

Execution timeout is not reset correctly by the session var, because not all query logic would pass through and trigger out the execution timeout reset.

Currently we move execution timeout calculation into getter to calculate a realtime execution timeout when we about to use it, rather than set or reset it in many other places, which add lots of complexity.

fix result

```
mysql> set query_timeout = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> set insert_timeout = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from lineorder limit 1000000;
ERROR 1105 (HY000): errCode = 2, detailMessage = query timeout

mysql> insert into lineorder select * from lineorder limit 10000000;
ERROR 1105 (HY000): errCode = 2, detailMessage = Execute timeout

mysql> create table copy_lineorder PROPERTIES("replication_num" = "1") as select * from lineorder li
mit 10000000;
ERROR 1105 (HY000): errCode = 2, detailMessage = Execute timeout
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run p0

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java [hunk 1]
```diff
@@ -652,16 +644,33 @@ public String getCurrentConnectedFEIp() {
...
+     * @return exact execution timeout
+     */
     public int getExecTimeout() {
+        if (env != null) {
+            userQueryTimeout = env.getAuth().getQueryTimeout(qualifiedUser);
+        }
+        if (userQueryTimeout > 0) {
+            // user-set query-timeout, has the highest priority
+            executionTimeoutS = (int) userQueryTimeout;
+        } else if (executor.isInsertStmt()) {
```
Comment (SaintBacchus) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:667]: check null of `executor `

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java [hunk 2]
```diff
@@ -652,16 +644,33 @@ public String getCurrentConnectedFEIp() {
...
-    }
-
+    /**
+     * We calculate and get the exact execution timeout here, rather than setting
+     * execution timeout in many other places.
+     *
+     * @return exact execution timeout
+     */
     public int getExecTimeout() {
+        if (env != null) {
```
Comment (SaintBacchus) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:661]: Can get env from `Env.getCurrentEnv`

**Comment by TangSiyang2001** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java (hunk 1 above)
Comment (TangSiyang2001) [reply fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:667]: Ok, I'll modify it.

**Comment by TangSiyang2001** [comment]
run build all

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java [hunk 3]
```diff
@@ -596,20 +595,13 @@ public void checkTimeout(long now) {
...
-                timeout = executionTimeoutS * 1000L;
-            }
-            //deal with insert stmt particularly
+            // insert stmt particularly
             if (executor != null && executor.isInsertStmt()) {
                 timeoutTag = "insert";
             }
-
+            //to ms
+            long timeout = executionTimeoutS * 1000L;
```
Comment (SaintBacchus) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:604]:
```suggestion
            long timeout = getExecTimeout() * 1000L;
```
Why not use method to get the timeout value

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java [hunk 4]
```diff
@@ -652,16 +644,31 @@ public String getCurrentConnectedFEIp() {
...
-    }
-
+    /**
+     * We calculate and get the exact execution timeout here, rather than setting
+     * execution timeout in many other places.
+     *
+     * @return exact execution timeout
+     */
     public int getExecTimeout() {
+        userQueryTimeout = Env.getCurrentEnv().getAuth().getQueryTimeout(qualifiedUser);
```
Comment (SaintBacchus) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:661]: this is a temp value of uer timeout.  If user timeout was -1, it will make the killer thread bad.

In my suggestion, do not modify the value of executionTimeoutS in `getExecTimeout()` just return the right value.

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java (hunk 3 above)
Comment (TangSiyang2001) [reply fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:604]: Because MysqlLoadManager#executeMySqlLoadJobFromStmt seems have to use setExecutionTimeout to directly control the kill thread behavior, if I use getter here, will it affect the MysqlLoadManager#executeMySqlLoadJobFromStmt?

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java (hunk 4 above)
Comment (TangSiyang2001) [reply fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java:661]: If user timeout was -1, we will not use it as execution timeout, and will use session var instead. And in ConnectContext#checkTimeout, we use directly use executionTimeout for kill thread timeout checking. If we can change the setExecTimeout behavior in MysqlLoadManager#executeMySqlLoadJobFromStmt, the problem will be completely solved.

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by freemandealer** [comment]
There are some bugs involving timeout in FE UTs and P0 regression that cannot be resolved simply by retrying the pipeline. You can click the `Details` buttons on the right to check the 'Build Log' for specific failures.

**Comment by TangSiyang2001** [comment]
> There are some bugs involving timeout in FE UTs and P0 regression that cannot be resolved simply by retrying the pipeline. You can click the `Details` buttons on the right to check the 'Build Log' for specific failures.

OK, I think I've found out the problems.

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run build

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Review by liutang123 — APPROVED** [review]
LGTM
