### PR TITLE
[Bugfix] be crash when executing sql contains bitmap_intersect function

### LINKED ISSUE #9909: [Bug] be crash when executing sql contains bitmap_intersect function
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master 1.0

### What's Wrong?

be crash when executing sql

### What You Expected?

be return correct result

### How to Reproduce?

`create table test_bitmap (tag varchar(20),user_ids bitmap bitmap_union) aggregate key (tag) distributed by hash (tag) PROPERTIES("replication_num" = "1"); 

insert into test_bitmap values('A', to_bitmap(1)); 
insert into test_bitmap values('A', to_bitmap(2)); 
insert into test_bitmap values('A', to_bitmap(3)); 
insert into test_bitmap values('B', to_bitmap(1)); 
insert into test_bitmap values('B', to_bitmap(2)); 

set enable_vectorized_engine=false;

select (bitmap_intersect(user_ids))
from
(
    select
      tag,
      bitmap_union(user_ids) user_ids
    from
      test_bitmap
    group by
      tag HAVING tag not IN("A","B")
) t;
`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by starocean999**
# Proposed changes

Issue Number: close #9909 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exprs/bitmap_function.cpp [hunk 1]
```diff
@@ -393,7 +393,7 @@ StringVal BitmapFunctions::bitmap_hash(doris_udf::FunctionContext* ctx,
 
 StringVal BitmapFunctions::bitmap_serialize(FunctionContext* ctx, const StringVal& src) {
     if (src.is_null) {
-        return src;
```
Comment (morningman) [inline be/src/exprs/bitmap_function.cpp:396]: Could you explain more about the reason?
Maybe you can write some comment directly in code.
And P0 failed, please check.

**Review by yiguolei — APPROVED** [review]
LGTM
