### PR TITLE
[Fix](transaction) Fix committed transaction couldn't be finished when table is dropped

### LINKED ISSUE #8426: [Bug] Transaction may not be finished when table does not exist
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Transaction may not be finished when table does not exist

### What You Expected?

Transaction  can be finished when table does not exist

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #8426

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -793,19 +793,7 @@ public void finishTransaction(long transactionId, Set<Long> errorReplicaIds) thr
...
-                transactionState.setTransactionStatus(TransactionStatus.ABORTED);
-                transactionState.setReason("db is dropped");
-                LOG.warn("db is dropped during transaction, abort transaction {}", transactionState);
-                unprotectUpsertTransactionState(transactionState, false);
-                return;
-            } finally {
-                writeUnlock();
-            }
-        }
+        Database db = catalog.getDbOrMetaException(transactionState.getDbId());
```
Comment (wangbo) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:796]: Why not abort transaction when db is droped? Because it maybe recovered?

Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:798]: committed txn will be checked when db to be dropped. it will be aborted outside

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java [hunk 2]
```diff
@@ -410,28 +410,26 @@ public void dropTable(String tableName) {
         return views;
     }
 
-    public List<Table> getTablesOnIdOrderOrThrowException(List<Long> tableIdList) throws MetaNotFoundException {
-        List<Table> tableList = Lists.newArrayList();
+    public List<Table> getTablesOnIdOrderNullable(List<Long> tableIdList) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java:413]: Add comment to explain behavior of this method.
And it is strange to just ignore missing table instead of throwing exception.
The method name can not reflect this behavior, may leading misuse

File: fe/fe-core/src/main/java/org/apache/doris/common/util/MetaLockUtils.java [hunk 3]
```diff
@@ -17,6 +17,7 @@
 
 package org.apache.doris.common.util;
 
+import com.google.common.collect.Lists;
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/common/util/MetaLockUtils.java:20]: import order

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java [hunk 4]
```diff
@@ -17,6 +17,7 @@
 
 package org.apache.doris.transaction;
 
+import org.apache.commons.lang3.StringUtils;
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:20]: import order

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java [hunk 5]
```diff
@@ -793,22 +794,13 @@ public void finishTransaction(long transactionId, Set<Long> errorReplicaIds) thr
...
-                transactionState.setTransactionStatus(TransactionStatus.ABORTED);
-                transactionState.setReason("db is dropped");
-                LOG.warn("db is dropped during transaction, abort transaction {}", transactionState);
-                unprotectUpsertTransactionState(transactionState, false);
-                return;
-            } finally {
-                writeUnlock();
-            }
-        }
+        Database db = catalog.getDbOrMetaException(transactionState.getDbId());
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:797]: Add comment to describe the logic here.

**Comment by morningman** [comment]
Could you add more detail explaination of your modifying logic. Such as
1. What problem it is solved?
2. How can this solve the problem?
3. There is any concrete case to show?

**Comment by caiconghui** [comment]
> Could you add more detail explaination of your modifying logic. Such as
> 
> 1. What problem it is solved?
> 2. How can this solve the problem?
> 3. There is any concrete case to show?

this PR is to solve problem that transaction may not be finished, when some tables in table list have been dropped,
the solution is to finish transaction with exist table.

case1
table with committed txns and force drop table.

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java [hunk 6]
```diff
@@ -793,22 +794,20 @@ public void finishTransaction(long transactionId, Set<Long> errorReplicaIds) thr
...
-            }
-        }
+        // case 1 If database is dropped, then we just throw MetaNotFoundException, because all related tables are already force dropped,
+        // it is safe to abort the transaction with all tables been force dropped.
+        // case 2 If at least one table lock successfully, which means that the transaction should be finished for the existed tables
+        // while just ignore tables which have been dropped forcefully.
+        // case 3 Database exist and all tables already been dropped, this case is same with case1, just abort the transaction
+        // only three cases mentioned above may happen, because user cannot drop table without force while there are committed transactions on table
+        // and writeLockTablesIfExist is a blocking function, the returned result would be the existed table list which hold write lock
+        Database db = catalog.getDbOrMetaException(transactionState.getDbId());
```
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:804]: If database is recycled or dropped, db related txn manager will be removed. But when the db is restored from recycle bin,  some txns is lost, how to deal with this case?

File: fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java [hunk 7]
```diff
@@ -240,7 +241,13 @@ private void publishVersion() throws UserException {
                     // one transaction exception should not affect other transaction
                     globalTransactionMgr.finishTransaction(transactionState.getDbId(), transactionState.getTransactionId(), publishErrorReplicaIds);
                 } catch (Exception e) {
-                    LOG.warn("error happends when finish transaction {} ", transactionState.getTransactionId(), e);
+                    if (e instanceof MetaNotFoundException) {
+                        globalTransactionMgr.abortTransaction(transactionState.getDbId(), transactionState.getTransactionId(), e.getMessage(),
```
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java:245]: Do not need abort txn here? 
If the database is force dropped, we could not get db related txn manager and will skip the txn in next loop.

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM
