### PR TITLE
Fix large string val allocation failure

### LINKED ISSUE #3600: large bitmap serialization failed because of overflow of size
**Describe the bug**
when use bitmap to do insertsect, if the bitmap is large than the MAX_INT, the allocation of memory from free pool will failed, which will lead to serialization failed because of core dump.

the following is the bitmap size I come to is 3G+.

### PR DESCRIPTION
**Pull request by EmmyMiao87**
Large bitmap will need use StringVal to allocate large memory, which is large than MAX_INT.
The overflow will cause serialization failure of bitmap.

Fixed #3600

Change-Id: I720b9ea4646188a8e1402630601928b5f16fedb2

### CODE REVIEW

File: be/src/exprs/bitmap_function.cpp [hunk 1]
```diff
@@ -488,7 +488,8 @@ StringVal BitmapFunctions::bitmap_from_string(FunctionContext* ctx, const String
     }
 
     std::vector<uint64_t> bits;
-    if (!SplitStringAndParse({(const char*)input.ptr, input.len}, ",", &safe_strtou64, &bits)) {
+    // TODO(hkp): I think StringPiece's len should also be uint64_t
```
Comment (morningman) [inline be/src/exprs/bitmap_function.cpp:491]: Could you explain why not changing this to int64? You can just add comment here

**Review by morningman — APPROVED** [review]
LGTM
