### PR TITLE
Error happened when open a view in DBeaver

### LINKED ISSUE #4777: Error happened when open a view in DBeaver
**Describe the bug**
When you are operating doris using DBeaver, an error happens when you are opening a view.
You can't see the description information for a view in DBeaver.
This operation need to call SELECT CHECK_OPTION,DEFINER,IS_UPDATABLE FROM information_schema.VIEWS
information_schema.VIEWS doesn't exist, so it will get an error.

**To Reproduce**
1. Download DBeaver on version 6.0.0
2. Create a view
3. Open the view in DBeaver
4. You can see the error and can't get the description of the view.

**Expected behavior**
I want to see the description of the view.

**Additional context**
a new table names views is needed in database information_schema, which has the same schema as views in mysql.

### PR DESCRIPTION
**Pull request by pengxiangyu**
## Proposed changes

Fix bug #4777：Error happened when open a view in DBeaver

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #4777), and have described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

Fix bug #4777

### CODE REVIEW

**Comment by imay** [comment]
It is best to talk about the cause of the problem and the idea of PR change.
This will allow others to better review the code

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java [hunk 1]
```diff
@@ -95,6 +95,8 @@
     // table(view)'s comment
     protected String comment = "";
 
+    protected String ddlSql = "";
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java:98]: Add comment for this new field

File: be/src/exec/schema_scanner/schema_views_scanner.cpp [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+    {
+        void *slot = tuple->get_slot(_tuple_desc->slots()[6]->tuple_offset());
+        StringValue* str_slot = reinterpret_cast<StringValue*>(slot);
+        const std::string definer = "root@%";
+        str_slot->len = definer.length();
+        str_slot->ptr = (char *)pool->allocate(str_slot->len);
+        if (NULL == str_slot->ptr) {
+            return Status::InternalError("Allocate memcpy failed.");
+        }
+        memcpy(str_slot->ptr, definer.c_str(), str_slot->len);
```
Comment (yangzhg) [inline be/src/exec/schema_scanner/schema_views_scanner.cpp:154]: length always 6？

File: fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java [hunk 3]
```diff
@@ -281,6 +281,23 @@ public static Builder builder() {
...
+                                TableType.SCHEMA,
+                                builder()
+                                        .column("TABLE_CATALOG", ScalarType.createVarchar(512))
+                                        .column("TABLE_SCHEMA", ScalarType.createVarchar(64))
+                                        .column("TABLE_NAME", ScalarType.createVarchar(64))
+                                        .column("VIEW_DEFINITION", ScalarType.createVarchar(8096))
+                                        .column("CHECK_OPTION", ScalarType.createVarchar(8))
+                                        .column("IS_UPDATABLE", ScalarType.createVarchar(3))
+                                        .column("DEFINER", ScalarType.createVarchar(77))
+                                        .column("SECURITY_TYPE", ScalarType.createVarchar(7))
```
Comment (yangzhg) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java:297]: why this column length is 77, you should add a comment, this column in mysql is 288

File: fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java [hunk 4]
```diff
@@ -281,6 +281,23 @@ public static Builder builder() {
...
+                                        .column("CHARACTER_SET_CLIENT", ScalarType.createVarchar(32))
+                                        .column("COLLATION_CONNECTION", ScalarType.createVarchar(32))
```
Comment (yangzhg) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java:299]: why 32

File: fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java [hunk 5]
```diff
@@ -248,7 +248,19 @@ public TListTableStatusResult listTableStatus(TGetTablesParams params) throws TE
...
+                    tables = db.getTables();
+                } else {
+                    switch (params.getType()) {
+                        case "VIEW":
+                            tables = db.getViews();
+                            break;
+                        default:
+                            tables = db.getTables();
+                    }
+                }
```
Comment (yangzhg) [inline fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java:262]:
```suggestion
               List<Table> tables = db.getTables();
                if (params.isSetType() && "VIEW".equals(params.getType())) {
                    tables = db. getViews();
                }
```

File: be/src/exec/schema_scanner/schema_views_scanner.cpp (hunk 2 above)
Comment (pengxiangyu) [reply be/src/exec/schema_scanner/schema_views_scanner.cpp:154]: this is column for table views in mysql, palo has no this information, we can only set a default one

File: fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java (hunk 3 above)
Comment (pengxiangyu) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java:297]: Maybe you get another version of mysql. the sql I got is like this.

File: fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java (hunk 4 above)
Comment (pengxiangyu) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java:299]: the sql I got is like this.

File: fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java (hunk 5 above)
Comment (pengxiangyu) [reply fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java:262]: If type is view, this will call getTables() which is not required. When the count of tables in this db is too many, this will take more time.

**Review by yangzhg — DISMISSED** [review]
+1

File: be/src/exec/schema_scanner/schema_views_scanner.cpp [hunk 6]
```diff
@@ -0,0 +1,231 @@
...
+            return Status::InternalError("Allocate memcpy failed.");
+        }
+        memcpy(str_slot->ptr, check_option.c_str(), str_slot->len);
+    }
+    // is_updatable
+    {
+        void *slot = tuple->get_slot(_tuple_desc->slots()[5]->tuple_offset());
+        StringValue* str_slot = reinterpret_cast<StringValue*>(slot);
+        // This is from views in mysql
+        const std::string is_updatable = "YES";
```
Comment (morningman) [inline be/src/exec/schema_scanner/schema_views_scanner.cpp:138]: Better set it to "No". Because we do not support DELETE or UPDATE on view.

Comment (pengxiangyu) [reply be/src/exec/schema_scanner/schema_views_scanner.cpp]: DONE

**Review by morningman — APPROVED** [review]
LGTM
