### PR TITLE
fix restore with partitions cause some query fail

### LINKED ISSUE #8244: [Bug] Restore with partition cause some query fail "table status is not NORMAL: RESTORE"
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

1, create table like: 
CREATE TABLE `daily_jtk_ad_cps_user_detial` (
  `date_time` date NOT NULL COMMENT "",
  `adowner` varchar(256) NULL DEFAULT """" COMMENT "",
  `sku_id` bigint(20) NULL DEFAULT "0" COMMENT "",
  `union_id` bigint(20) NULL DEFAULT "0" COMMENT "",
  `plan_id` bigint(20) NULL COMMENT "",
  `plan_type` int(11) NULL COMMENT "",
  `cp_act_id` bigint(20) NULL COMMENT "",
  `cp_union_id` bigint(20) NULL COMMENT "",
  `ware_id` bigint(20) NULL COMMENT "",
  `jtk_uv_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_click_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_order_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_payed_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_finish_cnt` hll HLL_UNION NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`date_time`, `adowner`, `sku_id`, `union_id`, `plan_id`, `plan_type`, `cp_act_id`, `cp_union_id`, `ware_id`)
COMMENT "OLAP"
PARTITION BY RANGE(`date_time`)
(PARTITION p202103 VALUES [('0000-01-01'), ('2021-04-01')),
PARTITION p202104 VALUES [('2021-04-01'), ('2021-05-01')))
DISTRIBUTED BY HASH(`adowner`) BUCKETS 16
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
)

2, restore partition: p202103 succeed.
3, restore partition: p202104, while query with:
select * from daily_jtk_ad_cps_user_detial where date_time>"2021-03-01"  and date_time<"2021-03-30" limit 1;

RESULT:
ERROR 5014 (HY000): errCode = 2, detailMessage = Table state is not NORMAL: 'RESTORING'

### What You Expected?

query succeed without error message.

### How to Reproduce?

1, create table like: 
CREATE TABLE `daily_jtk_ad_cps_user_detial` (
  `date_time` date NOT NULL COMMENT "",
  `adowner` varchar(256) NULL DEFAULT """" COMMENT "",
  `sku_id` bigint(20) NULL DEFAULT "0" COMMENT "",
  `union_id` bigint(20) NULL DEFAULT "0" COMMENT "",
  `plan_id` bigint(20) NULL COMMENT "",
  `plan_type` int(11) NULL COMMENT "",
  `cp_act_id` bigint(20) NULL COMMENT "",
  `cp_union_id` bigint(20) NULL COMMENT "",
  `ware_id` bigint(20) NULL COMMENT "",
  `jtk_uv_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_click_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_order_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_payed_cnt` hll HLL_UNION NULL COMMENT "",
  `jtk_finish_cnt` hll HLL_UNION NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`date_time`, `adowner`, `sku_id`, `union_id`, `plan_id`, `plan_type`, `cp_act_id`, `cp_union_id`, `ware_id`)
COMMENT "OLAP"
PARTITION BY RANGE(`date_time`)
(PARTITION p202103 VALUES [('0000-01-01'), ('2021-04-01')),
PARTITION p202104 VALUES [('2021-04-01'), ('2021-05-01')))
DISTRIBUTED BY HASH(`adowner`) BUCKETS 16
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
)

2, restore partition: p202104 succeed.
3, restore partition: p202103, while query with:
select * from daily_jtk_ad_cps_user_detial where date_time>"2021-03-01"  and date_time<"2021-03-30" limit 1;

RESULT:
ERROR 5014 (HY000): errCode = 2, detailMessage = Table state is not NORMAL: 'RESTORING'

### Anything Else?

NO

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GoGoWen**
# Proposed changes

Issue Number: close #8244

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java [hunk 1]
```diff
@@ -585,7 +587,17 @@ public TableRef resolveTableRef(TableRef tableRef) throws AnalysisException {
...
                 || ((OlapTable) table).getState() == OlapTableState.RESTORE_WITH_LOAD)) {
-            ErrorReport.reportAnalysisException(ErrorCode.ERR_BAD_TABLE_STATE, "RESTORING");
+            Boolean isNotRestoring = ((OlapTable) table).getPartitions().stream().filter(
+                    partition -> partition.getState() == PartitionState.RESTORE
+            ).collect(Collectors.toList()).isEmpty();
+
+            if(!isNotRestoring){
+                // if doing restore with partitions, the status check push down to OlapScanNode::computePartitionInfo to
+                // support query that partitions is not restoring.
+            }else {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java:597]:
```suggestion
            } else {
```

File: fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java [hunk 2]
```diff
@@ -469,6 +470,16 @@ private void checkAndPrepareMeta() {
...
                 olapTbl.setState(OlapTableState.RESTORE);
+                // set restore status for partitions
+                BackupOlapTableInfo tblInfo = jobInfo.backupOlapTableObjects.get(tableName);
+                for (Map.Entry<String, BackupPartitionInfo> partitionEntry : tblInfo.partitions.entrySet()) {
+                    String partitionName = partitionEntry.getKey();
+                    Partition partition = olapTbl.getPartition(partitionName);
+                    if (partition == null) {
+                        continue;
+                    }
+                    partition.setState(PartitionState.RESTORE);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java:481]: you also need to modify `replayCheckAndPrepareMeta()` method.

**Review by morningman — APPROVED** [review]
LGTM
