### PR TITLE
[Bug] Fix bug that isPreAggregation is incorrectly set

### LINKED ISSUE #5609: [Bug] BE crash on SegmentIterator
**Describe the bug**
BE crash with error:

image

**To Reproduce**

Hard to reproduce.
The direct reason is because the read parameters passed by the BE side does not contain columns
related to the deletion conditions, which results in the corresponding column iterator being null when
preparing to filter the data according to the deletion conditions.

The root cause is that the FE side does not correctly set the `isPreAggregate` attribute during query planning,
which causes the BE side to skip the delete condition column by mistake.

 - Version [0.14.7]

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. The MaterializedViewSelector should be reset for each scan node
2. On the BE side, columns with delete conditions must be added to the return column.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have created an issue on (Fix #5609 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/reader.cpp [hunk 1]
```diff
@@ -458,7 +458,8 @@ OLAPStatus Reader::_init_params(const ReaderParams& read_params) {
 OLAPStatus Reader::_init_return_columns(const ReaderParams& read_params) {
     if (read_params.reader_type == READER_QUERY) {
         _return_columns = read_params.return_columns;
-        if (!_delete_handler.empty() && read_params.aggregation) {
```
Comment (morningman) [inline be/src/olap/reader.cpp:461]: For reviewer:
Remove `read_params.aggregation` because this is just a tricky optimization.
That is, if `aggregation` is false, than all key columns has already been added to the `_return_columns`.
And delete conditions can only be applied on key columns, so no need to iterate and add them again.

But this is not always right, because for DUPLICATION KEY table, the delete conditions can be applied on any columns. Although the query optimizer will guarantee that for  DUPLICATION KEY table, the aggregation is always true, but we should not depend on it.

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
