### PR TITLE
[fix] Fix the query result error caused by the grouping sets statemen…

### LINKED ISSUE #4427: Rollup SQL in TPCDS encounter the wrong answer.
```
select 'catalog channel' as channel
       , cs_call_center_sk as id
       , sum(cs_ext_sales_price)
from  catalog_sales
where cs_sold_date_sk = 2451780
group by rollup (channel, id)
order by channel,id
```

### PR DESCRIPTION
**Pull request by luozenglin**
…t grouping as an expression

Push the expression down to the repeat node.

# Proposed changes

Issue Number: close #4427

## Checklist(Required)

1. Type of your changes:
    - [ ] Improvement
    - [x] Fix
    - [ ] Feature-WIP
    - [ ] Feature
    - [ ] Doc
    - [ ] Refator
    - [ ] Others: 
2. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
3. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/exec/repeat_node.h [hunk 1]
```diff
@@ -52,12 +55,17 @@ class RepeatNode : public ExecNode {
...
-    const TupleDescriptor* _tuple_desc;
+    const TupleDescriptor* _output_tuple_desc;
 
     std::unique_ptr<RowBatch> _child_row_batch;
     bool _child_eos;
     int _repeat_id_idx;
     RuntimeState* _runtime_state;
+
+    // Exprs used to evaluate input rows
+    std::vector<Expr*> _probe_exprs;
```
Comment (yangzhg) [inline be/src/exec/repeat_node.h:66]: why called `_probe_exprs` ？ there is no probe ops, you should remove probe

Comment (luozenglin) [reply be/src/exec/repeat_node.h]: done

**Review by yangzhg — APPROVED** [review]
LGTM
