### PR TITLE
[fix](cooldown)Fix bug for single cooldown compaction, add remote meta

### LINKED ISSUE #16811: [Bug] Fix bug for single cooldown compaction, add remote meta
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.3

### What's Wrong?

Fix bug for single cooldown compaction, add remote meta

### What You Expected?

Fix bug for single cooldown compaction, add remote meta

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #16811

## Problem summary

Fix bug for single cooldown compaction, add remote meta

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/tablet.h [hunk 1]
```diff
@@ -448,6 +450,7 @@ class Tablet : public BaseTablet {
     std::mutex _ingest_lock;
     std::mutex _base_compaction_lock;
     std::mutex _cumulative_compaction_lock;
+    std::mutex _cooldown_compaction_lock;
```
Comment (platoneko) [inline be/src/olap/tablet.h:453]: We already have `_cold_data_compaction_lock`, what's the different between these two lock?

**Comment by platoneko** [comment]
LGTM

**Review by platoneko — APPROVED** [review]

**Review by adonis0147 — APPROVED** [review]
LGTM
