### PR TITLE
[fix](mtmv) Choose a valid partition column when there are both valid and invalid expressions

### LINKED ISSUE #38366: [Bug] (mtmv) Unable to find a suitable base table for partitioning when there are both valid and invalid expressions
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1

### What's Wrong?

reproduce:
```
CREATE TABLE `test_t` (
  `id` VARCHAR(36) NOT NULL COMMENT 'id',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT ''
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT ''
PARTITION BY RANGE(`created_time`)
(PARTITION P_2024071713 VALUES [('2024-07-17 13:00:00'), ('2024-07-17 14:00:00')),
PARTITION P_2024071714 VALUES [('2024-07-17 14:00:00'), ('2024-07-17 15:00:00')))
DISTRIBUTED BY HASH(`id`) BUCKETS AUTO
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);
CREATE MATERIALIZED VIEW test_mtmv
        BUILD IMMEDIATE REFRESH AUTO ON MANUAL
        partition by(date_trunc(created_time_minute, 'day'))
        DISTRIBUTED BY RANDOM BUCKETS 3
        PROPERTIES ('replication_num' = '1') 
        AS 
select  id 
        ,date_trunc(created_time, 'minute') as created_time_minute
        ,min(created_time) as start_time
        ,if(count(id) > 0, 1, 0) as status
        from test_t 
        group by id, date_trunc(created_time, 'minute');
```
An error occurs:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unable to find a suitable base table for partitioning, the fail reason is can't not find valid partition track column, because column to check use invalid implicit expression, invalid expression is min(created_time#12)
```

### What You Expected?

`test_t` should be selected as base table.
`date_trunc(created_time, 'minute')` should pass the check and `min(created_time)` should be ignore.

### How to Reproduce?

 Refer to the description above.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes
Choose a partition column when there are both valid and invalid expressions.
Issue Number: close #38366

### CODE REVIEW

**Comment by liutang123** [comment]
Will add regression tests later

**Comment by seawinde** [comment]
Could you add some tests for this fix?

**Comment by liutang123** [comment]
> Could you add some tests for this fix? Partition track test is all in `org.apache.doris.nereids.rules.exploration.mv.MaterializedViewUtilsTest`

sure, i said i will add regression tests later.

**Comment by xy720** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Review by xy720 — DISMISSED** [review]
LGTM

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
@seawinde hello, this PR is ready, do you have time to take a look?

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java [hunk 1]
```diff
@@ -652,16 +658,17 @@ private static boolean checkPartition(Collection<? extends Expression> expressio
...
                 if (!partitionColumn.isColumnFromTable()) {
                     context.setMvPartitionColumn(partitionColumns.iterator().next());
                 }
                 if (!context.getPartitionExpression().isPresent()) {
                     context.setPartitionExpression(partitionExpression);
                 }
+                return true;
             }
-            return true;
+            return false;
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java:671]: Maybe the code  `return context.getMvPartitionColumn().isColumnFromTable();` maybe better

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java [hunk 2]
```diff
@@ -589,9 +589,15 @@ private SlotReference getContextPartitionColumn(IncrementCheckerContext context)
         private static boolean checkPartition(Collection<? extends Expression> expressionsToCheck, Plan plan,
                 IncrementCheckerContext context) {
             NamedExpression partitionColumn = context.getMvPartitionColumn();
-            for (Expression projectSlot : expressionsToCheck) {
+
+            OUTER_CHECK: for (Expression projectSlot : expressionsToCheck) {
                 if (projectSlot.isColumnFromTable() && projectSlot.equals(partitionColumn.toSlot())) {
-                    continue;
+                    if (!context.getPartitionExpression().isPresent()) {
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java:595]: if `projectSlot.isColumnFromTable() && projectSlot.equals(partitionColumn.toSlot()) ` is true
the partitionExpression in context is always right because line 667. the code is duplicated to line 667.

if `return context.getMvPartitionColumn().isColumnFromTable();` at end. this can be removed.

Comment (liutang123) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java:595]: line 667 may not execute.

**Comment by liutang123** [comment]
run buildall

**Comment by seawinde** [comment]
LGTM!

**Review by seawinde — APPROVED** [review]

**Comment by liutang123** [comment]
run feut

**Comment by morrySnow** [comment]
run cloud_p0

**Review by morrySnow — APPROVED** [review]
