### PR TITLE
[fix](outfile) select OBJECT and HLL columns into outfile as null.

### LINKED ISSUE #12733: [Bug] when exporting hll columns, the file gets binary data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

When exporting hll columns, the file gets binary data：
```
mysql> desc test_select_into_datatype_test_select_hll_into_tb;
+-------+------+------+-------+---------+-----------+
| Field | Type | Null | Key   | Default | Extra     |
+-------+------+------+-------+---------+-----------+
| k1    | INT  | No   | true  | NULL    |           |
| v1    | HLL  | No   | false |         | HLL_UNION |
| v2    | INT  | No   | false | NULL    | SUM       |
+-------+------+------+-------+---------+-----------+


select * from test_select_into_datatype_test_select_hll_into_tb INTO OUTFILE 
"hdfs://xxxx:xxxx/user/palo/test/data/export/test_select_into_datatype_test_select_hll_into_db/label_18_04_48_58_267754_1153537483/label_18_04_48_58_267809_1380471842"  
PROPERTIES ("broker.name"="ahdfs","broker.username"="xxxx","broker.password"="xxxx");


 >> cat label_18_04_49_24_934768_1507551182e8d9ac87685e4c89-b8de49ecab016905_0_v.csv
-1593835520	�@�X�	4
-1543503872	�ͭ��ͭ�	4
-1459617792	��ͭ��ͭ�	4
-1358954496	�`ͭ�xͭ�	4
-1224736768	�@ͭ�Xͭ�	4
-654311424     	ͭ�ͭ�p`�
                       �	4
-369098752	 ͭ�8ͭ�	4
-234881024	��̭��̭�	4
301989888	�̭��̭�	4
452984832	�̭��̭�	4
520093696	`̭�x̭�	4
637534208	��̭��̭�	4
1090519040	@̭�X̭���������	4
1191182336	 ̭�8̭����	4
1308622848	�̭�̭�	4
1996488704	�˭��˭� 	4
2147483647	�˭��˭�	5
-1979711488	�`{��x{��	4
-1962934272	�@{��X{��	4
-1191182336	�y���y��@�)�	4
-1174405120	��y���y���	4
-1090519040	�y���y��p:2�	4
-956301312	��y���y��yn �	4
-268435456	�`y��xy���	4
-218103808	@y��Xy��	4
-33554432	 y��8y������	4
268435456	�y��y��	4

```

### What You Expected?

```
mysql> select * from test_select_into_datatype_test_select_hll_into_tb;
+-------------+------+------+
| k1          | v1   | v2   |
+-------------+------+------+
| -1979711488 | NULL |    4 |
| -1962934272 | NULL |    4 |
| -1191182336 | NULL |    4 |
| -1174405120 | NULL |    4 |
| -1090519040 | NULL |    4 |
|  -956301312 | NULL |    4 |
|  -268435456 | NULL |    4 |
|  -218103808 | NULL |    4 |
|   -33554432 | NULL |    4 |
|   268435456 | NULL |    4 |
|   369098752 | NULL |    4 |
|   587202560 | NULL |    4 |
|   654311424 | NULL |    4 |
|  1006632960 | NULL |    4 |
|  1107296256 | NULL |    4 |
|  1157627904 | NULL |    4 |
|  1241513984 | NULL |    4 |
|  1342177280 | NULL |    4 |
|  1593835520 | NULL |    4 |
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #12733

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/runtime/vfile_result_writer.cpp [hunk 1]
```diff
@@ -327,7 +325,7 @@ Status VFileResultWriter::_write_csv_file(const Block& block) {
                     break;
                 }
                 default: {
-                    // not supported type, like BITMAP, HLL, just export null
+                    // not supported type, like BITMAP, OBJECT, HLL, just export null
```
Comment (Gabriel39) [inline be/src/vec/runtime/vfile_result_writer.cpp:328]: I think we should use SessionVariable `return_object_data_as_binary` to control whether output HLL/BitMap as ParquetWriter did.

Comment (luozenglin) [reply be/src/vec/runtime/vfile_result_writer.cpp]: done

**Review by Gabriel39 — APPROVED** [review]
LGTM
