### PR TITLE
[Bug] Support BetweenPredicate enable fold const expr

### LINKED ISSUE #8449: [Bug] BetweenPredicate failed when enable the fold const expr
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
mysql> select 2 between NULL and 1,2 between 3 AND NULL,NULL between 1 and 2,            2 between NULL and 3, 2 between 1 AND NULL;
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: BetweenPredicate needs to be rewritten into a CompoundPredicate.
```

### What You Expected?

get the right result

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #8449

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/columns/column_vector.cpp [hunk 1]
```diff
@@ -231,8 +231,8 @@ void ColumnVector<T>::insert_indices_from(const IColumn& src, const int* indices
             // Now Uint8 use to identify null and non null
             // 1. nullable column : offset == -1 means is null at the here, set true here
             // 2. real data column : offset == -1 what at is meaningless
-            // 3. -1 only use in outer join to hint the null is produced by outer join
-            data[origin_size + i] = (offset == -1) ? UInt8(-1) : src_vec.get_element(offset);
+            // 3. 2 only use in outer join to hint the null is produced by outer join
+            data[origin_size + i] = (offset == -1) ? 2 : src_vec.get_element(offset);
```
Comment (morningman) [inline be/src/vec/columns/column_vector.cpp:235]: define `2` somewhere as a constant, to avoid magic number.

**Review by morningman — APPROVED** [review]
LGTM
