### PR TITLE
Fix BE do_tablet_meta_checkpoint retain _meta_lock for a long time

### LINKED ISSUE #2419: BE do_tablet_meta_checkpoint retain _meta_lock for a long time
**Describe the bug**
After starting stream load for some time, the transactions’ publish version will become slower and slower.

**To Reproduce**
We have a cluster with 3 FE and 8 BE, version: 0.11, OS: CentOS 7
FE：CPU cores: 16;  Mem: 32
BE: CPU cores： 40; Mem: 128; Disk: 3.6T * 12

This problem occurs when doing large data stream load
- More than 20M messages per minutes.
- Use 20 clients send data to Doris.
- Each client Sends 250K messages every batch.

**Expected behavior**
After starting stream load for some time, the transactions’ publish version will become very slow.
Through add some logs, I find that Tablet::do_tablet_meta_checkpoint will retain the _meta_lock for a long time.
```I1210 17:47:23.343849 191992 tablet.cpp:1270] 26239 do_tablet_meta_checkpoint retain _meta_lock cost: 1570 s, check_rowset_meta cost: 1569 s, remove cost: 0 s, all_rs_metas: 39973```

And through perf, I find that rocksdb cost much time in Get:
image

### PR DESCRIPTION
**Pull request by liutang123**
Fix #2419
Add a flag in RowsetMeta to record whether it has been deleted from rowset meta.
Before this PR, 37156 rowsets only cost 1642 s.
With this PR, 37319 rowsets just cost 1 s.

### CODE REVIEW

File: be/src/olap/rowset/rowset_meta.h [hunk 1]
```diff
@@ -296,6 +296,19 @@ class RowsetMeta {
...
+    // Some time, we may check if this rowset is in rowset meta manager's meta by using RowsetMetaManager::check_rowset_meta.
+    // But, this check behavior may cost a lot of time when it is frequent.
+    // If we explicitly remove this rowset from rowset meta manager's meta, we can set _is_removed_from_rowset_meta to true,
+    // And next time when we want to check if this rowset is in rowset mata manager's meta, we can
+    // check is_remove_from_rowset_meta() first.
+    void set_remove_from_rowset_meta() {
+        _is_removed_from_rowset_meta = true;
+    }
+
+    bool is_remove_from_rowset_meta() {
```
Comment (imay) [inline be/src/olap/rowset/rowset_meta.h]:
```suggestion
    bool is_remove_from_rowset_meta() const {
```

File: be/src/olap/tablet.cpp [hunk 2]
```diff
@@ -1065,12 +1065,17 @@ OLAPStatus Tablet::do_tablet_meta_checkpoint() {
...
+        // If we delete it from rowset manager's meta explicitly in previous checkpoint, just skip.
+        if(rs_meta->is_remove_from_rowset_meta()) {
+            continue;
+        }
         if (RowsetMetaManager::check_rowset_meta(_data_dir->get_meta(), tablet_uid(), rs_meta->rowset_id())) {
             RowsetMetaManager::remove(_data_dir->get_meta(), tablet_uid(), rs_meta->rowset_id());
             LOG(INFO) << "remove rowset id from meta store because it is already persistent with tablet meta"
                        << ", rowset_id=" << rs_meta->rowset_id();
         }
+        rs_meta->set_remove_from_rowset_meta();
```
Comment (imay) [inline be/src/olap/tablet.cpp]: It seems that this line of code should be executed in above if clause.

**Review by imay — CHANGES_REQUESTED** [review]

**Review by imay — APPROVED** [review]
LGTM
