### PR TITLE
[Enhancement] [Memory] [Vectorized] Stress test and optimize memory allocation

### LINKED ISSUE #9540: [Bug] DCHECK failed caused by tls_ctx()->type() == ThreadContext::TaskType::UNKNOWN
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master-289608cc2

### What's Wrong?

load coredumped:
```
start time: Thu May 12 06:38:30 PM CST 2022
*** Check failure stack trace: ***
    @     0x55a8476f53bd  google::LogMessage::Fail()
    @     0x55a8476f78f9  google::LogMessage::SendToLog()
    @     0x55a8476f4f26  google::LogMessage::Flush()
    @     0x55a8476f7f69  google::LogMessageFatal::~LogMessageFatal()
    @     0x55a841e7f391  doris::SwitchThreadMemTracker<>::SwitchThreadMemTracker()
    @     0x55a841fda939  doris::LoadChannel::cancel()
    @     0x55a841fca4b0  doris::LoadChannelMgr::_start_load_channels_clean()
    @     0x55a841fc92c9  _ZZN5doris14LoadChannelMgr16_start_bg_workerEvENKUlvE_clEv
    @     0x55a841fcc196  _ZSt13__invoke_implIvRZN5doris14LoadChannelMgr16_start_bg_workerEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @     0x55a841fcc000  _ZSt10__invoke_rIvRZN5doris14LoadChannelMgr16_start_bg_workerEvEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES5_E4typeEOS6_DpOS7_
    @     0x55a841fcbc7a  _ZNSt17_Function_handlerIFvvEZN5doris14LoadChannelMgr16_start_bg_workerEvEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x55a841e11b36  std::function<>::operator()()
    @     0x55a8424a0b00  doris::Thread::supervise_thread()
    @     0x7fcedcfe2450  start_thread
    @     0x7fcedd112d53  clone
    @              (nil)  (unknown)
*** Aborted at 1652406931 (unix time) try "date -d @1652406931" if you are using GNU date ***
*** SIGABRT unkown detail explain (@0x1e8756) received by PID 2000726 (TID 0x7fce7821b640) from PID 2000726; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zhanglei/incubator-doris/be/src/common/signal_handler.h:407
 1# 0x00007FCEDD03C040 in /lib/x86_64-linux-gnu/libc.so.6
 2# raise in /lib/x86_64-linux-gnu/libc.so.6
 3# abort in /lib/x86_64-linux-gnu/libc.so.6
 4# google::ReadFromOffset(int, void*, unsigned long, long) [clone .cold] at src/symbolize.cc:146
 5# 0x000055A8476F53BD at src/logging.cc:1650
 6# google::LogMessage::SendToLog() at src/logging.cc:1607
 7# google::LogMessage::Flush() at src/logging.cc:1477
 8# google::LogMessageFatal::~LogMessageFatal() at src/logging.cc:2227
 9# doris::SwitchThreadMemTracker<false>::SwitchThreadMemTracker(std::shared_ptr<doris::MemTracker> const&, bool) at /home/zhanglei/incubator-doris/be/src/runtime/thread_context.cpp:95
10# doris::LoadChannel::cancel() at /home/zhanglei/incubator-doris/be/src/runtime/load_channel.cpp:141
11# doris::LoadChannelMgr::_start_load_channels_clean() at /home/zhanglei/incubator-doris/be/src/runtime/load_channel_mgr.cpp:250
12# doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}::operator()() const at /home/zhanglei/incubator-doris/be/src/runtime/load_channel_mgr.cpp:202
13# void std::__invoke_impl<void, doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}&>(std::__invoke_other, doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}&) at /usr/include/c++/11/bits/invoke.h:61
14# std::enable_if<is_invocable_r_v<void, doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}&>, void>::type std::__invoke_r<void, doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}&>(doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}&) at /usr/include/c++/11/bits/invoke.h:117
15# std::_Function_handler<void (), doris::LoadChannelMgr::_start_bg_worker()::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /usr/include/c++/11/bits/std_function.h:292
16# std::function<void ()>::operator()() const at /usr/include/c++/11/bits/std_function.h:560
17# doris::Thread::supervise_thread(void*) at /home/zhanglei/incubator-doris/be/src/util/thread.cpp:409
18# start_thread at ./nptl/pthread_create.c:474
19# clone in /lib/x86_64-linux-gnu/libc.so.6
```

log:
```
I0513 09:55:27.098309 2001220 snapshot_loader.cpp:353] finished to download snapshots. job: 32603, task id: 33692
I0513 09:55:27.098703 2001220 task_worker_pool.cpp:1344] finished download task, signature: 33692, job id:32603
I0513 09:55:30.596575 2001418 heartbeat_server.cpp:58] get heartbeat from FE.host:172.21.16.2, port:9420, cluster id:556303565, counter:10981
I0513 09:55:31.409724 2001141 load_channel_mgr.cpp:224] cleaning timed out load channels
I0513 09:55:31.409765 2001141 load_channel_mgr.cpp:242] erase timeout load channel: 6a47ab9692546a45-800190cfa6522188
F0513 09:55:31.409852 2001141 thread_context.cpp:95] Check failed: in_task == false || tls_ctx()->type() != ThreadContext::TaskType::UNKNOWN ,tls ctx type=0
```

qJVo3zuXZD

### What You Expected?

no coredump

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #9540
#9580 

## Problem Summary:

1. High concurrency stress test on SSB and wide table. Compare the performance of turning the vectorization engine on and off. Turning on the vectorization engine is slower for most SSB queries.

2. Optimize the Allocator in the vectorization engine. In most queries, the performance is improved by about **10%**.
Memory allocation between 4KB and 64MB will be through ChunkAllocator, those less than 4KB will be through malloc, and those greater than 64MB will be through MMAP.

3. Optimize Chunk Allocator, increase the limit that allows chunks to be stolen from other core's arena, and optimize reserved bytes conf.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No)
7. Has document been added or modified: (Yes)
8. Does it need to update dependencies: (No)
9. Are there any changes that cannot be rolled back: (Yes)

## Further comments

Stress testing the vectorization engine.
## 1. Env and Test Set
```
> Based on Doris V1.0

Env: 1 FE, 1 BE
Test Set: 
	SSB, 100G, lineorder 60003w rows
	Width table from online service, 419 columns, 1710549 rows
set global parallel_fragment_exec_instance_num=10

jmeter conf:
	<stringProp name="ThreadGroup.num_threads">100</stringProp>
	<stringProp name="ThreadGroup.ramp_time">1</stringProp>
	<boolProp name="ThreadGroup.scheduler">true</boolProp>
	<stringProp name="ThreadGroup.duration">30</stringProp>
	<stringProp name="ThreadGroup.delay">0</stringProp>

actual concurrency = parallel_fragment_exec_instance_num * ThreadGroup.num_threads
```

## 2. Test

- TO: Master, set global enable_vectorized_engine=false;
- T1: Master, set global enable_vectorized_engine=true;
- T2: Master, set global enable_vectorized_engine=true, tc_max_total_thread_cache_bytes=100G；
- T3: This PR, set global enable_vectorized_engine=true, allocate 4k < size < 64M use ChunkAllocator; 
- T4: This PR, set global enable_vectorized_engine=true, Allocator 4k < size < 64M use chunkAllocator, and compile USE_MEM_TRACKER=0；
- R1: (T0mid-T1mid)/T0mid, Compare the performance of turning the vectorization engine on and off.
- R2: (T1mid-T3mid)/T1mid, Performance changes brought by allocating 4K < size < 64M memory through ChunkAllocator in the vectorization engine.
- R3: (T1mid-T4mid)/T1mid, Same as above, close memtracker.

> Form Notes: "xxx,xxx,xxx": Repeat 3 times, the AvgTime(ms) of each time.

| query | num_threads | R1 | R2 | R3 | T0 | T1 | T2 | T3 | T4 |
| ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |  ------ |
| Q1.1 | 100 | 4.7% | 9.2% | 12.1% | 36252,36903,36800 | 34297,35053,36087 | 35757,34483,33825 | 33314,31657,31838 | 30801,31496,30445 |
| Q1.2 | 100 | -3.8% | 7% | 6.2% | 24017,24338,25478 | 25273.25222,25914 | 26647,24651,25406 | 23453,23498,23604 | 23771,23084,23704 |
| Q1.3 | 100 | -2.6% | 9% | 7.9 | 24349,23780,22844 | 24073,24487,24401 | 23842,23149,24198 | 22614,22984,23050 | 22678,22466,22225 |
| Q2.1 | 20 | -11.2% | 0.6% | 19.3% | 89466,21528,21889 | 26300,24345,24222 | 89662,25042,24069 | 24094,24542,24197 | 20538,19651,19627 |
| Q2.2| 20 | 12.7% | 4.9% | 0.8% | 16963,21435,18154 | 15855,16936,15047 | 16006,17251,16593 | 15072,14407,15648 | 15716,16347,15588 |
| Q2.3 | 20 | 1% | 3.2% | 8.9% | 15183,16194,13977 | 15551,15033,14801 | 14338,14605,14531 | 14302,14548,15301 | 14318,13601,13689 |
| Q3.1 | 20 | 5.4% | 19.4% | 23.6% | 32021,32176,31427 | 31037,30283,30231 | 38002,30272,30016 | 25162,23187,24411 | 27673,23147,22492 |
| Q3.2 | 20 | -8% | 15.8% | 17.3% | 10379,10433,9893 | 11837,11184,11223 | 11403,11481,9788 | 9296,9452,9455 | 9576,9172,9283 |
| Q3.3 | 20 | -5% | 10.6% | 12.8% | 8559,8472,8639 | 8713,9390,8992 | 8367,8153,8133 | 7998,8618,8040 | 7952,7476,7845 |
| Q4.1 | 20 | -35% | 27.9% | 31.8% | 32249,29965,29136 | 47405,40357,40443 | 41912,36981,37571 | 31230,27683,29166 | 31848,27585,27435 |
| Q4.2 | 20 | -73.5 | 16.2% | 15.2% | 19979,18798,17169 | 34066,32614,30849 | 34560,34460,35194 | 27117,29645,27337 | 27651,29205,27149 |
| Q4.3 | 20 | -46.2% | -2.8% | 0.5% | 19357,20762,19992 | 28256,29862,29230 | 27647,29216,29091 | 30523,30067,29260 | 29092,26644,30017 |
| Width table (419 rows) | 100 | 100% | 17.6% | 17.9% | no work | 4211,4546,4710 | 4089,4479,4551 | 3679,3745,3816 | 3664,3732,3829 |

image

## 3. Detailed description
- T2:  Theoretically, when the capacity of the tcmalloc thread cache is sufficient, the spin lock in the central free list will be avoided to a great extent, but in practice, the spin lock cost is still large in high concurrency queries, I will test this matter in more detail below.
- T3:  Because tcmalloc thread cache cannot avoid spin lock, the introduction of ChunkAllocator is equivalent to adding a layer of cache in User Mode. 
	In allocator.h, Memory allocation between 4KB and 64MB will be through ChunkAllocator, those less than 4KB will be through malloc (for example, tcmalloc), and those greater than 64MB will be through MMAP.
	In the actual test, chunkallocator allocates less than 4KB of memory slower than malloc, and chunkallocator allocates more than 64MB of memory slower than MMAP, but the 4KB threshold is an empirical value, which needs to be determined by more detailed test later.
- T4: Close memtracker at compile time can be selected during POC. Memtracker records the consumption value through an atomic variable. In high query concurrency, the atomic variable spin lock has a high cost. I'll optimize memtracker. After that

### CODE REVIEW

File: be/src/common/config.h [hunk 1]
```diff
@@ -413,10 +413,14 @@ CONF_Bool(disable_mem_pools, "false");
...
-// acquire more free memory which can not be used by other modules
-CONF_Int64(chunk_reserved_bytes_limit, "2147483648");
+// process memory limit specified as number of bytes
+// defaults to bytes if no unit is given, increase this variable can improve performance,
+// but will acquire more free memory which can not be used by other modules.
+// must larger than 0. and if larger than physical memory size,
+// it will be set to physical memory size.
+CONF_mString(chunk_reserved_bytes_limit, "20%");
+// 1024, The minimum chunk allocator size (in bytes)
+CONF_Int32(min_chunk_reserved_bytes, "1024");
```
Comment (cambyzju) [inline be/src/common/config.h:423]: we need this config `BitUtil::IsPowerOf2`, we should better add more guide for how to set it.

File: be/src/runtime/memory/chunk_allocator.cpp [hunk 2]
```diff
@@ -219,6 +224,10 @@ void ChunkAllocator::free(const Chunk& chunk, MemTracker* tracker) {
         }
     } while (!_reserved_bytes.compare_exchange_weak(old_reserved_bytes, new_reserved_bytes));
 
+    // Reduce set metric frequency
+    if (_reserved_bytes % 100 == 32) {
```
Comment (cambyzju) [inline be/src/runtime/memory/chunk_allocator.cpp:228]: How to make sure the correctness?

At the first look, (_reserved_bytes % 100 < 32) or (_reserved_bytes % 100 > 32) both will not update the metric.

Comment (xinyiZzz) [reply be/src/runtime/memory/chunk_allocator.cpp:228]: At the first look, ChunkAllocator will allocate/free many times, the memory size of each allocate/free is a multiple of 2, so `_reserved_bytes% 100 == 32` will definitely happen, and the latest `_reserved_bytes` value will be set each time .

The real-time and accurate `_reserved_bytes` value is not required. Usually, the value of `_reserved_bytes` is equal to ChunkAllocator MemTracker. The `_reserved_bytes` metric is only concerned when verifying the accuracy of MemTracker.

Therefore, reduce the number of sets and reduce the performance impact.

File: be/src/common/config.h (hunk 1 above)
Comment (xinyiZzz) [reply be/src/common/config.h:423]: 1. fix
2. Enough. Usually no modification is required.

File: build.sh [hunk 3]
```diff
@@ -212,6 +212,9 @@ fi
 if [[ -z ${STRIP_DEBUG_INFO} ]]; then
     STRIP_DEBUG_INFO=OFF
 fi
+if [[ -z ${NO_MEM_TRACKER} ]]; then
+    NO_MEM_TRACKER=OFF
```
Comment (yangzhg) [inline build.sh:216]: USE_MEM_TRACKER=OFF

File: be/src/gutil/strings/numbers.cc [hunk 4]
```diff
@@ -1480,7 +1479,7 @@ string ItoaKMGT(int64 i) {
 }
 
 string AccurateItoaKMGT(int64 i) {
-    const char *sign = "";
+    const char* sign = "";
```
Comment (yangzhg) [inline be/src/gutil/strings/numbers.cc:1482]: why modify this ？

Comment (xinyiZzz) [reply be/src/gutil/strings/numbers.cc:1482]: fix, forget the format.

File: build.sh (hunk 3 above)
Comment (xinyiZzz) [reply build.sh:216]: Yes, I changed to `USE_MEM_TRACKER` in pr: https://github.com/apache/incubator-doris/pull/9661

File: be/src/vec/common/allocator.h [hunk 5]
```diff
@@ -101,12 +113,75 @@ template <bool clear_memory_, bool mmap_populate>
 class Allocator {
 public:
     /// Allocate memory range.
-    void* alloc(size_t size, size_t alignment = 0) { return alloc_no_track(size, alignment); }
+    void* alloc(size_t size, size_t alignment = 0) {
+        void* buf;
+
+        if (size >= MMAP_THRESHOLD) {
+            if (alignment > MMAP_MIN_ALIGNMENT)
```
Comment (yiguolei) [inline be/src/vec/common/allocator.h:120]: Why not call populate to populate the memory to avoid too many page fault during usage?

File: be/src/runtime/memory/chunk_allocator.h [hunk 6]
```diff
@@ -74,10 +74,19 @@ class ChunkAllocator {
     // Free chunk allocated from this allocator
     void free(const Chunk& chunk, MemTracker* tracker = nullptr);
 
+    // Transfer the memory ownership to the chunk allocator.
+    // If the chunk allocator is full, then free to the system.
+    // Note: make sure that the length of 'data' is equal to size,
+    // otherwise the capacity of chunk allocator will be wrong.
+    void free_as_chunk(uint8_t* data, size_t size, MemTracker* tracker = nullptr);
```
Comment (yiguolei) [inline be/src/runtime/memory/chunk_allocator.h:81]: rename it to free(uint8_t* data, size_t size, MemTracker* tracker = nullptr)

File: be/src/vec/common/allocator.h (hunk 5 above)
Comment (xinyiZzz) [reply be/src/vec/common/allocator.h:120]: No need for zero-fill, because mmap guarantees it.

File: be/src/runtime/memory/chunk_allocator.h (hunk 6 above)
Comment (xinyiZzz) [reply be/src/runtime/memory/chunk_allocator.h]: done

**Comment by xinyiZzz** [comment]
Based on the latest master (commit id: 7898c818e98a7546450976eac1892dec88af1f77)
The test results are the same as above.

**Review by yiguolei — APPROVED** [review]
lgtm
