### PR TITLE
[Bug] Fix bug that the image cannot be pulled after the new fe nodes added

### LINKED ISSUE #5292: Doris 0.13.x FE meta image could not be sync
在前两天线上出现一个问题，我三个FE，出现了一个FE挂掉，然后我重启启动不起来，
Doris版本：0.13.11

我备份这个FE元数据后，将这个节点元数据清除掉，使用

--先删除
ALTER SYSTEM DROP FOLLOWER "FE:9010"
--在添加
ALTER SYSTEM ADD FOLLOWER "FE:9010"
删除改节点，然后在使用--helper方式把该节点作为一个新的FE加入到集群中，但是这时候启动会报错，同时会导致Master FE挂掉，具体异常信息如下

repImpl=com.sleepycat.je.rep.impl.RepImpl@68fa4d19 props={REFRESH_VLSN=17921230, PORT=9010, HOSTNAME=172.22.197.238, P_NODETYPE1=ELECTABLE, NODE_NAME=172.22.197.238_9010_1611290318143, P_NODETYPE0=SECONDARY, P_NODENAME1=172.22.197.240_9010_1608972313975, P_PORT1=9010, P_NODENAME0=172.22.197.238_9010_1611290318143, P_PORT0=9010, P_HOSTNAME1=172.22.197.240, GROUP_NAME=PALO_JOURNAL_GROUP, P_HOSTNAME0=172.22.197.238, ENV_DIR=/hdd_data01/doris-meta/bdb, P_NUMPROVIDERS=2}
 at com.sleepycat.je.rep.InsufficientLogException.wrapSelf(InsufficientLogException.java:315) ~[je-7.3.7.jar:7.3.7]
 at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[je-7.3.7.jar:7.3.7]

后来在社区，缪小姐姐及陈明雨大神的协助下，进行了各种尝试定位，认为是在启动的时候元数据同步异常，这个异常可能是因为我当时的load数据任务在同步修改元数据，造成的，后来在凌晨，生产开货完成以后，停掉所有load任务，然后执行删除问题FE节点元数据，然后在重新使用--helper启动，依然报错，最后没办法，尝试将master节点的fe元数据拷贝到问题节点FE，将问题节点FE的元数据目录删除，然后重建，将赋值过来的元数据，拷贝到元数据目录

（临时解决方案）具体步骤：

1.停止所有load任务
2.删除元数据目录，并重建目录
3.从master节点拷贝元数据到问题节点fe（将 fe.conf 中的 metadata_failure_recovery=true 配置项删除，或者设置为 false，这个非常重要）
4.执行 ALTER SYSTEM DROP FOLLOWER  删除改节点
5.在问题节点使用--helper启动服务
6.在mysql下执行 ALTER SYSTEM ADD FOLLOWER 将FE节点从新加入进去
7.启动正常

注意：

1.问题节点：将 fe.conf 中的 metadata_failure_recovery=true 配置项删除，或者设置为 false
2.Master节点启动使用 metadata_failure_recovery=true启动，进行恢复，启动正常以后，将这个配置删除或者设置为false，停掉Master fe，然后在重启，启动完成以后，要确认Master查询，导入是正常的
上述步骤执行完成以后，然后在问题节点在使用--helper方式启动fe，这个时候正常启动，问题解决

重新启动所有Load任务

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

This is because httpv2 modified the response body of the "/info" api,
causing FE to fail to obtain info from this api.
And the system did not exit correctly.

This will also cause issues in issue #5292

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have created an issue on (Fix #5292) and described the bug/feature there in detail

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 1]
```diff
@@ -1425,7 +1428,26 @@ private StorageInfo getStorageInfo(URL url) throws IOException {
...
+            try (BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
+                String line;
+                StringBuilder sb = new StringBuilder();
+                while ((line = bufferedReader.readLine()) != null) {
+                    sb.append(line);
+                }
+                response = sb.toString();
+            }
+
+			// For http v2, the response body for "/info" api changed from
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:1442]: The indentation here is strange.

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 2]
```diff
@@ -1425,7 +1428,26 @@ private StorageInfo getStorageInfo(URL url) throws IOException {
...
+			// StorageInfo to StorageInfoV2.
+			// So we need to make it compatible with old api.
+            try {
+                return mapper.readValue(response, StorageInfo.class);
+            } catch (Exception e) {
+				// try new response body
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:1448]: same as above

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 3]
```diff
@@ -1394,7 +1397,7 @@ private void getNewImage(Pair<String, Integer> helperNode) throws IOException {
                 MetaHelper.complete(filename, dir);
             }
         } catch (Exception e) {
-            return;
+            throw new IOException(e);
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:1400]: Could you please add some Error Log in here.

File: fe/fe-core/src/main/java/org/apache/doris/persist/StorageInfoV2.java [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+package org.apache.doris.persist;
+
+/**
+ * This class is wrapper of StorageInfo.
+ * Because for http v2, the response body of "/info" api changed to:
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/persist/StorageInfoV2.java:22]: Because after version 0.13, Doris use http v2 instead of http v1

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java (hunk 3 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:1400]: The error log will be printed outside

File: fe/fe-core/src/main/java/org/apache/doris/persist/StorageInfoV2.java (hunk 4 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/persist/StorageInfoV2.java:22]: the httpv2 is still disable by default.

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

**Review by yangzhg — APPROVED** [review]
LGTM
