### PR TITLE
[Bug] Fix alter table failed when none of new load jobs succeed on alter replica

### LINKED ISSUE #5612: [AlterTable] Failed to alter table
**Describe the bug**
Add a column to a table, but the process blocked.
I found an exception on FE like:
```
2021-04-08 13:39:44,663 INFO (thrift-server-pool-613|804) [AlterHandler.handleFinishAlterTask():451] before handle alter task tablet 481265671, replica: [replicaId=481265672, BackendId=62134593, version=1, versionHash=0, dataSize=331285058, rowCount=1823157, lastFailedVersion=3, lastFailedVersionHash=6798223064512349591, lastSuccessVersion=27, lastSuccessVersionHash=5339720724553352740, lastFailedTimestamp=1617814890844, schemaHash=80261792, state=ALTER], task version: 3-6798223064512349591
2021-04-08 13:39:44,664 WARN (thrift-server-pool-613|804) [MasterImpl.finishTask():221] finish agent task error.
java.lang.IllegalStateException: 3
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[jprotobuf-2.2.11-jar-with-dependencies.jar:?]
        at org.apache.doris.alter.AlterHandler.handleFinishAlterTask(AlterHandler.java:463) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.MasterImpl.finishAlterTask(MasterImpl.java:847) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.MasterImpl.finishTask(MasterImpl.java:210) [palo-fe.jar:3.4.0]
        at org.apache.doris.service.FrontendServiceImpl.finishTask(FrontendServiceImpl.java:376) [palo-fe.jar:3.4.0]
        at org.apache.doris.thrift.FrontendService$Processor$finishTask.getResult(FrontendService.java:1473) [palo-fe.jar:3.4.0]
        at org.apache.doris.thrift.FrontendService$Processor$finishTask.getResult(FrontendService.java:1458) [palo-fe.jar:3.4.0]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
The new tablet's info can not be updated, and the process blocked.

Why we need this check in case 1?
```
if (replica.getVersion() > task.getVersion()) {
                // Case 2.2, do nothing
            } else {
                if (replica.getLastFailedVersion() > task.getVersion()) {
                    // Case 2.1
                    replica.updateVersionInfo(task.getVersion(), task.getVersionHash(), replica.getDataSize(), replica.getRowCount());
                    versionChanged = true;
                } else {
                    // Case 1
                    Preconditions.checkState(replica.getLastFailedVersion() == -1, replica.getLastFailedVersion());  // Why we need this check?
                    replica.updateVersionInfo(task.getVersion(), task.getVersionHash(), replica.getDataSize(), replica.getRowCount());
                    versionChanged = true;
                }
            }
```

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes
 If none of new load jobs succeed on alter replica. the version can still be (0-1), and the replica's last failed version may be smaller than the specified version before which the history data has been transformed successfully. , because new load job may load data into alter replica with version smaller than the specified version.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5612 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java [hunk 1]
```diff
@@ -494,6 +494,7 @@ private void onFinished(OlapTable tbl) {
             partition.visualiseShadowIndex(rollupIndexId, false);
         }
         tbl.rebuildFullSchema();
+        tbl.setState(OlapTableState.NORMAL);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java:497]: We can to batch rollup jobs, and I think the table's state should be set to NORMAL after all jobs are done,
which is in MaterializedViewHandler.onJobDone()

File: fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java [hunk 2]
```diff
@@ -536,6 +537,7 @@ private void cancelInternal() {
                         partition.deleteRollupIndex(rollupIndexId);
                     }
                     tbl.deleteIndexInfo(rollupIndexName);
+                    tbl.setState(OlapTableState.NORMAL);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java:540]: Same as above

**Review by morningman — APPROVED** [review]
LGTM
