### PR TITLE
[enhancement](image): load image supports reading in batches

### LINKED ISSUE #6447: [Bug] DeleteInfos in the DeleteHandler will never be deleted
**Describe the bug**
DeleteInfos in the DeleteHandler will never be deleted, taking up too much memory and metadata storage.
When users use a large number of delete statements, FE metadata parsing problems will occur, resulting in failure to restart all FEs due to load image failure. 
An error is reported when starting FE:
```
java.lang.IllegalArgumentException: capacity < 0: (-2144832511 < 0)
  at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
  at java.base/java.nio.CharBuffer.allocate(CharBuffer.java:347)
  at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:809)
  at org.apache.doris.common.io.Text.decode(Text.java:362)
  at org.apache.doris.common.io.Text.decode(Text.java:341)
  at org.apache.doris.common.io.Text.readString(Text.java:416)
  at org.apache.doris.load.DeleteHandler.read(DeleteHandler.java:687)
  at org.apache.doris.catalog.Catalog.loadDeleteHandler(Catalog.java:1879)
  at org.apache.doris.catalog.Catalog.loadImage(Catalog.java:1530)
  at org.apache.doris.catalog.Catalog.initialize(Catalog.java:772)
  at org.apache.doris.PaloFe.start(PaloFe.java:109)
  at org.apache.doris.PaloFe.main(PaloFe.java:60)
```

**To Reproduce**
1. Execute the "show delete" statement to see all the historical deleted information
2. When there are too many deleteInfo, load image error when restarting FE, and FE cannot be started

**Expected behavior**
1. According to the `delete_info_keep_max_second` configuration, clean up the old deleteInfo
2. Support pagination to read metadata text when load image

**Environment**
 - OS: Centos7
 - Version: Doris branch-0.13

### PR DESCRIPTION
**Pull request by htyoung**
Text.readString supports reading in batches to avoid the situation where the size of delete info in image file becomes too large due to a long period without checkpointing, which could cause the method CharBuffer.allocate size to exceed the maximum value of Integer.MAX_VALUE and result in an overflow.

### What problem does this PR solve?

Issue Number: close #6447 

Related PR: #6448

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [x] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [  ] Confirm the release note
- [  ] Confirm test cases
- [  ] Confirm document
- [  ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by htyoung** [comment]
run buildall

**Comment by htyoung** [comment]
run buildall

File: fe/fe-common/src/main/java/org/apache/doris/common/io/Text.java [hunk 1]
```diff
@@ -413,8 +408,39 @@ public static String readString(DataInput in) throws IOException {
         int length = in.readInt();
         byte[] bytes = new byte[length];
         in.readFully(bytes, 0, length);
-        String res = decode(bytes);
-        return res;
+        //The maximum amount that can be read at one time is 16MB.
+        int stepLen = 1024 * 1024 * 16;
```
Comment (yiguolei) [inline fe/fe-common/src/main/java/org/apache/doris/common/io/Text.java:412]: change this value to a  config

Comment (htyoung) [reply fe/fe-common/src/main/java/org/apache/doris/common/io/Text.java]: I have already modified

**Comment by htyoung** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by htyoung** [comment]
run buildall

File: fe/fe-common/src/main/java/org/apache/doris/common/Config.java [hunk 2]
```diff
@@ -2883,6 +2883,19 @@ public class Config extends ConfigBase {
...
+            "的大小。等于-1的值表示一次性读取完整的字节数组后反序列化反序列化为utf8编码字符串；" +
+            "不等于-1的值（至少16MB）表示分批每次读取多大的字节数组后反序列化为utf8编码字符串，最后合并成完成的字符串。默认值为-1",
+        "The size of a single batch (in bytes) when loading the binary content of a module of the " +
+            "image file into a byte array and deserializing the byte array into a utf8 encoded string when FE starts." +
+            " A value equal to -1 means reading the entire byte array at once and " +
+            "then deserializing it into a utf8 encoded string; a value not equal to -1 means reading " +
+            "a certain size (at least 16MB) of byte array in batches and then deserializing it into a " +
+            "utf8 encoded string, and finally merging it into a completed string. The default value is -1"
+    })
+    public static int metadata_image_module_load_batch_size = -1;
```
Comment (morningman) [inline fe/fe-common/src/main/java/org/apache/doris/common/Config.java:2897]:
```suggestion
    public static int metadata_text_read_max_batch_bytes = -1;
```

Comment (htyoung) [reply fe/fe-common/src/main/java/org/apache/doris/common/Config.java]: Yeh, I have change the variable name

**Comment by htyoung** [comment]
image
Can checkstyle check be combined with code formatter check in advance to detect some coding problems in advance?

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
