### PR TITLE
[BUGFIX] forbidden create materialized view with distinct

### LINKED ISSUE #7516: [Bug] forbidden create materialized view with distinct
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

when user create materialized view with distinct, the materialized view can be created. it is not fit for the current condition, because  it is not can be used and doris does not suppot create materialized view for count distinct. so should forbid the operator.

### What You Expected?

we should forbid the operator when user create materialized view for count distinct.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xuzifu666**
## Proposed changes

Closed #7516  (replace it with issue number if it exists).

Describe the overview of changes, and introduce why we need it.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #7516) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by EmmyMiao87** [comment]
Could you please add an issue about your PR?

**Comment by xuzifu666** [comment]
> Could you please add an issue about your PR?

ok, i had commit a issue about it.   https://github.com/apache/incubator-doris/issues/7516

**Comment by xuzifu666** [comment]
> > Could you please add an issue about your PR?
> 
> ok, i had commit a issue about it. #7516

@EmmyMiao87

File: fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java [hunk 1]
```diff
@@ -102,6 +102,38 @@ public AggregateFunction(FunctionName fnName, List<Type> argTypes,
                 mergeFnSymbol, getValueFnSymbol, removeFnSymbol, finalizeFnSymbol, false);
     }
 
+    public AggregateFunction(FunctionName fnName, List<Type> argTypes,
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java:105]: Adding a constructor only for UT is a less elegant behavior. 
If you need to use this variable in UT, but there are some attributes that you can’t use, the better way is new an object and pass in an empty string instead of adding a constructor without a default value.

File: fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java [hunk 2]
```diff
@@ -193,6 +199,11 @@ public void analyzeSelectClause() throws AnalysisException {
                 // Function must match pattern.
                 FunctionCallExpr functionCallExpr = (FunctionCallExpr) selectListItemExpr;
                 String functionName = functionCallExpr.getFnName().getFunction();
+                // current version not support count(distinct) function in creating materialized view
+                if (!isReplay && functionName.toLowerCase().equals("count") && functionCallExpr.isDistinct()) {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java:203]: There is really no problem with this repair. But I think a better way is:
1. Modify MVColumnOneChildPattern
2. ```  if (isReplay) {
                  ignore pattern
            } else {match pattern}
     ```

File: fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java [hunk 3]
```diff
@@ -193,6 +199,15 @@ public void analyzeSelectClause() throws AnalysisException {
                 // Function must match pattern.
                 FunctionCallExpr functionCallExpr = (FunctionCallExpr) selectListItemExpr;
                 String functionName = functionCallExpr.getFnName().getFunction();
+                // current version not support count(distinct) function in creating materialized view
+                if (!isReplay) {
+                    for (Map.Entry<String, MVColumnPattern> env : FN_NAME_TO_PATTERN.entrySet()){
+                        if (!env.getValue().match(functionCallExpr)){
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java:205]: Each function corresponds to its own pattern. He only needs to ensure that his pattern is passed. It is not necessary to satisfy all patterns.

File: fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnOneChildPattern.java [hunk 4]
```diff
@@ -31,6 +34,11 @@ public boolean match(Expr expr) {
             return false;
         }
         FunctionCallExpr functionCallExpr = (FunctionCallExpr) expr;
+        if (functionName.toLowerCase().equals(AggregateType.SUM.name().toLowerCase()) || functionName.toLowerCase().equals(AggregateType.MAX.name().toLowerCase()) || functionName.toLowerCase().equals(AggregateType.MIN.name().toLowerCase()) || functionName.toLowerCase().equals(FunctionSet.COUNT)) {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnOneChildPattern.java:37]:
```suggestion
        if (functionCallExpr.isDistinct()) {
            return false;
        }
```

**Comment by EmmyMiao87** [comment]
Please fix the ut test ~

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
