### PR TITLE
[enhancement](load) merge single-replica related services as non-standalone 

### LINKED ISSUE #17333: [Enhancement] better merge single_replica_load_rpc_service into brpc_service
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

better merge single_replica_load_rpc_service into brpc_service

refer to these to see what is `single replica load`: 
[single replica load design](https://cwiki.apache.org/confluence/display/DORIS/DSIP-015:+Support+single+replica+load+for+load)
[single replica implement]( https://github.com/apache/doris/commit/f730a048b1e3baf3d78b27292698eecbae3fcef7)

The code would be much clarified if there is only one rpc service. The reason why the original code uses two services is that rpc will time out under heavy workloads if use just one.

However, according to the design of brpc thread model, even if running in separated service thread pools, the underlying pthreads/cpu cores are shared by the two services. I think the reason why the two services solution works is only because it claims more worker pthreads, which can also be achieved by simply setting bigger  `--bthread_concurrency`  gflag config.

So two services achieve nothing but messyness. We should merge them into one and identify&fix the root cause of the timeout problem.

### Solution

step1. merge single_replica_load_rpc_service into brpc_service

step2. test the system with heavy load jobs to try to reproduce the rpc timeout problem

step3. make assumptions & proving

> some of my guesses:
>
> ```c++
> void PInternalServiceImpl::request_slave_tablet_pull_rowset(...) {
>     ...
>     worker_pool.offer([=]() {
>        ...     
>     }
>     ...
> }
> ```
>
> if the worker pool is full (possible under heavy loads), the pthread will wait under std::condition_variable. If most of the pthreads in the pool are blocked, there would be few pthread to deal with rpc request and then timeout happens.
>
> If it is true, we need to use bthread's condition variable instead of std::condition_variable. The former one will only yeild the underlying pthread to other rpc jobs, rather than blocking it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

Issue Number: close #17333

## Problem summary

Changes:

1. Merge `single_replica_load_rpc_service` into `brpc_service`
2. Merge `single_replica_load_download_service` into `http_service`
3. Add a thread_pool for `single_replica_load_download`

Benefits:

1. Make it cleaer.
2. Reduce unnecessary port usage.

Tradeoff:

After merging the `single_replica_load_download_service` into `http_service`, when the http server gets a large number of requests in concurrency, not only `single_replica_load_download_num_workers`, but also `webserver_num_workers`  should be increased, for the reason that other heavy sync tasks will occupy the event base thread for a long time until they finish, and impact the single replica load, which needs a relatively large number of requests to complete. 

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.31 seconds
 stream load tsv:          458 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230406120426_clickbench_pr_125572.html

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run arm

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run arm

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
@weizuo93 Would you please give some comments on this PR?

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run arm

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

File: be/src/http/action/download_action.cpp [hunk 1]
```diff
@@ -114,6 +126,14 @@ void DownloadAction::handle_error_log(HttpRequest* req, const std::string& file_
 }
 
 void DownloadAction::handle(HttpRequest* req) {
+    if (_is_async) {
```
Comment (weizuo93) [inline be/src/http/action/download_action.cpp:129]: why is this asynchronous? Could you add some comments please?

Comment (TangSiyang2001) [reply be/src/http/action/download_action.cpp:129]: In my opinion, download job for single replica maybe a relatively heavy task, and it seems that dispatching their process logic to a standalone worker pool maybe more reasonable, and let free the IO threads  to some extent.

Do u think it is reasonable to do so? If so, I'll make some comments to clarify it, otherwise I'll modify the logic.

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run clickbench

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM
