### PR TITLE
[Bug]Fix BE coredump when manual compaction task is triggered

### LINKED ISSUE #7259: [Bug] BE coredump when manual compaction task is triggered
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch : 9b3c83439628317af77dc05b694a24f34e36ac9a

### What's Wrong?

BE coredump will occurs when manual compaction task is triggered by http interface. The stack is as follow:

```
*** Aborted at 1638243517 (unix time) try "date -d @1638243517" if you are using GNU date ***
PC: @          0x12f5fcc doris::Tablet::calculate_cumulative_point()
*** SIGSEGV (@0x0) received by PID 5240 (TID 0x7f2f1b541700) from PID 0; stack trace: ***
    @          0x21040a2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f2f7be38400 (unknown)
    @          0x12f5fcc doris::Tablet::calculate_cumulative_point()
    @          0x13767a6 doris::CumulativeCompaction::prepare_compact()
    @          0x1370e33 doris::Compaction::compact()
    @          0x19dc384 doris::CompactionAction::_execute_compaction_callback()
    @          0x19dc9ad _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIN5doris10OLAPStatusEEES3_EZNS1_11_Task_stateIZNS8_16CompactionAction22_handle_run_compactionEPNS8_11HttpRequestEPSsEUlvE_SaIiEFS9_vEE6_M_runEvEUlvE_S9_EEE9_M_invokeERKSt9_Any_data
    @          0x1549dcf std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f2f7bbec20b __pthread_once_slow
    @          0x19dcc06 std::thread::_State_impl<>::_M_run()
    @          0x38a2640 execute_native_thread_routine
    @     0x7f2f7bbedea5 start_thread
    @     0x7f2f7bf009fd __clone
    @                0x0 (unknown)
```

Member variable`_cumulative_compaction_policy`may be `nullptr` in Object `Tablet`, we should initialize it before compaction task.

### What You Expected?

When manual compaction task is triggered by http interface, compaction task can be implemented successfully.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by weizuo93**
## Proposed changes

Fix #7259
BE coredump will occurs when manual compaction task is triggered by http interface. 

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #7259) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

### CODE REVIEW

File: be/src/http/action/compaction_action.cpp [hunk 1]
```diff
@@ -275,4 +282,20 @@ void CompactionAction::handle(HttpRequest* req) {
         }
     }
 }
+
+std::shared_ptr<CumulativeCompactionPolicy> CompactionAction::_update_cumulative_compaction_policy() {
```
Comment (morningman) [inline be/src/http/action/compaction_action.cpp:286]: The method name is confused. Actually it is "check-and-create", not "update".

Comment (weizuo93) [reply be/src/http/action/compaction_action.cpp]: > 

OK, Thank you.

**Review by morningman — APPROVED** [review]
LGTM
