### PR TITLE
[enhancement](memtracker) Optimize readability of mem exceed limit error message

### LINKED ISSUE #11876: [Enhancement] Improve readability of mem exceed limit error message
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

mem exceed limit error message
```
ERROR 1105 (HY000): errCode = 2, detailMessage = vsort, while open., failed mem consume:<consume_size=-1.00 B, mem_limit=8000, mem_used=51472, tracker_label=RuntimeState:instance:36686ecbe69d41a6-87e33564ada67d81, in backend=172.24.47.117 free memory left=9.59 GB. details mem usage see be.INFO.
```

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #11876

## Problem summary

1. Mem exceed limit error message after optimization
```
memory limit exceeded:<exceeded_tracker=Query#queryId=1720e4ca3ac541c0-8dee8f4667ee7176, limit=80000, peak_used=133111504, current_used=133168448>, executing:<exec node:, vsort, while open.>, backend=172.24.47.117 free memory left=12.01 GB. If is query, can change the limit by `set exec_mem_limit=xxx`, details mem usage see be.INFO.
```
2. Optimize the constructor of mem tracker.
3. Restore `consume_local`, which has better applicability.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
4. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
5. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
6. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
7. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/service/doris_main.cpp [hunk 1]
```diff
@@ -503,6 +503,7 @@ int main(int argc, char** argv) {
         // this will cause coredump for ASAN build when running regression test,
         // disable temporarily.
         doris::ExecEnv::GetInstance()->task_pool_mem_tracker_registry()->logout_task_mem_tracker();
+        doris::ExecEnv::GetInstance()->process_mem_tracker()->enable_print_log_usage();
```
Comment (yiguolei) [inline be/src/service/doris_main.cpp:506]: If this method has to be called and it only set a property value. I think the property value should be a config.

Comment (xinyiZzz) [reply be/src/service/doris_main.cpp:506]: `enable_print_log_usage` is reset to true every 1s, this is to avoid frequent log printing when process mem tracker exceeds mem limit.

**Review by yiguolei — APPROVED** [review]
LGTM
