### PR TITLE
 [Bug] Fix bug that not erase meta such as tablet when force drop db, table, partition

### LINKED ISSUE #5331: [Bug] when force drop db, table, partition, related metas such as tablets are not erased
Sometimes, we need force drop meta and not need recycle db, table, partition anymore, but now, when we drop meta forcely, the related meta such as tablet is not erased.

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5331 ) and described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If these changes need document changes, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 1]
```diff
@@ -6811,5 +6820,67 @@ private void setReplicaStatusInternal(long tabletId, long backendId, ReplicaStat
             table.writeUnlock();
         }
     }
+
+    public void eraseDatabase(long dbId, boolean needEditLog) {
+        // remove jobs
+        Catalog.getCurrentCatalog().getLoadInstance().removeDbLoadJob(dbId);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:6826]: I think we don't need to call these `removeXXXJobs` functions. Because these jobs will be cancelled automatically when it find that database does not exist anymore.

**Review by morningman — COMMENTED** [review]
Hi @caiconghui , I think we should add some ut for dropping database/table/partition

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java (hunk 1 above)
Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:6826]: we need to remove these info from map? I don't find any other way to remove these infos.

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java:6826]: It's ok to leave these code in this PR. I will check these logic and refactor them later.

**Review by morningman — APPROVED** [review]
LGTM
