### PR TITLE
[bugfix](index) index page should not be bitshuffle decoded

### LINKED ISSUE #12230: [Bug] read bitmap index failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

read column data with bitmap index failed:
```
errCode = 2, detailMessage = failed to initialize storage reader. tablet=37661.1941406444.81452927a4f817c9-a11add9f5a37f39a, res=Internal error(error -3111):  0# doris::Status::ConstructErrorStatus(short) at /mnt/disk/tengjianping/doris-test/be/src/common/status.cpp:78
 1# doris::Status::OLAPInternalError(short) at /mnt/disk/tengjianping/doris-test/be/src/common/status.h:392
 2# doris::BetaRowsetReader::next_block(doris::vectorized::Block*) at /mnt/disk/tengjianping/doris-test/be/src/olap/rowset/beta_rowset_reader.cpp:270
 3# doris::vectorized::VCollectIterator::Level0Iterator::_refresh_current_row() at /mnt/disk/tengjianping/doris-test/be/src/vec/olap/vcollect_iterator.cpp:219
 4# doris::vectorized::VCollectIterator::Level0Iterator::init() at /mnt/disk/tengjianping/doris-test/be/src/vec/olap/vcollect_iterator.cpp:204
 5# doris::vectorized::VCollectIterator::build_heap(std::vector<std::shared_ptr<doris::RowsetReader>, std::allocator<std::shared_ptr<doris::RowsetReader> > >&) at /mnt/disk/tengjianping/doris-test/be/src/vec/olap/vcollect_iterator.cpp:74
 6# doris::vectorized::BlockReader::_init_collect_iter(doris::TabletReader::ReaderParams const&, std::vector<std::shared_ptr<doris::RowsetReader>, std::allocator<std::shared_ptr<doris::RowsetReader> > >*) at /mnt/disk/tengjianping/doris-test/be/src/vec/olap/block_reader.cpp:64
 7# doris::vectorized::BlockReader::init(doris::TabletReader::ReaderParams const&) at /mnt/disk/tengjianping/doris-test/be/src/vec/olap/block_reader.cpp:136
 8# doris::vectorized::VOlapScanner::open() at /mnt/disk/tengjianping/doris-test/be/src/vec/exec/volap_scanner.cpp:126
 9# doris::vectorized::VOlapScanNode::scanner_thread(doris::vectorized::VOlapScanner*) at /mnt/disk/tengjianping/doris-test/be/src/vec/exec/volap_scan_node.cpp:402
```

### What You Expected?

read data ok

### How to Reproduce?

```
CREATE TABLE `test` (
        `a` decimal(12, 6) NOT NULL
        ) ENGINE = OLAP
        DUPLICATE KEY(`a`)
        DISTRIBUTED BY HASH(`a`) BUCKETS 1
        PROPERTIES (
            "replication_allocation" = "tag.location.default: 1");
        """
    sql """
    create index bitmap_index_multi_page on test(a) using bitmap;
```

Load 100 million duplicate rows  into table, then execute sql:
```
select * from test limit 10;
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jacktengg**
# Proposed changes

Issue Number: close #12230 

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/olap/rowset/segment_v2/page_io.h [hunk 1]
```diff
@@ -115,7 +115,8 @@ class PageIO {
     //     `body' points to page body,
     //     `footer' stores the page footer.
     static Status read_and_decompress_page(const PageReadOptions& opts, PageHandle* handle,
-                                           Slice* body, PageFooterPB* footer);
+                                           Slice* body, PageFooterPB* footer,
+                                           bool pre_decode = true);
```
Comment (mrhhsg) [inline be/src/olap/rowset/segment_v2/page_io.h:119]: It may be better to make `pre_decode` a field of PageReadOptions.

**Review by yiguolei — APPROVED** [review]
LGTM
