### PR TITLE
[Fix] select nested type of string within type array should be wrappe…

### LINKED ISSUE #10497: [Enhancement] vectorized array mysql_result_writer should wrap nested string type with ''
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

```
mysql> create table test_array_string (k1 INT, k2 INT, k3 array<string>) ENGINE=olap DUPLICATE KEY(k1, k2) PARTITION BY RANGE (k1) (partition `p1` values less than ("1000"), partition `p2` values less than ("2000"),partition `p3` values less than ("3000"))  DISTRIBUTED BY HASH(k2) BUCKETS 3 PROPERTIES("replication_num" = "1");

mysql> insert into test_array_string  values(1, 2, ["a", "b", "c"]),(1, 2, ["a", "b"]),(1, 2, ["a", "xxqwdqw", "c"]),(1, 2, ["a", "b"]),(1, 2, ["a", "b", "c"]),(1, 2, ["a", "b", "c"]),(1, 2, ["a", "b", "c"]),(1, 2, ["a", "b"]),(1, 2, ["a", "b", "c", "d", "e"]),(1, 2, ["a", "b", "c"]), (1, 2, ["a", "b", "cdsdasd"]),(1, 2, [ "nishidabenzhu123"]),(1, 2, ["a", "b", "c"]),(1, 2, ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]), (1, 2, ["a", "cdsdasd"]), (1, 2, ["cdsdasd", "xxxx", "3", "4", "5"]);

mysql> select k3 from test_array_string order by k1 limit 1;
+------------------------------+
| k3                           |
+------------------------------+
| [cdsdasd, xxxx, 3, 4, 5] |
+------------------------------+
1 row in set (0.01 sec)

mysql> set enable_vectorized_engine = false;
Query OK, 0 rows affected (0.00 sec)

mysql> select k3 from test_array_string order by k2 limit 1;
+----------------------------------------+
| k3                                     |
+----------------------------------------+
| ['cdsdasd', 'xxxx', '3', '4', '5'] |
+----------------------------------------+
1 row in set (0.01 sec)
```

if enable_vectorized_engine = true, the output of nested type of string will not be wrapped with '' eg. cdsdasd, the behavior is not the same with none vectorized eg 'cdsdasd'

### Solution

wrap the string nested type of array with ''

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eldenmoon**
…d with '' in vectorized path

```
eg.
mysql> set enable_vectorized_engine = true;
mysql> select k3 from test_array_string order by k2 limit 1;
+----------------------------------------------+
| k3                                           |
+----------------------------------------------+
| ['cdsdasd', 'xxxx', '3', '4', '5', NULL] |
+----------------------------------------------+
```
# Proposed changes

Issue Number: close #10497 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/sink/mysql_result_writer.cpp [hunk 1]
```diff
@@ -136,7 +136,13 @@ Status VMysqlResultWriter::_add_one_column(const ColumnPtr& column_ptr,
                 if (data->is_null_at(j)) {
                     buf_ret = _buffer.push_string("NULL", strlen("NULL"));
                 } else {
-                    buf_ret = _add_one_cell(data, j, nested_type_ptr, _buffer);
+                    if (WhichDataType(remove_nullable(nested_type_ptr)).is_string()) {
+                        buf_ret = _buffer.push_string("'", 1);
+                        buf_ret = _add_one_cell(data, j, nested_type_ptr, _buffer);
```
Comment (yinzhijian) [inline be/src/vec/sink/mysql_result_writer.cpp:141]: What is the result if the nested data is null?

Comment (eldenmoon) [reply be/src/vec/sink/mysql_result_writer.cpp:141]:
```
mysql> set enable_vectorized_engine = true;
mysql> select k3 from test_array_string order by k2 limit 1;
+----------------------------------------------+
| k3                                           |
+----------------------------------------------+
| ['cdsdasd', 'xxxx', '3', '4', '5', NULL] |
+----------------------------------------------+
```
here is an example of nested data is null

Comment (yinzhijian) [reply be/src/vec/sink/mysql_result_writer.cpp:141]: ok

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by eldenmoon** [comment]
@qidaye sorry, i rebased, please approve again

**Review by qidaye — APPROVED** [review]
LGTM
