### PR TITLE
[Bug] Fix disk used pct only consider the data that used by Doris

### LINKED ISSUE #9704: [Bug] RootPathLoadStatistic only consider the data used by Doris
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

I'm using 0.15, but master has the same issue.

### What's Wrong?

RootPathLoadStatistic only consider the data used by Doris. Tablet will not be balanced away until this disk has only `storage_flood_stage_left_capacity_bytes` left (in `DiskInfo.exceedLimit()`) if this BE is at `MID` load.

### What You Expected?

Calculate the disk used pct instead of data used pct.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ccoffline**
# Proposed changes

Issue Number: close #9704 

## Problem Summary:

Calculate the disk used pct instead of data used pct.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java [hunk 1]
```diff
@@ -187,7 +187,7 @@ public void init() throws LoadBalanceException {
 
             RootPathLoadStatistic pathStatistic = new RootPathLoadStatistic(beId, diskInfo.getRootPath(),
                     diskInfo.getPathHash(), diskInfo.getStorageMedium(),
-                    diskInfo.getTotalCapacityB(), diskInfo.getDataUsedCapacityB(), diskInfo.getState());
+                    diskInfo.getTotalCapacityB(), diskInfo.getDiskUsedCapacityB(), diskInfo.getState());
```
Comment (carlvinhust2012) [inline fe/fe-core/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java:190]: your means that it should statistic the usage of disk instead of the data?

Comment (ccoffline) [reply fe/fe-core/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java:190]: Yes, and it seems that `TDisk.getDataUsedCapacity()` only counts all tablets, which means it ignores trash, meta and log

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
quick merge because it has been approve several days ago
