### PR TITLE
[fix] Check rs meta size during cool down progress

### LINKED ISSUE #57367: [Bug] Be core during hot/cold cooldown progress
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.11

### What's Wrong?

Image

### What You Expected?

Check the size of `cooldown_meta_pb.rs_metas()`.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhaorongsheng**
### What problem does this PR solve?

Issue Number: close #57367

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Review by gavinchou — DISMISSED** [review]

File: be/src/olap/tablet.cpp [hunk 1]
```diff
@@ -2273,6 +2273,15 @@ Status Tablet::_follow_cooldowned_data() {
         LOG(INFO) << "cannot read cooldown meta: " << st;
         return Status::InternalError<false>("cannot read cooldown meta");
     }
+
+    if (cooldown_meta_pb.rs_metas_size() <= 0) {
```
Comment (gavinchou) [inline be/src/olap/tablet.cpp:2277]: The follow up `DCHECK` seems not useless when this check hit, remove it?
BTW, it is better to figure out why the `DECHECK()`/`cooldown_meta_pb.rs_metas_size() == 0` happens.

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM
