### PR TITLE
[Bug](materialized-view) check groupby in agg-bottom-plan when rewrite agg query by mv

### LINKED ISSUE #34155: [Bug] rewrite by mv roll up bug? when query rewrite by materialized view
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

when rewrite query in AbstractMaterializedViewAggregateRule roll up, bad view is chosen

table structure:
```sql
CREATE TABLE IF NOT EXISTS orders  (
    o_orderkey       integer not null,
    o_custkey        integer not null,
    o_orderstatus    char(1) not null,
    o_totalprice     decimalv3(15,2) not null,
    o_orderdate      date not null,
    o_orderpriority  char(15) not null,
    o_clerk          char(15) not null,
    o_shippriority   integer not null,
    o_comment        varchar(79) not null
    )
    DUPLICATE KEY(o_orderkey, o_custkey)
    PARTITION BY RANGE(o_orderdate)(
    FROM ('2023-10-17') TO ('2023-10-20') INTERVAL 1 DAY)
    DISTRIBUTED BY HASH(o_orderkey) BUCKETS 3
    PROPERTIES ("replication_num" = "1");

insert into orders values
   (1, 1, 'ok', 99.5, '2023-10-17', 'a', 'b', 1, 'yy'),
   (2, 2, 'ok', 109.2, '2023-10-18', 'c','d',2, 'mm'),
   (3, 3, 'ok', 99.5, '2023-10-19', 'a', 'b', 1, 'yy');


CREATE MATERIALIZED VIEW mv4
DISTRIBUTED BY RANDOM BUCKETS 3
PROPERTIES ('replication_num' = '1')
AS
SELECT sum(o_totalprice)
FROM orders
GROUP BY o_orderdate, o_orderpriority;

CREATE MATERIALIZED VIEW mv5
DISTRIBUTED BY RANDOM BUCKETS 3
PROPERTIES ('replication_num' = '1')
AS
SELECT sum(o_totalprice)
FROM orders
GROUP BY o_orderstatus, o_orderpriority;
```

query:
```sql
select sum(o_totalprice) from orders group by o_orderdate
```

```
+----------------------------------------------------------------------+
| Explain String(Nereids Planner)                                      |
+----------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                      |
|   OUTPUT EXPRS:                                                      |
|     sum(o_totalprice)[#3]                                            |
|   PARTITION: UNPARTITIONED                                           |
|                                                                      |
|   HAS_COLO_PLAN_NODE: false                                          |
|                                                                      |
|   VRESULT SINK                                                       |
|      MYSQL_PROTOCAL                                                  |
|                                                                      |
|   3:VAGGREGATE (merge finalize)(369)                                 |
|   |  output: sum(partial_sum(__sum_0)[#1])[#2]                       |
|   |  group by:                                                       |
|   |  cardinality=3                                                   |
|   |  limit: 3                                                        |
|   |  final projections: non_nullable(sum(__sum_0)[#2])               |
|   |  final project output tuple id: 3                                |
|   |  distribute expr lists:                                          |
|   |                                                                  |
|   2:VEXCHANGE                                                        |
|      offset: 0                                                       |
|      distribute expr lists:                                          |
|                                                                      |
| PLAN FRAGMENT 1                                                      |
|                                                                      |
|   PARTITION: RANDOM                                                  |
|                                                                      |
|   HAS_COLO_PLAN_NODE: false                                          |
|                                                                      |
|   STREAM DATA SINK                                                   |
|     EXCHANGE ID: 02                                                  |
|     UNPARTITIONED                                                    |
|                                                                      |
|   1:VAGGREGATE (update serialize)(363)                               |
|   |  output: partial_sum(__sum_0[#0])[#1]                            |
|   |  group by:                                                       |
|   |  cardinality=1                                                   |
|   |  distribute expr lists:                                          |
|   |                                                                  |
|   0:VOlapScanNode(360)                                               |
|      TABLE: testdb.mv5(mv5), PREAGGREGATION: ON                      |
|      partitions=1/1 (mv5), tablets=3/3, tabletList=10505,10507,10509 |
|      cardinality=2, avgRowSize=0.0, numNodes=1                       |
|      pushAggOp=NONE                                                  |
|                                                                      |
| MaterializedView                                                     |
| MaterializedViewRewriteSuccessAndChose:                              |
|   Names: mv5                                                         |
| MaterializedViewRewriteSuccessButNotChose:                           |
|   Names: mv4                                                         |
| MaterializedViewRewriteFail:                                         |
+----------------------------------------------------------------------+
```

The result is both mv4 and mv5 rewrite success, I think maybe only mv4?

### What You Expected?

chose mv4 without mv5 for the case above

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Z-SWEI**
## Proposed changes

Issue Number: close #34155 

check groupby in agg-bottom-plan when rewrite and rollup agg query by mv

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Z-SWEI** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java [hunk 1]
```diff
@@ -230,57 +230,56 @@ protected Plan rewriteQueryByView(MatchMode matchMode,
...
+            Expression rollupedExpression = queryFunctionShuttled.accept(AGGREGATE_EXPRESSION_REWRITER,
+                    context);
+            if (!context.isValid()) {
+                materializationContext.recordFailReason(queryStructInfo,
+                        "Query function roll up fail",
+                        () -> String.format("queryFunctionShuttled = %s,\n mvExprToMvScanExprQueryBased = %s",
+                                queryFunctionShuttled, mvExprToMvScanExprQueryBased));
+                return null;
             }
+            finalOutputExpressions.add(new Alias(rollupedExpression));
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:282]: final output should contains both aggregate function and group by dimension， this may lost group by dimension out put and change original agg output

Comment (Z-SWEI) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:282]: > final output should contains both aggregate function and group by dimension， this may lost group by dimension out put and change original agg output

I think maybe line 261 does the job you mentioned.
This PR does not modify the logic in rewriteQueryByView().
The key change is line 428 in topPlanSplitToGroupAndFunction() that prevent the loss of groupby in child agg for rules like MaterializedViewProjectAggregateRule.

Comment (seawinde) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:282]: I get your point, the change may change the original agg output order. 
such as query is as following:
```
SELECT sum(o_totalprice), o_orderpriority
FROM orders
GROUP BY o_orderstatus, o_orderpriority;
```
after mv rewreite will be 
```
SELECT o_orderpriority, sum(o_totalprice)
FROM orders
GROUP BY o_orderstatus, o_orderpriority;
```

Maybe we should add another check as following
WDYT?
```
        // if top plan doesn't use group by but bottom agg has group by, should also check
        if (!queryGroupByExpressions.isEmpty() && queryTopPlanGroupBySet.isEmpty()) {
            // todo check as your code in line 242 to 262
        }
```

Comment (Z-SWEI) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:282]: Thx, I will try

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java [hunk 2]
```diff
@@ -230,57 +230,56 @@ protected Plan rewriteQueryByView(MatchMode matchMode,
...
         }
         // add project to guarantee group by column ref is slot reference,
         // this is necessary because physical createHash will need slotReference later
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:285]: Maybe add the following logic here is better, WDYT? 
// if top plan doesn't use group by but bottom agg has group by, should also check
        if (!queryGroupByExpressions.isEmpty() && queryTopPlanGroupBySet.isEmpty()) {
            // todo check as code in line 263 to 278
        }

Comment (Z-SWEI) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java]: I tried here but caused duplicated code about `rewrittenGroupByExpression`, so I just add the compensate groupby to `queryExpressions`.

Comment (seawinde) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java]: Duplicated code can extract a common method and call the method in different place.
`queryExpressions` means the expression query used readly, if you add compensate groupby to `queryExpressions`, this may change the `queryExpressions` original meaning.

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java [hunk 3]
```diff
@@ -284,6 +285,26 @@ protected Plan rewriteQueryByView(MatchMode matchMode,
...
+        for (Expression expression : queryChildrenGroupBySet) {
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:288]: this can add if condition as following for performance
        if (!queryGroupByExpressions.isEmpty() && queryTopPlanGroupBySet.isEmpty()) {
           do your check logic
        }

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java [hunk 4]
```diff
@@ -426,7 +447,8 @@ private Pair<Set<? extends Expression>, Set<? extends Expression>> topPlanSplitT
                 topGroupByExpressions.add(expression);
             }
         });
-        return Pair.of(topGroupByExpressions, topFunctionExpressions);
+        groupByExpressionSet.removeAll(topGroupByExpressions);
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:450]: `topPlanSplitToGroupAndFunction`  means get the group by and agg fuctions expression pair from top plan, this change the measing of the method
May be we can get the result of method `topPlanSplitToGroupAndFunction` and then do your removeAll logic

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java [hunk 5]
```diff
@@ -284,6 +285,26 @@ protected Plan rewriteQueryByView(MatchMode matchMode,
...
+                // group expr can not rewrite by view
+                materializationContext.recordFailReason(queryStructInfo,
+                        "View dimensions doesn't not cover the query dimensions in bottom agg ",
+                        () -> String.format("mvExprToMvScanExprQueryBased is %s,\n queryGroupShuttledExpr is %s",
+                                mvExprToMvScanExprQueryBased, queryGroupShuttledExpr));
+                return null;
+            }
+            NamedExpression groupByExpression = rewrittenGroupByExpression instanceof NamedExpression
+                    ? (NamedExpression) rewrittenGroupByExpression : new Alias(rewrittenGroupByExpression);
+            finalGroupExpressions.add(groupByExpression);
```
Comment (seawinde) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:306]: if doesn't pass when check, we return null as the code line 302, this is useful
We should not add the groupByExpression to `finalGroupExpressions` like code line 306,
`finalGroupExpressions` means mv rewrite result out put

Comment (Z-SWEI) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:306]: 感觉得留在finalGroupExpressions里边吧。比如像下面这个select语句在改写的时候，logicalProject里边不包含groupby的字段，这个时候不把child里边的logicalAggregate的groupby o_orderdate留着，那改写成功以后这个groupby不就被丢掉了吗？我理解错了吗
```sql
select sum(o_totalprice) from orders group by o_orderdate
```

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java (hunk 3 above)
Comment (Z-SWEI) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:288]: 有没有可能queryTopPlanGroupBySet不为空，但是也没有包含全部的groupby字段 这种情况？
比如 `select sum(o_totalprice), a from orders group by o_orderdate, a, b`
这种情况的话`if (!queryGroupByExpressions.isEmpty() && queryTopPlanGroupBySet.isEmpty())`是不是筛查不出来

Comment (seawinde) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:288]: you are right, this check condition should be  `if top group by doest equals bottom group by, we should add check`

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java (hunk 5 above)
Comment (seawinde) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:306]: you are right, this should add to the finalGroupExpressions.
your test case is nice, can you add the test case to [regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy](https://github.com/apache/doris/blob/master/regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy)?

Comment (Z-SWEI) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:306]: OK. I'd like to try.

Comment (seawinde) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java:306]: After add the test case to [aggregate_with_roll_up.groovy](https://github.com/apache/doris/blob/master/regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy)
you can run the command as following to re generate aggregate_with_roll_up.out:
`./run-regression-test.sh  --run -d nereids_rules_p0/mv/agg_with_roll_up  -s aggregate_with_roll_up -forceGenOut
`
see regresson-test detail in [https://doris.apache.org/community/developer-guide/regression-testing](https://doris.apache.org/community/developer-guide/regression-testing)

**Comment by seawinde** [comment]
run buildall

**Review by seawinde — APPROVED** [review]
LGTM

**Comment by seawinde** [comment]
Next We should make sure that required pipeline tests all pass

**Review by morrySnow — APPROVED** [review]
