### PR TITLE
[fix](storage)fix column dict incorrect result

### LINKED ISSUE #11644: [Bug] Returning incorrect amount of rows when enable vectorization in some where conditions with varchar data type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.1.1 rc03

### What's Wrong?

MySQL [testdb]> select count(*) from  lide_test where create_time>='2022-05-22 11:56:00' and create_time<='2022-05-22 11:58:00';
+----------+
| count(*) |
+----------+
|      105 |
+----------+
1 row in set (0.06 sec)

MySQL [testdb]> set enable_vectorized_engine=true;
Query OK, 0 rows affected (0.00 sec)

MySQL [testdb]> select count(*) from  lide_test where create_time>='2022-05-22 11:56:00' and create_time<='2022-05-22 11:58:00';
+----------+
| count(*) |
+----------+
|      104 |
+----------+
1 row in set (0.07 sec)

### What You Expected?

The same result between enable or disable vectorization

### How to Reproduce?

1. create table
CREATE TABLE `lide_test` (
  `uid` varchar(500) NULL COMMENT "",
  `dt` date NULL COMMENT "导入时间",
  `create_time` varchar(1050) NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`uid`, `dt`)
COMMENT "OLAP"
PARTITION BY RANGE(`dt`)
(PARTITION P19700101 VALUES [('1970-01-01'), ('2022-08-08')),
PARTITION P20220808 VALUES [('2022-08-08'), ('2022-08-09')),
PARTITION P20220809 VALUES [('2022-08-09'), ('2022-08-10')),
PARTITION P20220810 VALUES [('2022-08-10'), ('2022-08-11')),
PARTITION P20220811 VALUES [('2022-08-11'), ('2022-08-12')),
PARTITION P20220812 VALUES [('2022-08-12'), ('2022-08-13')),
PARTITION P20220813 VALUES [('2022-08-13'), ('2022-08-14')))
DISTRIBUTED BY HASH(`uid`, `dt`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);

2. import sample data
download from https://derenli-bj-1301087413.cos.ap-beijing.myqcloud.com/tmp/data.tgz

4. query

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangbo**
# Proposed changes

Issue Number: close #11644

## Problem summary

When ColumnIterator::next_batch put data from several pages to a batch, the 1st page may use DICT encoding while the 2nd page may use PLAIN encoding. Then we have to convert ColumnDictionary to PredicateColumn due to dict is not working any more.

There are two parts in a ColumnDictionary, codes and dict.  Codes is read from page decoder and converted if necessary to do range predicate. When a new batch is read, ColumnDictionary is cleared especially codes is  cleared, but dict is keep. So for a new batch, dict may be sorted but codes is same as on disk.

SegmentIterator convert dict codes to do range predicate by calling convert_dict_codes_if_necessary.  However if a ColumnDictionary is changed PredicateColumn by ColumnIterator, SegmentIterator does not know it, so ColumnIterator should handle it by itself.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/columns/column_dictionary.h [hunk 1]
```diff
@@ -257,6 +257,9 @@ class ColumnDictionary final : public COWHelper<IColumn, ColumnDictionary<T>> {
     bool is_dict_code_converted() const { return _dict_code_converted; }
 
     MutableColumnPtr convert_to_predicate_column_if_dictionary() override {
+        if (is_dict_sorted() && !is_dict_code_converted()) {
```
Comment (mrhhsg) [inline be/src/vec/columns/column_dictionary.h:260]: It seems that `is_dict_sorted()` and `is_dict_code_converted()` are always the same value.

**Review by dataroaring — APPROVED** [review]
LGTM

File: be/src/vec/columns/column_dictionary.h (hunk 1 above)
Comment (dataroaring) [reply be/src/vec/columns/column_dictionary.h:260]: Please refer to problem summary.

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM
