### PR TITLE
[BUG] Fix colocate balance bug when no available BE

### LINKED ISSUE #5075: [BUG] FE CPU 100%
**Describe the bug**
when i use stream load , cpu will increate to 100%

**To Reproduce**
1. start fe
2. start be
3. use stream load
4. cpu will increase to 100%
5. stop fe
6. cpu will recover to normal

**Expected behavior**
cpu should't cost so much cpu

**Screenshots**
image

**Additional context**
1 FE 1BE

### PR DESCRIPTION
**Pull request by stdpain**
## Proposed changes

will close #5075 

## Types of changes

What types of changes does your code introduce to Doris?

- [x] Bugfix (Fix colocate balance bug when no available BE)
- [x] Code refactor (Improve code readability)

## Checklist

- [x] I have create an issue on (Fix #5075  ), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged

## Further comments

When no avaliable BE，colocate rebalance will hang

### CODE REVIEW

File: fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java [hunk 1]
```diff
@@ -37,10 +37,7 @@
 import org.junit.Before;
 import org.junit.Test;
 
-import java.util.HashSet;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (morningman) [inline fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java:40]: Not using *

Comment (stdpain) [reply fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java]: fixed

**Review by morningman — APPROVED** [review]
LGTM
