### PR TITLE
[Vectorized][Bug] fix percentile_approx function to return always nullable

### LINKED ISSUE #8570: [Bug][Vectorized] percentile_approx function will be core when get result column nullable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

vectorized 1.0.1

### What's Wrong?

percentile_approx should always return nullable column, but it's now not set in FE

### What You Expected?

get right result

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangstar333**
…lable

# Proposed changes

Issue Number: close #8570 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h [hunk 1]
```diff
@@ -152,32 +151,57 @@ class AggregateFunctionPercentileApproxMerge : public AggregateFunctionPercentil
...
 class AggregateFunctionPercentileApproxTwoParams : public AggregateFunctionPercentileApprox {
 public:
     AggregateFunctionPercentileApproxTwoParams(const DataTypes& argument_types_)
             : AggregateFunctionPercentileApprox(argument_types_) {}
     void add(AggregateDataPtr __restrict place, const IColumn** columns, size_t row_num,
              Arena*) const override {
-        const auto& sources = static_cast<const ColumnVector<Float64>&>(*columns[0]);
-        const auto& quantile = static_cast<const ColumnVector<Float64>&>(*columns[1]);
+        if constexpr (is_nullable) {
+            const auto* nullable_column = check_and_get_column<ColumnNullable>(columns[0]);
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h:162]: need check null in nullable column first！！！

File: be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h [hunk 2]
```diff
@@ -152,32 +151,57 @@ class AggregateFunctionPercentileApproxMerge : public AggregateFunctionPercentil
...
 public:
     AggregateFunctionPercentileApproxThreeParams(const DataTypes& argument_types_)
             : AggregateFunctionPercentileApprox(argument_types_) {}
     void add(AggregateDataPtr __restrict place, const IColumn** columns, size_t row_num,
              Arena*) const override {
-        const auto& sources = static_cast<const ColumnVector<Float64>&>(*columns[0]);
-        const auto& quantile = static_cast<const ColumnVector<Float64>&>(*columns[1]);
-        const auto& compression = static_cast<const ColumnVector<Float64>&>(*columns[2]);
+        if constexpr (is_nullable) {
+            const auto* nullable_column = check_and_get_column<ColumnNullable>(columns[0]);
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h:188]: same to the up

File: be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h [hunk 3]
```diff
@@ -152,32 +166,86 @@ class AggregateFunctionPercentileApproxMerge : public AggregateFunctionPercentil
...
-        const auto& compression = static_cast<const ColumnVector<Float64>&>(*columns[2]);
+        if constexpr (is_nullable) {
+            double column_data[3] = {0};
+
+            for (int i = 0; i < 3; ++i) {
+                const auto* nullable_column = check_and_get_column<ColumnNullable>(columns[i]);
+                if (nullable_column == nullptr) { //Not Nullable column
+                    const auto& column = static_cast<const ColumnVector<Float64>&>(*columns[i]);
+                    column_data[i] = column.get_float64(row_num);
+
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h]: delete the useless space

File: be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h [hunk 4]
```diff
@@ -152,32 +166,86 @@ class AggregateFunctionPercentileApproxMerge : public AggregateFunctionPercentil
...
 public:
     AggregateFunctionPercentileApproxThreeParams(const DataTypes& argument_types_)
             : AggregateFunctionPercentileApprox(argument_types_) {}
     void add(AggregateDataPtr __restrict place, const IColumn** columns, size_t row_num,
              Arena*) const override {
-        const auto& sources = static_cast<const ColumnVector<Float64>&>(*columns[0]);
-        const auto& quantile = static_cast<const ColumnVector<Float64>&>(*columns[1]);
-        const auto& compression = static_cast<const ColumnVector<Float64>&>(*columns[2]);
+        if constexpr (is_nullable) {
+            double column_data[3] = {0};
```
Comment (HappenLee) [inline be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h]: {0,0,0}

**Review by HappenLee — APPROVED** [review]
LGTM
