### PR TITLE
[Bug-Fix] Fix bug that show view report "Unresolved table reference" error

### LINKED ISSUE #6183: [Bug] Show view report "Unresolved table reference" error
**Describe the bug**
Show view report "Unresolved table reference" error

**To Reproduce**

```
CREATE DATABASE test_sys_view_test_show_view_db
```

```
CREATE TABLE test_sys_view_test_show_view_db.test_sys_view_test_show_view_tb ( k1 TINYINT NOT NULL, v1 TINYINT NOT NULL, v2 TINYINT NOT NULL, v3 TINYINT NOT NULL, v4 TINYINT NOT NULL ) UNIQUE KEY(k1) DISTRIBUTED BY HASH(k1) BUCKETS 5
```

```
insert into test_sys_view_test_show_view_tb values(1, 2, 3, 4, 5)
```

```
create view test_view as select * from test_sys_view_test_show_view_tb
```

```
show view from test_sys_view_test_show_view_db.test_sys_view_test_show_view_tb
```

**Expected behavior**

Successful execute

**Actual behavior**

ERROR 5011 (HY000): errCode = 2, detailMessage = Unresolved table reference '`default_cluster:test_sys_view_test_show_view_db`.`test_sys_view_test_show_view_tb`'

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

1. Fix bug that show view report "Unresolved table reference" error.
2. Fix some typos in `Show Stream Load` document.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6183 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java [hunk 1]
```diff
@@ -324,17 +324,22 @@ public void getTables(Analyzer analyzer, Map<Long, Table> tableMap, Set<String>
...
+        getWithClauseTableRefs(analyzer, tblRefs, parentViewNameSet);
         for (TableRef tblRef : fromClause_) {
-            if (tblRef instanceof InlineViewRef) {
-                QueryStmt inlineStmt = ((InlineViewRef) tblRef).getViewStmt();
-                inlineStmt.getTableRefs(tblRefs, parentViewNameSet);
-            } else {
-                if (isViewTableRef(tblRef.getName().toString(), parentViewNameSet)) {
-                    continue;
+            try {
+                tblRef = analyzer.resolveTableRef(tblRef);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:331]: Better using a local variable to save the return value like:
```
TableRef tmpTblRef = analyzer.resolveTableRef(tblRef);
```

File: fe/fe-core/src/main/java/org/apache/doris/analysis/ShowViewStmt.java [hunk 2]
```diff
@@ -114,20 +114,20 @@ public void analyze(Analyzer analyzer) throws AnalysisException, UserException {
             View view = (View) table;
             List<TableRef> tblRefs = Lists.newArrayList();
             // get table refs instead of get tables because it don't need to check table's validity
-            getTableRefs(view, tblRefs);
+            getTableRefs(analyzer, view, tblRefs);
             for (TableRef tblRef : tblRefs) {
-                tblRef.analyze(analyzer);
+                tblRef.getName().analyze(analyzer);
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/ShowViewStmt.java:119]: Why not just call `tblRef.analyze(analyzer);`?

Comment (xy720) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/ShowViewStmt.java:119]: Because we only need TableName to compare. Besides, there are many unnecessary processes in analyze() in TableRef.

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java (hunk 1 above)
Comment (xy720) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java]: Ok

**Review by morningman — APPROVED** [review]
LGTM
