### PR TITLE
(#5261) System metric init failed cause be start failed

### LINKED ISSUE #5261: [BUG] System metric init failed cause be start failed
**Describe the bug**
```
start time: Fri Jan 15 12:47:53 CST 2021
*** Aborted at 1610686073 (unix time) try "date -d @1610686073" if you are using GNU date ***
PC: @          0x115eaaa doris::SystemMetrics::get_disks_io_time()
*** SIGSEGV (@0x28) received by PID 40968 (TID 0x7f31473fb700) from PID 40; stack trace: ***
    @     0x7f314b3bf6d0 (unknown)
    @          0x115eaaa doris::SystemMetrics::get_disks_io_time()
    @           0xd377e1 doris::Daemon::calculate_metrics_thread()
    @          0x11a9068 doris::Thread::supervise_thread()
    @     0x7f314b3b7e25 start_thread
    @     0x7f314a7bdbad __clone
```

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
System metric init failed cause be start failed

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have created an issue on (Fix #5261) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- x[] I have added tests that prove my fix is effective or that my feature works
- [] If these changes need document changes, I have updated the document
- [] Any dependent changes have been merged

### CODE REVIEW

File: be/src/common/daemon.cpp [hunk 1]
```diff
@@ -289,6 +289,11 @@ void Daemon::start() {
     CHECK(st.ok()) << st.to_string();
 
     if (config::enable_metric_calculator) {
+        CHECK(DorisMetrics::instance()->is_inited())
```
Comment (acelyc111) [inline be/src/common/daemon.cpp:292]: Can we just skip calculate **system metrics** in calculate_metrics_thread when `enable_system_metrics ` is false?

Comment (wangbo) [reply be/src/common/daemon.cpp:292]: If some check failed could also cause system metrics init failed,such as disk or inet interface.
So using a init field seems better.

**Review by morningman — APPROVED** [review]
LGTM
