### PR TITLE
[BUG] Fix query failure caused by using case-insensitive system view names in information_schema.

### LINKED ISSUE #6369: [Bug] query information_schema.ROUTINES table failed
**Describe the bug**
```
SELECT ROUTINE_SCHEMA, ROUTINE_NAME FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = 'ech_dw' ORDER BY ROUTINES.ROUTINE_SCHEMA
```

error:
```
ERROR 1054 (42S22): errCode = 2, detailMessage = Unknown column 'ROUTINE_SCHEMA' in 'ROUTINES'
```

**version**
trunk

### PR DESCRIPTION
**Pull request by luozenglin**
## Proposed changes

fix #6369

The system view names in information_schema are case-insensitive, but you should not refer to one of these using different cases within the same statement.  

The following sql is correct：
```
select * from information_schema.TAbles where TAbles.ENGINE = 'Doris';
```

The following sql is wrong because `TAbles` and `tables` are used:
```
select * from information_schema.TAbles order by tables.CREATE_TIME;
```

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6369) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java [hunk 1]
```diff
@@ -553,7 +552,7 @@ public TableRef resolveTableRef(TableRef tableRef) throws AnalysisException {
             ErrorReport.reportAnalysisException(ErrorCode.ERR_BAD_TABLE_STATE, "RESTORING");
         }
 
-        TableName tblName = new TableName(database.getFullName(), table.getName());
+        TableName tblName = new TableName(dbName, tableName.getTbl());
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java:555]: Add comment to explain why using `tableName.getTbl()` instead of `table.getName()` here.

File: fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java [hunk 2]
```diff
@@ -618,10 +617,6 @@ public SlotDescriptor registerColumnRef(TableName tblName, String colName) throw
         if (newTblName == null) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java:617]: The local variable `newTblName` seems unused now.

**Review by morningman — COMMENTED** [review]
Please add ut for these cases.

**Review by luozenglin — COMMENTED** [review]
> Please add ut for these cases.

done.

**Review by morningman — APPROVED** [review]
LGTM
