### PR TITLE
[Enhancement] Improve the performance of query with IN predicate 

### LINKED ISSUE #3693: [Enhancement] Improve the performance of query with IN predicate
**Describe the bug**
In the test, we found that a simple single-table aggregate query, even in the case of hit rollup, still can not achieve a high QPS.

Table: `id INT, name varchar(32), v1 INT SUM`

Query: `SELECT SUM(v1) FROM tbl WHERE id IN (1,2,3,4,5,6, ... (more than 100))`;

The phenomenon is that the CPU util is 100%, and the delay of a single query is significantly increased.

**Why**
I found that Doris use BE config `doris_max_scan_key_num` to limit both the number of scan keys and the number of conditions of a single column that can be pushed down to the storage engine.

In above example, when the elements of IN predicate is larger than `doris_max_scan_key_num`,
no conditions will be pushed to storage engine for column `id`, So that none of index of column `id` will be used. This causes the storage engine to read all the rows and need to filter at the query layer, thus making CPU util high.

**How to solve**
The BE config `doris_max_scan_key_num` should only be used to limit the number of scan keys. And we need another config to limit the number of conditions of a single column that can be pushed down to the storage engine.

**Solution**
I add a new BE config `max_pushdown_conditions_per_column`, default is 1024.

The test case is as follows:

1. Env: 3 BE and 1 FE, Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz, 56 core
2. Table:
```
+-----------------------------+--------------+------+-------+------------+-------+
| Field                       | Type         | Null | Key   | Default    | Extra |
+-----------------------------+--------------+------+-------+------------+-------+
| date_partition              | DATE         | No   | true  | 1900-01-01 |       |
| user_name                   | VARCHAR(256) | No   | true  |            |       |
| id                          | INT          | No   | true  | N/A        |       |
...
...                    
| commit                      | INT          | No   | false | 0          | SUM   |
+-----------------------------+--------------+------+-------+------------+-------+
25 rows in set (0.01 sec)

about 3674904 rows
```
3. SQL:
```
SELECT SUM(`commit`)  FROM tbl WHERE date_partition >= '2019-11-11' AND date_partition <= '2020-05-11' AND id IN (16730, 74818, 2575, 63428, 15571, 74345, 55241, 52375, 18464, 36687, 22306, 49033, 37124, 14697, 75679, 72319, 50219, 74723, 50778, 37782, 22152, 3573, 1567, 65673, 4366, 52784, 46973, 32716, 37056, 75585, 18418, 66659, 72058, 5423, 78679, 10656, 65591, 64949, 26560, 2709, 60128, 64406, 52200, 41163, 60266, 21974, 79801, 32669, 25025, 6374, 56828, 80599, 13163, 30660, 64337, 2134, 75150, 2985, 66069, 19964, 6054, 24464, 36888, 22353, 37502, 42207, 6411, 53184, 45586, 6169, 39933, 40313, 69984, 52314, 34314, 29295, 43091, 51925, 39434, 839, 27399, 25053, 12930, 39808, 68532, 77795, 33113, 34423, 28728, 38296, 53803, 55817, 63150, 3177, 53253, 27514, 24087, 1097, 21326, 33732, 63689, 52950, 1160, 68816, 76697, 55888, 26789, 42823, 63517, 67566, 38109, 41345, 39837, 78576, 32666, 37680, 78646, 55641, 5221, 80058, 65142, 40914, 72088, 55113, 1184, 45254, 54959, 37503, 1881, 66861, 29902, 2017, 34485, 74905, 29711, 3691, 2508, 66662, 23710, 58297, 42831, 80003, 38781, 13246, 21610, 4402, 52361, 47242, 73721, 17362, 51488, 239, 61924, 38887, 29551, 11765, 15387);
```
4. Test tool: Apache jmeter, 50 threads.

5. Result:

Origin Doris version:

251.5/s Avg:   198ms Min:    68ms Max:   805ms, CPU util: 92%

New Doris version:

604.5/s Avg:    82ms Min:    30ms Max:   369ms, CPU util: 65%

New Doris version with bitmap index on column `id`:

734.9/s Avg:    67ms Min:    18ms Max:   331ms, CPU util: 50%

image

The improve is significant.

I aslo add 2 new session variable `max_scan_key_num` and `doris_max_scan_key_num` which can overwrite the 2 configs in BE config. Because there is no CBO in Doris now, we need provide a method to let user change these 2 config to meet different query scenarios.

### PR DESCRIPTION
**Pull request by morningman**
Fix: #3693

This CL mainly changes:
1. Add a new BE config `max_pushdown_conditions_per_column` to limit the number of conditions of a single column that can be pushed down to storage engine.

2. Add 2 new session variables `max_scan_key_num` and `doris_max_scan_key_num` which can set in session level and overwrite the config value in BE.

### CODE REVIEW

File: be/src/exec/olap_scan_node.cpp [hunk 1]
```diff
@@ -884,25 +910,54 @@ Status OlapScanNode::normalize_in_predicate(SlotDescriptor* slot, ColumnValueRan
...
+            } // end for each binary predicate child
+        } // end of handling eq binary predicate
+
+        if (range->get_fixed_value_size() > 0) {
+            // this columns already meet some eq predicates(IN or Binary),
+            // There is no need to continue to iterate.
+            // TODO(cmy): In fact, this part of the judgment should be completed in
+            // the FE query planning stage. For the following predicate conditions,
+            // it should be possible to eliminate at the FE side.
+            //      WHERE A = 1 and A in (2,3,4)
```
Comment (kangkaisen) [inline be/src/exec/olap_scan_node.cpp:940]: I think we should do this work directly in FE, Not add a todo here. In FE we could directly get a empty set for this query.

File: be/src/exec/olap_scan_node.cpp [hunk 2]
```diff
@@ -715,7 +714,7 @@ Status OlapScanNode::start_scan_thread(RuntimeState* state) {
 template<class T>
 Status OlapScanNode::normalize_predicate(ColumnValueRange<T>& range, SlotDescriptor* slot) {
     // 1. Normalize InPredicate, add to ColumnValueRange
-    RETURN_IF_ERROR(normalize_in_predicate(slot, &range));
+    RETURN_IF_ERROR(normalize_in_and_eq_predicate(slot, &range));
 
     // 2. Normalize BinaryPredicate , add to ColumnValueRange
     RETURN_IF_ERROR(normalize_binary_predicate(slot, &range));
```
Comment (kangkaisen) [inline be/src/exec/olap_scan_node.cpp:720]: eq binary is also binary. So I think we would better also change the `normalize_binary_predicate` name.

**Review by yangzhg — COMMENTED** [review]
LGTM

File: be/src/exec/olap_scan_node.cpp (hunk 1 above)
Comment (morningman) [reply be/src/exec/olap_scan_node.cpp:940]: I will try to solve this in next PR.

File: be/src/exec/olap_scan_node.cpp (hunk 2 above)
Comment (morningman) [reply be/src/exec/olap_scan_node.cpp:720]: OK

File: be/src/exec/olap_scan_node.cpp [hunk 3]
```diff
@@ -736,100 +735,114 @@ static bool ignore_cast(SlotDescriptor* slot, Expr* expr) {
...
             if (Expr::type_without_cast(pred->get_child(0)) != TExprNodeType::SLOT_REF) {
+                // not a slot ref(column)
+                continue;
+            }
+
+            std::vector<SlotId> slot_ids;
+            if (pred->get_child(0)->get_slot_ids(&slot_ids) != 1) {
+                // not a single column predicate
+                continue;
+            }
```
Comment (wutiangan) [inline be/src/exec/olap_scan_node.cpp:763]: 754 line can guarantee it's a single coulumn predicate?

File: be/src/exec/olap_scan_node.cpp [hunk 4]
```diff
@@ -838,39 +851,52 @@ Status OlapScanNode::normalize_in_predicate(SlotDescriptor* slot, ColumnValueRan
...
+                }
 
-                    switch (slot->type().type) {
+                // begin to push condition value into ColumnValueRange
+                // clear the ColumnValueRange before adding new fixed values.
+                // because for AND compound predicates, it can overwrite previous conditions
+                switch (slot->type().type) {
                     case TYPE_TINYINT: {
                         int32_t v = *reinterpret_cast<int8_t*>(value);
+                        range->clear();
```
Comment (wutiangan) [inline be/src/exec/olap_scan_node.cpp:891]: Whether ”range->clear()“ can be preceded by the switch statement

File: be/src/exec/olap_scan_node.cpp (hunk 1 above)
Comment (kangkaisen) [reply be/src/exec/olap_scan_node.cpp:940]: OK

**Comment by WingsGo** [comment]
Hi, @morningman I have some question about olap_scan_node, could you plz help me figure it out?
1. what's the relationship between scanner and tablet, one tablet can be scanned by many scanner?they are n:1 or 1:1?
2. what's the relationship between TPaloScanRange and ColumnValueRange, is ColumnValueRange to deal with predicate case and TPaloScanRange can indicate that the range a scanner need to scan from StorageEngine's prefix index?
3. What's the usage of function `extend_scan_key` and the config variable `doris_scanner_row_num`?
I would appreciate your reply, thanks~

**Comment by morningman** [comment]
> Hi, @morningman I have some question about olap_scan_node, could you plz help me figure it out?
> 
> 1. what's the relationship between scanner and tablet, one tablet can be scanned by many scanner?they are n:1 or 1:1?
> 2. what's the relationship between TPaloScanRange and ColumnValueRange, is ColumnValueRange to deal with predicate case and TPaloScanRange can indicate that the range a scanner need to scan from StorageEngine's prefix index?
> 3. What's the usage of function `extend_scan_key` and the config variable `doris_scanner_row_num`?
>    I would appreciate your reply, thanks~

1. scanner and tablet is `n:m` relation
2. I am not familiar with `TPaloScanRange`, need a further look...
3. `extend_scan_key` is used to extend the scan keys.  `scan keys` are used to determine the number of scanners.

 For example, `WHERE a in (1,2,3) and b > 5` and `a`, `b` are key columns of the table.

First, for `a in (1,2,3)`, the `scan keys` become: `(a=1),(a=2),(a=3)`
Second, for `b > 5`, the `scan keys` extends to `(a=1, b>5), (a=2, b>5), (a=3, b>5)`

4. `doris_scanner_row_num` is used for priority scheduling of scanner. Doris has a scanner thread pool that is shared by all scanners. Therefore, a scheduling strategy is needed to prevent a scanner from occupying threads for a long time. `doris_scanner_row_num` can control the maximum number of rows a scanner can read in one scheduling. The details of the algorithm that are not specific need to be understood by reading the code.

@chaoyli may understand this better. If I said something wrong, he can help correct it.

File: be/src/exec/olap_scan_node.cpp (hunk 4 above)
Comment (morningman) [reply be/src/exec/olap_scan_node.cpp:891]: OK

File: be/src/exec/olap_scan_node.cpp (hunk 3 above)
Comment (morningman) [reply be/src/exec/olap_scan_node.cpp:763]: I am not sure about that, looks like line `754` can guarantee.
But just leave this judgement, because no matter what, we still have to call `get_slot_ids()` to get the slot id and check if it equals to the `slot->id()` later.

**Comment by WingsGo** [comment]
> > Hi, @morningman I have some question about olap_scan_node, could you plz help me figure it out?
> > 
> > 1. what's the relationship between scanner and tablet, one tablet can be scanned by many scanner?they are n:1 or 1:1?
> > 2. what's the relationship between TPaloScanRange and ColumnValueRange, is ColumnValueRange to deal with predicate case and TPaloScanRange can indicate that the range a scanner need to scan from StorageEngine's prefix index?
> > 3. What's the usage of function `extend_scan_key` and the config variable `doris_scanner_row_num`?
> >    I would appreciate your reply, thanks~
> 
> 1. scanner and tablet is `n:m` relation
> 2. I am not familiar with `TPaloScanRange`, need a further look...
> 3. `extend_scan_key` is used to extend the scan keys.  `scan keys` are used to determine the number of scanners.
> 
> For example, `WHERE a in (1,2,3) and b > 5` and `a`, `b` are key columns of the table.
> 
> First, for `a in (1,2,3)`, the `scan keys` become: `(a=1),(a=2),(a=3)`
> Second, for `b > 5`, the `scan keys` extends to `(a=1, b>5), (a=2, b>5), (a=3, b>5)`
> 
> 1. `doris_scanner_row_num` is used for priority scheduling of scanner. Doris has a scanner thread pool that is shared by all scanners. Therefore, a scheduling strategy is needed to prevent a scanner from occupying threads for a long time. `doris_scanner_row_num` can control the maximum number of rows a scanner can read in one scheduling. The details of the algorithm that are not specific need to be understood by reading the code.
> 
> @chaoyli may understand this better. If I said something wrong, he can help correct it.

Thanks for your reply, so if the `scan keys` extends to `(a=1, b>5), (a=2, b>5), (a=3, b>5)` , doris will split into 3 scanners to scan RowBatch which satisified the predicate? Do I understand correctly?

**Comment by morningman** [comment]
> Thanks for your reply, so if the `scan keys` extends to `(a=1, b>5), (a=2, b>5), (a=3, b>5)` , doris will split into 3 scanners to scan RowBatch which satisified the predicate? Do I understand correctly?

Not exactly, `extend_scan_key()` only extend all possible scan keys. the number of scanners is got from `get_hints()`

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Review by EmmyMiao87 — APPROVED** [review]
