### PR TITLE
[regression] add regression test for compaction

### LINKED ISSUE #9435: [Enhancement] Regression test for compaction
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Add regression test case for compaction

### Solution

Add regression test case for compaction

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gabriel39**
# Proposed changes

Issue Number: close #9435 

## Problem Summary:

Trigger compaction via REST API in this case.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
3. Has unit tests been added: (Yes/No/No Need)
4. Has document been added or modified: (Yes/No/No Need)
5. Does it need to update dependencies: (Yes/No)
6. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: regression-test/suites/compaction/test_compaction.groovy [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+                String command = sb.toString()
+                process = command.execute()
+                code = process.waitFor()
+                err = IOGroovyMethods.getText(new BufferedReader(new InputStreamReader(process.getErrorStream())));
+                out = process.getText()
+                logger.info("Get compaction status: code=" + code + ", out=" + out + ", err=" + err)
+                assertEquals(code, 0)
+                def compactionStatus = parseJson(out.trim())
+                assertEquals("success", compactionStatus.status.toLowerCase())
+                running = compactionStatus.run_status
```
Comment (morningman) [inline regression-test/suites/compaction/test_compaction.groovy:156]: Do we need to check the number of rowset of each table to see if it does the compaction?
`http://127.0.0.1:8044/api/compaction/show?tablet_id=11007`

Comment (Gabriel39) [reply regression-test/suites/compaction/test_compaction.groovy:156]: Add an assertion to ensure the total row count after compaction is less than origin inserted records count.

**Review by yiguolei — APPROVED** [review]
LGTM
