### PR TITLE
[fix](lateral-view) fix bugs of lateral view with CTE or where clause

### LINKED ISSUE #7823: [Bug] lateral view + subquery leads to the error predicate
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

#6746 

### What's Wrong?

The lateral view + subquery leads to the error join predicate ```equal join conjunct: `k3` = `k3` ```

### What You Expected?

Only one join predicate ```equal join conjunct: `k1` = `k3` ```

### How to Reproduce?

Steps:
1. create table 

```
CREATE TABLE `test_explode` (
  `k1` int(11) NULL COMMENT "",
  `k2` varchar(1) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
) 
```

2. query 
 ```
MySQL [test]> explain select k1 from test_explode lateral view explode_split(k2, ",") tmp as e1  where k1 in (select k3 from tbl1);
+--------------------------------------------------------------------------------------+
| Explain String                                                                       |
+--------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                      |
|  OUTPUT EXPRS:`k1`                                                                   |
|   PARTITION: UNPARTITIONED                                                           |
|                                                                                      |
|   RESULT SINK                                                                        |
|                                                                                      |
|   6:EXCHANGE                                                                         |
|                                                                                      |
| PLAN FRAGMENT 1                                                                      |
|  OUTPUT EXPRS:                                                                       |
|   PARTITION: HASH_PARTITIONED: `k3`, `k1`                                            |
|                                                                                      |
|   STREAM DATA SINK                                                                   |
|     EXCHANGE ID: 06                                                                  |
|     UNPARTITIONED                                                                    |
|                                                                                      |
|   3:HASH JOIN                                                                        |
|   |  join op: LEFT SEMI JOIN (PARTITIONED)                                           |
|   |  hash predicates:                                                                |
|   |  colocate: false, reason: The src data has been redistributed                    |
|   |  equal join conjunct: `k3` = `k3`                                                |
|   |  equal join conjunct: `k1` = `k3`                                                |
|   |  runtime filters: RF000[in] <- `k3`                                              |
|   |  cardinality=-1                                                                  |
|   |                                                                                  |
|   |----5:EXCHANGE                                                                    |
|   |                                                                                  |
|   4:EXCHANGE                                                                         |
|                                                                                      |
| PLAN FRAGMENT 2                                                                      |
|  OUTPUT EXPRS:                                                                       |
|   PARTITION: HASH_PARTITIONED: `default_cluster:test`.`tbl1`.`k1`                    |
|                                                                                      |
|   STREAM DATA SINK                                                                   |
|     EXCHANGE ID: 05                                                                  |
|     HASH_PARTITIONED: `k3`, `k3`                                                     |
|                                                                                      |
|   2:OlapScanNode                                                                     |
|      TABLE: tbl1                                                                     |
|      PREAGGREGATION: OFF. Reason: No AggregateInfo                                   |
|      partitions=1/1                                                                  |
|      rollup: tbl1                                                                    |
|      tabletRatio=3/3                                                                 |
|      tabletList=14007,14009,14011                                                    |
|      cardinality=1                                                                   |
|      avgRowSize=983.0                                                                |
|      numNodes=2                                                                      |
|                                                                                      |
| PLAN FRAGMENT 3                                                                      |
|  OUTPUT EXPRS:                                                                       |
|   PARTITION: HASH_PARTITIONED: `default_cluster:test`.`test_explode`.`k1`            |
|                                                                                      |
|   STREAM DATA SINK                                                                   |
|     EXCHANGE ID: 04                                                                  |
|     HASH_PARTITIONED: `k3`, `k1`                                                     |
|                                                                                      |
|   1:TABLE FUNCTION NODE                                                              |
|   |  table function: explode_split(`default_cluster:test`.`test_explode`.`k2`, ',')  |
|   |  lateral view tuple id: 1                                                        |
|   |  output slot id: 2                                                               |
|   |  cardinality=-1                                                                  |
|   |                                                                                  |
|   0:OlapScanNode                                                                     |
|      TABLE: test_explode                                                             |
|      PREAGGREGATION: ON                                                              |
|      runtime filters: RF000[in] -> `k1`                                              |
|      partitions=1/1                                                                  |
|      rollup: test_explode                                                            |
|      tabletRatio=5/5                                                                 |
|      tabletList=17010,17012,17014,17016,17018                                        |
|      cardinality=1                                                                   |
|      avgRowSize=842.0                                                                |
|      numNodes=2                                                                      |
+--------------------------------------------------------------------------------------+
73 rows in set (2 min 19.321 sec)
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

fix bugs of lateral view with CTE or where clause.
The error case can be found in newly added tests in `TableFunctionPlanTest.java`
But there are still some bugs not being fixed, so the unit test is annotated with @Ignore

This PR contains the change is #7824 :

> Issue Number: close #7823
> 
> After the subquery is rewritten, the rewritten stmt needs to be reset
> (that is, the content of the first analyze semantic analysis is cleared),
> and then the rewritten stmt can be reAnalyzed.
> 
> The lateral view ref in the previous implementation forgot to implement the reset function.
> This caused him to keep the first error message in the second analyze.
> Eventually, two duplicate tupleIds appear in the new stmt and are marked with different tuple.
> From the explain string, the following syntax will have an additional wrong join predicate.
> ```
> Query: explain select k1 from test_explode lateral view explode_split(k2, ",") tmp as e1  where k1 in (select k3 from tbl1);
> Error equal join conjunct: `k3` = `k3`
> ```
> 
> This pr mainly adds the reset function of the lateral view
> to avoid possible errors in the second analyze
> when the lateral view and subquery rewrite occur at the same time.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java [hunk 1]
```diff
@@ -611,7 +622,16 @@ public String tableRefToSql() {
         // if (resolvedPath_ != null) path = resolvedPath_.getFullyQualifiedRawPath();
         // return ToSqlUtils.getPathSql(path) + ((aliasSql != null) ? " " + aliasSql : "");
 
-        return name.toSql() + ((aliasSql != null) ? " " + aliasSql : "");
+        // tbl1
+        // tbl1 alias_tbl1
+        // tbl1 alias_tbl1 lateral view explode_split(k1, ",") tmp1 as e1
+        String tblName = name.toSql() + ((aliasSql != null) ? " " + aliasSql : "");
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java:628]: Which printing will be mainly affected after the change here?

File: fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java [hunk 2]
```diff
@@ -470,4 +478,55 @@ public void aggColumnInOuterQuery() throws Exception {
...
+    @Test
+    public void testLaterViewWithCTE() throws Exception {
+        String sql = "with tmp as (select k1,e1 from db1.table_for_view lateral view explode_split(k3,',') tmp2 as e1) select * from tmp;";
+        String explainString = UtFrameUtils.getSQLPlanOrErrorMsg(ctx, sql, true);
+        Assert.assertTrue(explainString.contains("table function: explode_split(`default_cluster:db1`.`table_for_view`.`k3`, ',') "));
+    }
+
+    @Ignore
+    // errCode = 2, detailMessage = Unknown column 'e1' in 'table list'
+    public void testLaterViewWithCTEBug() throws Exception {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java:515]: Why ignore this single test

File: fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java [hunk 3]
```diff
@@ -470,4 +478,55 @@ public void aggColumnInOuterQuery() throws Exception {
...
+        String sql = "with tmp as (select * from db1.table_for_view where k2=1) select k1,e1 from tmp lateral view explode_split(k3,',') tmp2 as e1;";
+        String explainString = UtFrameUtils.getSQLPlanOrErrorMsg(ctx, sql, true);
+        Assert.assertTrue(!explainString.contains("Unknown column 'e1' in 'table list'"));
+    }
+
+    @Ignore
+    // errCode = 2, detailMessage = Unknown column 'e1' in 'table list'
+    public void testLaterViewUnknowColumnBug() throws Exception {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java:523]: Why ignore this single test

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

File: fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java (hunk 3 above)
Comment (morningman) [reply fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java:523]: I leaves to you to fix it. LOL
