### PR TITLE
[bugfix](be): fix segment fault if the PID_DIR was NOT set

### LINKED ISSUE #18788: [Bug] Doris BE would crash if the PID_DIR wasn't set
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

https://github.com/apache/doris/commit/4a16eff16ddd8a438968c07cdcb2ab8f306f14ee

### What's Wrong?

As the title described, the doris_be would crash if the environment wasn't set.

### What You Expected?

Can print the error message and exit the program

### How to Reproduce?

- Start the `doris_be` without setting `PID_DIR`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by git-hulk**
# Proposed changes

Issue Number: close #18788 

## Problem summary

Doris BE would crash if the PID_DIR wasn't set

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

File: be/src/service/doris_main.cpp [hunk 1]
```diff
@@ -282,6 +282,10 @@ int main(int argc, char** argv) {
         fprintf(stderr, "you need set DORIS_HOME environment variable.\n");
         exit(-1);
     }
+    if (getenv("PID_DIR") == nullptr) {
```
Comment (carlvinhust2012) [inline be/src/service/doris_main.cpp:285]: why not set a default PID_DIR?

Comment (git-hulk) [reply be/src/service/doris_main.cpp:285]: Sure, is it good to set it as the current dir like the `start_be` script?

Comment (git-hulk) [reply be/src/service/doris_main.cpp:285]: I'm not sure if it's good to set the default value here since the start_be also set a default value.

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 37.33 seconds
 stream load tsv:          436 seconds loaded 74807831229 Bytes, about 163 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          61 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230419063620_clickbench_pr_130915.html

**Comment by adonis0147** [comment]
run p0

**Review by adonis0147 — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
run p0
