### PR TITLE
[fix](vec) VMergeIterator add key same label for agg table

### LINKED ISSUE #14726: [Bug] get many rows with same key from aggregate table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

right now, when query from aggregate table, VCollectIterator build a heap to sort all rows from rowsets, and set same if key column value is equal between rows. when there are many segments in one rowset, VMergeIterator build a heap to sort all rows from segment, but not set same if key column equal between rows. if you get many rows with same key from several segments of one rowset, VCollectIterator can not set same for all rows, _agg_key_next_block will get several rows with same key and not merge for agg.

for example:
table `dwd_fact_psd_order_details81` is a aggregate table, with key(`document_line_no`, `goods_no`, `company_code`, `document_no`, `dt`)

MySQL [test]> select `document_line_no`, `goods_no`, `company_code`, `document_no`, `dt`  from dwd_fact_psd_order_details81 where document_line_no='000010' and goods_no='xxxxxxxxxxxxx' and company_code = '2111' and document_no='0010000001' and dt='9999-12-30';
+------------------+-------------+--------------+-------------+------------+
| document_line_no | goods_no    | company_code | document_no | dt         |
+------------------+-------------+--------------+-------------+------------+
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
| 000010           | xxxxxxxxxxxxx | 2111         | 0010000001  | 9999-12-30 |
+------------------+-------------+--------------+-------------+------------+
8 rows in set (0.02 sec)

### What You Expected?

expect only one row 

### How to Reproduce?

大概通过如下步骤复现：
0、关闭自动compaction
1、写入一个tablet大批量的数据，这样rowset下有多个segment（这个地方需要大量数据，我测试环境把segment的大小设置为了几M）
2、一个rowset下的多个segment里有多条相同key的数据

读数据的时候触发这个逻辑：
以某个key进行查询，假定只从一个rowset中读取数据，按现在的代码，一个tablet内的数据理论是通过建立一个heap，对所有rowset下的数据，基于IteratorRowRef排序和相同key的标记（is_same = true).这个目前只用于排序从多个rowset读取的行。
假如key对应数据只从一个rowset读取，会触发不基于heap排序的逻辑，Level1Iterator只有一个child，不会走heap，直接从底层拿，这个时候没有标记相同key的逻辑。

而rowset内部,是从底层多个segment读取数据，走的是VMergeIterator，也会建立一个heap，这个地方也会基于key排序（但是没有相同key标记)。

基于以上过程获取到数据后，然后在_agg_key_next_block里，每一行数据都判断if (!_next_row.is_same)，如果相同则走聚合逻辑，但是在上边的读取逻辑下，is_same=false，这个地方认为两行key不同，并不会对相同key的行进行聚合，然后就返回了多行想通key的数据。

非向量化是在_agg_key_next_row这个地方现场对两row进行key比较，而不是在heap里通过is_same来标记，所以非向量化没问题。

另外上边只是一个出错的读取逻辑，当数据从多个rowset下读取时，也会存在问题。就算建立了heap去排序多个rowset下的key，并进行标记（is_same = true)，如果某个rowset下仍有多个相同key的行，仍然不能对所有row标记（is_same = true)，只会在_agg_key_next_block中对部分行进行聚合，仍返回多行的错误结果

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
right now, when query from aggregate table, VCollectIterator build a heap to sort all rows from rowsets, and set same if key column value is equal between rows. when there are many segments in one rowset,  VMergeIterator build a heap to sort all rows from segment, but not set same if key column equal between rows. if you get many rows with same key from several segments of one rowset, VCollectIterator can not set same for all rows, _agg_key_next_block will get several rows with same key and not merge for agg.

Signed-off-by: nextdreamblue <zxw520blue1@163.com>

# Proposed changes

Issue Number: close #14726

## Problem summary

right now, when query from aggregate table, VCollectIterator build a heap to sort all rows from rowsets, and set same if key column value is equal between rows. when there are many segments in one rowset,  VMergeIterator build a heap to sort all rows from segment, but not set same if key column equal between rows. if you get many rows with same key from several segments of one rowset, VCollectIterator can not set same for all rows, _agg_key_next_block will get several rows with same key and not merge for agg.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.87 seconds
 load time: 436 seconds
 storage size: 17123343172 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221201074534_clickbench_pr_56072.html

File: be/src/vec/olap/vgeneric_iterators.cpp [hunk 1]
```diff
@@ -123,6 +123,7 @@ bool VMergeIteratorContext::compare(const VMergeIteratorContext& rhs) const {
     if (_is_unique) {
```
Comment (liaoxin01) [inline be/src/vec/olap/vgeneric_iterators.cpp:123]: Can we use `_is_unique` to skip the same key in the agg model?

File: be/src/vec/core/block.h [hunk 2]
```diff
@@ -63,6 +63,7 @@ class Block {
 
     Container data;
     IndexByName index_by_name;
+    std::vector<uint64_t> row_same_bit;
```
Comment (zhannngchen) [inline be/src/vec/core/block.h:66]: Using a vector of uint64_t is kind of waste of space, can we use a roaringbitmap instead?

**Comment by zhannngchen** [comment]
Can't we just compare 2 rows to check if they are same? Just like what the rowwise interface did.

**Comment by nextdreamblue** [comment]
> Can't we just compare 2 rows in `_agg_key_next_block` to check if they are same? Just like what the rowwise implementation did.

like in 
`_agg_key_next_row` ,
```
 if (!equal_row(_key_cids, *row_cursor, *_next_key)) {
    break;
}
```
总感觉这样整个查询效率会低好多，多一次重复比较。我试试用roaringbitmap代替vector吧

File: be/src/vec/core/block.h (hunk 2 above)
Comment (nextdreamblue) [reply be/src/vec/core/block.h:66]: 我试试改造下代码

Comment (nextdreamblue) [reply be/src/vec/core/block.h:66]: std::vector<bool>，感觉用这个特殊的类型就可以实现位图效果了，我改造下
https://en.cppreference.com/w/cpp/container/vector_bool

**Review by freemandealer — DISMISSED** [review]
LGTM

File: be/src/vec/core/block.cpp [hunk 3]
```diff
@@ -339,6 +342,10 @@ void Block::set_num_rows(size_t length) {
                 elem.column = elem.column->cut(0, length);
             }
         }
+        if (length < row_same_bit.size()) {
+            std::vector<bool> tmp_row_same_bit(row_same_bit.begin(), row_same_bit.begin() + length);
```
Comment (zhannngchen) [inline be/src/vec/core/block.cpp:346]: We can use `resize` here directly?

File: be/src/vec/core/block.cpp [hunk 4]
```diff
@@ -353,6 +360,10 @@ void Block::skip_num_rows(int64_t& length) {
                 elem.column = elem.column->cut(length, origin_rows - length);
             }
         }
+        if (length < row_same_bit.size()) {
+            std::vector<bool> tmp_row_same_bit(row_same_bit.begin() + length, row_same_bit.end());
```
Comment (zhannngchen) [inline be/src/vec/core/block.cpp:364]: ditto

File: be/src/vec/olap/vgeneric_iterators.h [hunk 5]
```diff
@@ -120,6 +120,21 @@ class VMergeIteratorContext {
 
     void set_skip(bool skip) const { _skip = skip; }
 
+    bool is_same() const { return _same; }
+
+    void set_same(bool same) const { _same = same; }
+
+    std::vector<bool> get_pre_ctx_same() const { return _pre_ctx_same_bit; }
```
Comment (zhannngchen) [inline be/src/vec/olap/vgeneric_iterators.h:127]: return a const reference to avoid copy of the whole vector.

File: be/test/olap/segcompaction_test.cpp [hunk 6]
```diff
@@ -419,6 +419,7 @@ TEST_F(SegCompactionTest, SegCompactionInterleaveWithBig_ooooOOoOooooooooO) {
             }
             s = rowset_writer->flush();
             EXPECT_EQ(Status::OK(), s);
+            sleep(1);
```
[the remark this answers is not in the document]
Comment (nextdreamblue) [reply be/test/olap/segcompaction_test.cpp:422]: > why we need sleep here?

这个当时有一定几率还没来得及触发两次segcompaction，任务就执行完了，然后就加了一个这个sleep，我再试试

File: be/src/vec/core/block.cpp (hunk 3 above)
Comment (nextdreamblue) [reply be/src/vec/core/block.cpp:346]: it's better, i fix it

File: be/src/vec/core/block.cpp (hunk 4 above)
Comment (nextdreamblue) [reply be/src/vec/core/block.cpp:364]: > ditto

i fix it

File: be/src/vec/olap/vgeneric_iterators.h (hunk 5 above)
Comment (nextdreamblue) [reply be/src/vec/olap/vgeneric_iterators.h:127]: ok, i fix it

**Review by zhannngchen — APPROVED** [review]
LGTM

File: be/test/olap/segcompaction_test.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (freemandealer) [reply be/test/olap/segcompaction_test.cpp:313]: 任务执行过快确实会有这个问题，导致目录跟预期不一样。这个我统一加一些延迟吧。谢谢！

**Comment by freemandealer** [comment]
What if we let MergeIterator calculate Agg and provide CollectIterator with aggragated result?

**Comment by nextdreamblue** [comment]
> What if we let MergeIterator calculate Agg and provide CollectIterator with aggragated result?

feel it more complicated than this pr

**Review by dataroaring — APPROVED** [review]
LGTM
