### PR TITLE
[fix](index compaction)Fix construct index compaction columns core when reader close error

### LINKED ISSUE #46507: [Bug] index compaction exception core
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-2.1

### What's Wrong?

``` 
#0  0x00007f3f8723452f in raise () from /lib64/libc.so.6
#1  0x00007f3f87207e65 in abort () from /lib64/libc.so.6
#2  0x0000563d04a4911a in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x0000563d04a47a56 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x0000563d04a47ac1 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x0000563d04a47a3b in std::rethrow_exception (ep=...) at ../../../../libstdc++-v3/libsupc++/eh_ptr.cc:217
#6  0x0000563cd2c3ace9 in std::__basic_future<doris::Status>::_M_get_result (this=0x7f2d6488f380) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/future:721
#7  0x0000563cd2c2346c in std::future<doris::Status>::get (this=0x7f2d6488f380) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/future:805
#8  0x0000563cd4bcf3c4 in doris::CompactionAction::_handle_run_compaction (this=0x603001bee570, req=0x6120005a3640, json_result=0x7f2d646870c0) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/http/action/compaction_action.cpp:180
#9  0x0000563cd4bd4a21 in doris::CompactionAction::handle (this=0x603001bee570, req=0x6120005a3640) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/http/action/compaction_action.cpp:354
#10 0x0000563cd4d4da80 in doris::on_request (ev_req=0x611003be6500, arg=0x619000623980) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/http/ev_http_server.cpp:68
#11 0x0000563d0226d057 in ?? ()
#12 0x0000563d0224d2b1 in bufferevent_run_readcb_ ()
#13 0x0000563d0226f273 in ?? ()
#14 0x0000563d022560b9 in ?? ()
#15 0x0000563d02256737 in ?? ()
#16 0x0000563d02258d68 in ?? ()
#17 0x0000563cd4d4d750 in doris::EvHttpServer::start()::$_0::operator()() const (this=0x60600102f7b8) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/http/ev_http_server.cpp:139
#18 0x0000563cd4d4cf55 in std::__invoke_impl<void, doris::EvHttpServer::start()::$_0&>(std::__invoke_other, doris::EvHttpServer::start()::$_0&) (__f=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#19 0x0000563cd4d4cf05 in std::__invoke_r<void, doris::EvHttpServer::start()::$_0&>(doris::EvHttpServer::start()::$_0&) (__fn=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#20 0x0000563cd4d4cdcd in std::_Function_handler<void (), doris::EvHttpServer::start()::$_0>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
#21 0x0000563ccf873a93 in std::function<void ()>::operator()() const (this=0x60600102f7b8) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
#22 0x0000563cd3a581b9 in doris::FunctionRunnable::run (this=0x60600102f7b0) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/util/threadpool.cpp:48
#23 0x0000563cd3a43b00 in doris::ThreadPool::dispatch_thread (this=0x61500053be00) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/util/threadpool.cpp:544
#24 0x0000563cd3a6abd4 in std::__invoke_impl<void, void (doris::ThreadPool::*&)(), doris::ThreadPool*&> (
    __f=@0x603001bf0220: (void (doris::ThreadPool::*)(doris::ThreadPool * const)) 0x563cd3a41c30 <doris::ThreadPool::dispatch_thread()>, __t=@0x603001bf0230: 0x61500053be00)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
#25 0x0000563cd3a6aaad in std::__invoke<void (doris::ThreadPool::*&)(), doris::ThreadPool*&> (__fn=@0x603001bf0220: (void (doris::ThreadPool::*)(doris::ThreadPool * const)) 0x563cd3a41c30 <doris::ThreadPool::dispatch_thread()>,
    __args=@0x603001bf0230: 0x61500053be00) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
#26 0x0000563cd3a6aa35 in std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x603001bf0220, __args=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:420
#27 0x0000563cd3a6a8de in std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::operator()<, void>() (this=0x603001bf0220)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:503
#28 0x0000563cd3a6a7f5 in std::__invoke_impl<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) (__f=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#29 0x0000563cd3a6a795 in std::__invoke_r<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) (__fn=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#30 0x0000563cd3a6a43d in std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
#31 0x0000563ccf873a93 in std::function<void ()>::operator()() const (this=0x6110039b4718) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
#32 0x0000563cd3a12dec in doris::Thread::supervise_thread (arg=0x6110039b4700) at /mnt/disk2/luen/develop/workspace/doris-2.1/be/src/util/thread.cpp:498
#33 0x00007f3f868301ca in start_thread () from /lib64/libpthread.so.0
#34 0x00007f3f8721f8d3 in clone () from /lib64/libc.so.6
```

### What You Expected?

compaction successfully.

### How to Reproduce?

When construct columns to do index compaction columns, index reader close error, BE will core.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
fix #46507

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Review by zzzxl1993 — APPROVED** [review]
LGTM

File: be/src/olap/compaction.cpp [hunk 1]
```diff
@@ -858,72 +858,86 @@ Status Compaction::construct_output_rowset_writer(RowsetWriterContext& ctx, bool
...
-                                             ->index_file_exist(index_meta, &exists)
-                                             .ok()) {
-                                    LOG(ERROR) << inverted_index_file_reader->get_index_file_path(
-                                                          index_meta)
-                                               << " fs->exists error";
-                                    return false;
-                                }
-
-                                if (!exists) {
+                                std::string index_file_path;
```
Comment (airborne12) [inline be/src/olap/compaction.cpp:861]: if clucene error throw in file_reader->init, index_file_path will be empty string in catch block.

Comment (qidaye) [reply be/src/olap/compaction.cpp:861]: Only `InvertedIndexStorageFormatPB::V1` can construct index compaction columns.
When index format is v1, the inverted_index_file_reader->init just initialize member params and return OK. 
There will not throw any exception.

**Review by airborne12 — APPROVED** [review]
LGTM
