### PR TITLE
[fix](date_function) fix str_to_date function return wrong microsecond issue

### LINKED ISSUE #47105: [Bug] str_to_date always return result with microsecond no matter you specfic %f in date format strin
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master & 2.1

### What's Wrong?

In **Doris**
mysql> select id,str_to_date(dt, '%Y-%m-%d %H:%i:%s.%f') from test1 limit 1;
+------+--------------------------------------+
| id   | str_to_date(dt, '%Y-%m-%d %H:%i:%s') |
+------+--------------------------------------+
|    2 | 2024-12-28 10:11:12.000000           |
+------+--------------------------------------+
this is correct. But below is wrong: 

mysql> select id,str_to_date(dt, '%Y-%m-%d %H:%i:%s') from test1 limit 1;
+------+--------------------------------------+
| id   | str_to_date(dt, '%Y-%m-%d %H:%i:%s') |
+------+--------------------------------------+
|    2 | 2024-12-28 10:11:12.000000           |
+------+--------------------------------------+
**it should be 2024-12-28 10:11:12**

In **mysql** str_to_date(dt, '%Y-%m-%d %H:%i:%s') does not return microsecond part
mysql> desc test1;
+-------+-------------+------+-----+---------+-------+
| Field | Type        | Null | Key | Default | Extra |
+-------+-------------+------+-----+---------+-------+
| id    | int         | YES  |     | NULL    |       |
| name  | varchar(32) | YES  |     | NULL    |       |
| dt    | varchar(32) | YES  |     | NULL    |       |
+-------+-------------+------+-----+---------+-------+
3 rows in set (0.00 sec)

mysql> select * from test1;
+------+------+---------------------+
| id   | name | dt                  |
+------+------+---------------------+
|    3 | Carl | 2024-12-29 10:11:12 |
|    2 | Bob  | 2024-12-28 10:11:12 |
+------+------+---------------------+
2 rows in set (0.00 sec)

mysql> select id,str_to_date(dt, '%Y-%m-%d %H:%i:%s') from test1;
+------+--------------------------------------+
| id   | str_to_date(dt, '%Y-%m-%d %H:%i:%s') |
+------+--------------------------------------+
|    3 | 2024-12-29 10:11:12                  |
|    2 | 2024-12-28 10:11:12                  |
+------+--------------------------------------+
2 rows in set (0.00 sec)

mysql> select id,str_to_date(dt, '%Y-%m-%d %H:%i:%s.%f') from test1;
+------+-----------------------------------------+
| id   | str_to_date(dt, '%Y-%m-%d %H:%i:%s.%f') |
+------+-----------------------------------------+
|    3 | 2024-12-29 10:11:12.000000              |
|    2 | 2024-12-28 10:11:12.000000              |
+------+-----------------------------------------+
2 rows in set (0.00 sec)

### What You Expected?

fix it, worked same as mysql

### How to Reproduce?

_No response_

### Anything Else?

CREATE TABLE `test1` (
  `id` INT,
  `name` varchar(32),
   `dt` varchar(32)
) ENGINE=OLAP
UNIQUE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

insert into test1 values (3, 'Carl','2024-12-29 10:11:12'),(2, 'Bob','2024-12-28 10:11:12');
select id,str_to_date(dt, '%Y-%m-%d %H:%i:%s') from test1;

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yulei-Yang**
### What problem does this PR solve?

Issue Number: close #47105

Related PR: #24932

Problem Summary:

### Release note

str_to_date always return microsecond part for datetime even if user does not specfic %f in date format string. This is wrong.
mysql> select id,str_to_date(dt, '%Y-%m-%d %H:%i:%s') from test1 limit 1;
+------+--------------------------------------+
| id   | str_to_date(dt, '%Y-%m-%d %H:%i:%s') |
+------+--------------------------------------+
|    2 | 2024-12-28 10:11:12.000000           |
+------+--------------------------------------+

and constant fold scenario is wrong too:
mysql> select cast(str_to_date('2025-01-17 11:59:30', '%Y-%m-%d %H:%i:%s') as string);                                 
                                                                                                                          
+--------------------------------------------------------------------------+
| cast(str_to_date('2025-01-17 11:59:30', '%Y-%m-%d %H:%i:%s') as TEXT) |
+--------------------------------------------------------------------------+
| 2025-01-17 11:59:30.000000                                               |                                              
+--------------------------------------------------------------------------+                                              

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by Yulei-Yang** [comment]
run buildall

File: regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function_v2.groovy [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+                `dt` varchar(32)
+            ) ENGINE=OLAP
+            UNIQUE KEY(`id`)
+            DISTRIBUTED BY HASH(`id`) BUCKETS 1
+            PROPERTIES (
+            "replication_allocation" = "tag.location.default: 1"
+            )
+        """
+    sql """ insert into ${tableName} values (3, 'Carl','2024-12-29 10:11:12') """
+    def result1 = try_sql """
```
Comment (LiBinfeng-01) [inline regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function_v2.groovy:39]: should also check all constant parameters for fe fold constant

Comment (LiBinfeng-01) [reply regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function_v2.groovy:39]: like: `select cast(str_to_date('2024-12-29 10:11:12', '%Y-%m-%d %H:%i:%s.%f') as string);`

Comment (Yulei-Yang) [reply regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function_v2.groovy:39]: done

**Review by LiBinfeng-01 — APPROVED** [review]

**Review by englefly — APPROVED** [review]
