### PR TITLE
[fix](catalog) fix bug that replica missing version cause query -214 error

### LINKED ISSUE #9267: [Bug] failed to initialize storage reader. tablet=924991.xxxx, res=-214, backend=xxxx
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

the -214 error code means "some version of this replica is missing".
In #8209, I modified some logic to handle -214, but one logic is wrong, that is:

1. When BE report that one tablet is missing version, the FE will set replica's last failed version to 1:

https://github.com/apache/incubator-doris/blob/26bc462e1c46dd751de15d3b477d59015a948476/fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java#L829-L837

But this is wrong, because the replica's last failed version should always larger than replica's version, otherwise,
it will be rectified when calling updateReplicaInfo():

https://github.com/apache/incubator-doris/blob/26bc462e1c46dd751de15d3b477d59015a948476/fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java#L348-L357

### What You Expected?

the tablet report logic is valid.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #9267

## Problem Summary:

This CL mainly change:

1. Fix bug described in #9267 
    When report missing version replica, set last failed version to (replica version + 1)
2. Skip non-exist partition when handling transactions.

## Checklist(Required)

1. Does it affect the original behavior: (No)
4. Has unit tests been added: (No Need)
5. Has document been added or modified: (No Need)
6. Does it need to update dependencies: (No)
7. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -857,49 +857,19 @@ public void finishTransaction(long transactionId, Set<Long> errorReplicaIds) thr
...
-                                        LOG.warn("transaction state {} has error, the replica [{}] not appeared in error replica list "
-                                                + " and its version not equal to partition commit version or commit version - 1"
-                                                + " if its not a upgrade stage, its a fatal error. ", transactionState, replica);
-                                    }
-                                } else if (replica.getVersion() >= partitionCommitInfo.getVersion()) {
-                                    // the replica's version is larger than or equal to current transaction partition's version
-                                    // the replica is normal, then remove it from error replica ids
-                                    errorReplicaIds.remove(replica.getId());
+                                        && replica.getLastFailedVersion() < 0
+                                        && replica.checkVersionCatchUp(partition.getVisibleVersion(), true)) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:872]: For reviewer: Remove this part because we will update the replica version in `updateCatalogAfterVisible()`, so no need to update here.

File: fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java [hunk 2]
```diff
@@ -831,8 +831,12 @@ private static void handleRecoverTablet(ListMultimap<Long, Long> tabletRecoveryM
                                 // The absolute value is meaningless, as long as it is greater than 0.
```
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java:831]: delete or update the comment

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java [hunk 3]
```diff
@@ -857,49 +857,19 @@ public void finishTransaction(long transactionId, Set<Long> errorReplicaIds) thr
...
-                                        replica.updateVersionInfo(replica.getVersion(),
-                                                partition.getVisibleVersion(), 
-                                                partitionCommitInfo.getVersion());
-                                        LOG.warn("transaction state {} has error, the replica [{}] not appeared in error replica list "
-                                                + " and its version not equal to partition commit version or commit version - 1"
-                                                + " if its not a upgrade stage, its a fatal error. ", transactionState, replica);
-                                    }
-                                } else if (replica.getVersion() >= partitionCommitInfo.getVersion()) {
-                                    // the replica's version is larger than or equal to current transaction partition's version
-                                    // the replica is normal, then remove it from error replica ids
```
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:901]: This logic is not covered by updateCatalogAfterVisible.

File: fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java (hunk 2 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java:831]: done

File: fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java (hunk 3 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java:901]: I added it back

**Review by hf200012 — APPROVED** [review]
LGTM
