### PR TITLE
[Bug][Compaction] Fix bug that output rowset is not deleted after compaction failure.

### LINKED ISSUE #4963: [Bug][Compaction] The data files are not deleted after compaction failed.
**Describe the bug**
When the compaction fails, the new data files generated are not cleaned up,
resulting in a large number of files remaining on the disk.

The reason of compaction failure is because the number of filtered rows is wrong, so that
the validation after compaction will fail. log like this:

```
row_num does not match between cumulative input and output! input_row_num=4, merged_row_num=0, filtered_row_num=0, output_row_num=0
failed to init base compaction. res=-224, table=10209.1604932729.e643691394eb8627-841daf125e14c3a0
```

Version 0.13.11

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

This CL fix 2 bugs:

1. 
When the compaction fails, we must explicitly delete the output rowset,
otherwise the GC logic cannot process these rows.

2. 
Base compaction failed if compaction process include some delete version in SegmentV2,
Because the number of filtered rows is wrong. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have create an issue on (Fix #4963 ), and have described the bug/feature there in detail

### CODE REVIEW

File: be/src/olap/reader.h [hunk 1]
```diff
@@ -128,7 +128,7 @@ class Reader {
     }
 
     uint64_t filtered_rows() const {
-        return _stats.rows_del_filtered;
```
Comment (xy720) [inline be/src/olap/reader.h:131]: Hi, is it compatible with segment v1?
In alpha_rowset_reader.h, filtered_rows() is only calculate rows_del_filtered.

Comment (morningman) [reply be/src/olap/reader.h:131]: Yes, it is compatible. Because rows_conditions_filtered is only used for SegmentV2, so it should always to 0 in Segment V1.

**Review by xy720 — COMMENTED** [review]
LGTM

**Review by yangzhg — DISMISSED** [review]
+1

File: be/src/olap/compaction.cpp [hunk 2]
```diff
@@ -164,17 +173,11 @@ void Compaction::modify_rowsets() {
     _tablet->save_meta();
 }
 
-OLAPStatus Compaction::gc_unused_rowsets() {
+void Compaction::gc_output_rowset() {
```
Comment (chaoyli) [inline be/src/olap/compaction.cpp:176]: why not call gc_output_rowset in every succeed? It seems a new imported bug ?

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: be/src/olap/compaction.cpp (hunk 2 above)
Comment (morningman) [reply be/src/olap/compaction.cpp:176]: `gc_output_rowset()` should only be called when compaction succeed.

In #4212, we have implemented a new compaction logic, so that the input rowset will be deleted later. And we only need to delete the output rowset when failed.

**Review by chaoyli — DISMISSED** [review]

**Review by yangzhg — APPROVED** [review]
+1
