### PR TITLE
[bugfix 1.1.1] fix bug of vhash join build

### LINKED ISSUE #10595: [Bug] be coredump when building RF
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master-e68ab00

### What's Wrong?

Found this issue when verifying issue #10576 

coredump stack:
` #0  0x000055555b629f3e in COW<doris::vectorized::IColumn>::intrusive_ptr<doris::vectorized::IColumn const>::operator*() const & (this=0x38) at /mnt/disk/tengjianping/doris/be/src/vec/common/cow.h:204
#1  0x000055555cfe656d in doris::RuntimeFilterSlotsBase<doris::vectorized::VExprContext>::insert (this=0x7fff1c128340, datas=...) at /mnt/disk/tengjianping/doris/be/src/exprs/runtime_filter_slots.h:177
#2  0x000055555cfe15e3 in doris::vectorized::ProcessRuntimeFilterBuild<doris::vectorized::PrimaryTypeHashTableContext<unsigned int> >::operator() (this=0x7fff1c128be0, state=0x555565987000, hash_table_ctx=...)
    at /mnt/disk/tengjianping/doris/be/src/vec/exec/join/vhash_join_node.cpp:152
#3  0x000055555cd684f4 in operator()<doris::vectorized::PrimaryTypeHashTableContext<unsigned int>&> (__closure=0x7fff1c128ea0, arg=...) at /mnt/disk/tengjianping/doris/be/src/vec/exec/join/vhash_join_node.cpp:1051
#4  0x000055555cd66b4f in std::__invoke_impl<doris::Status, doris::vectorized::HashJoinNode::_hash_table_build(doris::RuntimeState*)::<lambda(auto:36&&)>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>&>(std::__invoke_other, struct {...} &&) (__f=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
#5  0x000055555cd51ba4 in std::__invoke<doris::vectorized::HashJoinNode::_hash_table_build(doris::RuntimeState*)::<lambda(auto:36&&)>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>&>(struct {...} &&) (
    __fn=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/invoke.h:97
#6  0x000055555cd361c6 in std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<doris::Status> (*)(doris::vectorized::HashJoinNode::_hash_table_build(doris::RuntimeState*)::<lambda(auto:36&&)>&&, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<short unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<long unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<long unsigned int, true>, doris::vectorized::FixedKeyHashTableContext<long unsigned int, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&)>, std::integer_sequence<long unsigned int, 4> >::__visit_invoke(struct {...} &&, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<unsigned short>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned long>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<unsigned long, true>, doris::vectorized::FixedKeyHashTableContext<unsigned long, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> > &) (__visitor=..., __vars#0=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/variant:1015
#7  0x000055555cd36814 in std::__do_visit<std::__detail::__variant::__deduce_visit_result<doris::Status>, doris::vectorized::HashJoinNode::_hash_table_build(doris::RuntimeState*)::<lambda(auto:36&&)>, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<short unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<long unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<long unsigned int, true>, doris::vectorized::FixedKeyHashTableContext<long unsigned int, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&>(struct {...} &&) (__visitor=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/variant:1715
#8  0x000055555cd368ac in std::visit<doris::vectorized::HashJoinNode::_hash_table_build(doris::RuntimeState*)::<lambda(auto:36&&)>, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vect--Type <RET> for more, q to quit, c to continue without paging--c
orized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<short unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<long unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<long unsigned int, true>, doris::vectorized::FixedKeyHashTableContext<long unsigned int, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&>(struct {...} &&) (__visitor=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/variant:1766
#9  0x000055555cd36f0e in doris::vectorized::HashJoinNode::_hash_table_build (this=0x555564b88300, state=0x555565987000) at /mnt/disk/tengjianping/doris/be/src/vec/exec/join/vhash_join_node.cpp:1056
#10 0x000055555cd357ae in doris::vectorized::HashJoinNode::_hash_table_build_thread (this=0x555564b88300, state=0x555565987000, status=0x7fffabd5a910) at /mnt/disk/tengjianping/doris/be/src/vec/exec/join/vhash_join_node.cpp:1002
#11 0x000055555d05cd9d in std::__invoke_impl<void, void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&> (__f=@0x55556ee48758: (void (doris::vectorized::HashJoinNode::*)(doris::vectorized::HashJoinNode * const, doris::RuntimeState *, std::promise<doris::Status> *)) 0x55555cd35716 <doris::vectorized::HashJoinNode::_hash_table_build_thread(doris::RuntimeState*, std::promise<doris::Status>*)>, __t=@0x55556ee48778: 0x555564b88300) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/invoke.h:74
#12 0x000055555d05ccc3 in std::__invoke<void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&> (__fn=@0x55556ee48758: (void (doris::vectorized::HashJoinNode::*)(doris::vectorized::HashJoinNode * const, doris::RuntimeState *, std::promise<doris::Status> *)) 0x55555cd35716 <doris::vectorized::HashJoinNode::_hash_table_build_thread(doris::RuntimeState*, std::promise<doris::Status>*)>) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/invoke.h:96
#13 0x000055555d05cbbf in std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x55556ee48758, __args=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/functional:420
#14 0x000055555d05cadf in std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>::operator()<, void>() (this=0x55556ee48758) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/functional:503
#15 0x000055555d05ca8e in std::__invoke_impl<void, std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>>(std::__invoke_other, std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>&&) (__f=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
#16 0x000055555d05ca43 in std::__invoke<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>>(std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>&&) (__fn=...) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/invoke.h:96
#17 0x000055555d05c9f0 in std::thread::_Invoker<std::tuple<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55556ee48758) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/std_thread.h:253
#18 0x000055555d05c9c4 in std::thread::_Invoker<std::tuple<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)> > >::operator()() (this=0x55556ee48758) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/std_thread.h:260
#19 0x000055555d05c9a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)> > > >::_M_run() (this=0x55556ee48750) at /mnt/disk/tengjianping/local/ldb_toolchain/include/c++/11/bits/std_thread.h:211
#20 0x000055556092c090 in execute_native_thread_routine ()
#21 0x00007ffff70d8ea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007ffff73ebb0d in clone () from /lib64/libc.so.6
(gdb) f 1
#1  0x000055555cfe656d in doris::RuntimeFilterSlotsBase<doris::vectorized::VExprContext>::insert (this=0x7fff1c128340, datas=...) at /mnt/disk/tengjianping/doris/be/src/exprs/runtime_filter_slots.h:177
177                                 vectorized::check_and_get_column<vectorized::ColumnNullable>(*column)) {
(gdb) p it.first
$5 = (const doris::vectorized::Block * const) 0x5555659eefb0
(gdb) p *(it.first)
$6 = {data = {<std::_Vector_base<doris::vectorized::ColumnWithTypeAndName, std::allocator<doris::vectorized::ColumnWithTypeAndName> >> = {
      _M_impl = {<std::allocator<doris::vectorized::ColumnWithTypeAndName>> = {<__gnu_cxx::new_allocator<doris::vectorized::ColumnWithTypeAndName>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<doris::vectorized::ColumnWithTypeAndName, std::allocator<doris::vectorized::ColumnWithTypeAndName> >::_Vector_impl_data> = {_M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}, 
  index_by_name = {<phmap::priv::raw_hash_map<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {ctrl_ = 0x55555952a540 <phmap::priv::EmptyGroup()::empty_group> "\377", '\200' <repeats 15 times>, "N5doris14StringValueSetE", 
        slots_ = 0x0, size_ = 0, capacity_ = 0, infoz_ = {<No data fields>}, 
        settings_ = {<phmap::priv::internal_compressed_tuple::CompressedTupleImpl<phmap::priv::CompressedTuple<unsigned long, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >, phmap::integer_sequence<unsigned long, 0, 1, 2, 3> >> = {<phmap::priv::internal_compressed_tuple::Storage<phmap::priv::CompressedTuple<unsigned long, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >, 0, false>> = {
              value = 0}, <phmap::priv::internal_compressed_tuple::Storage<phmap::priv::CompressedTuple<unsigned long, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >, 1, true>> = {<phmap::priv::StringHashT<char>> = {<No data fields>}, <No data fields>}, <phmap::priv::internal_compressed_tuple::Storage<phmap::priv::CompressedTuple<unsigned long, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >, 2, true>> = {<phmap::priv::StringHashEqT<char>::Eq> = {<No data fields>}, <No data fields>}, <phmap::priv::internal_compressed_tuple::Storage<phmap::priv::CompressedTuple<unsigned long, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >, 3, true>> = {<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> >> = {<__gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}, <No data fields>}, info = {
    is_overflows = false, bucket_num = -1}}
(gdb)   `

### What You Expected?

no coredump

### How to Reproduce?

Status HashJoinNode::_hash_table_build(RuntimeState* state) 函数中，将BUILD_BLOCK_MAX_SIZE修改为一个很小的值：

    constexpr static auto BUILD_BLOCK_MAX_SIZE = 1024; 

Then run tpch_sf1 q8

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jacktengg**
# Proposed changes

Issue Number: close #10595

## Problem Summary:

When build hash table in `HashJoinNode::_hash_table_build`, build side data is collected as a vector of Blocks of size 4G at maximum, if it happens that the total size of build side data is exactly e.g. 4G, then an empty Block will be added to the vector:
```
    while (!eos) {
        block.clear_column_data();
        RETURN_IF_CANCELLED(state);

        RETURN_IF_ERROR(child(1)->get_next(state, &block, &eos));
        _hash_table_mem_tracker->consume(block.allocated_bytes());
        _mem_used += block.allocated_bytes();

        if (block.rows() != 0) {
            mutable_block.merge(block);
        }

        // make one block for each 4 gigabytes
        constexpr static auto BUILD_BLOCK_MAX_SIZE = 4 * 1024UL * 1024UL * 1024UL;
        if (UNLIKELY(_mem_used - last_mem_used > BUILD_BLOCK_MAX_SIZE)) {
            _build_blocks.emplace_back(mutable_block.to_block());
            // TODO:: Rethink may we should do the proess after we recevie all build blocks ?
            // which is better.
            RETURN_IF_ERROR(_process_build_block(state, _build_blocks[index], index));

            mutable_block = MutableBlock();
            ++index;
            last_mem_used = _mem_used;
        }
    }

    _build_blocks.emplace_back(mutable_block.to_block());
```

Later when building RF in `RuntimeFilterSlotsBase::insert`, it will try to get a column from an empty Block, which causes the problem.

Also fixed a potential bug: when build side data exceed 4G * 128, the Blocks added previously into the vector may be relocated, which will invalidate the Block address used as map key in `td::unordered_map<const Block*, std::vector<int>> _inserted_rows;`.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/exec/join/vhash_join_node.cpp [hunk 1]
```diff
@@ -26,6 +26,7 @@
 #include "vec/exprs/vexpr_context.h"
 #include "vec/utils/template_helpers.hpp"
 #include "vec/utils/util.hpp"
+#include "gutil/strings/substitute.h"
```
Comment (carlvinhust2012) [inline be/src/vec/exec/join/vhash_join_node.cpp:29]: should use BE code formater to format the code.

File: be/src/vec/exec/join/vhash_join_node.cpp [hunk 2]
```diff
@@ -1023,6 +1024,9 @@ Status HashJoinNode::_hash_table_build(RuntimeState* state) {
     int64_t last_mem_used = 0;
     bool eos = false;
 
+    // make one block for each 4 gigabytes
+    constexpr static auto BUILD_BLOCK_MAX_SIZE = 4 * 1024UL * 1024UL * 1024UL;
```
Comment (carlvinhust2012) [inline be/src/vec/exec/join/vhash_join_node.cpp:1028]: why not define this constexpr in 'class HashJoinNode'?

File: be/src/vec/exec/join/vhash_join_node.cpp (hunk 1 above)
Comment (jacktengg) [reply be/src/vec/exec/join/vhash_join_node.cpp]: done

**Review by dataroaring — COMMENTED** [review]
It is better to explain how the bug happens.

**Comment by jacktengg** [comment]
> 

Comment is added in Problem Summary.

**Review by yiguolei — APPROVED** [review]
LGTM
