### PR TITLE
[Function][Vectorized] Fix multi args function call the DATETIME type not effective in DATE type and add the alias function

### LINKED ISSUE #8047: [Vectorized][Bug] Some multi arg funtion use in DATETIME not effective in DATE type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

vectorized

### What's Wrong?

```
mysql> select yearweek(k10) from baseall_mysql order by k1;
ERROR 1105 (HY000): errCode = 2, detailMessage = Function yearweek is not implemented

```

### What You Expected?

get the right exe in DATE type

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
1. Support some function alias of mod/fmod, adddate/add_data
2. Support some function of multi args: week, yearweek
3. Fix bug of multi args function call the DATETIME type not effective in DATE type

# Proposed changes

Issue Number: close #8047 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (Yes)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: run-be-ut.sh [hunk 1]
```diff
@@ -75,7 +75,7 @@ fi
 
 eval set -- "$OPTS"
 
-PARALLEL=$[$(nproc)/5+1]
+PARALLEL=$[$(nproc)/4+1]
```
Comment (BiteTheDDDDt) [inline run-be-ut.sh:78]: better not modify this.

**Review by yangzhg — APPROVED** [review]
LGTM
