### PR TITLE
[bug] Fix BE core about vectorized join build thread memtracker switch, and FileStat duplicate

### LINKED ISSUE #9865: [Bug] DCHECK failed caused by tls_ctx()->type() == ThreadContext::TaskType::UNKNOWN
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Similar to this issue, but not completely repaired
https://github.com/apache/incubator-doris/issues/9540

### What's Wrong?

*** Aborted at 1653918666 (unix time) try "date -d @1653918666" if you are using GNU date ***
*** SIGABRT unkown detail explain (@0x24a620) received by PID 2401824 (TID 0x7f2de766e700) from PID 2401824; stack trace: ***
    @     0x55f1b1398b9c  std::thread::_State_impl<>::_M_run()
    @     0x55f1b5d4d700  execute_native_thread_routine
    @     0x7f2ea1e42609  start_thread
    @     0x7f2ea1f7c133  clone
    @              (nil)  (unknown)
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/selectdb_cold_on_s3/selectdb/be/src/common/signal_handler.h:407
 1# 0x00007F2EA1EA0090 in /lib/x86_64-linux-gnu/libc.so.6
 2# raise in /lib/x86_64-linux-gnu/libc.so.6
 3# abort in /lib/x86_64-linux-gnu/libc.so.6
 4# google::ReadFromOffset(int, void*, unsigned long, long) [clone .cold] at src/symbolize.cc:146
 5# 0x000055F1B3C1A79D at src/logging.cc:1650
 6# google::LogMessage::SendToLog() at src/logging.cc:1607
 7# google::LogMessage::Flush() at src/logging.cc:1477
 8# google::LogMessageFatal::~LogMessageFatal() at src/logging.cc:2227
 9# doris::SwitchThreadMemTracker<false>::SwitchThreadMemTracker(std::shared_ptr<doris::MemTracker> const&, bool) at /home/zcp/repo_center/selectdb_cold_on_s3/selectdb/be/src/runtime/thread_context.cpp:108
10# doris::vectorized::AggregationNode::open(doris::RuntimeState*) at /home/zcp/repo_center/selectdb_cold_on_s3/selectdb/be/src/vec/exec/vaggregation_node.cpp:336
11# doris::vectorized::HashJoinNode::_hash_table_build(doris::RuntimeState*) at /home/zcp/repo_center/selectdb_cold_on_s3/selectdb/be/src/vec/exec/join/vhash_join_node.cpp:1004
12# doris::vectorized::HashJoinNode::_hash_table_build_thread(doris::RuntimeState*, std::promise<doris::Status>*) at /home/zcp/repo_center/selectdb_cold_on_s3/selectdb/be/src/vec/exec/join/vhash_join_node.cpp:1000
13# void std::__invoke_impl<void, void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&>(std::__invoke_memfun_deref, void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:74
14# std::__invoke_result<void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&>::type std::__invoke<void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&>(void (doris::vectorized::HashJoinNode::*&)(doris::RuntimeState*, std::promise<doris::Status>*), doris::vectorized::HashJoinNode*&, doris::RuntimeState*&, std::promise<doris::Status>*&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:97
15# void std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) at /home/ubuntu/tools/ldb-tools/include/c++/11/functional:422
16# void std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>::operator()<, void>() at /home/ubuntu/tools/ldb-tools/include/c++/11/functional:505
17# void std::__invoke_impl<void, std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>>(std::__invoke_other, std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>&&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:61
18# std::__invoke_result<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>>::type std::__invoke<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>>(std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)>&&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:97
19# void std::thread::_Invoker<std::tuple<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_thread.h:253
20# std::thread::_Invoker<std::tuple<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)> > >::operator()() at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_thread.h:260
21# std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (doris::vectorized::HashJoinNode::*(doris::vectorized::HashJoinNode*, doris::RuntimeState*, std::promise<doris::Status>*))(doris::RuntimeState*, std::promise<doris::Status>*)> > > >::_M_run() at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_thread.h:211
22# execute_native_thread_routine in /mnt/ssd01/cold_on_s3/VEC_ASAN/be/lib/palo_be
23# start_thread in /lib/x86_64-linux-gnu/libpthread.so.0
24# __clone in /lib/x86_64-linux-gnu/libc.so.6

### What You Expected?

no coredump

### How to Reproduce?

test_issue_8850.sql
image

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #9865 #9869

## Problem Summary:

1. Vectorized join builds the hash table in a separate thread, but does not attach the query mem tracker in TLS when the thread starts, which will result in missing query memory statistics.

2. Minidump FileStat and StorageBackend FileStat have the same name, resulting in an incorrect destructor call.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/runtime/minidump.cpp [hunk 1]
```diff
@@ -32,11 +32,12 @@ int Minidump::_signo = SIGUSR1;
 std::unique_ptr<google_breakpad::ExceptionHandler> Minidump::_error_handler = nullptr;
 
 // Save the absolute path and create_time of a minidump file
-struct FileStat {
+struct MinidumpFileStat {
     std::string abs_path;
```
Comment (yiguolei) [inline be/src/runtime/minidump.cpp:36]: Maybe we could remove minidump， it is not too much useful any more.

Comment (xinyiZzz) [reply be/src/runtime/minidump.cpp:36]: I agree,
Usually online clusters do not enable core dump, not sure if minidump will help

Comment (yiguolei) [reply be/src/runtime/minidump.cpp:36]: There is already a core stack in be.out, most of us use this core stack.

**Review by morningman — DISMISSED** [review]
LGTM

File: be/src/runtime/minidump.cpp (hunk 1 above)
Comment (HappenLee) [reply be/src/runtime/minidump.cpp:36]: > Maybe we could remove minidump， it is not too much useful any more.

i agree too

Comment (xinyiZzz) [reply be/src/runtime/minidump.cpp:36]: > > Maybe we could remove minidump， it is not too much useful any more.
> 
> i agree too

ok, I plan to remove minidump.

**Comment by xinyiZzz** [comment]
> LGTM

p0 failed, not the problem of this pr, 

force push after rebase

**Review by yiguolei — APPROVED** [review]
LGTM
