### PR TITLE
[Bug] fix don't rewrite nested union statement bug

### LINKED ISSUE #8512: [Bug] Don't rewrite nested union statement
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
create table union_test
(
    k1 int,
    k2 int
)
DISTRIBUTED BY HASH(k2) BUCKETS 3
PROPERTIES("replication_num" = "1");

SELECT k1
  FROM test.union_test
  WHERE k1 IN (
      SELECT k1
      FROM (
        SELECT k1
        FROM test.union_test
        ORDER BY k2 DESC, k1 DESC
        LIMIT 300
        INTERSECT
        (SELECT k1
          FROM test.union_test
        ORDER BY k2 DESC, k1 DESC
        LIMIT 9
        EXCEPT
        SELECT k1
        FROM test.union_test
        ORDER BY k2 DESC, k1 DESC
        LIMIT 2)
      ) t
  )

ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: null

```

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qzsee**
# Proposed changes

Issue Number: close #8512

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java [hunk 1]
```diff
@@ -310,10 +310,15 @@ private static SelectList addMissingAggregationColumns(SelectList selectList,
...
-                    (SelectStmt)operand.getQueryStmt(), operand.getAnalyzer());
-            operand.setQueryStmt(rewrittenQueryStmt);
+            QueryStmt queryStmt = operand.getQueryStmt();
+            if (queryStmt instanceof SelectStmt) {
+                QueryStmt rewrittenQueryStmt = rewriteSelectStatement((SelectStmt)queryStmt, operand.getAnalyzer());
+                operand.setQueryStmt(rewrittenQueryStmt);
+            } else if (queryStmt instanceof SetOperationStmt) {
+                rewriteUnionStatement((SetOperationStmt)queryStmt, operand.getAnalyzer());
+            } else {
+                throw new IllegalStateException();
```
Comment (wangshuo128) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java:320]: It's better to have an exception message here.

**Review by wangshuo128 — CHANGES_REQUESTED** [review]

**Review by morningman — COMMENTED** [review]
Please add a unit test in PlanerTest.java for this case

**Comment by qzsee** [comment]
> Please add a unit test in PlanerTest.java for this case

done

File: fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java [hunk 2]
```diff
@@ -310,10 +310,16 @@ private static SelectList addMissingAggregationColumns(SelectList selectList,
...
-                    (SelectStmt)operand.getQueryStmt(), operand.getAnalyzer());
-            operand.setQueryStmt(rewrittenQueryStmt);
+            QueryStmt queryStmt = operand.getQueryStmt();
+            if (queryStmt instanceof SelectStmt) {
+                QueryStmt rewrittenQueryStmt = rewriteSelectStatement((SelectStmt)queryStmt, operand.getAnalyzer());
+                operand.setQueryStmt(rewrittenQueryStmt);
+            } else if (queryStmt instanceof SetOperationStmt) {
+                rewriteUnionStatement((SetOperationStmt)queryStmt, operand.getAnalyzer());
+            } else {
+                LOG.warn("Rewrite union statement failed. Because QueryStmt is neither SelectStmt nor SetOperationStmt");
```
Comment (wangshuo128) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java:320]: I meat to add a message in the exception description, thus users can ask questions with the specific error message. WDYT?

```suggestion
                LOG.warn("Rewrite union statement failed. Because QueryStmt is neither SelectStmt nor SetOperationStmt");
                throw new IllegalStateException("Rewrite union statement failed. Because QueryStmt is neither SelectStmt nor SetOperationStmt");
```

Comment (qzsee) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java]: you are right .
done

**Comment by jackwener** [comment]
It's been a while.
let's fix the conflicts and then merge.
BTW, thanks for your contribution❤

**Comment by qzsee** [comment]
> It's been a while.
> let's fix the conflicts and then merge.
> BTW, thanks for your contribution❤

done

**Comment by jackwener** [comment]
I'm so sorry that forgot to this thing. I'm busy to do other things.....😢

Now, Doris must pass most CI. let's `rebase` the master, fix the conflict and CI will be pass.

**Comment by jackwener** [comment]
If it's done, please feel free to @me, and I will push the maintainer to merge it.

File: fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java [hunk 3]
```diff
@@ -320,11 +320,16 @@ private static SelectList addMissingAggregationColumns(SelectList selectList,
      */
     private static void rewriteUnionStatement(SetOperationStmt stmt, Analyzer analyzer)
             throws AnalysisException {
-        for (SetOperationStmt.SetOperand operand : stmt.getOperands()) {
-            Preconditions.checkState(operand.getQueryStmt() instanceof SelectStmt);
-            QueryStmt rewrittenQueryStmt = StmtRewriter.rewriteSelectStatement(
-                    (SelectStmt) operand.getQueryStmt(), operand.getAnalyzer());
-            operand.setQueryStmt(rewrittenQueryStmt);
+        for (SetOperationStmt.SetOperand operand: stmt.getOperands()) {
```
Comment (jackwener) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java:323]: We can fix those `checkstyle` problem by following hint.

**Review by jackwener — COMMENTED** [review]
There is [doc](https://doris.apache.org/zh-CN/developer-guide/java-format-code.html#idea-2) about `fix code style` problem.

**Review by jackwener — DISMISSED** [review]
LGTM, cc @EmmyMiao87

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
