### PR TITLE
Fix IllegalArgumentException in LoadManager

### LINKED ISSUE #1239: IllegalArgumentException when loadLoadJobsV2
**Describe the bug**
```
java.lang.IllegalArgumentException: No enum constant org.apache.doris.load.EtlJobType.
        at java.base/java.lang.Enum.valueOf(Enum.java:264)
        at org.apache.doris.load.EtlJobType.valueOf(EtlJobType.java:23)
        at org.apache.doris.load.loadv2.LoadJob.read(LoadJob.java:537)
        at org.apache.doris.load.loadv2.LoadManager.readFields(LoadManager.java:367)
        at org.apache.doris.catalog.Catalog.loadLoadJobsV2(Catalog.java:1760)
        at org.apache.doris.catalog.Catalog.loadImage(Catalog.java:1335)
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:645)
        at org.apache.doris.service.FeServer.setup(FeServer.java:44)
        at org.apache.doris.PaloFe.main(PaloFe.java:102)

```
The reason is the `loadManager.write` method has a bug.

### PR DESCRIPTION
**Pull request by kangkaisen**
Fix https://github.com/apache/incubator-doris/issues/1239

### CODE REVIEW

File: fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java [hunk 1]
```diff
@@ -294,6 +294,10 @@ public void submitJobs() {
                 loadJob -> loadJob.state == JobState.PENDING).collect(Collectors.toList()));
     }
 
+    Map<Long, LoadJob> getIdToLoadJobs() {
```
Comment (morningman) [inline fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: Why remove the qualifier of the method and `void addLoadJob(LoadJob loadJob)`

File: fe/src/main/java/org/apache/doris/load/loadv2/LoadJob.java [hunk 2]
```diff
@@ -662,6 +662,24 @@ public void replayOnVisible(TransactionState txnState) {
         }
     }
 
+    public boolean equals(Object obj) {
```
Comment (morningman) [inline fe/src/main/java/org/apache/doris/load/loadv2/LoadJob.java]:
```suggestion
    @Override
    public boolean equals(Object obj) {
```

**Review by morningman — CHANGES_REQUESTED** [review]

File: fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java (hunk 1 above)
Comment (kangkaisen) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: Because `LoadManagerTest` need access  these method.

Comment (EmmyMiao87) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: You can use the invoke function to access these method.

Comment (morningman) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: OK, but I think it is better to add an explicit qualifier~

**Review by morningman — DISMISSED** [review]

File: fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java (hunk 1 above)
Comment (kangkaisen) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: > You can use the invoke function to access these method.
I don't think use reflection is necessary in here.

Comment (kangkaisen) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: > OK, but I think it is better to add an explicit qualifier~

The accessible level for Java access modifiers is :
public > protected >  default(package) > private,

and we should keep accessible level as small as possible.

So I think use default(package) access modifier is reasonable here.

Comment (EmmyMiao87) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: > > You can use the invoke function to access these method.
> 
> I don't think use reflection is necessary in here.

The function of Deencapsulation.invoke() specifically designed to test private method without change private to default.
So maybe Deencapsulation.invoke() is better? It can keep the smaller accessible level for `getIdToLoadJobs`

Comment (kangkaisen) [reply fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java]: @EmmyMiao87 I got it!
I misunderstood the `invoke` word before.
Thanks you!

**Review by morningman — APPROVED** [review]
LGTM
