### PR TITLE
[Auidt] Fix bug for that only the last statement can be audited when user send multi-statement

### LINKED ISSUE #5245: [Bug][Audit] Only the last statement can be audited when user send multi-statement
**Describe the bug**
Only the last statement can be audited when user send multi-statement
**To Reproduce**
select 2; select 3; select 13;
now, only statement 'select 13' will be audited.
**Expected behavior**
audit three statement when all execute all statements succeed

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have create an issue on (Fix #5245), and have described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java [hunk 1]
```diff
@@ -180,9 +182,12 @@ private void handleQuery() {
 
         // execute this query.
         StatementBase parsedStmt = null;
+        List<Pair<StatementBase, PQueryStatistics>> auditInfoList = Lists.newArrayList();
+        boolean alreadyAddedToAuditInfoList = false;
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java:186]: `alreadyAddedToAuditInfoList` seems useless, we can just check `auditInfoList.isEmpty()`

Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java:186]: if some statement execute failed before added to auditInfoList， we should try to record it

**Review by morningman — APPROVED** [review]
LGTM
