### PR TITLE
[bug](udf) add synchronized to test resolve error of zip file closed

### LINKED ISSUE #17810: [Bug] java udf have some error Unexpected exception: zip file closed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

`2023-03-14 16:35:51,686 WARN (mysql-nio-pool-24|647) [StmtExecutor.analyze():838] Analyze failed. stmt[2699, a7aacfdfc9504873-866ebf9e77aef802]
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669) ~[?:1.8.0_131]
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:351) ~[?:1.8.0_131]
        at java.util.jar.JarFile.getInputStream(JarFile.java:447) ~[?:1.8.0_131]
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:162) ~[?:1.8.0_131]
        at sun.misc.URLClassPath$Loader$1.getInputStream(URLClassPath.java:753) ~[?:1.8.0_131]
        at sun.misc.Resource.cachedInputStream(Resource.java:77) ~[?:1.8.0_131]
        at sun.misc.Resource.getByteBuffer(Resource.java:160) ~[?:1.8.0_131]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:454) ~[?:1.8.0_131]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at org.apache.doris.analysis.CreateFunctionStmt.analyzeJavaUdaf(CreateFunctionStmt.java:370) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.CreateFunctionStmt.analyzeUda(CreateFunctionStmt.java:322) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.CreateFunctionStmt.analyze(CreateFunctionStmt.java:182) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:834) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:482) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:433) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:413) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:557) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:794) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
2023-03-14 16:35:51,686 WARN (mysql-nio-pool-24|647) [StmtExecutor.execute():633] execute Exception. stmt[2699, a7aacfdfc9504873-866ebf9e77aef802]
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Unexpected exception: zip file closed
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:839) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:482) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:433) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:413) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:557) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:794) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131] `

### What You Expected?

test/run well

### How to Reproduce?

This problem is very difficult to reproduce, But we have meet this error in P0 sometimes,

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes
   this error report in P0 test, But can't reproduce it in local
   so add this change to test it.

Issue Number: close #17810

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run P0

**Comment by zhangstar333** [comment]
run p0

File: fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java [hunk 1]
```diff
@@ -175,14 +175,19 @@ public Expr getOriginFunction() {
...
-        if (isAggregate) {
-            analyzeUda();
-        } else if (isAlias) {
-            analyzeAliasFunction();
-        } else {
-            analyzeUdf();
+        // https://github.com/apache/doris/issues/17810
+        // this error report in P0 test, so we suspect that it is related to concurrency
+        // add this change to test it.
+        synchronized (CreateFunctionStmt.class) {
```
Comment (yiguolei) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java:181]: If we release doris 2.0 now, this code will be released. It may cause FE analysis time very long....

I think you could using Config.use_fuzzy_session_variable to control that the sychronized logic only work in github workflow.

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p1

**Review by Gabriel39 — APPROVED** [review]
LGTM
