### PR TITLE
[Bug] Fix isnull(null) analyze error

### LINKED ISSUE #4093: [BUG] Analyze isnull(null) function fail
Analyze isnull(null) function fail

mysql> select isnull(null);
ERROR 1064 (HY000): errCode = 2, detailMessage = Unexpected exception: tupleisNull fn == NULL

### PR DESCRIPTION
**Pull request by HangyuanLiu**
Fix isnull(null) analyze error
FIX #4093

### CODE REVIEW

File: fe/src/test/java/org/apache/doris/analysis/IsNullPredicateTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import org.junit.Assert;
+import org.junit.Test;
+
+public class IsNullPredicateTest {
+    @Mocked
+    Analyzer analyzer;
+
+    @Test
+    public void testNullParam() {
+        IsNullPredicate isNullPredicate = new IsNullPredicate(new NullLiteral(), false);
```
Comment (morningman) [inline fe/src/test/java/org/apache/doris/analysis/IsNullPredicateTest.java:31]: How about add test for isnotnull too?

Comment (HangyuanLiu) [reply fe/src/test/java/org/apache/doris/analysis/IsNullPredicateTest.java:31]: OK

**Review by wutiangan — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
+1
