### PR TITLE
[Bug] Unify the timezone

### LINKED ISSUE #3919: [Bug] Create table with dynamic partition encounter exception
**Describe the bug**
When create table with dynamic partition without specifying the time zone, it will throw exception:

`nknown or incorrect time zone: 'PRC'`

**To Reproduce**
Ccreate table with dynamic partition without specifying the time zone

**Expected behavior**
Use default time zone to create table with dynamic partition successfully.

### PR DESCRIPTION
**Pull request by morningman**
When we get default system time zone, it will return `PRC`, which is not supported by us, thus
will cause dynamic partition create failed. Fix #3919

This CL mainly changes:
1. Use a unified method to get the system default time zone
2. Now the default variable `system_time_zone` and `time_zone` is set to the default system
time zone, which is `Asia/Shanghai`.
3. Modify related unit test.
4. Support time zone `PRC`.

### CODE REVIEW

File: fe/src/main/java/org/apache/doris/catalog/Catalog.java [hunk 1]
```diff
@@ -554,6 +554,13 @@ public static Catalog getCurrentCatalog() {
         }
     }
 
+    // NOTICE: In most cases, you should use getCurrentCatalog() to get the catalog.
+    // getServiingCatalog() is only used for Checkpoint thread and some special places
```
Comment (WingsGo) [inline fe/src/main/java/org/apache/doris/catalog/Catalog.java:558]: getServingCatalog

Comment (morningman) [reply fe/src/main/java/org/apache/doris/catalog/Catalog.java:558]: Oh, I moved the change to PR #3229
I will rebase after that PR merged.

Comment (morningman) [reply fe/src/main/java/org/apache/doris/catalog/Catalog.java]: Already for review.

**Comment by WingsGo** [comment]
LGTM

**Review by EmmyMiao87 — APPROVED** [review]
LGTM
