### PR TITLE
[fix](intersect) fix wrong result of intersect node

### LINKED ISSUE #24046: Doirs INTERSECT  结果错误
### Discussed in https://github.com/apache/doris/discussions/23918

<div type='discussions-op-text'>

<sup>Originally posted by **qiaoshiling** September  5, 2023</sup>
Doris版本 1.2.5
我现在有一张表a，想取到他在三种不同条件下的交集 使用到了INTERSECT关键字
测试语句

```plpgsql

 (
SELECT
	a.sku_code
FROM
	(
	   SELECT  *  FROM	a
    ) a
WHERE
	  a.is_lst > 0 AND a.site_code = 'UK'
 )
INTERSECT
 (
SELECT
     b.sku_code
FROM
    (
       SELECT * FROM a 
    ) b
WHERE
      b.is_lst >= 0 AND b.site_code = 'DE'
 )
INTERSECT
 (
SELECT
     c.sku_code
FROM
    (
     SELECT  * FROM  a 
    ) c
 WHERE
     c.is_lst >= 0   AND c.site_code = 'ES'
 )
``` 

每次查询结果数据量从 198~200 不等
后经过sql 修改
```plpgsql
select
	mqxwmfam.*
from
	((
	SELECT
		a.sku_code
	FROM
	    (
		select * from	a
         ) a
where
   a.is_lst > 0 AND a.site_code = 'UK')
INTERSECT
		(
	SELECT
		b.sku_code
	FROM
		(
		select * from	a
		) b
	WHERE
		b.is_lst >= 0 AND b.site_code = 'DE' ) ) mqxwmfam
INTERSECT
	(
    SELECT
		c.sku_code
    FROM
		(
	select	* from	a
	    ) c
WHERE
 c.is_lst >= 0	AND c.site_code = 'ES' )
```

可以看到我将第一个 INTERSECT 变为了一个子查询并取了别名再进行交集运算，数据稳定在了201条。
是否可以告知我Doris INTERSECT关键字的实现逻辑以及为什么会出现这样的问题
如果更多的子集求交集应该怎么写 一层一层的做嵌套么？</div>

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #24046

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/vec/exec/vset_operation_node.cpp [hunk 1]
```diff
@@ -682,47 +682,41 @@ void VSetOperationNode<is_intersect>::refresh_hash_table() {
...
-                                        tmp_hash_table.hash_table.insert(iter->get_value());
+                        std::visit(
+                                [&](auto is_need_shrink_const) {
+                                    while (iter != iter_end) {
+                                        auto& mapped = iter->get_second();
+                                        auto it = mapped.begin();
+
+                                        if constexpr (is_intersect) { //intersected
+                                            if (it->visited) {
+                                                it->visited = false;
```
Comment (HappenLee) [inline be/src/vec/exec/vset_operation_node.cpp:701]: no need to the work

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM
