### PR TITLE
[fix](brpc-attachment) Fix bug that may cause BE crash when enable `transfer_data_by_brpc_attachment`

### LINKED ISSUE #7920: [Bug] BE crash after enable `transfer_data_by_brpc_attachment`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

When set be config `transfer_data_by_brpc_attachment` to true. And run some join query which has exchange node,
BE may crash with following stack:

```
start time: Thu Jan 27 15:57:55 CST 2022
Minidump created at: /home/cmy/palo/be/minidump/c9476a55-12e8-493c-21b4f1ab-c2308bc9.dmp
*** Aborted at 1643270317 (unix time) try "date -d @1643270317" if you are using GNU date ***
PC: @          0x1b06030 doris::HashTable::hash_variable_len_row()
*** SIGSEGV (@0x17539d10) received by PID 21897 (TID 0x7fa129f58700) from PID 391355664; stack trace: ***
    @          0x21e6e22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fa22d6c4f90 (unknown)
    @          0x1b06030 doris::HashTable::hash_variable_len_row()
    @          0x1b05473 doris::HashJoinNode::process_build_batch()
    @          0x1b02510 doris::HashJoinNode::construct_hash_table()
    @          0x1b02a12 doris::HashJoinNode::build_side_thread()
    @          0x3a403a0 execute_native_thread_routine
    @     0x7fa22d674f84 start_thread
    @     0x7fa22d781ddf __GI___clone
    @                0x0 (unknown)
```

### What You Expected?

Not crash

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #7920 

## Problem Summary:

This PR mainly changes:

1. Fix bug when enable `transfer_data_by_brpc_attachment`

    In `data_stream_sender`, we will send a serialized PRowBatch data to multiple Channels.
    And if `transfer_data_by_brpc_attachment` is enabled, we will mistakenly clear the data in PRowBatch
    after sending PRowBatch to the first Channel.
    As a result, the following Channel cannot receive the correct data, causing an error.

    So I use a separate buffer instead of `tuple_data` in PRowBatch to store the serialized data
    and reuse it in multiple channels.

2. Fix bug that the the offset in serialized row batch may overflow

    Use int64 to replace int32 offset. And for compatibility, add a new field `new_tuple_offsets` in PRowBatch.

3. Remove TRowBatch

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/runtime/data_stream_sender.h [hunk 1]
```diff
@@ -204,7 +199,11 @@ class DataStreamSender : public DataSink {
 
         // TODO(zc): initused for brpc
         PUniqueId _finst_id;
-        PRowBatch _pb_batch;
+
+        PRowBatch* _ch_cur_pb_batch;
+        PRowBatch _ch_pb_batch1;
```
Comment (yangzhg) [inline be/src/runtime/data_stream_sender.h:204]: Add some comment to explain why named batch1 and batch2, or rename to a meaningful name?

Comment (morningman) [reply be/src/runtime/data_stream_sender.h:208]: Comment added

**Review by yangzhg — APPROVED** [review]
LGTM
