### PR TITLE
[Bug] Fix some bugs

### LINKED ISSUE #6656: [Bug] BE crash when loading data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk 61c9d11

### What's Wrong?

coredump:

```
(gdb) bt
#0  0x0000000001566883 in doris::RowBatch::resize_and_allocate_tuple_buffer (this=<optimized out>, state=0x800, tuple_buffer_size=0x5657cc528, buffer=0x54ce04000)
    at /path/be/src/runtime/row_batch.cpp:519
#1  0x000000000156752d in doris::RowBatch::serialize (this=<optimized out>, output_batch=0x55e03db30) at /path/be/src/runtime/row_batch.cpp:497
#2  0x0000000001a59d81 in doris::OlapTableSchemaParam::to_protobuf (this=0x55e03db30) at /path/be/src/exec/tablet_info.h:68
#3  doris::stream_load::NodeChannel::open (this=0xe60b00 <__pthread_key_create@plt>) at /path/be/src/exec/tablet_sink.cpp:105
#4  0x000000000164bbc3 in doris::ThreadPool::ThreadPool (this=0x67e05dbd0, builder=...) at /path/be/src/common/status.h:134
#5  0x0000000001645c34 in std::string::operator= (__str=..., this=0x533a33a40) at /home/opt/compiler/gcc-10-r5/include/c++/10.1.0/bits/basic_string.h:3749
#6  doris::ThreadMgr::ThreadDescriptor::operator= (this=0x533a33a40) at /path/be/src/util/thread.cpp:88
#7  doris::ThreadMgr::add_thread (this=0x6017700, pthread_id=<error reading variable>, name=..., category=..., tid=<optimized out>)
```

### What You Expected?

Not crash

### How to Reproduce?

It seems that this error will occur if a load job ends early due to other errors (such as -235).

### Anything Else?

Maybe related to #6397.
Because I found that the thread token is not shutdown before tablet sink is closed.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #6657: [Bug] BE crash when doing alter task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk 61c9d11

### What's Wrong?

BE crash when visiting `_input_batch` of rowset reader.

### What You Expected?

Not crash

### How to Reproduce?

If the  rowset reader is not initialized successfully, the reader should not be used.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #6658: [Feature] Add `order` column in `SHOW TABLET` stmt result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Sometimes, I want to know the order of tablet (AKA bucket sequence of tablet) of a colocation table. So that I can find the Backends list assigned to this bucket.

### Use case

```
mysql> show tablet 126684560\G
*************************** 1. row ***************************
       DbName: default_cluster:db1
    TableName: tbl1
PartitionName: partition1
    IndexName: tbl1
         DbId: 1501243
      TableId: 59019459
  PartitionId: 59019458
      IndexId: 126684539
       IsSync: true
        Order: 5
    DetailCmd: SHOW PROC '/dbs/1501243/59019459/partitions/59019458/126684539/126684560';
```

And now I know the order of this tablet is `5`. Than I can find backend lists of this bucket by:

```
mysql> show proc "/colocation_group/61190005.97437015";                                                                                                                                                     +-------------+------------------------------+
| BucketIndex | {"location" : "default"}     |
+-------------+------------------------------+
| 0           | 65109230, 63737443, 65108975 |
| 1           | 63737443, 65108975, 65102017 |
| 2           | 63737443, 65108975, 65102017 |
| 3           | 63737443, 65108975, 65109230 |
| 4           | 65102017, 63737443, 65109230 |
| 5           | 65102017, 63737443, 65108975 |
| 6           | 63737443, 65109230, 65108975 |
```

The backend list of bucket 5 is `65102017, 63737443, 65108975`

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #6659: [Bug] Tablet scheduler stop working
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk 61c9d11

### What's Wrong?

Tablet scheduler stop working. Result in tablet not being repaired.

### What You Expected?

Working well

### How to Reproduce?

This is a bug introduced from #6513.

The working slot is not released when choosing source replica to do clone task

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #6660: [Bug] REPLICA_MISSING error can not be handled.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk 61c9d11

### What's Wrong?

Error in master fe.log:

```
2021-09-14 22:47:08,585 INFO (tablet scheduler|38) [TabletScheduler.removeTabletCtx():1256] remove the tablet 109647076. because: no proper tag is chose for tablet 109647076
```

### What You Expected?

working well

### How to Reproduce?

This is a bug introduced from #6203

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #6663: [Feature] the health status of colocate table's tablet is not shown in show proc statistic
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

`show proc '/statistic'` does not handle the status of tablets of colocate table.
So that we can not known the statistic of healthy of these tablets.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #6664: [Bug] `show load where state='pending'` can not be executed.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk 61c9d11

### What's Wrong?

`show load where state="pending"`
return error: `Where clause should looks like: LABEL....`

### What You Expected?

execute ok

### How to Reproduce?

This bug is introduced from #6314

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. Fix a potential BE coredump of sending batch when loading data. (Fix #6656)
2. Fix a potential BE coredump when doing schema change. (Fix #6657)
3. Optimize the metric of base_compaction_request_failed.
4. Add `Order` column in `show tablet` result. (Fix #6658)
5. Fix bug that tablet repair slot not being released. (Fix #6659)
6. Fix bug that REPLICA_MISSING error can not be handled. (Fix #6660)
7. Modify column name of `SHOW PROC "/cluster_balance/cluster_load_stat"`
8. Optimize the result of `SHOW PROC "/statistic"` to show COLOCATE_MISMATCH tablets (Fix #6663)
9. Fix bug that `show load where state='pending'` can not be executed. (Fix #6664)

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [x] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
cc @caiconghui #6656

File: fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java [hunk 1]
```diff
@@ -1102,4 +1088,14 @@ public String toString() {
         }
         return sb.toString();
     }
+
+    // Comparator to sort the replica with version count, asc
+    public static class VersionCountComparator implements Comparator<Replica> {
+        @Override
+        public int compare(Replica r1, Replica r2) {
+            long verCount1 = r1.getVersionCount() == -1 ? Integer.MAX_VALUE : r1.getVersionCount();
+            long verCount2 = r2.getVersionCount() == -1 ? Integer.MAX_VALUE : r2.getVersionCount();
```
Comment (caiconghui) [inline fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java:1097]: Integer.MAX_VALUE -> Long.MAX_VALUE

File: be/src/olap/tablet.cpp [hunk 2]
```diff
@@ -1345,8 +1345,8 @@ int64_t Tablet::prepare_compaction_and_calculate_permits(CompactionType compacti
         OLAPStatus res = _base_compaction->prepare_compact();
         if (res != OLAP_SUCCESS) {
             set_last_base_compaction_failure_time(UnixMillis());
-            DorisMetrics::instance()->base_compaction_request_failed->increment(1);
             if (res != OLAP_ERR_BE_NO_SUITABLE_VERSION) {
+				DorisMetrics::instance()->base_compaction_request_failed->increment(1);
```
Comment (caiconghui) [inline be/src/olap/tablet.cpp:1349]:
```suggestion
		DorisMetrics::instance()->base_compaction_request_failed->increment(1);
```

File: fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java (hunk 1 above)
Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java:1097]: This is intentional, because `compare()` return int. If I use Long.MAX_VALUE, it may be overflow.

File: be/src/olap/tablet.cpp (hunk 2 above)
Comment (morningman) [reply be/src/olap/tablet.cpp]: ok

**Review by yangzhg — DISMISSED** [review]
LGTM

File: fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java (hunk 1 above)
Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java:1097]: the type of verCount is long, so I think we just need to return 1, -1, 0 to support bigger scope of version count value

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java]: Done

**Comment by yangzhg** [comment]
LGTM

**Review by yangzhg — APPROVED** [review]
LGTM
