### PR TITLE
[fix](nereids) Use correct PREAGGREGATION in agg(filter(scan))

### LINKED ISSUE #33351: [Bug] (nereids) Close PREAGGREGATION in simple aggregation
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.1

### What's Wrong?

1. Create a olap table:
```
CREATE TABLE `llj_test` (
  `timeSec` BIGINT NULL COMMENT '',
  `ruleId` BIGINT NULL COMMENT '',
  `decisionId` BIGINT NULL COMMENT '',
  `isEffect` TINYINT NULL COMMENT '',
  `isMarked` TINYINT NULL COMMENT '',
  `userid` BIGINT NULL COMMENT '',
  `orderid` BIGINT NULL COMMENT '',
  `uuid` VARCHAR(128) NULL COMMENT '',
  `businessCode` INT NULL COMMENT '',
  `sceneId` BIGINT NULL COMMENT '',
  `action` INT NULL COMMENT '',
  `mobile` VARCHAR(32) NULL COMMENT '',
  `mobile_operatorname` VARCHAR(64) NULL COMMENT '',
  `dealid` BIGINT NULL COMMENT '',
  `requestId` VARCHAR(64) NULL COMMENT '',
  `timeMin` INT NULL COMMENT '',
  `hitRules` VARCHAR(2048) NULL COMMENT '',
  `dt` INT NULL COMMENT '',
  `requestNum` INT SUM NULL COMMENT '',
  `expandNum` DOUBLE SUM NULL COMMENT ''
) ENGINE=OLAP
AGGREGATE KEY(`timeSec`, `ruleId`, `decisionId`, `isEffect`, `isMarked`, `userid`, `orderid`, `uuid`, `businessCode`, `sceneId`, 
              `action`, `mobile`, `mobile_operatorname`, `dealid`, `requestId`, `timeMin`, `hitRules`, `dt`)
COMMENT '测试'
PARTITION BY RANGE(`dt`)
(PARTITION p20240304 VALUES [("19700101"), ("20240409")),
PARTITION p20240410 VALUES [("20240409"), ("20240410")))
DISTRIBUTED BY HASH(`timeSec`) BUCKETS 6
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"min_load_replica_num" = "-1",
"bloom_filter_columns" = "orderid, sceneId",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V1",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);
```
2. Insert som data.
```
insert  into llj_test values(123,444,555,1,1,6666,7777,'uuid', 1,8,9,'mobile', 'mobile_operatorname',10,'requestId',1234,'111',20240409,-1,-2)
```
3. explain a simple aggregation sql:
```
set global experimental_enable_nereids_planner = true;

select requestid,
               sceneid,
    max(timeSec) maxTime
          from llj_test
         where dt between 20240403 AND 20240410
           AND ruleId = 2279
           and timeSec between UNIX_TIMESTAMP('2024-04-03 00:03:46') AND UNIX_TIMESTAMP('2024-04-10 23:59:49')
         group by requestId,
                  sceneid
order by maxTime desc
limit 100;
The OlapScanNode's PREAGGREGATION is OFF and reaseon is No aggregate on scan. 
```

### What You Expected?

The `PREAGGREGATION` should be `ON`

### How to Reproduce?

See bug description.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes

Issue Number: close #33351

1. set `PreAggStatus` to `ON` when agg key column by max or min;
2. #28747 may change `PreAggStatus` of scan, inherit it from the previous one.

## Further comments
Further regression test case will be conducted later.

### CODE REVIEW

**Comment by liutang123** [comment]
@BiteTheDDDDt hello, do you have time to see this pr?

**Comment by liutang123** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java [hunk 1]
```diff
@@ -829,15 +832,16 @@ public PreAggStatus visitHllUnion(HllUnion hllUnion, CheckContext context) {
...
+                boolean canUseKeyColumn) {
             String childNameWithFuncName = ctx.isBaseIndex()
                     ? normalizeName(aggFunc.child(0).toSql())
                     : normalizeName(CreateMaterializedViewStmt.mvColumnBuilder(
                         matchingAggType, normalizeName(aggFunc.child(0).toSql())));
 
             boolean contains = containsAllColumn(aggFunc.child(0), ctx.keyNameToColumn.keySet());
             if (contains || ctx.keyNameToColumn.containsKey(childNameWithFuncName)) {
-                if (ctx.isDupKeysOrMergeOnWrite || (!ctx.isBaseIndex() && contains)) {
+                if (canUseKeyColumn || ctx.isDupKeysOrMergeOnWrite || (!ctx.isBaseIndex() && contains)) {
```
Comment (BiteTheDDDDt) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java:844]: maybe we can use ctx.isBaseIndex() to replace canUseKeyColumn?

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java [hunk 2]
```diff
@@ -745,22 +748,22 @@ public PreAggStatus visit(Expression expr, CheckContext context) {
...
         @Override
         public PreAggStatus visitAggregateFunction(AggregateFunction aggregateFunction, CheckContext context) {
-            return checkAggFunc(aggregateFunction, AggregateType.NONE, context);
+            return checkAggFunc(aggregateFunction, AggregateType.NONE, context, false);
         }
 
         @Override
         public PreAggStatus visitMax(Max max, CheckContext context) {
-            return checkAggFunc(max, AggregateType.MAX, context);
+            return checkAggFunc(max, AggregateType.MAX, context, true);
```
Comment (BiteTheDDDDt) [inline fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java:756]: I don't know why min/max should be different from other aggregation methods. Can you explain it?

Comment (liutang123) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java:756]: Because max value or min value is not affected by the number of keys.
For example:
There are two rowsets. One includes key values: [1, 2]，the ohter one includes key values:[2, 3].
The merge key values should be [1, 2, 3].
The value of max(max([1,2]),  max([2, 3]) and the value of max([1, 2, 3]) are all 3.
min is the same as max.
But, the other funcs like sum are not.
The value of sum(sum([1,2]),  sum([2, 3]) is 8 and the right value of sum([1, 2, 3]) should be 6.

File: fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java (hunk 1 above)
Comment (liutang123) [reply fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java:844]: It doesn't seem to work.

**Comment by liutang123** [comment]
run feut

**Review by morrySnow — DISMISSED** [review]

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by liutang123** [comment]
run buildall`

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
@morrySnow Hi, Wenxin. This PR is ready for merge. Do you have time to have a look at it?

File: regression-test/suites/nereids_p0/explain/test_scan_preaggregation_explain.groovy [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+    sql """ insert into test_scan_preaggregation values
+            (1, 2, 3, 4),
+            (1, 5, 6, 7); """
+    explain {
+        sql("select k1, min(k2), max(k3) from test_scan_preaggregation where k1 = 0 group by k1;")
+        contains "PREAGGREGATION: ON"
+    }
+
+    qt_right_when_preagg_on "select k1, min(k2), max(k3) from test_scan_preaggregation where k1 = 1 group by k1;"
+    qt_right_when_preagg_off "select k1, sum(v1) from test_scan_preaggregation group by k1;"
```
Comment (starocean999) [inline regression-test/suites/nereids_p0/explain/test_scan_preaggregation_explain.groovy:48]: qt_right_when_preagg_off is misleading, the preagg should be on ?

Comment (liutang123) [reply regression-test/suites/nereids_p0/explain/test_scan_preaggregation_explain.groovy:48]: hello, the `qt_right_when_preagg_off` shoud not be on because the aggregation is sum.

Comment (liutang123) [reply regression-test/suites/nereids_p0/explain/test_scan_preaggregation_explain.groovy]: Sorry, I was originally going to test aggregation on key columns. I modified the test sql.

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
@starocean999 Hi, I fix the regression test case, can you take another look at this PR?

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]
