### PR TITLE
[Bug](ReportHandler) Fix bug that tabletReport function of ReportHandler in fe may throw NullPointerException due to transaction check logic

### LINKED ISSUE #8480: [Bug] tabletReport function of ReportHandler in fe throws NullPointerException
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

2022-03-14 20:42:21,668 ERROR (Thread-35|83) [Daemon.run():118] daemon thread got exception. name: Thread-35
java.lang.NullPointerException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603) ~[?:?]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[?:?]
        at org.apache.doris.catalog.TabletInvertedIndex.tabletReport(TabletInvertedIndex.java:134) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.ReportHandler.tabletReport(ReportHandler.java:276) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.ReportHandler.access$400(ReportHandler.java:95) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.ReportHandler$ReportTask.exec(ReportHandler.java:240) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.ReportHandler.runOneCycle(ReportHandler.java:1060) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:3.4.0]
Caused by: java.lang.NullPointerException

### What You Expected?

not throw NullPointerException

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #8480 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java [hunk 1]
```diff
@@ -212,20 +212,8 @@ public void tabletReport(long backendId, Map<Long, TTablet> backendTablets,
...
-                                                 * 3. At the same time, some of partitions have been dropped, so partitionCommitInfos does not contain these partitions.
-                                                 * 4. So we will not able to get partitionCommitInfo here.
-                                                 *
-                                                 * Just print a log to observe
-                                                 */
-                                                LOG.info("failed to find partition commit info. table: {}, partition: {}, tablet: {}, txn id: {}",
-                                                        tabletMeta.getTableId(), partitionId, tabletId, transactionState.getTransactionId());
-                                            } else {
+                                            PartitionCommitInfo partitionCommitInfo = tableCommitInfo == null ? null : tableCommitInfo.getPartitionCommitInfo(partitionId);
+                                            if (partitionCommitInfo != null) {
```
Comment (EmmyMiao87) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java:216]: May be keep this info log is better ?

Comment (caiconghui) [reply fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java:216]: I think print log for normal situation is so necessary if we could not get any useful information

**Review by morningman — APPROVED** [review]
LGTM
