### PR TITLE
[fix](multi-catalog) use last used database for catalog when switch back

### LINKED ISSUE #14792: [Bug] lost last used database when switch catalog back
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

mysql> switch internal;
Query OK, 0 rows affected (0.00 sec)

mysql> use db1;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> switch hive;
Query OK, 0 rows affected (0.01 sec)

mysql> switch internal;
Query OK, 0 rows affected (0.00 sec)

mysql> show tables;
ERROR 1046 (3D000): errCode = 2, detailMessage = No database selected

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yulei-Yang**
remember last used database of every catalog and use it when switch back

# Proposed changes

Issue Number: close #14792

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.04 seconds
 load time: 443 seconds
 storage size: 17123356242 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221203153208_clickbench_pr_57230.html

File: fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java [hunk 1]
```diff
@@ -74,6 +74,8 @@ public class CatalogMgr implements Writable, GsonPostProcessable {
     private final Map<Long, CatalogIf> idToCatalog = Maps.newConcurrentMap();
     // this map will be regenerated from idToCatalog, so not need to persist.
     private final Map<String, CatalogIf> nameToCatalog = Maps.newConcurrentMap();
+    // record last used database of every catalog
+    private final Map<String, String> lastDBOfCatalog = Maps.newConcurrentMap();
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java:78]: You need to clear this map when catalog is droped.
And please add some regression test for this case.

File: fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java [hunk 2]
```diff
@@ -4443,8 +4443,16 @@ public void changeCatalog(ConnectContext ctx, String catalogName) throws DdlExce
...
+        String currentDB = ctx.getDatabase();
+        if (StringUtils.isNotEmpty(currentDB)) {
+            catalogMgr.addLastDBOfCatalog(ctx.getCurrentCatalog().getName(), currentDB);
+        }
         ctx.changeDefaultCatalog(catalogName);
-        if (catalogIf instanceof EsExternalCatalog) {
+        String lastDb = catalogMgr.getLastDB(catalogName);
+        if (StringUtils.isNotEmpty(lastDb)) {
+            ctx.setDatabase(lastDb);
+        } else if (catalogIf instanceof EsExternalCatalog) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java:4455]:
```suggestion
        }
        if (catalogIf instanceof EsExternalCatalog) {
```

File: fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java [hunk 3]
```diff
@@ -241,6 +251,8 @@ public void dropCatalog(DropCatalogStmt stmt) throws UserException {
             CatalogLog log = CatalogFactory.constructorCatalogLog(catalog.getId(), stmt);
             replayDropCatalog(log);
             Env.getCurrentEnv().getEditLog().logCatalogLog(OperationType.OP_DROP_CATALOG, log);
+
+            lastDBOfCatalog.remove(stmt.getCatalogName());
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java:255]: Need to modify `removeCatalog()` too.
Because `removeCatalog()` will be called when replaying edit log

**Review by morningman — APPROVED** [review]
LGTM
