### PR TITLE
[Bug] Fix timestamp_diff issue when timeunit is year and month

### LINKED ISSUE #9296: [Bug] TIMESTAMPDIFF(unit,datetime_expr1,datetime_expr2) get wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

```SQL
# doris 0.15
# timestampdiff between 1981-09-11 and 2022-04-28 should be 40 years
SELECT 
  TIMESTAMPDIFF(YEAR,DATE('1981-09-11'),'2022-04-28') AS `date-str`,
  TIMESTAMPDIFF(YEAR,'1981-09-11','2022-04-28') AS `str-str`,
  TIMESTAMPDIFF(YEAR,DATE('1981-09-11'),DATE('2022-04-28')) AS `date-date`,
  TIMESTAMPDIFF(YEAR,'1981-09-11',DATE('2022-04-28')) AS `str-date`

# while the result is 
date-str	str-str		date-date		str-date
41		40		41			41
	
# timestampdiff between 1981-04-11 and 2022-04-28 should be 41 years
SELECT
  TIMESTAMPDIFF(YEAR,DATE('1981-09-11'),'2022-04-28') AS `date-str`,
  TIMESTAMPDIFF(YEAR,'1981-09-11','2022-04-28') AS `str-str`,
  TIMESTAMPDIFF(YEAR,DATE('1981-04-11'),DATE('2022-04-28')) AS `date-date`,
  TIMESTAMPDIFF(YEAR,'1981-04-11',DATE('2022-04-28')) AS `str-date`

# while the result is 
date-str	str-str		date-date		str-date
41		40		41			41
```

### What You Expected?

timestampdiff between 1981-09-11 and 2022-04-28 should be 40 year
timestampdiff between 1981-04-11 and 2022-04-28 should be 41 year

### Anything Else?

This also happens when `unit` is `MONTH` !
And it even get different result using `TIMESTAMP(expr)` instead of `DATE(expr)`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #9296

## Problem Summary:
`DateTimeValue.to_int64()` will get different value when type is different but the `datetime_diff` treat it as datetime.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
It seems there are the same problem in vectorized engine (file: vdatatime_value.h), could you fix it together?

How to open vectorized engine:
`set enable_vectorized_engine=true;`

**Comment by cambyzju** [comment]
LGTM

File: be/src/vec/runtime/vdatetime_value.h [hunk 1]
```diff
@@ -288,21 +288,23 @@ class VecDateTimeValue { // Now this type is a temp solution with little changes
         case YEAR: {
             int year = (ts_value2.year() - ts_value1.year());
             if (year > 0) {
-                year -= (ts_value2.to_int64() % 10000000000 - ts_value1.to_int64() % 10000000000) <
-                        0;
+                year -= (ts_value2.to_datetime_int64() % 10000000000 -
```
Comment (yiguolei) [inline be/src/vec/runtime/vdatetime_value.h:291]: Why not use to_int64 here? I find it will check the type of datetimevalue. 
int64_t VecDateTimeValue::to_int64() const {
    switch (_type) {
    case TIME_TIME:
        return to_time_int64();
    case TIME_DATE:
        return to_date_int64();
    case TIME_DATETIME:
        return to_datetime_int64();
    default:
        return 0;
    }
}
Are you sure, that the value here is always with TIME_DATETIME type?

Comment (SaintBacchus) [reply be/src/vec/runtime/vdatetime_value.h:291]: Because the logic of `% 10000000000` is depend on `datetime` type.
If the type is `date`, this logic should be like this `(ts_value2.to_int64() % 10000 - ts_value1.to_int64() % 10000) < 0`

Comment (yiguolei) [reply be/src/vec/runtime/vdatetime_value.h:291]: Sorry for late reply. I will merge it. Thanks for your contribution.

**Review by yiguolei — APPROVED** [review]
LGTM
