### PR TITLE
[fix] fix a bug of encryption function with iv  may return wrong result

### LINKED ISSUE #8276: [Bug] encryption functions with iv  may return wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

encryption function with iv  may return wrong result
```
MySQL [test]> select to_base64(SM4_ENCRYPT('text','F3229A0B371ED2D9441B830D21A390C3', '0123456789','SM4_128_CBC'));
+-----------------------------------------------------+
| to_base64(sm4_encrypt('text', '***', '0123456789')) |
+-----------------------------------------------------+
| /Q0/XwXDm8Vy2kpDtSERZQ==                            |
+-----------------------------------------------------+
1 row in set (0.004 sec)

MySQL [test]> select to_base64(SM4_ENCRYPT('text','F3229A0B371ED2D9441B830D21A390C3', '0123456789','SM4_128_CBC'));
+-----------------------------------------------------+
| to_base64(sm4_encrypt('text', '***', '0123456789')) |
+-----------------------------------------------------+
| Yd/afQ1l5WZZ1VFSiWPQVg==                            |
+-----------------------------------------------------+
1 row in set (0.004 sec)

MySQL [test]> select to_base64(SM4_ENCRYPT('text','F3229A0B371ED2D9441B830D21A390C3', '0123456789','SM4_128_CBC'));
+-----------------------------------------------------+
| to_base64(sm4_encrypt('text', '***', '0123456789')) |
+-----------------------------------------------------+
| FgDet0kcwM5jumAsE8vh9g==                            |
+-----------------------------------------------------+
1 row in set (0.006 sec)
```

### What You Expected?

result for same text, key, iv the result should be same 

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yangzhg**
# Proposed changes

Issue Number: close #8276

## Problem Summary:

this bug is caused by the iv should be the same length of block， so if iv is less than block we should pad some char to the length

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/util/encryption_util.cpp [hunk 1]
```diff
@@ -219,21 +230,30 @@ static int do_decrypt(EVP_CIPHER_CTX* cipher_ctx, const EVP_CIPHER* cipher,
...
+        memcpy(init_vec, iv_str, strnlen(iv_str, EVP_MAX_IV_LENGTH));
+        init_vec[iv_length] = '\0';
+    }
     EVP_CIPHER_CTX* cipher_ctx = EVP_CIPHER_CTX_new();
     EVP_CIPHER_CTX_reset(cipher_ctx);
     int length = 0;
-    int ret = do_decrypt(cipher_ctx, cipher, encrypt, encrypt_length, encrypt_key, iv, padding,
-                         decrypt_content, &length);
+    int ret = do_decrypt(cipher_ctx, cipher, encrypt, encrypt_length, encrypt_key,
+                         (unsigned char*)init_vec, padding, decrypt_content, &length);
```
Comment (jackwener) [inline be/src/util/encryption_util.cpp:256]: reinterpret_cast may be better?

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
And do we need to change vectorized method too?
