### PR TITLE
[Bug] Fix bug that adding conflicting partition doesn't report errors

### LINKED ISSUE #6108: [Bug] Adding conflicting partition doesn't report errors
**Describe the bug**
Adding conflicting partition doesn't report errors

**To Reproduce**
        add the following RangePartitionDescs in order 
        PartitionKeyDesc p1 = PartitionKeyDesc.createFixed(
                Lists.newArrayList(new PartitionValue("2021-06-01")),
                Lists.newArrayList(new PartitionValue("2021-06-02")));

        PartitionKeyDesc p2 = PartitionKeyDesc.createFixed(
                Lists.newArrayList(new PartitionValue("2021-07-01")),
                Lists.newArrayList(new PartitionValue("2021-08-01")));

        PartitionKeyDesc p3 = PartitionKeyDesc.createFixed(
                Lists.newArrayList(new PartitionValue("2021-06-01")),
                Lists.newArrayList(new PartitionValue("2021-07-01")));

**Expected behavior**
throw exception 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6108 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/catalog/RangePartitionInfo.java [hunk 1]
```diff
@@ -90,6 +91,8 @@ public PartitionItem createAndCheckPartitionItem(SinglePartitionDesc desc, boole
             if (upperKey.compareTo(newRangeUpper) >= 0) {
                 newRange = checkNewRange(partKeyDesc, newRangeUpper, lastRange, currentRange);
                 break;
+            } else if (partKeyDesc.getPartitionType() == PartitionKeyDesc.PartitionKeyValueType.FIXED) {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/RangePartitionInfo.java:94]: This is not a good algorithm. The original method is optimized for the grammar of `less than`. It will first find a suitable position and then compare it. But for the grammar of `fix range`, it should be judged by comparing the lower value instead of upper value when finding the suitable position.
Therefore, different algorithms should be used for different grammars.

**Review by morningman — APPROVED** [review]
LGTM
