### PR TITLE
[Bug] Fix bdbje getDatabaseNames() bug and scan node close bug

### LINKED ISSUE #6770: [Bug] Checkpoint thread throw NPE
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk cdf9f9e

### What's Wrong?

```
2021-09-28 00:00:01,275 ERROR (leaderCheckpointer|76) [Daemon.run():118] daemon thread got exception. name: leaderCheckpointer
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:492) ~[spark-dpp-1.0.0.jar:1.0.0]
        at org.apache.doris.catalog.Catalog.getHelperNode(Catalog.java:5053) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.journal.bdbje.BDBJEJournal.getDatabaseNames(BDBJEJournal.java:423) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.journal.bdbje.BDBJEJournal.getFinalizedJournalId(BDBJEJournal.java:397) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.persist.EditLog.getFinalizedJournalId(EditLog.java:114) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.master.Checkpoint.runAfterCatalogReady(Checkpoint.java:81) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:3.4.0]
```

### What You Expected?

Works well

### How to Reproduce?

Just start a FE , do some operation and wait it triggering checkpoint

### Anything Else?

T

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. This bug is introduced from #6582
2. Optimize the error log of Address used used error msg.
3. Add some document about compilation.
    1. Add a custom thirdparty download url.
    2. Add a custom com.alibaba maven jar package for DataX.
4. Fix bug that BE crash when closing scan node, introduced from #6622.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #6770) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: fe/fe-core/src/main/java/org/apache/doris/PaloFe.java [hunk 1]
```diff
@@ -162,6 +166,28 @@ public static void start(String dorisHomeDir, String pidDir, String[] args) {
         }
     }
 
+    private static void checkAllPorts() throws IOException {
+        if (!NetUtils.isPortAvailable(FrontendOptions.getLocalHostAddress(), Config.edit_log_port,
```
Comment (yangzhg) [inline fe/fe-core/src/main/java/org/apache/doris/PaloFe.java:170]: Make those suggesstions into const string ？

Comment (morningman) [reply fe/fe-core/src/main/java/org/apache/doris/PaloFe.java:170]: Move to NetUtils

**Review by yangzhg — APPROVED** [review]
LGTM
