### PR TITLE
[Fix](Planner) Change return type in where, having and on clause

### LINKED ISSUE #19613: [Bug] Wrong result when `right outer join and where false`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 RELEASE

### What's Wrong?

I'm trying to add Apache Doris support to SQLancer, this may be a logic bug found by @[SQLancer](https://github.com/sqlancer/sqlancer).

Two opposing SQLs achieve the same result.
```
SELECT * FROM  t15 RIGHT  OUTER JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' LIKE 'abc');
SELECT * FROM  t15 RIGHT  OUTER JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' NOT LIKE 'abc');
```
image

### What You Expected?

The SQL `SELECT * FROM  t15 RIGHT  OUTER JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' NOT LIKE 'abc');` should obtain empty set as result.

### How to Reproduce?

You can reproduce this error from the following steps.

1. data prepare
```
DROP DATABASE IF EXISTS doris34;
CREATE DATABASE doris34;
USE doris34;
SET enable_nereids_planner=true;
CREATE TABLE t0(c0 DECIMALV3(8,3)) DISTRIBUTED BY HASH (c0) BUCKETS 1 PROPERTIES ("replication_num" = "1");
CREATE TABLE t1(c0 SMALLINT NOT NULL DEFAULT -1833256236) DISTRIBUTED BY HASH (c0) BUCKETS 24 PROPERTIES ("replication_num" = "1");
CREATE TABLE t15(c0 CHAR(249)) AGGREGATE KEY(c0) DISTRIBUTED BY RANDOM BUCKETS 30 PROPERTIES ("replication_num" = "1");
INSERT INTO t15 (c0) VALUES ('dr'), ('x7Tq'), ('');
INSERT INTO t0 (c0) VALUES (0.47683432698249817), (0.8864791393280029);
INSERT INTO t0 (c0) VALUES (0.11287713050842285);
INSERT INTO t15 (c0) VALUES ('');
INSERT INTO t15 (c0) VALUES ('');
INSERT INTO t15 (c0) VALUES ('hb');
```

2. check data of table t15 and t0
image

3. execute `SELECT * FROM  t15 RIGHT  OUTER JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' LIKE 'abc');`, this sql should obtain 3 reocrds, and the real result is correct. 
image

4. Change where condition to NOT and execute, `SELECT * FROM  t15 RIGHT  OUTER JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' NOT LIKE 'abc');`, this sql should return empty set because where condition is always false, but obtain 3 reocrds in actually.
image

5.  Change join type t0 left outer join or natural join and execute, they get the same and correct results (empty set).
```
SELECT * FROM  t15 JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' NOT LIKE 'abc');
SELECT * FROM  t15 LEFT  OUTER JOIN t0 ON (('') like ('15DScmSM')) WHERE ('abc' NOT LIKE 'abc');
```
image

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
## Proposed changes

Issue Number: close #19613

Problem: When using no boolean type as return type in where or having clause, the analyzer will check the return type and throw an error. But in some other databases, this usage is enable. 

Solved: Cast return type to boolean in where clause and having clause. select *** from *** where case when *** then 1 else 0 end;

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run buildall

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java [hunk 1]
```diff
@@ -1263,6 +1269,9 @@ private void analyzeAggregation(Analyzer analyzer) throws AnalysisException {
                 havingClauseAfterAnaylzed = havingClause.substitute(aliasSMap, analyzer, false);
             }
             havingClauseAfterAnaylzed = rewriteQueryExprByMvColumnExpr(havingClauseAfterAnaylzed, analyzer);
+            if (havingClauseAfterAnaylzed.getType().isTinyint()) {
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:1272]: i think it should be `!isBoolean()`

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java [hunk 2]
```diff
@@ -851,6 +852,11 @@ private void whereClauseRewrite() {
             } else {
                 whereClause = new BoolLiteral(true);
             }
+        } else if (whereClause instanceof CaseExpr
+                && (((CaseExpr) whereClause).getChild(1) instanceof IntLiteral)
+                && (((CaseExpr) whereClause).getChild(2) instanceof IntLiteral)) {
+            whereClause = new CastExpr(TypeDef.create(PrimitiveType.BOOLEAN), whereClause);
+            whereClause.setType(Type.BOOLEAN);
```
Comment (morrySnow) [inline fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java:859]: all whereClause should boolean type, so do not only process case when

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java (hunk 1 above)
Comment (LiBinfeng-01) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java]: yes, in master branch, old planner should be the same behavior as new planner

File: fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java (hunk 2 above)
Comment (LiBinfeng-01) [reply fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java]: done

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run fe_ut

File: fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java [hunk 3]
```diff
@@ -346,6 +346,10 @@ public boolean isBoolean() {
         return isScalarType(PrimitiveType.BOOLEAN);
     }
 
+    public boolean isTinyint() {
+        return isScalarType(PrimitiveType.TINYINT);
+    }
+
```
Comment (morrySnow) [inline fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java:352]: remove this

**Review by morrySnow — COMMENTED** [review]
not see any change about on clause~

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
miss on clause in Nereids

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 39.81 seconds
 stream load tsv:          451 seconds loaded 74807831229 Bytes, about 158 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          64.3 seconds inserted 10000000 Rows, about 155K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230625133711_clickbench_pr_167268.html

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 41.5 seconds
 stream load tsv:          451 seconds loaded 74807831229 Bytes, about 158 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          68.7 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230626084437_clickbench_pr_167770.html

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new mechine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.76 seconds
 stream load tsv:          515 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          89.1 seconds inserted 10000000 Rows, about 112K ops/s
 storage size: 17162312111 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230705163233_clickbench_pr_172602.html

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.15 seconds
 stream load tsv:          461 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          67.4 seconds inserted 10000000 Rows, about 148K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230705142615_clickbench_pr_172945.html

**Comment by hello-stephen** [comment]
(From new mechine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.75 seconds
 stream load tsv:          512 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         18 seconds loaded 2358488459 Bytes, about 124 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          87.0 seconds inserted 10000000 Rows, about 114K ops/s
 storage size: 17162069744 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230705231144_clickbench_pr_172950.html

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run feut

**Comment by LiBinfeng-01** [comment]
run feut

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.08 seconds
 stream load tsv:          472 seconds loaded 74807831229 Bytes, about 151 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          69.6 seconds inserted 10000000 Rows, about 143K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706010945_clickbench_pr_173154.html

**Comment by hello-stephen** [comment]
(From new mechine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 49.97 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          88.5 seconds inserted 10000000 Rows, about 112K ops/s
 storage size: 17162210859 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706095915_clickbench_pr_173155.html

**Comment by starocean999** [comment]
pls add some regression test case to cover the 3 scenarios

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 54.24 seconds
 stream load tsv:          499 seconds loaded 74807831229 Bytes, about 142 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          88.1 seconds inserted 10000000 Rows, about 113K ops/s
 storage size: 17167930340 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706161656_clickbench_pr_173519.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.79 seconds
 stream load tsv:          442 seconds loaded 74807831229 Bytes, about 161 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          68.9 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706082606_clickbench_pr_173517.html

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48 seconds
 stream load tsv:          449 seconds loaded 74807831229 Bytes, about 158 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          69.7 seconds inserted 10000000 Rows, about 143K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707015338_clickbench_pr_174047.html

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 55.5 seconds
 stream load tsv:          505 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          87.2 seconds inserted 10000000 Rows, about 114K ops/s
 storage size: 17161697706 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707114301_clickbench_pr_174145.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.63 seconds
 stream load tsv:          453 seconds loaded 74807831229 Bytes, about 157 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          67.2 seconds inserted 10000000 Rows, about 148K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707044305_clickbench_pr_174142.html

**Review by morrySnow — APPROVED** [review]

**Review by Kikyou1997 — APPROVED** [review]
