### PR TITLE
[Bug](bitmap) intersect_count function use in string cause ASAN error

### LINKED ISSUE #11935: [Bug] `intersect_count` function use in string cause ASAN error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

heap use after free. when call `intersect_count(bitmap, cast(int as string), string)`;

### What You Expected?

work well

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #11935 

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [x] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: be/src/util/bitmap_intersect.h [hunk 1]
```diff
@@ -242,4 +266,91 @@ struct BitmapIntersect {
...
+            std::string key;
+            detail::Helper::read_from(&reader, &key);
+            BitmapValue bitmap(reader);
+            reader += bitmap.getSizeInBytes();
+            _bitmaps[key] = bitmap;
+        }
+    }
+
+private:
+    phmap::flat_hash_map<std::string, BitmapValue> _bitmaps;
```
Comment (zhangstar333) [inline be/src/util/bitmap_intersect.h:353]: Is the ASAN error caused by the stringValue stored here as Key?

**Review by yangzhg — DISMISSED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM
