### PR TITLE
[multi-catalog]Fix hive partiton prune in hive and hudi exteranl table.

### LINKED ISSUE #10546: [Bug] Hive and hudi exteranal table get wrong partition prune for some case.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch

### What's Wrong?

Use tpch table to execute sql like below:
```
select count(*) from lineitem where  l_shipdate <= date '1998-12-01';
```
this only return 41 rows.

### What You Expected?

as the trino do:
image

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #10546

## Problem Summary:
`ExprBuilder` use stack to build the expr. 
The input order is : col, value and the output is value, col, but the `>=` is not reverse.
Example:
`col >=  1` => `1 >= col`

In this case, it's better use the queue to keeper the input order.

And also the `CompoundPredicate(OR)` have some problems,  it should be `alwaysTrue` whenever it's not a partiton key or it's not a supported op.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
It is strange that all exprs should pass the `NormalizeBinaryPredicatesRule`, and expr like `1 < col` should be converted to `col > 1` already.

**Comment by SaintBacchus** [comment]
> It is strange that all exprs should pass the `NormalizeBinaryPredicatesRule`, and expr like `1 < col` should be converted to `col > 1` already.

it get the col,value and op expr one by one, and then compose they by fixed order. so it will cause issue

File: fe/fe-core/src/main/java/org/apache/doris/planner/HudiScanNode.java [hunk 1]
```diff
@@ -229,41 +225,11 @@ private void initParams(Analyzer analyzer) {
...
-                    .val(TypeInfoFactory.intTypeInfo, 1)
-                    .pred("=", 2).build();
-        }
-    }
-
     private InputSplit[] getSplits() throws UserException, IOException {
         String splitsPath = basePath;
         if (partitionKeys.size() > 0) {
-            extractHivePartitionPredicate();
+            hivePartitionPredicate = HiveMetaStoreClientHelper.convertToHivePartitionExpr(
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/planner/HudiScanNode.java:231]: We call `convertToHivePartitionExpr` twice in `HudiScanNode`.
I think the call in `getFileStatus()` can be removed?

File: fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java [hunk 2]
```diff
@@ -400,61 +401,123 @@ public static List<FieldSchema> getSchema(String dbName, String tableName, Strin
...
+            return eligible;
+        }
+
+        public ExprNodeGenericFuncDesc getFuncDesc() {
+            return funcDesc;
+        }
+    }
+
+    private static ExprNodeGenericFuncDescContext convertToHivePartitionExpr(Expr dorisExpr,
             List<String> partitions, String tblName) throws DdlException {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java:469]:
```suggestion
            List<String> partitionKeys, String tblName) throws DdlException {
```

File: fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java [hunk 3]
```diff
@@ -400,61 +401,123 @@ public static List<FieldSchema> getSchema(String dbName, String tableName, Strin
...
+    private static class ExprNodeGenericFuncDescContext {
+        private final ExprNodeGenericFuncDesc funcDesc;
+        private final boolean eligible;
+
+        public ExprNodeGenericFuncDescContext(ExprNodeGenericFuncDesc funcDesc) {
+            this.funcDesc = funcDesc;
+            this.eligible = true;
+        }
+
+        public ExprNodeGenericFuncDescContext() {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java:451]: We can use a `static final` field to replace this constructor.

File: fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java [hunk 4]
```diff
@@ -400,61 +401,123 @@ public static List<FieldSchema> getSchema(String dbName, String tableName, Strin
...
                 default:
-                    return null;
+                    return new ExprNodeGenericFuncDescContext();
             }
         }
+        return binaryExprDesc(dorisExpr, partitions, tblName);
+    }
 
+    private static ExprNodeGenericFuncDescContext binaryExprDesc(Expr dorisExpr,
+            List<String> partitions, String tblName) throws DdlException {
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java:520]:
```suggestion
            List<String> partitionKeys, String tblName) throws DdlException {
```

File: fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java [hunk 5]
```diff
@@ -400,61 +401,123 @@ public static List<FieldSchema> getSchema(String dbName, String tableName, Strin
...
+                    } else {
+                        return new ExprNodeGenericFuncDescContext();
                     }
-                    return null;
                 }
                 case OR: {
-                    ExprNodeGenericFuncDesc left = convertToHivePartitionExpr(
-                            compoundPredicate.getChild(0), partitions, tblName);
-                    ExprNodeGenericFuncDesc right = convertToHivePartitionExpr(
+                    ExprNodeGenericFuncDescContext left = convertToHivePartitionExpr(
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java:497]:
```
                    ExprNodeGenericFuncDescContext left = convertToHivePartitionExpr(
                            compoundPredicate.getChild(0), partitions, tblName);
                    ExprNodeGenericFuncDescContext right = convertToHivePartitionExpr(
                            compoundPredicate.getChild(1), partitions, tblName);
```
This part can be extracted out of `switch case` block

File: fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java [hunk 6]
```diff
@@ -400,61 +401,123 @@ public static List<FieldSchema> getSchema(String dbName, String tableName, Strin
...
+                            compoundPredicate.getChild(1), partitions, tblName);
+                    if (left.isEligible() && right.isEligible()) {
+                        List<ExprNodeDesc> andArgs = new ArrayList<>();
+                        andArgs.add(left.getFuncDesc());
+                        andArgs.add(right.getFuncDesc());
+                        return new ExprNodeGenericFuncDescContext(getCompoundExpr(andArgs, "or"));
+                    } else {
+                        // If it is not a partition key, this is an always true expr.
+                        // Or if is a partition key and also is a not supportedOp, this is an always true expr.
+                        return new ExprNodeGenericFuncDescContext(genAlwaysTrueExpr(tblName));
```
Comment (morningman) [inline fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java:509]: I think it can just return `new ExprNodeGenericFuncDescContext()` ?

**Review by morningman — APPROVED** [review]

**Review by morningman — CHANGES_REQUESTED** [review]
need modify

**Review by morningman — APPROVED** [review]
LGTM
