### PR TITLE
[fix][storage]BetaRowsetReader::next_block does not return 0 rows before eof

### LINKED ISSUE #10366: [Bug] query with predicate returns wrong result when enable storage vectorization
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev-1.0.1
master

### What's Wrong?

select count(*) from table where value_column = xxx  returns 0, but expected result is greater than 0.

### What You Expected?

as above.

### How to Reproduce?

The first batch of rows are filtered by predicate of a rowset.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dataroaring**
Doris uses both Status::Eof and 0 rows as eof in iterators, it is
a little messy. VCollectIterator::Level0Iterator::_refresh_current_row
returns EOF when empty block is returned, then VCollectIterator::build_heap
does not put the iterator to the heap.

So if we have a rowset of which the first batch rows is filtered by
pushed down predicates, then the rowset is not read any more. However,
there may be valid rows after the first batch.

# Proposed changes

Issue Number: close #10366 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by wangbo — APPROVED** [review]
LGTM

File: be/src/olap/rowset/beta_rowset_reader.cpp [hunk 1]
```diff
@@ -184,15 +184,17 @@ Status BetaRowsetReader::next_block(RowBlock** block) {
...
+            if (!s.ok()) {
+                if (s.is_end_of_file()) {
+                    return Status::OLAPInternalError(OLAP_ERR_DATA_EOF);
+                } else {
+                    LOG(WARNING) << "failed to read next block: " << s.to_string();
+                    return Status::OLAPInternalError(OLAP_ERR_ROWSET_READ_FAILED);
+                }
             }
-        }
+        } while (block->rows() == 0);
```
Comment (Gabriel39) [inline be/src/olap/rowset/beta_rowset_reader.cpp:197]: After this PR, rows in block will never be 0 unless EOF. So maybe you also need to update codes in `_refresh_current_row`?
